export default {
  appDEFields: [
    {
      codeName: 'create_uid',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODEL.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_date',
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODEL.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'is_transient',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODEL.TRANSIENT',
      },
      logicName: '瞬态模型',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'TRANSIENT',
      id: 'is_transient',
    },
    {
      codeName: 'is_mail_thread',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODEL.IS_MAIL_THREAD',
      },
      logicName: '有邮件会话',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_MAIL_THREAD',
      id: 'is_mail_thread',
    },
    {
      codeName: 'is_mail_activity',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODEL.IS_MAIL_ACTIVITY',
      },
      logicName: '有邮件活动',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_MAIL_ACTIVITY',
      id: 'is_mail_activity',
    },
    {
      codeName: 'is_mail_blacklist',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODEL.IS_MAIL_BLACKLIST',
      },
      logicName: '有邮件黑名单',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_MAIL_BLACKLIST',
      id: 'is_mail_blacklist',
    },
    {
      codeName: 'info',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODEL.INFO',
      },
      logicName: '信息',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'INFO',
      id: 'info',
    },
    {
      codeName: 'model',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODEL.MODEL',
      },
      logicName: '模型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'MODEL',
      id: 'model',
    },
    {
      codeName: 'order',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODEL.ORDER',
      },
      logicName: '排序',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 250,
      name: 'ORDER',
      id: 'order',
    },
    {
      codeName: 'state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.IR_MODEL.STATE',
      },
      logicName: '类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATE',
      id: 'state',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'ir_model_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'info',
          logicName: '信息',
          appDEFieldId: 'info',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'info',
        },
        {
          codeName: 'is_mail_activity',
          logicName: '有邮件活动',
          appDEFieldId: 'is_mail_activity',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_mail_activity',
        },
        {
          codeName: 'is_mail_blacklist',
          logicName: '有邮件黑名单',
          appDEFieldId: 'is_mail_blacklist',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_mail_blacklist',
        },
        {
          codeName: 'is_mail_thread',
          logicName: '有邮件会话',
          appDEFieldId: 'is_mail_thread',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_mail_thread',
        },
        {
          codeName: 'is_transient',
          logicName: '瞬态模型',
          appDEFieldId: 'is_transient',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_transient',
        },
        {
          codeName: 'model',
          logicName: '模型',
          appDEFieldId: 'model',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'model',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'order',
          logicName: '排序',
          appDEFieldId: 'order',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'order',
        },
        {
          codeName: 'state',
          logicName: '类型',
          appDEFieldId: 'state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'state',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'ir_model_dto',
    },
    {
      codeName: 'ir_model_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_state_eq',
          logicName: '类型',
          appDEFieldId: 'state',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_state_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'ir_model_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'ir_model_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'ir_model_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'ir_model',
  deapicodeName: 'ir_model',
  deapicodeName2: 'ir_models',
  deapitag: 'IR_MODEL',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.IR_MODEL',
  },
  logicName: '模型',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'IR_MODEL',
  id: 'ehrapp.ir_model',
  codeName2: 'ir_models',
  requestPaths: [],
};
