export default {
  appDEFields: [
    {
      codeName: 'favorite_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.FAVORITE_COUNT',
      },
      logicName: '收藏计数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'FAVORITE_COUNT',
      id: 'favorite_count',
    },
    {
      codeName: 'is_favorite',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.IS_FAVORITE',
      },
      logicName: '收藏',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_FAVORITE',
      id: 'is_favorite',
    },
    {
      codeName: 'res_id',
      logicName: '资源标识',
      predefinedType: 'PARENTID',
      stdDataType: 25,
      stringLength: 100,
      name: 'RES_ID',
      id: 'res_id',
    },
    {
      codeName: 'parent_body',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.PARENT_BODY',
      },
      logicName: '上级消息内容',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'PARENT_BODY',
      id: 'parent_body',
    },
    {
      codeName: 'parent_author_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.PARENT_AUTHOR_ID',
      },
      logicName: '上级消息作者',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARENT_AUTHOR_ID',
      id: 'parent_author_id',
    },
    {
      codeName: 'create_date',
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'create_uid',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'email_add_signature',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.EMAIL_ADD_SIGNATURE',
      },
      logicName: '电子邮件添加签字',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'EMAIL_ADD_SIGNATURE',
      id: 'email_add_signature',
    },
    {
      codeName: 'is_internal',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.IS_INTERNAL',
      },
      logicName: '仅限员工',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_INTERNAL',
      id: 'is_internal',
    },
    {
      codeName: 'reply_to_force_new',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.REPLY_TO_FORCE_NEW',
      },
      logicName: '无响应',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'REPLY_TO_FORCE_NEW',
      id: 'reply_to_force_new',
    },
    {
      codeName: 'pinned_at',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.PINNED_AT',
      },
      logicName: '已置顶',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'PINNED_AT',
      id: 'pinned_at',
    },
    {
      codeName: 'date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.DATE',
      },
      logicName: '日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'DATE',
      id: 'date',
    },
    {
      codeName: 'body',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.BODY',
      },
      logicName: '内容',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'BODY',
      id: 'body',
    },
    {
      codeName: 'model',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.MODEL',
      },
      logicName: '相关单据模型',
      predefinedType: 'PARENTTYPE',
      stdDataType: 25,
      stringLength: 500,
      name: 'MODEL',
      id: 'model',
    },
    {
      codeName: 'record_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.RECORD_NAME',
      },
      logicName: '消息记录名称',
      predefinedType: 'PARENTNAME',
      stdDataType: 25,
      stringLength: 500,
      name: 'RECORD_NAME',
      id: 'record_name',
    },
    {
      codeName: 'message_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.MESSAGE_ID',
      },
      logicName: '消息ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'MESSAGE_ID',
      id: 'message_id',
    },
    {
      codeName: 'email_from',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.EMAIL_FROM',
      },
      logicName: '来自',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'EMAIL_FROM',
      id: 'email_from',
    },
    {
      codeName: 'reply_to',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.REPLY_TO',
      },
      logicName: '回复 至',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'REPLY_TO',
      id: 'reply_to',
    },
    {
      codeName: 'subject',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.SUBJECT',
      },
      logicName: '主旨',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SUBJECT',
      id: 'subject',
    },
    {
      codeName: 'email_layout_xmlid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.EMAIL_LAYOUT_XMLID',
      },
      logicName: '布局',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'EMAIL_LAYOUT_XMLID',
      id: 'email_layout_xmlid',
    },
    {
      codeName: 'message_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.MESSAGE_TYPE',
      },
      logicName: '类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'MESSAGE_TYPE',
      id: 'message_type',
    },
    {
      codeName: 'parent_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.PARENT_ID',
      },
      logicName: '上级消息',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARENT_ID',
      id: 'parent_id',
    },
    {
      codeName: 'record_company_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.RECORD_COMPANY_ID',
      },
      logicName: '公司',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'RECORD_COMPANY_ID',
      id: 'record_company_id',
    },
    {
      codeName: 'subtype_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.SUBTYPE_ID',
      },
      logicName: '子类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'SUBTYPE_ID',
      id: 'subtype_id',
    },
    {
      codeName: 'record_alias_domain_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.RECORD_ALIAS_DOMAIN_ID',
      },
      logicName: '别名域',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'RECORD_ALIAS_DOMAIN_ID',
      id: 'record_alias_domain_id',
    },
    {
      codeName: 'mail_activity_type_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.MAIL_ACTIVITY_TYPE_ID',
      },
      logicName: '邮件活动类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MAIL_ACTIVITY_TYPE_ID',
      id: 'mail_activity_type_id',
    },
    {
      codeName: 'author_guest_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.AUTHOR_GUEST_ID',
      },
      logicName: '访客',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'AUTHOR_GUEST_ID',
      id: 'author_guest_id',
    },
    {
      codeName: 'author_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.AUTHOR_ID',
      },
      logicName: '作者',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'AUTHOR_ID',
      id: 'author_id',
    },
    {
      codeName: 'starred',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.STARRED',
      },
      logicName: '星标消息',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'STARRED',
      id: 'starred',
    },
    {
      codeName: 'needaction',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.NEEDACTION',
      },
      logicName: '需要行动',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'NEEDACTION',
      id: 'needaction',
    },
    {
      codeName: 'is_current_user_or_guest_author',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.IS_CURRENT_USER_OR_GUEST_AUTHOR',
      },
      logicName: '是当前用户还是访客作者',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_CURRENT_USER_OR_GUEST_AUTHOR',
      id: 'is_current_user_or_guest_author',
    },
    {
      codeName: 'has_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.HAS_ERROR',
      },
      logicName: '有错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HAS_ERROR',
      id: 'has_error',
    },
    {
      codeName: 'has_sms_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.HAS_SMS_ERROR',
      },
      logicName: '有短信息错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HAS_SMS_ERROR',
      id: 'has_sms_error',
    },
    {
      codeName: 'snailmail_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.SNAILMAIL_ERROR',
      },
      logicName: '蜗牛邮件错误消息',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SNAILMAIL_ERROR',
      id: 'snailmail_error',
    },
    {
      codeName: 'rating_value',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.RATING_VALUE',
      },
      logicName: '评级值',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'RATING_VALUE',
      id: 'rating_value',
    },
    {
      codeName: 'account_audit_log_activated',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.ACCOUNT_AUDIT_LOG_ACTIVATED',
      },
      logicName: '审计日志已启动',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACCOUNT_AUDIT_LOG_ACTIVATED',
      id: 'account_audit_log_activated',
    },
    {
      codeName: 'account_audit_log_preview',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.ACCOUNT_AUDIT_LOG_PREVIEW',
      },
      logicName: '描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ACCOUNT_AUDIT_LOG_PREVIEW',
      id: 'account_audit_log_preview',
    },
    {
      codeName: 'preview',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.PREVIEW',
      },
      logicName: '预览',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'PREVIEW',
      id: 'preview',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_MESSAGE.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'mail_message_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'favorite_count',
          logicName: '收藏计数',
          appDEFieldId: 'favorite_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'favorite_count',
        },
        {
          codeName: 'is_favorite',
          logicName: '收藏',
          appDEFieldId: 'is_favorite',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_favorite',
        },
        {
          codeName: 'res_id',
          logicName: '资源标识',
          appDEFieldId: 'res_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'res_id',
        },
        {
          codeName: 'parent_body',
          logicName: '上级消息内容',
          appDEFieldId: 'parent_body',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_body',
        },
        {
          codeName: 'parent_author_id',
          logicName: '上级消息作者',
          appDEFieldId: 'parent_author_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_author_id',
        },
        {
          codeName: 'account_audit_log_activated',
          logicName: '审计日志已启动',
          appDEFieldId: 'account_audit_log_activated',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_audit_log_activated',
        },
        {
          codeName: 'account_audit_log_preview',
          logicName: '描述',
          appDEFieldId: 'account_audit_log_preview',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_audit_log_preview',
        },
        {
          codeName: 'author_guest_id',
          logicName: '访客',
          appDEFieldId: 'author_guest_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'author_guest_id',
        },
        {
          codeName: 'author_id',
          logicName: '作者',
          appDEFieldId: 'author_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'author_id',
        },
        {
          codeName: 'body',
          logicName: '内容',
          appDEFieldId: 'body',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'body',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '日期',
          appDEFieldId: 'date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'email_add_signature',
          logicName: '电子邮件添加签字',
          appDEFieldId: 'email_add_signature',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_add_signature',
        },
        {
          codeName: 'email_from',
          logicName: '来自',
          appDEFieldId: 'email_from',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_from',
        },
        {
          codeName: 'email_layout_xmlid',
          logicName: '布局',
          appDEFieldId: 'email_layout_xmlid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_layout_xmlid',
        },
        {
          codeName: 'has_error',
          logicName: '有错误',
          appDEFieldId: 'has_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'has_error',
        },
        {
          codeName: 'has_sms_error',
          logicName: '有短信息错误',
          appDEFieldId: 'has_sms_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'has_sms_error',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'is_current_user_or_guest_author',
          logicName: '是当前用户还是访客作者',
          appDEFieldId: 'is_current_user_or_guest_author',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_current_user_or_guest_author',
        },
        {
          codeName: 'is_internal',
          logicName: '仅限员工',
          appDEFieldId: 'is_internal',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_internal',
        },
        {
          codeName: 'mail_activity_type_id',
          logicName: '邮件活动类型',
          appDEFieldId: 'mail_activity_type_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mail_activity_type_id',
        },
        {
          codeName: 'message_id',
          logicName: '消息ID',
          appDEFieldId: 'message_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_id',
        },
        {
          codeName: 'message_type',
          logicName: '类型',
          appDEFieldId: 'message_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'message_type',
        },
        {
          codeName: 'model',
          logicName: '相关单据模型',
          appDEFieldId: 'model',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'model',
        },
        {
          codeName: 'needaction',
          logicName: '需要行动',
          appDEFieldId: 'needaction',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'needaction',
        },
        {
          codeName: 'parent_id',
          logicName: '上级消息',
          appDEFieldId: 'parent_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_id',
        },
        {
          codeName: 'pinned_at',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '已置顶',
          appDEFieldId: 'pinned_at',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'pinned_at',
        },
        {
          codeName: 'preview',
          logicName: '预览',
          appDEFieldId: 'preview',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'preview',
        },
        {
          codeName: 'rating_value',
          logicName: '评级值',
          appDEFieldId: 'rating_value',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rating_value',
        },
        {
          codeName: 'record_alias_domain_id',
          logicName: '别名域',
          appDEFieldId: 'record_alias_domain_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'record_alias_domain_id',
        },
        {
          codeName: 'record_company_id',
          logicName: '公司',
          appDEFieldId: 'record_company_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'record_company_id',
        },
        {
          codeName: 'record_name',
          logicName: '消息记录名称',
          appDEFieldId: 'record_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'record_name',
        },
        {
          codeName: 'reply_to',
          logicName: '回复 至',
          appDEFieldId: 'reply_to',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'reply_to',
        },
        {
          codeName: 'reply_to_force_new',
          logicName: '无响应',
          appDEFieldId: 'reply_to_force_new',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'reply_to_force_new',
        },
        {
          codeName: 'snailmail_error',
          logicName: '蜗牛邮件错误消息',
          appDEFieldId: 'snailmail_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'snailmail_error',
        },
        {
          codeName: 'starred',
          logicName: '星标消息',
          appDEFieldId: 'starred',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'starred',
        },
        {
          codeName: 'subject',
          logicName: '主旨',
          appDEFieldId: 'subject',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'subject',
        },
        {
          codeName: 'subtype_id',
          logicName: '子类型',
          appDEFieldId: 'subtype_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'subtype_id',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'mail_message_dto',
    },
    {
      codeName: 'mail_message_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_author_guest_id_eq',
          logicName: '访客',
          appDEFieldId: 'author_guest_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_author_guest_id_eq',
        },
        {
          codeName: 'n_author_id_eq',
          logicName: '作者',
          appDEFieldId: 'author_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_author_id_eq',
        },
        {
          codeName: 'n_body_like',
          logicName: '内容',
          appDEFieldId: 'body',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_body_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_is_favorite_eq',
          logicName: '收藏',
          appDEFieldId: 'is_favorite',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_is_favorite_eq',
        },
        {
          codeName: 'n_mail_activity_type_id_eq',
          logicName: '邮件活动类型',
          appDEFieldId: 'mail_activity_type_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_mail_activity_type_id_eq',
        },
        {
          codeName: 'n_message_type_eq',
          logicName: '类型',
          appDEFieldId: 'message_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_message_type_eq',
        },
        {
          codeName: 'n_needaction_eq',
          logicName: '需要行动',
          appDEFieldId: 'needaction',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_needaction_eq',
        },
        {
          codeName: 'n_parent_id_eq',
          logicName: '上级消息',
          appDEFieldId: 'parent_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_parent_id_eq',
        },
        {
          codeName: 'n_record_alias_domain_id_eq',
          logicName: '别名域',
          appDEFieldId: 'record_alias_domain_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_record_alias_domain_id_eq',
        },
        {
          codeName: 'n_record_company_id_eq',
          logicName: '公司',
          appDEFieldId: 'record_company_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_record_company_id_eq',
        },
        {
          codeName: 'n_res_id_eq',
          logicName: '资源标识',
          appDEFieldId: 'res_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_res_id_eq',
        },
        {
          codeName: 'n_subtype_id_eq',
          logicName: '子类型',
          appDEFieldId: 'subtype_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_subtype_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'mail_message_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'add_favorite',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/add_favorite',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'add_favorite',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'delete',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/delete',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'delete',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'pin',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/pin',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'pin',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'remove_all_favorites',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'POST',
      requestParamType: 'FIELD',
      requestPath: '/remove_all_favorites',
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'remove_all_favorites',
    },
    {
      codeName: 'remove_favorite',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'POST',
      requestParamType: 'FIELD',
      requestPath: '/remove_favorite',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'remove_favorite',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'unpin',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/unpin',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'unpin',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_common',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_common',
      actionType: 'REMOTE',
      addedqconditions: [
        {
          condOp: 'EQ',
          condValue: 'srfmodelname',
          fieldName: 'MODEL',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(MODEL) 等于(=) 数据上下文 srfmodelname',
          id: '(model) 等于(=) 数据上下文 srfmodelname',
        },
        {
          condOp: 'EQ',
          condValue: 'mail_thread',
          fieldName: 'RES_ID',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(RES_ID) 等于(=) 数据上下文 mail_thread',
          id: '(res_id) 等于(=) 数据上下文 mail_thread',
        },
      ],
      dataSetName: 'common',
      dataSetTag: 'common',
      dataSetType: 'REMOTE',
      id: 'fetch_common',
    },
    {
      codeName: 'fetch_common_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_common_all',
      actionType: 'REMOTE',
      addedqconditions: [
        {
          condOp: 'EQ',
          condValue: 'srfmodelname',
          fieldName: 'MODEL',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(MODEL) 等于(=) 数据上下文 srfmodelname',
          id: '(model) 等于(=) 数据上下文 srfmodelname',
        },
      ],
      dataSetName: 'common_all',
      dataSetTag: 'common_all',
      dataSetType: 'REMOTE',
      id: 'fetch_common_all',
    },
    {
      codeName: 'fetch_cur_user',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_cur_user',
      actionType: 'REMOTE',
      dataSetName: 'cur_user',
      dataSetTag: 'cur_user',
      dataSetType: 'REMOTE',
      id: 'fetch_cur_user',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_pinned',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_message_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_message_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_pinned',
      actionType: 'REMOTE',
      dataSetName: 'pinned',
      dataSetTag: 'pinned',
      dataSetType: 'REMOTE',
      id: 'fetch_pinned',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '清空',
      codeName: 'clear_comment',
      frontProcessType: 'OTHER',
      fullCodeName: 'mail_message_clear_comment',
      scriptCode: "console.log('清空评论')",
      uiactionMode: 'FRONT',
      uiactionTag: 'clear_comment',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'clear_comment',
      appDataEntityId: 'ehrapp.mail_message',
      name: '清空评论',
      id: 'clear_comment@mail_message',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '删除评论',
      codeName: 'del_comment',
      confirmMsg: '确认删除该评论？',
      fullCodeName: 'mail_message_del_comment',
      appDEMethodId: 'delete',
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'del_comment',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'AFTER',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'refresh_comment',
      appDataEntityId: 'ehrapp.mail_message',
      name: '删除评论',
      id: 'del_comment@mail_message',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'panel_message_layout_button_calluilogic1_click',
      frontProcessType: 'OTHER',
      fullCodeName:
        'mail_message_panel_message_layout_button_calluilogic1_click',
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_message_layout_button_calluilogic1_click',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      uilogicType: 'DELOGIC',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'edit_comment',
      appDataEntityId: 'ehrapp.mail_message',
      name: '编辑',
      id: 'panel_message_layout_button_calluilogic1_click@mail_message',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '回复',
      codeName: 'panel_message_layout_button_calluilogic2_click',
      frontProcessType: 'OTHER',
      fullCodeName:
        'mail_message_panel_message_layout_button_calluilogic2_click',
      uiactionMode: 'FRONT',
      uiactionTag: 'panel_message_layout_button_calluilogic2_click',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      uilogicType: 'DELOGIC',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'reply_comment',
      appDataEntityId: 'ehrapp.mail_message',
      name: '回复',
      id: 'panel_message_layout_button_calluilogic2_click@mail_message',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '发送评论',
      codeName: 'send_comment',
      frontProcessType: 'OTHER',
      fullCodeName: 'mail_message_send_comment',
      uiactionMode: 'FRONT',
      uiactionTag: 'send_comment',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'send_comment',
      appDataEntityId: 'ehrapp.mail_message',
      name: '发送评论',
      id: 'send_comment@mail_message',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'clear_comment',
      defaultParamName: 'Default',
      logicName: '清空评论',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 230,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 260,
          name: '开始',
          id: 'begin',
        },
        {
          code: 'uiLogic.view.layoutPanel.panelItems.message_inputbox.editor.clear();\nuiLogic.view.edit_comment_id = null;\nuiLogic.view.reply_comment_id = null;',
          codeName: 'RAWJSCODE1',
          leftPos: 190,
          logicNodeType: 'RAWJSCODE',
          topPos: 470,
          name: '清空评论',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '清空评论',
      id: 'clear_comment',
    },
    {
      codeName: 'comment_icon_hidden',
      defaultParamName: 'Default',
      logicName: '控制评论按钮隐藏',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: -30,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM2',
          leftPos: 500,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicNodeParams: [
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'send',
              expression: 'view.layoutPanel.panelItems.field_textbox.value',
              paramAction: 'SETPARAMVALUE',
              srcFieldName:
                'layoutPanel.panelItems.message_inputbox.value?true:false',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.field_textbox.value?true:false] ==> send[visible]',
              id: 'view[layoutpanel.panelitems.field_textbox.value?true:false] ==> send[visible]',
            },
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'reset',
              expression: 'view.layoutPanel.panelItems.field_textbox.value',
              paramAction: 'SETPARAMVALUE',
              srcFieldName:
                'layoutPanel.panelItems.message_inputbox.value?true:false',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.field_textbox.value?true:false] ==> reset[visible]',
              id: 'view[layoutpanel.panelitems.field_textbox.value?true:false] ==> reset[visible]',
            },
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'icon',
              expression: '!view.layoutPanel.panelItems.field_textbox.value',
              paramAction: 'SETPARAMVALUE',
              srcFieldName:
                'layoutPanel.panelItems.message_inputbox.value?false:true',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.field_textbox.value?false:true] ==> icon[visible]',
              id: 'view[layoutpanel.panelitems.field_textbox.value?false:true] ==> icon[visible]',
            },
          ],
          topPos: 8,
          name: '控制部件显示隐藏',
          id: 'preparejsparam2',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 260,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'send',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_send.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_send.state] ==> send',
              id: 'view[layoutpanel.panelitems.comment_send.state] ==> send',
            },
            {
              dstDEUILogicParamId: 'reset',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_cancel.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_cancel.state] ==> reset',
              id: 'view[layoutpanel.panelitems.comment_cancel.state] ==> reset',
            },
            {
              dstDEUILogicParamId: 'icon',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_icon.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_icon.state] ==> icon',
              id: 'view[layoutpanel.panelitems.comment_icon.state] ==> icon',
            },
          ],
          topPos: 8,
          name: '获取部件状态信息',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'view',
          activeViewParam: true,
          name: '视图',
          id: 'view',
        },
        {
          codeName: 'reset',
          entityParam: true,
          name: '清空',
          id: 'reset',
        },
        {
          codeName: 'send',
          entityParam: true,
          name: '评论',
          id: 'send',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'icon',
          entityParam: true,
          name: '图标',
          id: 'icon',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '控制评论按钮隐藏',
      id: 'comment_icon_hidden',
    },
    {
      codeName: 'comment_icon_show',
      defaultParamName: 'Default',
      logicName: '控制评论按钮显示',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 140,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM2',
          leftPos: 582,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicNodeParams: [
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'send',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'true',
              srcValueType: 'SRCVALUE',
              id: '直接值[true] ==> send[visible]',
            },
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'reset',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'true',
              srcValueType: 'SRCVALUE',
              id: '直接值[true] ==> reset[visible]',
            },
            {
              dstFieldName: 'visible',
              dstDEUILogicParamId: 'icon',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'false',
              srcValueType: 'SRCVALUE',
              id: '直接值[false] ==> icon[visible]',
            },
          ],
          topPos: 208,
          name: '控制部件显示隐藏',
          id: 'preparejsparam2',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 378,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'send',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_send.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_send.state] ==> send',
              id: 'view[layoutpanel.panelitems.comment_send.state] ==> send',
            },
            {
              dstDEUILogicParamId: 'reset',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_cancel.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_cancel.state] ==> reset',
              id: 'view[layoutpanel.panelitems.comment_cancel.state] ==> reset',
            },
            {
              dstDEUILogicParamId: 'icon',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.comment_icon.state',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.comment_icon.state] ==> icon',
              id: 'view[layoutpanel.panelitems.comment_icon.state] ==> icon',
            },
          ],
          topPos: 208,
          name: '获取部件状态信息',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'send',
          entityParam: true,
          name: '评论',
          id: 'send',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'reset',
          entityParam: true,
          name: '清空',
          id: 'reset',
        },
        {
          codeName: 'icon',
          entityParam: true,
          name: '图标',
          id: 'icon',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '视图',
          id: 'view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '控制评论按钮显示',
      id: 'comment_icon_show',
    },
    {
      codeName: 'edit_comment',
      defaultParamName: 'Default',
      logicName: '编辑评论',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 210,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode_01',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'body',
                    dstLogicParamId: 'default',
                    logicType: 'SINGLE',
                    name: 'Default[body] 值不为空(NotNil)',
                    id: 'default[body] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'begin',
              id: '无评论内容时不执行',
            },
          ],
          topPos: 144,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 150,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'reply_comment_id',
              dstDEUILogicParamId: 'view',
              paramAction: 'SETPARAMVALUE',
              srcValueType: 'NULLVALUE',
              name: '空值（NULL） ==> parentView[reply_comment_id]',
              id: '空值（null） ==> parentview[reply_comment_id]',
            },
            {
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.message_inputbox.editor',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'parentView[layoutPanel.panelItems.field_textbox.editor] ==> comment',
              id: 'parentview[layoutpanel.panelitems.field_textbox.editor] ==> comment',
            },
            {
              dstFieldName: 'edit_comment_id',
              dstDEUILogicParamId: 'view',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'id',
              srcDEUILogicParamId: 'default',
              srcValueType: 'SRCDLPARAM',
              name: 'Default[id] ==> parentView[edit_comment_id]',
              id: 'default[id] ==> parentview[edit_comment_id]',
            },
          ],
          topPos: 330,
          name: '设置评论id',
          id: 'preparejsparam1',
        },
        {
          code: '// 获取目标面板项\r\nconst panelItem = view.layoutPanel.findPanelItemByName("message_panel");\r\nif (panelItem) {\r\n  // 切换可见状态\r\n  panelItem.state.visible =true;\r\n}',
          codeName: 'RAWJSCODE_01',
          leftPos: 430,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'rawjscode_01',
              id: '连接名称',
            },
          ],
          topPos: 310,
          parallelOutput: true,
          name: '显示消息输入框',
          id: 'rawjscode_01',
        },
        {
          code: 'uiLogic.comment.toggleCollapse(true);\nuiLogic.comment.setValue(uiLogic.default.body);\nuiLogic.comment.reply.value = null;\n\n',
          codeName: 'RAWJSCODE1',
          leftPos: 160,
          logicNodeType: 'RAWJSCODE',
          topPos: 480,
          name: '展开评论输入框并设值',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'comment',
          entityParam: true,
          name: '评论对象',
          id: 'comment',
        },
        {
          codeName: 'comment_id',
          entityParam: true,
          name: '评论id存储对象',
          id: 'comment_id',
        },
        {
          codeName: 'parentView',
          entityParam: true,
          name: '父视图对象',
          id: 'parentview',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '编辑评论',
      id: 'edit_comment',
    },
    {
      codeName: 'refresh_comment',
      defaultParamName: 'Default',
      logicName: '刷新评论列表',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 310,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: "ibiz.mc.command.update.send({ srfdecodename: 'mail_message',srfkey: uiLogic.default.id})",
          codeName: 'RAWJSCODE1',
          leftPos: 538,
          logicNodeType: 'RAWJSCODE',
          topPos: 200,
          name: '注入脚本代码',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'ctx',
          navContextParam: true,
          id: 'ctx',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '刷新评论列表',
      id: 'refresh_comment',
    },
    {
      codeName: 'reply_comment',
      defaultParamName: 'Default',
      logicName: '回复评论',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          name: '开始',
          id: 'begin',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 160,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'edit_comment_id',
              dstDEUILogicParamId: 'view',
              paramAction: 'SETPARAMVALUE',
              srcValueType: 'NULLVALUE',
              name: '空值（NULL） ==> parentView[edit_comment_id]',
              id: '空值（null） ==> parentview[edit_comment_id]',
            },
            {
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.message_inputbox.editor',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'parentView[layoutPanel.panelItems.field_textbox.editor] ==> comment',
              id: 'parentview[layoutpanel.panelitems.field_textbox.editor] ==> comment',
            },
            {
              dstFieldName: 'reply_comment_id',
              dstDEUILogicParamId: 'view',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'id',
              srcDEUILogicParamId: 'default',
              srcValueType: 'SRCDLPARAM',
              name: 'Default[id] ==> parentView[reply_comment_id]',
              id: 'default[id] ==> parentview[reply_comment_id]',
            },
          ],
          topPos: 374,
          name: '设置回复id',
          id: 'preparejsparam1',
        },
        {
          code: "const _app = ibiz.hub.getApp(context.srfappid);\n_app.codeList.get('SysOperator', context, params).then(items => {\n\tconst create_uid = uiLogic.default.create_uid;\n\tconst findItem = items.find(item => item.value == create_uid);\n\tconst name = findItem ? findItem.text : create_uid;\n\tconst content = uiLogic.default.body;\n\tuiLogic.comment.setReply({name, content});\n\tuiLogic.comment.toggleCollapse(true);\n})",
          codeName: 'RAWJSCODE1',
          leftPos: 160,
          logicNodeType: 'RAWJSCODE',
          topPos: 510,
          name: '展开评论输入框并设值回复',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'comment',
          entityParam: true,
          name: '评论对象',
          id: 'comment',
        },
        {
          codeName: 'parentView',
          entityParam: true,
          name: '父视图对象',
          id: 'parentview',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '回复评论',
      id: 'reply_comment',
    },
    {
      codeName: 'send_comment',
      defaultParamName: 'Default',
      logicName: '发送评论',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 476,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: -160,
          name: '开始',
          id: 'begin',
        },
        {
          dstAppDEActionId: 'create',
          dstAppDataEntityId: 'ehrapp.mail_message',
          codeName: 'DEACTION2',
          dstDEUILogicParamId: 'comment',
          leftPos: 586,
          logicNodeType: 'DEACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode2',
              srcDEUILogicNodeId: 'deaction2',
              id: '连接名称',
            },
          ],
          topPos: 720,
          name: '创建评论（简单模式）',
          id: 'deaction2',
        },
        {
          codeName: 'END1',
          leftPos: 476,
          logicNodeType: 'END',
          topPos: 1090,
          parallelOutput: true,
          name: '结束',
          id: 'end1',
        },
        {
          code: "uiLogic.view.layoutPanel.panelItems.message_inputbox.value = '';\nuiLogic.view.layoutPanel.panelItems.message_inputbox.data.message_inputbox = '';\nuiLogic.view.edit_comment_id = null;\nuiLogic.view.reply_comment_id = null;\nuiLogic.editor.reply.value = null;\nuiLogic.editor.toggleCollapse(false)\n// 清空本地上传文件\nuiLogic.editor.clearFiles();\n//通知消息刷新\nibiz.mc.command.create.send({ srfdecodename: 'mail_message'})\n",
          codeName: 'RAWJSCODE2',
          leftPos: 436,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'end1',
              srcDEUILogicNodeId: 'rawjscode2',
              id: '连接名称',
            },
          ],
          topPos: 970,
          name: '清空评论框与评论id,通知刷新',
          id: 'rawjscode2',
        },
        {
          codeName: 'PREPAREJSPARAM4',
          leftPos: 300,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deaction_01',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNULL',
                    dstFieldName: 'edit_comment_id',
                    dstLogicParamId: 'view',
                    logicType: 'SINGLE',
                    name: 'view[edit_comment_id] 值为空(Nil)',
                    id: 'view[edit_comment_id] 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'preparejsparam4',
              id: '无存在评论id',
            },
            {
              dstDEUILogicNodeId: 'preparejsparam3',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'edit_comment_id',
                    dstLogicParamId: 'view',
                    logicType: 'SINGLE',
                    name: 'view[edit_comment_id] 值不为空(NotNil)',
                    id: 'view[edit_comment_id] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'preparejsparam4',
              id: '存在评论id',
            },
          ],
          topPos: 540,
          parallelOutput: true,
          name: '空，用于条件分支',
          id: 'preparejsparam4',
        },
        {
          code: 'uiLogic.comment.body = uiLogic.view.layoutPanel.panelItems.message_inputbox.value;',
          codeName: 'RAWJSCODE1',
          leftPos: 436,
          logicNodeType: 'RAWJSCODE',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'body',
                    dstLogicParamId: 'comment',
                    logicType: 'SINGLE',
                    name: 'comment[body] 值不为空(NotNil)',
                    id: 'comment[body] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'rawjscode1',
              id: '评论内容不为空',
            },
          ],
          name: '获取评论框内容',
          id: 'rawjscode1',
        },
        {
          codeName: 'PREPAREJSPARAM2',
          leftPos: 596,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deaction_01',
              srcDEUILogicNodeId: 'preparejsparam2',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'parent_id',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'reply_comment_id',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              id: 'view[reply_comment_id] ==> comment[pid]',
            },
          ],
          topPos: 500,
          name: '回复标识',
          id: 'preparejsparam2',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 436,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam6',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'srfowner_type',
                    dstLogicParamId: 'ctx',
                    logicType: 'SINGLE',
                    name: 'ctx[srfowner_type] 值不为空(NotNil)',
                    id: 'ctx[srfowner_type] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '视图上下文中存在srfowner_type参数',
            },
            {
              dstDEUILogicNodeId: 'preparejsparam5',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNULL',
                    dstFieldName: 'srfowner_type',
                    dstLogicParamId: 'ctx',
                    logicType: 'SINGLE',
                    name: 'ctx[srfowner_type] 值为空(Nil)',
                    id: 'ctx[srfowner_type] 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '视图上下文不存在srfowner_type参数',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'res_id',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'mail_thread',
              srcDEUILogicParamId: 'params',
              srcValueType: 'SRCDLPARAM',
              id: 'ctx[principal_id] ==> comment[principal_id]',
            },
            {
              dstFieldName: 'model',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'srfmodelname',
              srcDEUILogicParamId: 'params',
              srcValueType: 'SRCDLPARAM',
              id: 'ctx[principal_type] ==> comment[principal_type]',
            },
            {
              dstDEUILogicParamId: 'editor',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.message_inputbox.editor',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.field_textbox.editor] ==> editor',
              id: 'view[layoutpanel.panelitems.field_textbox.editor] ==> editor',
            },
            {
              dstFieldName: 'message_type',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcValue: 'comment',
              srcValueType: 'SRCVALUE',
              id: 'ctx[principal_type] ==> comment[owner_type]',
            },
          ],
          topPos: 190,
          parallelOutput: true,
          name: '设置评论model与res_id',
          id: 'preparejsparam1',
        },
        {
          dstAppDEActionId: 'update',
          dstAppDataEntityId: 'ehrapp.mail_message',
          codeName: 'DEACTION3',
          dstDEUILogicParamId: 'comment',
          leftPos: 300,
          logicNodeType: 'DEACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode2',
              srcDEUILogicNodeId: 'deaction3',
              id: '连接名称',
            },
          ],
          topPos: 830,
          name: '修改评论',
          id: 'deaction3',
        },
        {
          codeName: 'PREPAREJSPARAM6',
          leftPos: 750,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam5',
              srcDEUILogicNodeId: 'preparejsparam6',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'owner_type',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'srfowner_type',
              srcDEUILogicParamId: 'ctx',
              srcValueType: 'SRCDLPARAM',
              id: 'ctx[srfowner_type] ==> comment[owner_type]',
            },
            {
              dstFieldName: 'model',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'srfowner_type',
              srcDEUILogicParamId: 'ctx',
              srcValueType: 'SRCDLPARAM',
              id: 'ctx[srfowner_type] ==> comment[principal_type]',
            },
          ],
          topPos: 310,
          name: '为评论重新赋值参数',
          id: 'preparejsparam6',
        },
        {
          dstAppDEActionId: 'mail_message_post',
          dstAppDataEntityId: 'ehrapp.mail_thread',
          codeName: 'DEACTION_01',
          dstDEUILogicParamId: 'comment',
          leftPos: 787,
          logicNodeType: 'DEACTION',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode2',
              srcDEUILogicNodeId: 'deaction_01',
              id: '连接名称',
            },
          ],
          topPos: 720,
          parallelOutput: true,
          name: '发送消息',
          id: 'deaction_01',
        },
        {
          codeName: 'PREPAREJSPARAM5',
          leftPos: 436,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam4',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNULL',
                    dstFieldName: 'reply.value',
                    dstLogicParamId: 'editor',
                    logicType: 'SINGLE',
                    name: 'editor[reply.value] 值为空(Nil)',
                    id: 'editor[reply.value] 值为空(nil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'preparejsparam5',
              id: '不存在回复评论标识',
            },
            {
              dstDEUILogicNodeId: 'preparejsparam2',
              deuilogicLinkGroupCond: {
                groupOP: 'AND',
                deuilogicLinkConds: [
                  {
                    condOP: 'ISNOTNULL',
                    dstFieldName: 'reply.value',
                    dstLogicParamId: 'editor',
                    logicType: 'SINGLE',
                    name: 'editor[reply.value] 值不为空(NotNil)',
                    id: 'editor[reply.value] 值不为空(notnil)',
                  },
                ],
                logicType: 'GROUP',
              },
              srcDEUILogicNodeId: 'preparejsparam5',
              id: '存在回复评论标识',
            },
          ],
          topPos: 380,
          parallelOutput: true,
          name: '无操作（仅用于连接）',
          id: 'preparejsparam5',
        },
        {
          codeName: 'PREPAREJSPARAM3',
          leftPos: 300,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'deaction3',
              srcDEUILogicNodeId: 'preparejsparam3',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstFieldName: 'id',
              dstDEUILogicParamId: 'comment',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'edit_comment_id',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              id: 'view[edit_comment_id] ==> comment[id]',
            },
            {
              dstFieldName: 'mail_message',
              dstDEUILogicParamId: 'ctx',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'edit_comment_id',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              id: 'view[edit_comment_id] ==> ctx[comment]',
            },
          ],
          topPos: 720,
          name: '设置评论id',
          id: 'preparejsparam3',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'ctx',
          navContextParam: true,
          name: '应用上下文变量',
          id: 'ctx',
        },
        {
          codeName: 'params',
          viewNavDataParam: true,
          name: '视图参数',
          id: 'params',
        },
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'comment',
          entityParam: true,
          name: '评论对象',
          id: 'comment',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '当前视图对象',
          id: 'view',
        },
        {
          codeName: 'editor',
          entityParam: true,
          name: '编辑器',
          id: 'editor',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '发送评论',
      id: 'send_comment',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'mail_message',
  deapicodeName: 'mail_message',
  deapicodeName2: 'mail_messages',
  deapitag: 'MAIL_MESSAGE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_MESSAGE',
  },
  logicName: '消息',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'mail_messages',
      majorAppDataEntityId: 'ehrapp.mail_thread',
      parentAppDEFieldId: 'res_id',
      rsmode: 2,
      name: '邮件会话-邮件消息',
      id: 'mail_messages',
    },
  ],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'MAIL_MESSAGE',
  id: 'ehrapp.mail_message',
  codeName2: 'mail_messages',
  requestPaths: ['mail_threads/${mail_thread}/mail_messages/${mail_message}'],
};
