export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'ehrapp.mail_activity_type',
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'search_act_data',
      logicName: 'search_act_data',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
        {
          appDEFieldId: 'chaining_type',
          dataType: 25,
          id: 'chaining_type',
        },
        {
          appDEFieldId: 'summary',
          dataType: 25,
          id: 'summary',
        },
        {
          appDEFieldId: 'default_note',
          dataType: 25,
          id: 'note',
        },
      ],
      pagingSize: 50,
      appDataEntityId: 'ehrapp.mail_activity_type',
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      id: 'search_act_data',
    },
  ],
  appDEFields: [
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'create_uid',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_date',
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'active',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.ACTIVE',
      },
      logicName: '有效',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACTIVE',
      id: 'active',
    },
    {
      codeName: 'keep_done',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.KEEP_DONE',
      },
      logicName: '保持完成',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'KEEP_DONE',
      id: 'keep_done',
    },
    {
      codeName: 'sequence',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.SEQUENCE',
      },
      logicName: '序列',
      predefinedType: 'ORDERVALUE',
      stdDataType: 9,
      name: 'SEQUENCE',
      id: 'sequence',
    },
    {
      codeName: 'delay_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DELAY_COUNT',
      },
      logicName: '安排',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'DELAY_COUNT',
      id: 'delay_count',
    },
    {
      codeName: 'default_note',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DEFAULT_NOTE',
      },
      logicName: '默认备注',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DEFAULT_NOTE',
      id: 'default_note',
    },
    {
      codeName: 'summary',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.SUMMARY',
      },
      logicName: '默认摘要',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SUMMARY',
      id: 'summary',
    },
    {
      codeName: 'icon',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.ICON',
      },
      logicName: '图标',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'ICON',
      id: 'icon',
    },
    {
      codeName: 'delay_from',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DELAY_FROM',
      },
      logicName: '延迟类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'DELAY_FROM',
      id: 'delay_from',
    },
    {
      codeName: 'delay_unit',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DELAY_UNIT',
      },
      logicName: '延迟单位',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'DELAY_UNIT',
      id: 'delay_unit',
    },
    {
      codeName: 'chaining_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.CHAINING_TYPE',
      },
      logicName: '链接类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CHAINING_TYPE',
      id: 'chaining_type',
    },
    {
      codeName: 'decoration_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DECORATION_TYPE',
      },
      logicName: '排版类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'DECORATION_TYPE',
      id: 'decoration_type',
    },
    {
      codeName: 'category',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.CATEGORY',
      },
      logicName: '操作',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CATEGORY',
      id: 'category',
    },
    {
      codeName: 'triggered_next_type_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.TRIGGERED_NEXT_TYPE_ID',
      },
      logicName: '触发方式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TRIGGERED_NEXT_TYPE_ID',
      id: 'triggered_next_type_id',
    },
    {
      codeName: 'default_user_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DEFAULT_USER_ID',
      },
      logicName: '默认用户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'DEFAULT_USER_ID',
      id: 'default_user_id',
    },
    {
      codeName: 'res_model_change',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.RES_MODEL_CHANGE',
      },
      logicName: '模型已更改',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'RES_MODEL_CHANGE',
      id: 'res_model_change',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'delay_label',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.DELAY_LABEL',
      },
      logicName: '延迟标签',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DELAY_LABEL',
      id: 'delay_label',
    },
    {
      codeName: 'triggered_next_type_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_TYPE.TRIGGERED_NEXT_TYPE_ID',
      },
      logicName: '触发方式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'TRIGGERED_NEXT_TYPE_NAME',
      id: 'triggered_next_type_name',
    },
    {
      codeName: 'res_model',
      logicName: '资源模型',
      predefinedType: 'PARENTTYPE',
      stdDataType: 25,
      stringLength: 200,
      name: 'RES_MODEL',
      id: 'res_model',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'mail_activity_type_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'active',
          logicName: '有效',
          appDEFieldId: 'active',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'active',
        },
        {
          codeName: 'category',
          logicName: '操作',
          appDEFieldId: 'category',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'category',
        },
        {
          codeName: 'chaining_type',
          logicName: '链接类型',
          appDEFieldId: 'chaining_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'chaining_type',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'decoration_type',
          logicName: '排版类型',
          appDEFieldId: 'decoration_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'decoration_type',
        },
        {
          codeName: 'default_note',
          logicName: '默认备注',
          appDEFieldId: 'default_note',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'default_note',
        },
        {
          codeName: 'default_user_id',
          logicName: '默认用户',
          appDEFieldId: 'default_user_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'default_user_id',
        },
        {
          codeName: 'delay_count',
          logicName: '安排',
          appDEFieldId: 'delay_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'delay_count',
        },
        {
          codeName: 'delay_from',
          logicName: '延迟类型',
          appDEFieldId: 'delay_from',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'delay_from',
        },
        {
          codeName: 'delay_label',
          logicName: '延迟标签',
          appDEFieldId: 'delay_label',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'delay_label',
        },
        {
          codeName: 'delay_unit',
          logicName: '延迟单位',
          appDEFieldId: 'delay_unit',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'delay_unit',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'icon',
          logicName: '图标',
          appDEFieldId: 'icon',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'icon',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'keep_done',
          logicName: '保持完成',
          appDEFieldId: 'keep_done',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'keep_done',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'res_model',
          logicName: '资源模型',
          appDEFieldId: 'res_model',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'res_model',
        },
        {
          codeName: 'res_model_change',
          logicName: '模型已更改',
          appDEFieldId: 'res_model_change',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'res_model_change',
        },
        {
          codeName: 'sequence',
          logicName: '序列',
          appDEFieldId: 'sequence',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sequence',
        },
        {
          codeName: 'summary',
          logicName: '默认摘要',
          appDEFieldId: 'summary',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'summary',
        },
        {
          codeName: 'triggered_next_type_id',
          logicName: '触发方式',
          appDEFieldId: 'triggered_next_type_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'triggered_next_type_id',
        },
        {
          codeName: 'triggered_next_type_name',
          logicName: '触发方式',
          appDEFieldId: 'triggered_next_type_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'triggered_next_type_name',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'mail_activity_type_dto',
    },
    {
      codeName: 'mail_activity_type_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_category_eq',
          logicName: '操作',
          appDEFieldId: 'category',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_category_eq',
        },
        {
          codeName: 'n_chaining_type_eq',
          logicName: '链接类型',
          appDEFieldId: 'chaining_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_chaining_type_eq',
        },
        {
          codeName: 'n_decoration_type_eq',
          logicName: '排版类型',
          appDEFieldId: 'decoration_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_decoration_type_eq',
        },
        {
          codeName: 'n_default_user_id_eq',
          logicName: '默认用户',
          appDEFieldId: 'default_user_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_default_user_id_eq',
        },
        {
          codeName: 'n_delay_from_eq',
          logicName: '延迟类型',
          appDEFieldId: 'delay_from',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_delay_from_eq',
        },
        {
          codeName: 'n_delay_unit_eq',
          logicName: '延迟单位',
          appDEFieldId: 'delay_unit',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_delay_unit_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_triggered_next_type_id_eq',
          logicName: '触发方式',
          appDEFieldId: 'triggered_next_type_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_triggered_next_type_id_eq',
        },
        {
          codeName: 'n_triggered_next_type_name_eq',
          logicName: '触发方式',
          appDEFieldId: 'triggered_next_type_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_triggered_next_type_name_eq',
        },
        {
          codeName: 'n_triggered_next_type_name_like',
          logicName: '触发方式',
          appDEFieldId: 'triggered_next_type_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_triggered_next_type_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'mail_activity_type_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_date_deadline',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'PUT',
      requestParamType: 'FIELD',
      requestPath: '/get_date_deadline',
      needResourceKey: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'get_date_deadline',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'move_order',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTOS',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/move_order',
      needResourceKey: true,
      actionMode: 'MOVEORDER',
      actionTag: 'MoveOrder',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'MoveOrder',
      id: 'move_order',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_activity_type_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_res_and_sys',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_activity_type_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_activity_type_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_res_and_sys',
      actionType: 'REMOTE',
      addedqconditions: [
        {
          condOp: 'EQ',
          condValue: 'srfmodelname',
          fieldName: 'RES_MODEL',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(RES_MODEL) 等于(=) 数据上下文 srfmodelname',
          id: '(res_model) 等于(=) 数据上下文 srfmodelname',
        },
      ],
      dataSetName: 'res_and_sys',
      dataSetTag: 'res_and_sys',
      dataSetType: 'REMOTE',
      id: 'fetch_res_and_sys',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'mail_activity_type',
  deapicodeName: 'mail_activity_type',
  deapicodeName2: 'mail_activity_types',
  deapitag: 'MAIL_ACTIVITY_TYPE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_ACTIVITY_TYPE',
  },
  logicName: '活动类型',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'MAIL_ACTIVITY_TYPE',
  id: 'ehrapp.mail_activity_type',
  codeName2: 'mail_activity_types',
  requestPaths: [],
};
