export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'ehrapp.res_company',
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'activities',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_MIXIN.ACTIVITIES',
      },
      logicName: '活动集合',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ACTIVITIES',
      id: 'activities',
    },
    {
      codeName: 'attachments',
      logicName: '附件集合',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
    {
      codeName: 'followers',
      logicName: '关注者',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'FOLLOWERS',
      id: 'followers',
    },
    {
      codeName: 'create_uid',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'create_date',
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'id',
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'name',
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'portal_confirmation_pay',
      logicName: '线上付款',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PORTAL_CONFIRMATION_PAY',
      id: 'portal_confirmation_pay',
    },
    {
      codeName: 'portal_confirmation_sign',
      logicName: '线上签署',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PORTAL_CONFIRMATION_SIGN',
      id: 'portal_confirmation_sign',
    },
    {
      codeName: 'iap_enrich_auto_done',
      logicName: '丰富完成',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IAP_ENRICH_AUTO_DONE',
      id: 'iap_enrich_auto_done',
    },
    {
      codeName: 'active',
      logicName: '有效',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACTIVE',
      id: 'active',
    },
    {
      codeName: 'uses_default_logo',
      logicName: '使用默认徽标',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'USES_DEFAULT_LOGO',
      id: 'uses_default_logo',
    },
    {
      codeName: 'snailmail_color',
      logicName: '实体邮寄颜色',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SNAILMAIL_COLOR',
      id: 'snailmail_color',
    },
    {
      codeName: 'snailmail_duplex',
      logicName: '双面',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SNAILMAIL_DUPLEX',
      id: 'snailmail_duplex',
    },
    {
      codeName: 'snailmail_cover',
      logicName: '添加一个封面页',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SNAILMAIL_COVER',
      id: 'snailmail_cover',
    },
    {
      codeName: 'hr_presence_control_attendance',
      logicName: '根据出勤率',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HR_PRESENCE_CONTROL_ATTENDANCE',
      id: 'hr_presence_control_attendance',
    },
    {
      codeName: 'hr_presence_control_email',
      logicName: '根据发送的电子邮件数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HR_PRESENCE_CONTROL_EMAIL',
      id: 'hr_presence_control_email',
    },
    {
      codeName: 'hr_presence_control_login',
      logicName: '基于系统中的用户状态',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HR_PRESENCE_CONTROL_LOGIN',
      id: 'hr_presence_control_login',
    },
    {
      codeName: 'hr_presence_control_ip',
      logicName: '基于IP地址',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HR_PRESENCE_CONTROL_IP',
      id: 'hr_presence_control_ip',
    },
    {
      codeName: 'expects_chart_of_accounts',
      logicName: 'Expects a Chart of Accounts',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'EXPECTS_CHART_OF_ACCOUNTS',
      id: 'expects_chart_of_accounts',
    },
    {
      codeName: 'autopost_bills',
      logicName: '自动验证账单',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'AUTOPOST_BILLS',
      id: 'autopost_bills',
    },
    {
      codeName: 'tax_exigibility',
      logicName: '采用现金收付',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'TAX_EXIGIBILITY',
      id: 'tax_exigibility',
    },
    {
      codeName: 'check_account_audit_trail',
      logicName: '审计跟踪',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'CHECK_ACCOUNT_AUDIT_TRAIL',
      id: 'check_account_audit_trail',
    },
    {
      codeName: 'qr_code',
      logicName: 'Display QR-code on invoices',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'QR_CODE',
      id: 'qr_code',
    },
    {
      codeName: 'account_use_credit_limit',
      logicName: '销售信用额度',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACCOUNT_USE_CREDIT_LIMIT',
      id: 'account_use_credit_limit',
    },
    {
      codeName: 'display_invoice_tax_company_currency',
      logicName: '税款以公司币别表示',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'DISPLAY_INVOICE_TAX_COMPANY_CURRENCY',
      id: 'display_invoice_tax_company_currency',
    },
    {
      codeName: 'account_storno',
      logicName: 'Storno会计应用程序',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACCOUNT_STORNO',
      id: 'account_storno',
    },
    {
      codeName: 'anglo_saxon_accounting',
      logicName: '使用盎格鲁撒克逊会计',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ANGLO_SAXON_ACCOUNTING',
      id: 'anglo_saxon_accounting',
    },
    {
      codeName: 'display_invoice_amount_total_words',
      logicName: '大写发票总额',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'DISPLAY_INVOICE_AMOUNT_TOTAL_WORDS',
      id: 'display_invoice_amount_total_words',
    },
    {
      codeName: 'absence_management',
      logicName: '缺勤管理',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ABSENCE_MANAGEMENT',
      id: 'absence_management',
    },
    {
      codeName: 'attendance_kiosk_use_pin',
      logicName: '员工PIN',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ATTENDANCE_KIOSK_USE_PIN',
      id: 'attendance_kiosk_use_pin',
    },
    {
      codeName: 'hr_attendance_display_overtime',
      logicName: '显示额外时间',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HR_ATTENDANCE_DISPLAY_OVERTIME',
      id: 'hr_attendance_display_overtime',
    },
    {
      codeName: 'stock_move_email_validation',
      logicName: '邮件确认拣货',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'STOCK_MOVE_EMAIL_VALIDATION',
      id: 'stock_move_email_validation',
    },
    {
      codeName: 'has_received_warning_stock_sms',
      logicName: '已收到库存警告短信息',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HAS_RECEIVED_WARNING_STOCK_SMS',
      id: 'has_received_warning_stock_sms',
    },
    {
      codeName: 'auto_check_out',
      logicName: '自动签退',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'AUTO_CHECK_OUT',
      id: 'auto_check_out',
    },
    {
      codeName: 'attendance_from_systray',
      logicName: '来自 Systray 的出席情况',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ATTENDANCE_FROM_SYSTRAY',
      id: 'attendance_from_systray',
    },
    {
      codeName: 'stock_move_sms_validation',
      logicName: '短信息确认',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'STOCK_MOVE_SMS_VALIDATION',
      id: 'stock_move_sms_validation',
    },
    {
      codeName: 'sale_onboarding_payment_method',
      logicName: '销售入门选择的付款方式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'SALE_ONBOARDING_PAYMENT_METHOD',
      id: 'sale_onboarding_payment_method',
    },
    {
      codeName: 'font',
      logicName: '字体',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'FONT',
      id: 'font',
    },
    {
      codeName: 'layout_background',
      logicName: '布局背景',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'LAYOUT_BACKGROUND',
      id: 'layout_background',
    },
    {
      codeName: 'payment_onboarding_payment_method',
      logicName: '选择支付方式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'PAYMENT_ONBOARDING_PAYMENT_METHOD',
      id: 'payment_onboarding_payment_method',
    },
    {
      codeName: 'po_double_validation',
      logicName: '批准等级',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'PO_DOUBLE_VALIDATION',
      id: 'po_double_validation',
    },
    {
      codeName: 'po_lock',
      logicName: '销售订单修改',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'PO_LOCK',
      id: 'po_lock',
    },
    {
      codeName: 'terms_type',
      logicName: 'Terms & Conditions format',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'TERMS_TYPE',
      id: 'terms_type',
    },
    {
      codeName: 'annual_inventory_month',
      logicName: '年度库存月',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ANNUAL_INVENTORY_MONTH',
      id: 'annual_inventory_month',
    },
    {
      codeName: 'account_price_include',
      logicName: 'Default Sales Price Include',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ACCOUNT_PRICE_INCLUDE',
      id: 'account_price_include',
    },
    {
      codeName: 'attendance_overtime_validation',
      logicName: '额外工时验证',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ATTENDANCE_OVERTIME_VALIDATION',
      id: 'attendance_overtime_validation',
    },
    {
      codeName: 'quick_edit_mode',
      logicName: '快速编码',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'QUICK_EDIT_MODE',
      id: 'quick_edit_mode',
    },
    {
      codeName: 'tax_calculation_rounding_method',
      logicName: 'Tax Calculation Rounding Method',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'TAX_CALCULATION_ROUNDING_METHOD',
      id: 'tax_calculation_rounding_method',
    },
    {
      codeName: 'fiscalyear_last_month',
      logicName: '会计年度最后一个月',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'FISCALYEAR_LAST_MONTH',
      id: 'fiscalyear_last_month',
    },
    {
      codeName: 'attendance_barcode_source',
      logicName: '条码来源',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ATTENDANCE_BARCODE_SOURCE',
      id: 'attendance_barcode_source',
    },
    {
      codeName: 'attendance_kiosk_mode',
      logicName: '考勤模式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ATTENDANCE_KIOSK_MODE',
      id: 'attendance_kiosk_mode',
    },
    {
      codeName: 'po_double_validation_amount',
      logicName: '再次验证金额',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'PO_DOUBLE_VALIDATION_AMOUNT',
      id: 'po_double_validation_amount',
    },
    {
      codeName: 'quotation_validity_days',
      logicName: '默认报价有效期',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'QUOTATION_VALIDITY_DAYS',
      id: 'quotation_validity_days',
    },
    {
      codeName: 'sequence',
      logicName: '序列',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SEQUENCE',
      id: 'sequence',
    },
    {
      codeName: 'hr_presence_control_email_amount',
      logicName: '# 要发送的电子邮件',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HR_PRESENCE_CONTROL_EMAIL_AMOUNT',
      id: 'hr_presence_control_email_amount',
    },
    {
      codeName: 'fiscalyear_last_day',
      logicName: '会计年度最后一天',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'FISCALYEAR_LAST_DAY',
      id: 'fiscalyear_last_day',
    },
    {
      codeName: 'annual_inventory_day',
      logicName: '日期',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ANNUAL_INVENTORY_DAY',
      id: 'annual_inventory_day',
    },
    {
      codeName: 'contract_expiration_notice_period',
      logicName: '合同到期通知期',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'CONTRACT_EXPIRATION_NOTICE_PERIOD',
      id: 'contract_expiration_notice_period',
    },
    {
      codeName: 'attendance_kiosk_delay',
      logicName: '自助考勤终端延迟',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ATTENDANCE_KIOSK_DELAY',
      id: 'attendance_kiosk_delay',
    },
    {
      codeName: 'overtime_employee_threshold',
      logicName: '对员工有利的宽容时间',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'OVERTIME_EMPLOYEE_THRESHOLD',
      id: 'overtime_employee_threshold',
    },
    {
      codeName: 'overtime_company_threshold',
      logicName: '对公司有利的宽容时间',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'OVERTIME_COMPANY_THRESHOLD',
      id: 'overtime_company_threshold',
    },
    {
      codeName: 'work_permit_expiration_notice_period',
      logicName: '工作许可证到期通知期',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'WORK_PERMIT_EXPIRATION_NOTICE_PERIOD',
      id: 'work_permit_expiration_notice_period',
    },
    {
      codeName: 'report_header',
      logicName: '公司标语',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'REPORT_HEADER',
      id: 'report_header',
    },
    {
      codeName: 'invoice_terms',
      logicName: 'Default Terms and Conditions',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'INVOICE_TERMS',
      id: 'invoice_terms',
    },
    {
      codeName: 'report_footer',
      logicName: '报告页脚',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'REPORT_FOOTER',
      id: 'report_footer',
    },
    {
      codeName: 'company_details',
      logicName: '公司详情',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'COMPANY_DETAILS',
      id: 'company_details',
    },
    {
      codeName: 'invoice_terms_html',
      logicName: 'Default Terms and Conditions as a Web page',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'INVOICE_TERMS_HTML',
      id: 'invoice_terms_html',
    },
    {
      codeName: 'prepayment_percent',
      logicName: '预付百分比',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'PREPAYMENT_PERCENT',
      id: 'prepayment_percent',
    },
    {
      codeName: 'auto_check_out_tolerance',
      logicName: 'null',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'AUTO_CHECK_OUT_TOLERANCE',
      id: 'auto_check_out_tolerance',
    },
    {
      codeName: 'po_lead',
      logicName: '采购提前期',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'PO_LEAD',
      id: 'po_lead',
    },
    {
      codeName: 'manufacturing_lead',
      logicName: '制造提前期',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'MANUFACTURING_LEAD',
      id: 'manufacturing_lead',
    },
    {
      codeName: 'security_lead',
      logicName: '销售安全天数',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'SECURITY_LEAD',
      id: 'security_lead',
    },
    {
      codeName: 'days_to_purchase',
      logicName: '采购前置天数',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'DAYS_TO_PURCHASE',
      id: 'days_to_purchase',
    },
    {
      codeName: 'job_properties_definition',
      logicName: '职位属性',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'JOB_PROPERTIES_DEFINITION',
      id: 'job_properties_definition',
    },
    {
      codeName: 'employee_properties_definition',
      logicName: '员工属性',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'EMPLOYEE_PROPERTIES_DEFINITION',
      id: 'employee_properties_definition',
    },
    {
      codeName: 'candidate_properties_definition',
      logicName: '候选人属性',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CANDIDATE_PROPERTIES_DEFINITION',
      id: 'candidate_properties_definition',
    },
    {
      codeName: 'sale_lock_date',
      logicName: '销售锁定日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'SALE_LOCK_DATE',
      id: 'sale_lock_date',
    },
    {
      codeName: 'tax_lock_date',
      logicName: '纳税申报表锁定日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'TAX_LOCK_DATE',
      id: 'tax_lock_date',
    },
    {
      codeName: 'fiscalyear_lock_date',
      logicName: '全球锁定日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'FISCALYEAR_LOCK_DATE',
      id: 'fiscalyear_lock_date',
    },
    {
      codeName: 'hard_lock_date',
      logicName: '硬锁定日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'HARD_LOCK_DATE',
      id: 'hard_lock_date',
    },
    {
      codeName: 'account_opening_date',
      logicName: '期初分录',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'ACCOUNT_OPENING_DATE',
      id: 'account_opening_date',
    },
    {
      codeName: 'purchase_lock_date',
      logicName: '采购锁定日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'PURCHASE_LOCK_DATE',
      id: 'purchase_lock_date',
    },
    {
      codeName: 'social_github',
      logicName: 'GitHub账户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SOCIAL_GITHUB',
      id: 'social_github',
    },
    {
      codeName: 'social_twitter',
      logicName: 'X 账户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SOCIAL_TWITTER',
      id: 'social_twitter',
    },
    {
      codeName: 'social_facebook',
      logicName: 'Facebook 账户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SOCIAL_FACEBOOK',
      id: 'social_facebook',
    },
    {
      codeName: 'social_tiktok',
      logicName: 'TikTok / 抖音账号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SOCIAL_TIKTOK',
      id: 'social_tiktok',
    },
    {
      codeName: 'social_linkedin',
      logicName: '领英账号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SOCIAL_LINKEDIN',
      id: 'social_linkedin',
    },
    {
      codeName: 'social_instagram',
      logicName: 'Instagram 账号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SOCIAL_INSTAGRAM',
      id: 'social_instagram',
    },
    {
      codeName: 'social_youtube',
      logicName: 'Youtube账号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SOCIAL_YOUTUBE',
      id: 'social_youtube',
    },
    {
      codeName: 'primary_color',
      logicName: '原色',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'PRIMARY_COLOR',
      id: 'primary_color',
    },
    {
      codeName: 'secondary_color',
      logicName: '次要颜色',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SECONDARY_COLOR',
      id: 'secondary_color',
    },
    {
      codeName: 'email_primary_color',
      logicName: '电子邮件标题颜色',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'EMAIL_PRIMARY_COLOR',
      id: 'email_primary_color',
    },
    {
      codeName: 'email_secondary_color',
      logicName: '电子邮件按钮颜色',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'EMAIL_SECONDARY_COLOR',
      id: 'email_secondary_color',
    },
    {
      codeName: 'parent_path',
      logicName: '上级路径',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'PARENT_PATH',
      id: 'parent_path',
    },
    {
      codeName: 'hr_presence_control_ip_list',
      logicName: '有效的IP地址',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'HR_PRESENCE_CONTROL_IP_LIST',
      id: 'hr_presence_control_ip_list',
    },
    {
      codeName: 'bank_account_code_prefix',
      logicName: 'Prefix of the bank accounts',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'BANK_ACCOUNT_CODE_PREFIX',
      id: 'bank_account_code_prefix',
    },
    {
      codeName: 'transfer_account_code_prefix',
      logicName: 'Prefix of the transfer accounts',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'TRANSFER_ACCOUNT_CODE_PREFIX',
      id: 'transfer_account_code_prefix',
    },
    {
      codeName: 'attendance_kiosk_key',
      logicName: '自助考勤终端密钥',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'ATTENDANCE_KIOSK_KEY',
      id: 'attendance_kiosk_key',
    },
    {
      codeName: 'cash_account_code_prefix',
      logicName: 'Prefix of the cash accounts',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'CASH_ACCOUNT_CODE_PREFIX',
      id: 'cash_account_code_prefix',
    },
    {
      codeName: 'alias_domain_id',
      logicName: '电子邮件域名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ALIAS_DOMAIN_ID',
      id: 'alias_domain_id',
    },
    {
      codeName: 'currency_id',
      logicName: '币别',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CURRENCY_ID',
      id: 'currency_id',
    },
    {
      codeName: 'partner_id',
      logicName: '合作伙伴',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARTNER_ID',
      id: 'partner_id',
    },
    {
      codeName: 'parent_id',
      logicName: '上级公司',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARENT_ID',
      id: 'parent_id',
    },
    {
      codeName: 'batch_payment_sequence_id',
      logicName: 'Batch Payment Sequence',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'BATCH_PAYMENT_SEQUENCE_ID',
      id: 'batch_payment_sequence_id',
    },
    {
      codeName: 'account_fiscal_country_id',
      logicName: '会计所在国家/地区',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ACCOUNT_FISCAL_COUNTRY_ID',
      id: 'account_fiscal_country_id',
    },
    {
      codeName: 'stock_mail_confirmation_template_id',
      logicName: '确认拣货邮件模版',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'STOCK_MAIL_CONFIRMATION_TEMPLATE_ID',
      id: 'stock_mail_confirmation_template_id',
    },
    {
      codeName: 'is_company_details_empty',
      logicName: '公司详细信息是否为空',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_COMPANY_DETAILS_EMPTY',
      id: 'is_company_details_empty',
    },
    {
      codeName: 'has_message',
      logicName: '有消息',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HAS_MESSAGE',
      id: 'has_message',
    },
    {
      codeName: 'message_is_follower',
      logicName: '是关注者',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_IS_FOLLOWER',
      id: 'message_is_follower',
    },
    {
      codeName: 'message_needaction',
      logicName: '待处理',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_NEEDACTION',
      id: 'message_needaction',
    },
    {
      codeName: 'message_has_error',
      logicName: 'Message Delivery error',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_ERROR',
      id: 'message_has_error',
    },
    {
      codeName: 'message_has_sms_error',
      logicName: '短信发送错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_SMS_ERROR',
      id: 'message_has_sms_error',
    },
    {
      codeName: 'user_fiscalyear_lock_date',
      logicName: '用户财政年度锁定日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'USER_FISCALYEAR_LOCK_DATE',
      id: 'user_fiscalyear_lock_date',
    },
    {
      codeName: 'user_tax_lock_date',
      logicName: 'User Tax Lock Date',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'USER_TAX_LOCK_DATE',
      id: 'user_tax_lock_date',
    },
    {
      codeName: 'color',
      logicName: '颜色',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'COLOR',
      id: 'color',
    },
    {
      codeName: 'user_hard_lock_date',
      logicName: '用户硬性锁定日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'USER_HARD_LOCK_DATE',
      id: 'user_hard_lock_date',
    },
    {
      codeName: 'user_purchase_lock_date',
      logicName: '用户采购锁定日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'USER_PURCHASE_LOCK_DATE',
      id: 'user_purchase_lock_date',
    },
    {
      codeName: 'user_sale_lock_date',
      logicName: '用户销售锁定日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'USER_SALE_LOCK_DATE',
      id: 'user_sale_lock_date',
    },
    {
      codeName: 'message_attachment_count',
      logicName: 'Attachment Count',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_ATTACHMENT_COUNT',
      id: 'message_attachment_count',
    },
    {
      codeName: 'message_needaction_counter',
      logicName: '操作数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_NEEDACTION_COUNTER',
      id: 'message_needaction_counter',
    },
    {
      codeName: 'message_has_error_counter',
      logicName: '错误数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_ERROR_COUNTER',
      id: 'message_has_error_counter',
    },
    {
      codeName: 'bounce_email',
      logicName: '退件电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'BOUNCE_EMAIL',
      id: 'bounce_email',
    },
    {
      codeName: 'street',
      logicName: '街道',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'STREET',
      id: 'street',
    },
    {
      codeName: 'bounce_formatted',
      logicName: '退回',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'BOUNCE_FORMATTED',
      id: 'bounce_formatted',
    },
    {
      codeName: 'zip',
      logicName: '邮编',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'ZIP',
      id: 'zip',
    },
    {
      codeName: 'city',
      logicName: '城市',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'CITY',
      id: 'city',
    },
    {
      codeName: 'street2',
      logicName: '详细地址',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'STREET2',
      id: 'street2',
    },
    {
      codeName: 'catchall_formatted',
      logicName: '预设',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'CATCHALL_FORMATTED',
      id: 'catchall_formatted',
    },
    {
      codeName: 'email_formatted',
      logicName: '格式化的邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'EMAIL_FORMATTED',
      id: 'email_formatted',
    },
    {
      codeName: 'catchall_email',
      logicName: '预设邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'CATCHALL_EMAIL',
      id: 'catchall_email',
    },
    {
      codeName: 'display_name',
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'company_registry_placeholder',
      logicName: '公司注册处占位符',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'COMPANY_REGISTRY_PLACEHOLDER',
      id: 'company_registry_placeholder',
    },
    {
      codeName: 'attendance_kiosk_url',
      logicName: '自助考勤终端网址',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'ATTENDANCE_KIOSK_URL',
      id: 'attendance_kiosk_url',
    },
    {
      codeName: 'company_vat_placeholder',
      logicName: '公司增值税占位符',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'COMPANY_VAT_PLACEHOLDER',
      id: 'company_vat_placeholder',
    },
    {
      codeName: 'resource_calendar_id',
      logicName: '默认工作时间',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'RESOURCE_CALENDAR_ID',
      id: 'resource_calendar_id',
    },
    {
      codeName: 'partner_name',
      logicName: '合作伙伴',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PARTNER_NAME',
      id: 'partner_name',
    },
    {
      codeName: 'currency_name',
      logicName: '币别',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'CURRENCY_NAME',
      id: 'currency_name',
    },
    {
      codeName: 'parent_name',
      logicName: '上级公司',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PARENT_NAME',
      id: 'parent_name',
    },
    {
      codeName: 'activity_state',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_MIXIN.ACTIVITY_STATE',
      },
      logicName: '活动状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACTIVITY_STATE',
      id: 'activity_state',
    },
    {
      codeName: 'activity_date_deadline',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_MIXIN.ACTIVITY_DATE_DEADLINE',
      },
      logicName: '下一活动截止日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'ACTIVITY_DATE_DEADLINE',
      id: 'activity_date_deadline',
    },
    {
      codeName: 'activity_exception_decoration',
      lnlanguageRes: {
        lanResTag:
          'DEF.LNAME.MAIL_ACTIVITY_MIXIN.ACTIVITY_EXCEPTION_DECORATION',
      },
      logicName: '活动异常标示',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ACTIVITY_EXCEPTION_DECORATION',
      id: 'activity_exception_decoration',
    },
    {
      codeName: 'activity_exception_icon',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_MIXIN.ACTIVITY_EXCEPTION_ICON',
      },
      logicName: '图标',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'ACTIVITY_EXCEPTION_ICON',
      id: 'activity_exception_icon',
    },
    {
      codeName: 'my_activity_date_deadline',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_ACTIVITY_MIXIN.MY_ACTIVITY_DATE_DEADLINE',
      },
      logicName: '我的活动截止时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'MY_ACTIVITY_DATE_DEADLINE',
      id: 'my_activity_date_deadline',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'res_company_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'activities',
          logicName: '活动集合',
          appDEFieldId: 'activities',
          refAppDEMethodDTOId: 'mail_activity_dto',
          refAppDataEntityId: 'ehrapp.mail_activity',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'activities',
        },
        {
          codeName: 'attachments',
          logicName: '附件集合',
          appDEFieldId: 'attachments',
          refAppDEMethodDTOId: 'ir_attachment_dto',
          refAppDataEntityId: 'ehrapp.ir_attachment',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'followers',
          logicName: '关注者',
          appDEFieldId: 'followers',
          refAppDEMethodDTOId: 'mail_followers_dto',
          refAppDataEntityId: 'ehrapp.mail_followers',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'followers',
        },
        {
          codeName: 'absence_management',
          logicName: '缺勤管理',
          appDEFieldId: 'absence_management',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'absence_management',
        },
        {
          codeName: 'account_fiscal_country_id',
          logicName: '会计所在国家/地区',
          appDEFieldId: 'account_fiscal_country_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_fiscal_country_id',
        },
        {
          codeName: 'account_opening_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '期初分录',
          appDEFieldId: 'account_opening_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_opening_date',
        },
        {
          codeName: 'account_price_include',
          logicName: 'Default Sales Price Include',
          appDEFieldId: 'account_price_include',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_price_include',
        },
        {
          codeName: 'account_storno',
          logicName: 'Storno会计应用程序',
          appDEFieldId: 'account_storno',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_storno',
        },
        {
          codeName: 'account_use_credit_limit',
          logicName: '销售信用额度',
          appDEFieldId: 'account_use_credit_limit',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'account_use_credit_limit',
        },
        {
          codeName: 'active',
          logicName: '有效',
          appDEFieldId: 'active',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'active',
        },
        {
          codeName: 'activity_date_deadline',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '下一活动截止日期',
          appDEFieldId: 'activity_date_deadline',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_date_deadline',
        },
        {
          codeName: 'activity_exception_decoration',
          logicName: '活动异常标示',
          appDEFieldId: 'activity_exception_decoration',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_exception_decoration',
        },
        {
          codeName: 'activity_exception_icon',
          logicName: '图标',
          appDEFieldId: 'activity_exception_icon',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_exception_icon',
        },
        {
          codeName: 'activity_state',
          logicName: '活动状态',
          appDEFieldId: 'activity_state',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'activity_state',
        },
        {
          codeName: 'alias_domain_id',
          logicName: '电子邮件域名',
          appDEFieldId: 'alias_domain_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'alias_domain_id',
        },
        {
          codeName: 'anglo_saxon_accounting',
          logicName: '使用盎格鲁撒克逊会计',
          appDEFieldId: 'anglo_saxon_accounting',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'anglo_saxon_accounting',
        },
        {
          codeName: 'annual_inventory_day',
          logicName: '日期',
          appDEFieldId: 'annual_inventory_day',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'annual_inventory_day',
        },
        {
          codeName: 'annual_inventory_month',
          logicName: '年度库存月',
          appDEFieldId: 'annual_inventory_month',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'annual_inventory_month',
        },
        {
          codeName: 'attendance_barcode_source',
          logicName: '条码来源',
          appDEFieldId: 'attendance_barcode_source',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'attendance_barcode_source',
        },
        {
          codeName: 'attendance_from_systray',
          logicName: '来自 Systray 的出席情况',
          appDEFieldId: 'attendance_from_systray',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'attendance_from_systray',
        },
        {
          codeName: 'attendance_kiosk_delay',
          logicName: '自助考勤终端延迟',
          appDEFieldId: 'attendance_kiosk_delay',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'attendance_kiosk_delay',
        },
        {
          codeName: 'attendance_kiosk_key',
          logicName: '自助考勤终端密钥',
          appDEFieldId: 'attendance_kiosk_key',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'attendance_kiosk_key',
        },
        {
          codeName: 'attendance_kiosk_mode',
          logicName: '考勤模式',
          appDEFieldId: 'attendance_kiosk_mode',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'attendance_kiosk_mode',
        },
        {
          codeName: 'attendance_kiosk_url',
          logicName: '自助考勤终端网址',
          appDEFieldId: 'attendance_kiosk_url',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'attendance_kiosk_url',
        },
        {
          codeName: 'attendance_kiosk_use_pin',
          logicName: '员工PIN',
          appDEFieldId: 'attendance_kiosk_use_pin',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'attendance_kiosk_use_pin',
        },
        {
          codeName: 'attendance_overtime_validation',
          logicName: '额外工时验证',
          appDEFieldId: 'attendance_overtime_validation',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'attendance_overtime_validation',
        },
        {
          codeName: 'auto_check_out',
          logicName: '自动签退',
          appDEFieldId: 'auto_check_out',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'auto_check_out',
        },
        {
          codeName: 'auto_check_out_tolerance',
          logicName: 'null',
          appDEFieldId: 'auto_check_out_tolerance',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'auto_check_out_tolerance',
        },
        {
          codeName: 'autopost_bills',
          logicName: '自动验证账单',
          appDEFieldId: 'autopost_bills',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'autopost_bills',
        },
        {
          codeName: 'bank_account_code_prefix',
          logicName: 'Prefix of the bank accounts',
          appDEFieldId: 'bank_account_code_prefix',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'bank_account_code_prefix',
        },
        {
          codeName: 'batch_payment_sequence_id',
          logicName: 'Batch Payment Sequence',
          appDEFieldId: 'batch_payment_sequence_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'batch_payment_sequence_id',
        },
        {
          codeName: 'bounce_email',
          logicName: '退件电子邮件',
          appDEFieldId: 'bounce_email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'bounce_email',
        },
        {
          codeName: 'bounce_formatted',
          logicName: '退回',
          appDEFieldId: 'bounce_formatted',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'bounce_formatted',
        },
        {
          codeName: 'candidate_properties_definition',
          logicName: '候选人属性',
          appDEFieldId: 'candidate_properties_definition',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'candidate_properties_definition',
        },
        {
          codeName: 'cash_account_code_prefix',
          logicName: 'Prefix of the cash accounts',
          appDEFieldId: 'cash_account_code_prefix',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'cash_account_code_prefix',
        },
        {
          codeName: 'catchall_email',
          logicName: '预设邮件',
          appDEFieldId: 'catchall_email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'catchall_email',
        },
        {
          codeName: 'catchall_formatted',
          logicName: '预设',
          appDEFieldId: 'catchall_formatted',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'catchall_formatted',
        },
        {
          codeName: 'check_account_audit_trail',
          logicName: '审计跟踪',
          appDEFieldId: 'check_account_audit_trail',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'check_account_audit_trail',
        },
        {
          codeName: 'city',
          logicName: '城市',
          appDEFieldId: 'city',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'city',
        },
        {
          codeName: 'color',
          logicName: '颜色',
          appDEFieldId: 'color',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'color',
        },
        {
          codeName: 'company_details',
          logicName: '公司详情',
          appDEFieldId: 'company_details',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company_details',
        },
        {
          codeName: 'company_registry_placeholder',
          logicName: '公司注册处占位符',
          appDEFieldId: 'company_registry_placeholder',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company_registry_placeholder',
        },
        {
          codeName: 'company_vat_placeholder',
          logicName: '公司增值税占位符',
          appDEFieldId: 'company_vat_placeholder',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company_vat_placeholder',
        },
        {
          codeName: 'contract_expiration_notice_period',
          logicName: '合同到期通知期',
          appDEFieldId: 'contract_expiration_notice_period',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'contract_expiration_notice_period',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'currency_id',
          logicName: '币别',
          appDEFieldId: 'currency_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'currency_id',
        },
        {
          codeName: 'currency_name',
          logicName: '币别',
          appDEFieldId: 'currency_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'currency_name',
        },
        {
          codeName: 'days_to_purchase',
          logicName: '采购前置天数',
          appDEFieldId: 'days_to_purchase',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'days_to_purchase',
        },
        {
          codeName: 'display_invoice_amount_total_words',
          logicName: '大写发票总额',
          appDEFieldId: 'display_invoice_amount_total_words',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_invoice_amount_total_words',
        },
        {
          codeName: 'display_invoice_tax_company_currency',
          logicName: '税款以公司币别表示',
          appDEFieldId: 'display_invoice_tax_company_currency',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_invoice_tax_company_currency',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'email_formatted',
          logicName: '格式化的邮件',
          appDEFieldId: 'email_formatted',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_formatted',
        },
        {
          codeName: 'email_primary_color',
          logicName: '电子邮件标题颜色',
          appDEFieldId: 'email_primary_color',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_primary_color',
        },
        {
          codeName: 'email_secondary_color',
          logicName: '电子邮件按钮颜色',
          appDEFieldId: 'email_secondary_color',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_secondary_color',
        },
        {
          codeName: 'employee_properties_definition',
          logicName: '员工属性',
          appDEFieldId: 'employee_properties_definition',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'employee_properties_definition',
        },
        {
          codeName: 'expects_chart_of_accounts',
          logicName: 'Expects a Chart of Accounts',
          appDEFieldId: 'expects_chart_of_accounts',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'expects_chart_of_accounts',
        },
        {
          codeName: 'fiscalyear_last_day',
          logicName: '会计年度最后一天',
          appDEFieldId: 'fiscalyear_last_day',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'fiscalyear_last_day',
        },
        {
          codeName: 'fiscalyear_last_month',
          logicName: '会计年度最后一个月',
          appDEFieldId: 'fiscalyear_last_month',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'fiscalyear_last_month',
        },
        {
          codeName: 'fiscalyear_lock_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '全球锁定日期',
          appDEFieldId: 'fiscalyear_lock_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'fiscalyear_lock_date',
        },
        {
          codeName: 'font',
          logicName: '字体',
          appDEFieldId: 'font',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'font',
        },
        {
          codeName: 'hard_lock_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '硬锁定日期',
          appDEFieldId: 'hard_lock_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'hard_lock_date',
        },
        {
          codeName: 'has_message',
          logicName: '有消息',
          appDEFieldId: 'has_message',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'has_message',
        },
        {
          codeName: 'has_received_warning_stock_sms',
          logicName: '已收到库存警告短信息',
          appDEFieldId: 'has_received_warning_stock_sms',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'has_received_warning_stock_sms',
        },
        {
          codeName: 'hr_attendance_display_overtime',
          logicName: '显示额外时间',
          appDEFieldId: 'hr_attendance_display_overtime',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'hr_attendance_display_overtime',
        },
        {
          codeName: 'hr_presence_control_attendance',
          logicName: '根据出勤率',
          appDEFieldId: 'hr_presence_control_attendance',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'hr_presence_control_attendance',
        },
        {
          codeName: 'hr_presence_control_email',
          logicName: '根据发送的电子邮件数量',
          appDEFieldId: 'hr_presence_control_email',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'hr_presence_control_email',
        },
        {
          codeName: 'hr_presence_control_email_amount',
          logicName: '# 要发送的电子邮件',
          appDEFieldId: 'hr_presence_control_email_amount',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'hr_presence_control_email_amount',
        },
        {
          codeName: 'hr_presence_control_ip',
          logicName: '基于IP地址',
          appDEFieldId: 'hr_presence_control_ip',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'hr_presence_control_ip',
        },
        {
          codeName: 'hr_presence_control_ip_list',
          logicName: '有效的IP地址',
          appDEFieldId: 'hr_presence_control_ip_list',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'hr_presence_control_ip_list',
        },
        {
          codeName: 'hr_presence_control_login',
          logicName: '基于系统中的用户状态',
          appDEFieldId: 'hr_presence_control_login',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'hr_presence_control_login',
        },
        {
          codeName: 'iap_enrich_auto_done',
          logicName: '丰富完成',
          appDEFieldId: 'iap_enrich_auto_done',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'iap_enrich_auto_done',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'invoice_terms',
          logicName: 'Default Terms and Conditions',
          appDEFieldId: 'invoice_terms',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'invoice_terms',
        },
        {
          codeName: 'invoice_terms_html',
          logicName: 'Default Terms and Conditions as a Web page',
          appDEFieldId: 'invoice_terms_html',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'invoice_terms_html',
        },
        {
          codeName: 'is_company_details_empty',
          logicName: '公司详细信息是否为空',
          appDEFieldId: 'is_company_details_empty',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_company_details_empty',
        },
        {
          codeName: 'job_properties_definition',
          logicName: '职位属性',
          appDEFieldId: 'job_properties_definition',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'job_properties_definition',
        },
        {
          codeName: 'layout_background',
          logicName: '布局背景',
          appDEFieldId: 'layout_background',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'layout_background',
        },
        {
          codeName: 'manufacturing_lead',
          logicName: '制造提前期',
          appDEFieldId: 'manufacturing_lead',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'manufacturing_lead',
        },
        {
          codeName: 'message_attachment_count',
          logicName: 'Attachment Count',
          appDEFieldId: 'message_attachment_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_attachment_count',
        },
        {
          codeName: 'message_has_error',
          logicName: 'Message Delivery error',
          appDEFieldId: 'message_has_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_error',
        },
        {
          codeName: 'message_has_error_counter',
          logicName: '错误数量',
          appDEFieldId: 'message_has_error_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_error_counter',
        },
        {
          codeName: 'message_has_sms_error',
          logicName: '短信发送错误',
          appDEFieldId: 'message_has_sms_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_sms_error',
        },
        {
          codeName: 'message_is_follower',
          logicName: '是关注者',
          appDEFieldId: 'message_is_follower',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_is_follower',
        },
        {
          codeName: 'message_needaction',
          logicName: '待处理',
          appDEFieldId: 'message_needaction',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_needaction',
        },
        {
          codeName: 'message_needaction_counter',
          logicName: '操作数量',
          appDEFieldId: 'message_needaction_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_needaction_counter',
        },
        {
          codeName: 'my_activity_date_deadline',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '我的活动截止时间',
          appDEFieldId: 'my_activity_date_deadline',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'my_activity_date_deadline',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'overtime_company_threshold',
          logicName: '对公司有利的宽容时间',
          appDEFieldId: 'overtime_company_threshold',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'overtime_company_threshold',
        },
        {
          codeName: 'overtime_employee_threshold',
          logicName: '对员工有利的宽容时间',
          appDEFieldId: 'overtime_employee_threshold',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'overtime_employee_threshold',
        },
        {
          codeName: 'parent_id',
          logicName: '上级公司',
          appDEFieldId: 'parent_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_id',
        },
        {
          codeName: 'parent_name',
          logicName: '上级公司',
          appDEFieldId: 'parent_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_name',
        },
        {
          codeName: 'parent_path',
          logicName: '上级路径',
          appDEFieldId: 'parent_path',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'parent_path',
        },
        {
          codeName: 'partner_id',
          logicName: '合作伙伴',
          appDEFieldId: 'partner_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'partner_id',
        },
        {
          codeName: 'partner_name',
          logicName: '合作伙伴',
          appDEFieldId: 'partner_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'partner_name',
        },
        {
          codeName: 'payment_onboarding_payment_method',
          logicName: '选择支付方式',
          appDEFieldId: 'payment_onboarding_payment_method',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'payment_onboarding_payment_method',
        },
        {
          codeName: 'po_double_validation',
          logicName: '批准等级',
          appDEFieldId: 'po_double_validation',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'po_double_validation',
        },
        {
          codeName: 'po_double_validation_amount',
          logicName: '再次验证金额',
          appDEFieldId: 'po_double_validation_amount',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'po_double_validation_amount',
        },
        {
          codeName: 'po_lead',
          logicName: '采购提前期',
          appDEFieldId: 'po_lead',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'po_lead',
        },
        {
          codeName: 'po_lock',
          logicName: '销售订单修改',
          appDEFieldId: 'po_lock',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'po_lock',
        },
        {
          codeName: 'portal_confirmation_pay',
          logicName: '线上付款',
          appDEFieldId: 'portal_confirmation_pay',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'portal_confirmation_pay',
        },
        {
          codeName: 'portal_confirmation_sign',
          logicName: '线上签署',
          appDEFieldId: 'portal_confirmation_sign',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'portal_confirmation_sign',
        },
        {
          codeName: 'prepayment_percent',
          logicName: '预付百分比',
          appDEFieldId: 'prepayment_percent',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'prepayment_percent',
        },
        {
          codeName: 'primary_color',
          logicName: '原色',
          appDEFieldId: 'primary_color',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'primary_color',
        },
        {
          codeName: 'purchase_lock_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '采购锁定日期',
          appDEFieldId: 'purchase_lock_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'purchase_lock_date',
        },
        {
          codeName: 'qr_code',
          logicName: 'Display QR-code on invoices',
          appDEFieldId: 'qr_code',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'qr_code',
        },
        {
          codeName: 'quick_edit_mode',
          logicName: '快速编码',
          appDEFieldId: 'quick_edit_mode',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'quick_edit_mode',
        },
        {
          codeName: 'quotation_validity_days',
          logicName: '默认报价有效期',
          appDEFieldId: 'quotation_validity_days',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'quotation_validity_days',
        },
        {
          codeName: 'report_footer',
          logicName: '报告页脚',
          appDEFieldId: 'report_footer',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'report_footer',
        },
        {
          codeName: 'report_header',
          logicName: '公司标语',
          appDEFieldId: 'report_header',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'report_header',
        },
        {
          codeName: 'resource_calendar_id',
          logicName: '默认工作时间',
          appDEFieldId: 'resource_calendar_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'resource_calendar_id',
        },
        {
          codeName: 'sale_lock_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '销售锁定日期',
          appDEFieldId: 'sale_lock_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sale_lock_date',
        },
        {
          codeName: 'sale_onboarding_payment_method',
          logicName: '销售入门选择的付款方式',
          appDEFieldId: 'sale_onboarding_payment_method',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sale_onboarding_payment_method',
        },
        {
          codeName: 'secondary_color',
          logicName: '次要颜色',
          appDEFieldId: 'secondary_color',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'secondary_color',
        },
        {
          codeName: 'security_lead',
          logicName: '销售安全天数',
          appDEFieldId: 'security_lead',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'security_lead',
        },
        {
          codeName: 'sequence',
          logicName: '序列',
          appDEFieldId: 'sequence',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'sequence',
        },
        {
          codeName: 'snailmail_color',
          logicName: '实体邮寄颜色',
          appDEFieldId: 'snailmail_color',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'snailmail_color',
        },
        {
          codeName: 'snailmail_cover',
          logicName: '添加一个封面页',
          appDEFieldId: 'snailmail_cover',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'snailmail_cover',
        },
        {
          codeName: 'snailmail_duplex',
          logicName: '双面',
          appDEFieldId: 'snailmail_duplex',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'snailmail_duplex',
        },
        {
          codeName: 'social_facebook',
          logicName: 'Facebook 账户',
          appDEFieldId: 'social_facebook',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'social_facebook',
        },
        {
          codeName: 'social_github',
          logicName: 'GitHub账户',
          appDEFieldId: 'social_github',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'social_github',
        },
        {
          codeName: 'social_instagram',
          logicName: 'Instagram 账号',
          appDEFieldId: 'social_instagram',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'social_instagram',
        },
        {
          codeName: 'social_linkedin',
          logicName: '领英账号',
          appDEFieldId: 'social_linkedin',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'social_linkedin',
        },
        {
          codeName: 'social_tiktok',
          logicName: 'TikTok / 抖音账号',
          appDEFieldId: 'social_tiktok',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'social_tiktok',
        },
        {
          codeName: 'social_twitter',
          logicName: 'X 账户',
          appDEFieldId: 'social_twitter',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'social_twitter',
        },
        {
          codeName: 'social_youtube',
          logicName: 'Youtube账号',
          appDEFieldId: 'social_youtube',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'social_youtube',
        },
        {
          codeName: 'stock_mail_confirmation_template_id',
          logicName: '确认拣货邮件模版',
          appDEFieldId: 'stock_mail_confirmation_template_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'stock_mail_confirmation_template_id',
        },
        {
          codeName: 'stock_move_email_validation',
          logicName: '邮件确认拣货',
          appDEFieldId: 'stock_move_email_validation',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'stock_move_email_validation',
        },
        {
          codeName: 'stock_move_sms_validation',
          logicName: '短信息确认',
          appDEFieldId: 'stock_move_sms_validation',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'stock_move_sms_validation',
        },
        {
          codeName: 'street',
          logicName: '街道',
          appDEFieldId: 'street',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'street',
        },
        {
          codeName: 'street2',
          logicName: '详细地址',
          appDEFieldId: 'street2',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'street2',
        },
        {
          codeName: 'tax_calculation_rounding_method',
          logicName: 'Tax Calculation Rounding Method',
          appDEFieldId: 'tax_calculation_rounding_method',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'tax_calculation_rounding_method',
        },
        {
          codeName: 'tax_exigibility',
          logicName: '采用现金收付',
          appDEFieldId: 'tax_exigibility',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'tax_exigibility',
        },
        {
          codeName: 'tax_lock_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '纳税申报表锁定日期',
          appDEFieldId: 'tax_lock_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'tax_lock_date',
        },
        {
          codeName: 'terms_type',
          logicName: 'Terms & Conditions format',
          appDEFieldId: 'terms_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'terms_type',
        },
        {
          codeName: 'transfer_account_code_prefix',
          logicName: 'Prefix of the transfer accounts',
          appDEFieldId: 'transfer_account_code_prefix',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'transfer_account_code_prefix',
        },
        {
          codeName: 'user_fiscalyear_lock_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '用户财政年度锁定日期',
          appDEFieldId: 'user_fiscalyear_lock_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_fiscalyear_lock_date',
        },
        {
          codeName: 'user_hard_lock_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '用户硬性锁定日期',
          appDEFieldId: 'user_hard_lock_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_hard_lock_date',
        },
        {
          codeName: 'user_purchase_lock_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '用户采购锁定日期',
          appDEFieldId: 'user_purchase_lock_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_purchase_lock_date',
        },
        {
          codeName: 'user_sale_lock_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '用户销售锁定日期',
          appDEFieldId: 'user_sale_lock_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_sale_lock_date',
        },
        {
          codeName: 'user_tax_lock_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: 'User Tax Lock Date',
          appDEFieldId: 'user_tax_lock_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_tax_lock_date',
        },
        {
          codeName: 'uses_default_logo',
          logicName: '使用默认徽标',
          appDEFieldId: 'uses_default_logo',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'uses_default_logo',
        },
        {
          codeName: 'work_permit_expiration_notice_period',
          logicName: '工作许可证到期通知期',
          appDEFieldId: 'work_permit_expiration_notice_period',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'work_permit_expiration_notice_period',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
        {
          codeName: 'zip',
          logicName: '邮编',
          appDEFieldId: 'zip',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'zip',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'res_company_dto',
    },
    {
      codeName: 'res_company_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_account_fiscal_country_id_eq',
          logicName: '会计所在国家/地区',
          appDEFieldId: 'account_fiscal_country_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_fiscal_country_id_eq',
        },
        {
          codeName: 'n_account_price_include_eq',
          logicName: 'Default Sales Price Include',
          appDEFieldId: 'account_price_include',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_account_price_include_eq',
        },
        {
          codeName: 'n_alias_domain_id_eq',
          logicName: '电子邮件域名',
          appDEFieldId: 'alias_domain_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_alias_domain_id_eq',
        },
        {
          codeName: 'n_annual_inventory_month_eq',
          logicName: '年度库存月',
          appDEFieldId: 'annual_inventory_month',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_annual_inventory_month_eq',
        },
        {
          codeName: 'n_attendance_barcode_source_eq',
          logicName: '条码来源',
          appDEFieldId: 'attendance_barcode_source',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_attendance_barcode_source_eq',
        },
        {
          codeName: 'n_attendance_kiosk_mode_eq',
          logicName: '考勤模式',
          appDEFieldId: 'attendance_kiosk_mode',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_attendance_kiosk_mode_eq',
        },
        {
          codeName: 'n_attendance_overtime_validation_eq',
          logicName: '额外工时验证',
          appDEFieldId: 'attendance_overtime_validation',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_attendance_overtime_validation_eq',
        },
        {
          codeName: 'n_batch_payment_sequence_id_eq',
          logicName: 'Batch Payment Sequence',
          appDEFieldId: 'batch_payment_sequence_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_batch_payment_sequence_id_eq',
        },
        {
          codeName: 'n_currency_id_eq',
          logicName: '币别',
          appDEFieldId: 'currency_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_currency_id_eq',
        },
        {
          codeName: 'n_currency_name_eq',
          logicName: '币别',
          appDEFieldId: 'currency_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_currency_name_eq',
        },
        {
          codeName: 'n_currency_name_like',
          logicName: '币别',
          appDEFieldId: 'currency_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_currency_name_like',
        },
        {
          codeName: 'n_fiscalyear_last_month_eq',
          logicName: '会计年度最后一个月',
          appDEFieldId: 'fiscalyear_last_month',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_fiscalyear_last_month_eq',
        },
        {
          codeName: 'n_font_eq',
          logicName: '字体',
          appDEFieldId: 'font',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_font_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_layout_background_eq',
          logicName: '布局背景',
          appDEFieldId: 'layout_background',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_layout_background_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_parent_id_eq',
          logicName: '上级公司',
          appDEFieldId: 'parent_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_parent_id_eq',
        },
        {
          codeName: 'n_parent_name_eq',
          logicName: '上级公司',
          appDEFieldId: 'parent_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_parent_name_eq',
        },
        {
          codeName: 'n_parent_name_like',
          logicName: '上级公司',
          appDEFieldId: 'parent_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_parent_name_like',
        },
        {
          codeName: 'n_partner_id_eq',
          logicName: '合作伙伴',
          appDEFieldId: 'partner_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_partner_id_eq',
        },
        {
          codeName: 'n_partner_name_eq',
          logicName: '合作伙伴',
          appDEFieldId: 'partner_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_partner_name_eq',
        },
        {
          codeName: 'n_partner_name_like',
          logicName: '合作伙伴',
          appDEFieldId: 'partner_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_partner_name_like',
        },
        {
          codeName: 'n_payment_onboarding_payment_method_eq',
          logicName: '选择支付方式',
          appDEFieldId: 'payment_onboarding_payment_method',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_payment_onboarding_payment_method_eq',
        },
        {
          codeName: 'n_po_double_validation_eq',
          logicName: '批准等级',
          appDEFieldId: 'po_double_validation',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_po_double_validation_eq',
        },
        {
          codeName: 'n_po_lock_eq',
          logicName: '销售订单修改',
          appDEFieldId: 'po_lock',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_po_lock_eq',
        },
        {
          codeName: 'n_quick_edit_mode_eq',
          logicName: '快速编码',
          appDEFieldId: 'quick_edit_mode',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_quick_edit_mode_eq',
        },
        {
          codeName: 'n_resource_calendar_id_eq',
          logicName: '默认工作时间',
          appDEFieldId: 'resource_calendar_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_resource_calendar_id_eq',
        },
        {
          codeName: 'n_sale_onboarding_payment_method_eq',
          logicName: '销售入门选择的付款方式',
          appDEFieldId: 'sale_onboarding_payment_method',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_sale_onboarding_payment_method_eq',
        },
        {
          codeName: 'n_stock_mail_confirmation_template_id_eq',
          logicName: '确认拣货邮件模版',
          appDEFieldId: 'stock_mail_confirmation_template_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_stock_mail_confirmation_template_id_eq',
        },
        {
          codeName: 'n_tax_calculation_rounding_method_eq',
          logicName: 'Tax Calculation Rounding Method',
          appDEFieldId: 'tax_calculation_rounding_method',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_tax_calculation_rounding_method_eq',
        },
        {
          codeName: 'n_terms_type_eq',
          logicName: 'Terms & Conditions format',
          appDEFieldId: 'terms_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_terms_type_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'res_company_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_company_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_company_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'res_company',
  deapicodeName: 'res_company',
  deapicodeName2: 'res_companies',
  deapitag: 'RES_COMPANY',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  logicName: '公司',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'RES_COMPANY',
  id: 'ehrapp.res_company',
  codeName2: 'res_companies',
  requestPaths: [],
};
