export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'ehrapp.res_groups',
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'rule_group_rels',
      logicName: '规则权限引用',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'RULE_GROUP_RELS',
      id: 'rule_group_rels',
    },
    {
      codeName: 'groups_users_rels',
      logicName: '权限组用户',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'GROUPS_USERS_RELS',
      id: 'groups_users_rels',
    },
    {
      codeName: 'create_date',
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RES_GROUPS.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_uid',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RES_GROUPS.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'share',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RES_GROUPS.SHARE',
      },
      logicName: '共享组',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SHARE',
      id: 'share',
    },
    {
      codeName: 'color',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RES_GROUPS.COLOR',
      },
      logicName: '颜色索引',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'COLOR',
      id: 'color',
    },
    {
      codeName: 'comment',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RES_GROUPS.COMMENT',
      },
      logicName: '评论',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'COMMENT',
      id: 'comment',
    },
    {
      codeName: 'api_key_duration',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RES_GROUPS.API_KEY_DURATION',
      },
      logicName: 'API 密钥最长有效期（天）',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'API_KEY_DURATION',
      id: 'api_key_duration',
    },
    {
      codeName: 'full_name',
      computeAppDEFLogicId: 'compute_full_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RES_GROUPS.FULL_NAME',
      },
      logicName: '组名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'FULL_NAME',
      id: 'full_name',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RES_GROUPS.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'category_id',
      logicName: '应用',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CATEGORY_ID',
      id: 'category_id',
    },
    {
      codeName: 'category_name',
      logicName: '应用',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'CATEGORY_NAME',
      id: 'category_name',
    },
  ],
  appDELogics: [
    {
      deflogicMode: 'COMPUTE',
      appDEFieldId: 'full_name',
      codeName: 'compute_full_name',
      defaultParamName: 'DEFAULT',
      logicName: '组名称计算',
      logicSubType: 'DEFIELD',
      scriptCode:
        "if(data.category_name){\r\n  data.full_name=data.category_name+' / '+data.name;\r\n}else{\r\n  data.full_name=data.name;\r\n}\r\n",
      customCode: true,
      enableFront: true,
      valid: true,
      name: '组名称计算',
      id: 'compute_full_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'res_groups_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'rule_group_rels',
          logicName: '规则权限引用',
          appDEFieldId: 'rule_group_rels',
          refAppDEDataSetId: 'fetch_default',
          refAppDEMethodDTOId: 'rule_group_rel_dto',
          refAppDataEntityId: 'ehrapp.rule_group_rel',
          refPickupAppDEFieldId: 'gid',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'rule_group_rels',
        },
        {
          codeName: 'groups_users_rels',
          logicName: '权限组用户',
          appDEFieldId: 'groups_users_rels',
          refAppDEDataSetId: 'fetch_default',
          refAppDEMethodDTOId: 'res_groups_users_rel_dto',
          refAppDataEntityId: 'ehrapp.res_groups_users_rel',
          refPickupAppDEFieldId: 'gid',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'groups_users_rels',
        },
        {
          codeName: 'api_key_duration',
          logicName: 'API 密钥最长有效期（天）',
          appDEFieldId: 'api_key_duration',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'api_key_duration',
        },
        {
          codeName: 'category_id',
          logicName: '应用',
          appDEFieldId: 'category_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'category_id',
        },
        {
          codeName: 'category_name',
          logicName: '应用',
          appDEFieldId: 'category_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'category_name',
        },
        {
          codeName: 'color',
          logicName: '颜色索引',
          appDEFieldId: 'color',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'color',
        },
        {
          codeName: 'comment',
          logicName: '评论',
          appDEFieldId: 'comment',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'comment',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'full_name',
          logicName: '组名称',
          appDEFieldId: 'full_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'full_name',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'share',
          logicName: '共享组',
          appDEFieldId: 'share',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'share',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
        {
          codeName: 'groups_implied_rels',
          refAppDEDataSetId: 'fetch_default',
          refAppDEMethodDTOId: 'res_groups_implied_rel_dto',
          refAppDataEntityId: 'ehrapp.res_groups_implied_rel',
          refPickupAppDEFieldId: 'gid',
          sourceType: 'DER',
          type: 'DTOS',
          allowEmpty: true,
          id: 'groups_implied_rels',
        },
        {
          codeName: 'model_access',
          refAppDEDataSetId: 'fetch_default',
          refAppDEMethodDTOId: 'ir_model_access_dto',
          refAppDataEntityId: 'ehrapp.ir_model_access',
          refPickupAppDEFieldId: 'group_id',
          sourceType: 'DER',
          type: 'DTOS',
          allowEmpty: true,
          id: 'model_access',
        },
        {
          codeName: 'unires_group_rels',
          refAppDEDataSetId: 'fetchdefault',
          refAppDEMethodDTOId: 'unires_group_reldto',
          refAppDataEntityId: 'ehrapp.unires_group_rel',
          refPickupAppDEFieldId: 'gid',
          sourceType: 'DER',
          type: 'DTOS',
          allowEmpty: true,
          id: 'unires_group_rels',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'res_groups_dto',
    },
    {
      codeName: 'res_groups_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_category_id_eq',
          logicName: '应用',
          appDEFieldId: 'category_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_category_id_eq',
        },
        {
          codeName: 'n_category_name_eq',
          logicName: '应用',
          appDEFieldId: 'category_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_category_name_eq',
        },
        {
          codeName: 'n_category_name_like',
          logicName: '应用',
          appDEFieldId: 'category_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_category_name_like',
        },
        {
          codeName: 'n_groups_users_rels_exists_n_user_id_eq',
          logicName: '权限组用户',
          appDEFieldId: 'groups_users_rels',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_groups_users_rels_exists_n_user_id_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'res_groups_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_cur_user_ref',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_cur_user_ref',
      actionType: 'REMOTE',
      dataSetName: 'cur_user_ref',
      dataSetTag: 'cur_user_ref',
      dataSetType: 'REMOTE',
      id: 'fetch_cur_user_ref',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_psmodel_sync',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_psmodel_sync',
      actionType: 'REMOTE',
      dataSetName: 'psmodel_sync',
      dataSetTag: 'psmodel_sync',
      dataSetType: 'REMOTE',
      id: 'fetch_psmodel_sync',
    },
    {
      codeName: 'fetch_user_ref',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_user_ref',
      actionType: 'REMOTE',
      addedqconditions: [
        {
          condOp: 'EQ',
          condValue: 'user_id',
          fieldName: 'USER_ID',
          vartypeId: 'DATACONTEXT',
          condType: 'SINGLE',
          name: '(USER_ID) 等于(=) 数据上下文 user_id',
          id: '(user_id) 等于(=) 数据上下文 user_id',
        },
      ],
      dataSetName: 'user_ref',
      dataSetTag: 'user_ref',
      dataSetType: 'REMOTE',
      id: 'fetch_user_ref',
    },
    {
      codeName: 'fetch_with_nested',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'res_groups_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'res_groups_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_with_nested',
      actionType: 'REMOTE',
      dataSetName: 'with_nested',
      dataSetTag: 'with_nested',
      dataSetType: 'REMOTE',
      id: 'fetch_with_nested',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'res_groups',
  deapicodeName: 'res_groups',
  deapicodeName2: 'res_groups',
  deapitag: 'RES_GROUPS',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.RES_GROUPS',
  },
  logicName: '权限组',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'RES_GROUPS',
  id: 'ehrapp.res_groups',
  codeName2: 'res_groups',
  requestPaths: [],
};
