export default {
  appDEFields: [
    {
      codeName: 'share',
      logicName: '共享用户',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SHARE',
      id: 'share',
    },
    {
      codeName: 'email',
      logicName: '电子邮件',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'EMAIL',
      id: 'email',
    },
    {
      codeName: 'phone',
      logicName: '电话',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'PHONE',
      id: 'phone',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'create_uid',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_date',
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'active',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.ACTIVE',
      },
      logicName: '有效',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ACTIVE',
      id: 'active',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'time_efficiency',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.TIME_EFFICIENCY',
      },
      logicName: '效率因子',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'TIME_EFFICIENCY',
      id: 'time_efficiency',
    },
    {
      codeName: 'resource_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.RESOURCE_TYPE',
      },
      logicName: '类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'RESOURCE_TYPE',
      id: 'resource_type',
    },
    {
      codeName: 'display_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.DISPLAY_NAME',
      },
      logicName: '显示名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'DISPLAY_NAME',
      id: 'display_name',
    },
    {
      codeName: 'calendar_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.CALENDAR_ID',
      },
      logicName: '工时',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CALENDAR_ID',
      id: 'calendar_id',
    },
    {
      codeName: 'company_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.COMPANY_ID',
      },
      logicName: '公司',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'COMPANY_ID',
      id: 'company_id',
    },
    {
      codeName: 'user_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.USER_ID',
      },
      logicName: '用户',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'USER_ID',
      id: 'user_id',
    },
    {
      codeName: 'company_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.COMPANY_ID',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'COMPANY_NAME',
      id: 'company_name',
    },
    {
      codeName: 'calendar_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.CALENDAR_ID',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'CALENDAR_NAME',
      id: 'calendar_name',
    },
    {
      codeName: 'user_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.RESOURCE_RESOURCE.USER_ID',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'USER_NAME',
      id: 'user_name',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'resource_resource_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'email',
          logicName: '电子邮件',
          appDEFieldId: 'email',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email',
        },
        {
          codeName: 'phone',
          logicName: '电话',
          appDEFieldId: 'phone',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'phone',
        },
        {
          codeName: 'share',
          logicName: '共享用户',
          appDEFieldId: 'share',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'share',
        },
        {
          codeName: 'active',
          logicName: '有效',
          appDEFieldId: 'active',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'active',
        },
        {
          codeName: 'calendar_id',
          logicName: '工时',
          appDEFieldId: 'calendar_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'calendar_id',
        },
        {
          codeName: 'calendar_name',
          logicName: '名称',
          appDEFieldId: 'calendar_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'calendar_name',
        },
        {
          codeName: 'company_id',
          logicName: '公司',
          appDEFieldId: 'company_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company_id',
        },
        {
          codeName: 'company_name',
          logicName: '名称',
          appDEFieldId: 'company_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'company_name',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'display_name',
          logicName: '显示名称',
          appDEFieldId: 'display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'display_name',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'resource_type',
          logicName: '类型',
          appDEFieldId: 'resource_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'resource_type',
        },
        {
          codeName: 'time_efficiency',
          logicName: '效率因子',
          appDEFieldId: 'time_efficiency',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          id: 'time_efficiency',
        },
        {
          codeName: 'user_id',
          logicName: '用户',
          appDEFieldId: 'user_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_id',
        },
        {
          codeName: 'user_name',
          logicName: '名称',
          appDEFieldId: 'user_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_name',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'resource_resource_dto',
    },
    {
      codeName: 'resource_resource_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_calendar_id_eq',
          logicName: '工时',
          appDEFieldId: 'calendar_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_calendar_id_eq',
        },
        {
          codeName: 'n_calendar_name_eq',
          logicName: '名称',
          appDEFieldId: 'calendar_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_calendar_name_eq',
        },
        {
          codeName: 'n_calendar_name_like',
          logicName: '名称',
          appDEFieldId: 'calendar_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_calendar_name_like',
        },
        {
          codeName: 'n_company_id_eq',
          logicName: '公司',
          appDEFieldId: 'company_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_company_id_eq',
        },
        {
          codeName: 'n_company_name_eq',
          logicName: '名称',
          appDEFieldId: 'company_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_company_name_eq',
        },
        {
          codeName: 'n_company_name_like',
          logicName: '名称',
          appDEFieldId: 'company_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_company_name_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_resource_type_eq',
          logicName: '类型',
          appDEFieldId: 'resource_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_resource_type_eq',
        },
        {
          codeName: 'n_user_id_eq',
          logicName: '用户',
          appDEFieldId: 'user_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_id_eq',
        },
        {
          codeName: 'n_user_name_eq',
          logicName: '名称',
          appDEFieldId: 'user_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_name_eq',
        },
        {
          codeName: 'n_user_name_like',
          logicName: '名称',
          appDEFieldId: 'user_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'resource_resource_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'resource_resource_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'resource_resource_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'resource_resource',
  deapicodeName: 'resource_resource',
  deapicodeName2: 'resource_resources',
  deapitag: 'RESOURCE_RESOURCE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.RESOURCE_RESOURCE',
  },
  logicName: '资源',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'resource_resources',
      majorAppDataEntityId: 'ehrapp.resource_calendar',
      parentAppDEFieldId: 'calendar_id',
      parentTextAppDEFieldId: 'calendar_name',
      rsmode: 2,
      name: '资源工作时间-资源',
      id: 'resource_resources',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'RESOURCE_RESOURCE',
  id: 'ehrapp.resource_resource',
  codeName2: 'resource_resources',
  requestPaths: [
    'resource_calendars/${resource_calendar}/resource_resources/${resource_resource}',
  ],
};
