export default {
  defaultPage: true,
  caption: 'iBizEHR 招聘管理',
  codeName: 'app_index_view',
  controls: [
    {
      layoutMode: 'TABLE_24COL',
      appMenuItems: [
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'usrappfunc0827955364',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-home',
            glyph: 'xf015@FontAwesome',
          },
          openDefault: true,
          valid: true,
          caption: '工作台',
          tooltip: '工作台',
          id: 'menuitem9',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'appfunc3',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-user',
            glyph: 'xf007@FontAwesome',
          },
          valid: true,
          caption: '候选人管理',
          tooltip: '候选人管理',
          id: 'menuitem1',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'usrappfunc0826476593',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-archive',
            glyph: 'xf187@FontAwesome',
          },
          valid: true,
          caption: '面试安排',
          tooltip: '面试安排',
          id: 'menuitem3',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'usrappfunc0806841809',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-book',
            glyph: 'xf02d@FontAwesome',
          },
          valid: true,
          caption: '职位管理',
          tooltip: '职位管理',
          id: 'menuitem2',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'usrappfunc0821386148',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-users',
            glyph: 'xf0c0@FontAwesome',
          },
          valid: true,
          caption: '人才库',
          tooltip: '人才库',
          id: 'menuitem11',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'usrappfunc0825533665',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-tachometer',
            glyph: 'xf0e4@FontAwesome',
          },
          valid: true,
          caption: '报表中心',
          tooltip: '报表中心',
          id: 'menuitem12',
        },
        {
          itemType: 'SEPERATOR',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          valid: true,
          id: 'seperator1',
        },
        {
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0912315937',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              sysImage: {
                cssClass: 'fa fa-home',
                glyph: 'xf015@FontAwesome',
              },
              valid: true,
              caption: '工作台',
              tooltip: '工作台',
              id: 'menuitem6',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0813630705',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              sysImage: {
                cssClass: 'fa fa-filter',
                glyph: 'xf0b0@FontAwesome',
              },
              valid: true,
              caption: '简历筛选',
              tooltip: '简历筛选',
              id: 'menuitem7',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0829399946',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              sysImage: {
                cssClass: 'fa fa-archive',
                glyph: 'xf187@FontAwesome',
              },
              valid: true,
              caption: '我的面试',
              tooltip: '我的面试',
              id: 'menuitem8',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'appfunc',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              sysImage: {
                cssClass: 'fa fa-pencil',
                glyph: 'xf040@FontAwesome',
              },
              valid: true,
              caption: '考试/评测',
              tooltip: '考试/评测',
              id: 'menuitem13',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0822244697',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              sysImage: {
                cssClass: 'fa fa-legal',
                glyph: 'xf0e3@FontAwesome',
              },
              valid: true,
              caption: 'Offer审批',
              tooltip: 'Offer审批',
              id: 'menuitem14',
            },
            {
              itemType: 'MENUITEM',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              sysImage: {
                cssClass: 'fa fa-laptop',
                glyph: 'xf109@FontAwesome',
              },
              hidden: true,
              valid: true,
              caption: '招聘进展',
              tooltip: '招聘进展',
              id: 'menuitem15',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-user-md',
            glyph: 'xf0f0@FontAwesome',
          },
          valid: true,
          caption: '用人经理',
          tooltip: '用人经理',
          expanded: true,
          id: 'menuitem5',
        },
        {
          itemType: 'SEPERATOR',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          valid: true,
          id: 'seperator2',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'usrappfunc0815029160',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-cog',
            glyph: 'xf013@FontAwesome',
          },
          valid: true,
          caption: '系统设置',
          tooltip: '系统设置',
          id: 'menuitem10',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'usrappfunc0826268624',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          sysImage: {
            cssClass: 'fa fa-joomla',
            glyph: 'xf1aa@FontAwesome',
          },
          valid: true,
          caption: '应用管理',
          tooltip: '应用管理',
          id: 'menuitem4',
        },
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'usrappfunc0924959812',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          valid: true,
          caption: '消息通知',
          tooltip: '消息通知',
          id: 'menuitem16',
        },
        {
          itemType: 'MENUITEM',
          appMenuItems: [
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0928924036',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '组织管理',
              tooltip: '组织管理',
              id: 'menuitem20',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0928145263',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '部门管理',
              tooltip: '部门管理',
              id: 'menuitem19',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0926304993',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '人员管理',
              tooltip: '人员管理',
              id: 'menuitem18',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0928915988',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '工作地点',
              tooltip: '工作地点',
              id: 'menuitem21',
            },
            {
              accUserMode: 2,
              itemType: 'MENUITEM',
              appFuncId: 'usrappfunc0929071054',
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              valid: true,
              caption: '测试岗位',
              tooltip: '测试岗位',
              id: 'menuitem22',
            },
          ],
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          valid: true,
          caption: '系统设置（临时）',
          tooltip: '系统设置（临时）',
          id: 'menuitem17',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'usr0804469295_menu',
      controlType: 'APPMENU',
      logicName: '应用首页视图菜单',
      controlParam: {},
      modelId: '6999083a70471afc0dd04f9e02a4f2eb',
      modelType: 'PSAPPMENU',
      name: 'appmenu',
      id: 'usr0804469295_menu',
    },
    {
      caption: 'iBizEHR 招聘管理',
      codeName: 'captionbar',
      controlType: 'CAPTIONBAR',
      controlParam: {},
      id: 'captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPINDEXVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: 'iBizEHR 招聘管理',
  viewStyle: 'DEFAULT',
  viewType: 'APPINDEXVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '2530708d453013b497aebeb7a0a9cd7c',
  modelType: 'PSAPPINDEXVIEW',
  name: 'AppIndexView',
  id: 'web.app_index_view',
};
