export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'add_info_view',
  deviewId: '77eaa2932253fece6e44878a74c7dbe2',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_APPLICANT',
  },
  caption: '候选人申请',
  codeName: 'hr_applicant_add_info_view',
  appDataEntityId: 'web.hr_applicant',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'add_info_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '候选人申请_附加信息_工具栏',
      appDataEntityId: 'web.hr_applicant',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '13a61e032379a000e65a4b3d0baee922',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'add_info_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.hr_applicant',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.hr_applicant',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.hr_applicant',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.hr_applicant',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.hr_applicant',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.hr_applicant',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              caption: '候选人申请基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'applicant_add_info_form',
      controlType: 'FORM',
      logicName: '候选人申请_附加信息_表单',
      appDataEntityId: 'web.hr_applicant',
      controlParam: {
        id: 'form',
      },
      modelId: '8356a299524747f44db5722569accae5',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.hr_applicant.applicant_add_info_form',
    },
    {
      codeName: 'add_info_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.hr_applicant',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'add_info_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_APPLICANT',
      },
      caption: '候选人申请',
      codeName: 'add_info_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.hr_applicant',
      controlParam: {},
      name: 'captionbar',
      id: 'add_info_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.hr_applicant',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '候选人申请_附加信息',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '16adcdc82e4cfc6a633b99365e36e575',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_applicantadd_info_view',
  id: 'web.hr_applicant_add_info_view',
};
