export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'main_calendar_view',
  deviewId: '5d036e89f6237a8cf562a3ef5e400694',
  accUserMode: 2,
  caption: '面试安排日历视图',
  codeName: 'hr_applicant_interview_main_calendar_view',
  appDataEntityId: 'web.hr_applicant_interview',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionType: 'UIACTION',
                buttonStyle: 'INFO',
                buttonType: 'PANELBUTTON',
                uiactionId: 'add_interview@hr_applicant_interview',
                renderMode: 'BUTTON',
                tooltip: '添加面试',
                uiactionTarget: 'NONE',
                caption: '添加面试',
                itemStyle: 'INFO',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysCss: {
                  cssName: 'top_but_sty',
                },
                showCaption: true,
                id: 'button_calluilogic',
              },
              {
                actionType: 'UIACTION',
                buttonStyle: 'INFO',
                buttonType: 'PANELBUTTON',
                uiactionId: 'appointment_interview@hr_applicant_interview',
                renderMode: 'BUTTON',
                tooltip: '预约面试',
                uiactionTarget: 'SINGLEDATA',
                caption: '预约面试',
                itemStyle: 'INFO',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysCss: {
                  cssName: 'top_but_sty',
                },
                showCaption: true,
                id: 'button_calluilogic1',
              },
            ],
            layout: {
              align: 'center',
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container',
          },
          {
            caption: '日历',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'calendar',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          editMode: true,
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    controls: [
      {
        calendarStyle: 'TIMELINE',
        groupMode: 'NONE',
        legendPos: 'NONE',
        sysCalendarItems: [
          {
            beginTimeAppDEFieldId: 'start_date',
            endTimeAppDEFieldId: 'start_date',
            idAppDEFieldId: 'id',
            itemStyle: 'DEFAULT',
            itemType: 'master',
            appDEDataSetId: 'fetch_interview_list',
            layoutPanel: {
              layoutMode: 'FLEX',
              layout: {
                layout: 'FLEX',
              },
              rootPanelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          rawItem: {
                            caption: '面试负责人',
                            halign: 'LEFT',
                            renderMode: 'TEXT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            contentType: 'RAW',
                            predefinedType: 'STATIC_TEXT',
                            rawItemWidth: 200,
                            id: 'static_text2',
                          },
                          caption: '文本',
                          contentWidth: 200,
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            width: 200,
                            widthMode: 'PX',
                          },
                          width: 200,
                          showCaption: true,
                          id: 'static_text2',
                        },
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'owner_name',
                          },
                          viewFieldName: 'owner_name',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'owner_name',
                        },
                      ],
                      layout: {
                        dir: 'row',
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        spacingBottom: 'OUTERMEDIUM',
                      },
                      id: 'container1',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          rawItem: {
                            caption: '候选人链接',
                            halign: 'LEFT',
                            renderMode: 'TEXT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            contentType: 'RAW',
                            predefinedType: 'STATIC_TEXT',
                            rawItemWidth: 200,
                            id: 'static_text',
                          },
                          caption: '文本',
                          contentWidth: 200,
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            width: 200,
                            widthMode: 'PX',
                          },
                          width: 200,
                          showCaption: true,
                          id: 'static_text',
                        },
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'candidate_url',
                          },
                          viewFieldName: 'candidate_url',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'candidate_url',
                        },
                      ],
                      layout: {
                        dir: 'row',
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        spacingBottom: 'OUTERMEDIUM',
                      },
                      id: 'container2',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          rawItem: {
                            caption: '会议号',
                            halign: 'LEFT',
                            renderMode: 'TEXT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            contentType: 'RAW',
                            predefinedType: 'STATIC_TEXT',
                            rawItemWidth: 200,
                            id: 'static_text1',
                          },
                          caption: '文本',
                          contentWidth: 200,
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            width: 200,
                            widthMode: 'PX',
                          },
                          width: 200,
                          showCaption: true,
                          id: 'static_text1',
                        },
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'meeting_id',
                          },
                          viewFieldName: 'meeting_id',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'meeting_id',
                        },
                      ],
                      layout: {
                        dir: 'row',
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        spacingBottom: 'OUTERMEDIUM',
                      },
                      id: 'container3',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              rawItem: {
                                caption: '面试信息',
                                halign: 'LEFT',
                                renderMode: 'TEXT',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                contentType: 'RAW',
                                predefinedType: 'STATIC_TEXT',
                                rawItemWidth: 200,
                                id: 'static_text3',
                              },
                              caption: '文本',
                              contentWidth: 200,
                              itemStyle: 'DEFAULT',
                              itemType: 'RAWITEM',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                                width: 200,
                                widthMode: 'PX',
                              },
                              width: 200,
                              showCaption: true,
                              id: 'static_text3',
                            },
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                appCodeListId: 'web.hr__interview_stage',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'stage_id',
                              },
                              viewFieldName: 'stage_id',
                              allowEmpty: true,
                              convertToCodeItemText: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                                spacingRight: 'OUTERMEDIUM',
                              },
                              id: 'stage_id',
                            },
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                appCodeListId: 'web.hr__interview_start_time',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'start_time',
                              },
                              viewFieldName: 'start_time',
                              allowEmpty: true,
                              convertToCodeItemText: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                                spacingRight: 'OUTERMEDIUM',
                              },
                              id: 'start_time',
                            },
                            {
                              rawItem: {
                                caption: '时长:',
                                halign: 'LEFT',
                                renderMode: 'TEXT',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                contentType: 'RAW',
                                predefinedType: 'STATIC_TEXT',
                                id: 'static_text4',
                              },
                              caption: '文本',
                              itemStyle: 'DEFAULT',
                              itemType: 'RAWITEM',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                                spacingRight: 'OUTERSMALL',
                              },
                              showCaption: true,
                              id: 'static_text4',
                            },
                            {
                              editor: {
                                halign: 'LEFT',
                                renderMode: 'TEXT_DYNAMIC',
                                valign: 'MIDDLE',
                                wrapMode: 'NOWRAP',
                                appCodeListId: 'web.hr__interview_duration',
                                editorType: 'SPAN',
                                predefinedType: 'FIELD_TEXT_DYNAMIC',
                                valueType: 'SIMPLE',
                                editable: true,
                                id: 'duration',
                              },
                              viewFieldName: 'duration',
                              allowEmpty: true,
                              convertToCodeItemText: true,
                              caption: '文本(动态)',
                              itemStyle: 'DEFAULT',
                              itemType: 'FIELD',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'duration',
                            },
                          ],
                          layout: {
                            dir: 'row',
                            layout: 'FLEX',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            spacingBottom: 'OUTERMEDIUM',
                          },
                          id: 'container4',
                        },
                        {
                          actionGroupExtractMode: 'ITEM',
                          panelItems: [
                            {
                              actionGroupExtractMode: 'ITEM',
                              panelItems: [
                                {
                                  actionGroupExtractMode: 'ITEM',
                                  panelItems: [
                                    {
                                      editor: {
                                        halign: 'LEFT',
                                        renderMode: 'TEXT_DYNAMIC',
                                        valign: 'MIDDLE',
                                        wrapMode: 'NOWRAP',
                                        editorType: 'SPAN',
                                        editorWidth: 200,
                                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                                        valueType: 'SIMPLE',
                                        editable: true,
                                        id: 'interviewer_name2',
                                      },
                                      viewFieldName: 'interviewer_name',
                                      allowEmpty: true,
                                      caption: '文本(动态)',
                                      contentWidth: 200,
                                      itemStyle: 'DEFAULT',
                                      itemType: 'FIELD',
                                      layoutPos: {
                                        shrink: 1,
                                        layout: 'FLEX',
                                        width: 200,
                                        widthMode: 'PX',
                                      },
                                      width: 200,
                                      id: 'interviewer_name2',
                                    },
                                    {
                                      actionGroupExtractMode: 'ITEM',
                                      panelItems: [
                                        {
                                          rawItem: {
                                            sysImage: {
                                              cssClass: 'fa fa-warning',
                                              glyph: 'xf071@FontAwesome',
                                            },
                                            contentType: 'IMAGE',
                                            predefinedType: 'STATIC_IMAGE',
                                            rawItemHeight: 20,
                                            id: 'static_image',
                                          },
                                          caption: '图片',
                                          contentHeight: 20,
                                          height: 20,
                                          itemStyle: 'DEFAULT',
                                          itemType: 'RAWITEM',
                                          layoutPos: {
                                            shrink: 1,
                                            height: 20,
                                            heightMode: 'PX',
                                            layout: 'FLEX',
                                            spacingLeft: 'OUTERSMALL',
                                            spacingRight: 'OUTERSMALL',
                                          },
                                          sysImage: {
                                            cssClass: 'fa fa-warning',
                                            glyph: 'xf071@FontAwesome',
                                          },
                                          showCaption: true,
                                          id: 'static_image',
                                        },
                                        {
                                          rawItem: {
                                            caption: '未评估',
                                            halign: 'LEFT',
                                            renderMode: 'TEXT',
                                            valign: 'MIDDLE',
                                            wrapMode: 'NOWRAP',
                                            contentType: 'RAW',
                                            predefinedType: 'STATIC_TEXT',
                                            id: 'static_text6',
                                          },
                                          caption: '文本',
                                          itemStyle: 'DEFAULT',
                                          itemType: 'RAWITEM',
                                          layoutPos: {
                                            shrink: 1,
                                            heightMode: 'FULL',
                                            layout: 'FLEX',
                                          },
                                          panelItemGroupLogics: [
                                            {
                                              logicCat: 'PANELVISIBLE',
                                              relatedItemNames: ['result_type'],
                                              groupOP: 'AND',
                                              panelItemLogics: [
                                                {
                                                  condOp: 'ISNULL',
                                                  dstModelField: 'result_type',
                                                  logicType: 'SINGLE',
                                                  id: '逻辑项',
                                                },
                                              ],
                                              logicType: 'GROUP',
                                            },
                                          ],
                                          showCaption: true,
                                          id: 'static_text6',
                                        },
                                      ],
                                      layout: {
                                        dir: 'row',
                                        layout: 'FLEX',
                                      },
                                      dataRegionType: 'INHERIT',
                                      caption: '容器',
                                      contentHeight: 32,
                                      height: 32,
                                      itemStyle: 'DEFAULT',
                                      itemType: 'CONTAINER',
                                      layoutPos: {
                                        grow: 1,
                                        shrink: 1,
                                        height: 32,
                                        heightMode: 'PX',
                                        layout: 'FLEX',
                                      },
                                      id: 'container8',
                                    },
                                    {
                                      actionType: 'UIACTION',
                                      buttonStyle: 'DEFAULT',
                                      buttonType: 'PANELBUTTON',
                                      uiactionId:
                                        'add_feedback_hr@hr_interview_feedback',
                                      renderMode: 'LINK',
                                      tooltip: '填写反馈',
                                      uiactionTarget: 'NONE',
                                      caption: '填写反馈',
                                      itemStyle: 'DEFAULT',
                                      itemType: 'BUTTON',
                                      layoutPos: {
                                        shrink: 1,
                                        layout: 'FLEX',
                                        spacingRight: 'OUTERMEDIUM',
                                      },
                                      sysCss: {
                                        cssName: 'add_feedback',
                                      },
                                      showCaption: true,
                                      id: 'button_link',
                                    },
                                  ],
                                  layout: {
                                    dir: 'row',
                                    layout: 'FLEX',
                                  },
                                  dataRegionType: 'INHERIT',
                                  caption: '容器',
                                  itemStyle: 'DEFAULT',
                                  itemType: 'CONTAINER',
                                  layoutPos: {
                                    shrink: 1,
                                    layout: 'FLEX',
                                    spacingBottom: 'OUTERMEDIUM',
                                  },
                                  panelItemGroupLogics: [
                                    {
                                      logicCat: 'PANELVISIBLE',
                                      relatedItemNames: ['result_type'],
                                      groupOP: 'AND',
                                      panelItemLogics: [
                                        {
                                          condOp: 'ISNULL',
                                          dstModelField: 'result_type',
                                          logicType: 'SINGLE',
                                          id: '逻辑项',
                                        },
                                      ],
                                      logicType: 'GROUP',
                                    },
                                  ],
                                  id: 'container7',
                                },
                                {
                                  actionGroupExtractMode: 'ITEM',
                                  panelItems: [
                                    {
                                      editor: {
                                        halign: 'LEFT',
                                        renderMode: 'TEXT_DYNAMIC',
                                        valign: 'MIDDLE',
                                        wrapMode: 'NOWRAP',
                                        editorType: 'SPAN',
                                        editorWidth: 200,
                                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                                        valueType: 'SIMPLE',
                                        editable: true,
                                        id: 'interviewer_name3',
                                      },
                                      viewFieldName: 'interviewer_name',
                                      allowEmpty: true,
                                      caption: '文本(动态)',
                                      contentWidth: 200,
                                      itemStyle: 'DEFAULT',
                                      itemType: 'FIELD',
                                      layoutPos: {
                                        shrink: 1,
                                        layout: 'FLEX',
                                        width: 200,
                                        widthMode: 'PX',
                                      },
                                      width: 200,
                                      id: 'interviewer_name3',
                                    },
                                    {
                                      actionGroupExtractMode: 'ITEM',
                                      panelItems: [
                                        {
                                          editor: {
                                            halign: 'LEFT',
                                            renderMode: 'TEXT_DYNAMIC',
                                            valign: 'MIDDLE',
                                            wrapMode: 'NOWRAP',
                                            appCodeListId:
                                              'web.hr__interview_result_type',
                                            editorType: 'SPAN',
                                            predefinedType:
                                              'FIELD_TEXT_DYNAMIC',
                                            valueType: 'SIMPLE',
                                            editable: true,
                                            id: 'result_type',
                                          },
                                          viewFieldName: 'result_type',
                                          allowEmpty: true,
                                          convertToCodeItemText: true,
                                          caption: '文本(动态)',
                                          itemStyle: 'DEFAULT',
                                          itemType: 'FIELD',
                                          layoutPos: {
                                            shrink: 1,
                                            layout: 'FLEX',
                                            spacingLeft: 'OUTERSMALL',
                                          },
                                          id: 'result_type',
                                        },
                                      ],
                                      layout: {
                                        dir: 'row',
                                        layout: 'FLEX',
                                      },
                                      dataRegionType: 'INHERIT',
                                      caption: '容器',
                                      itemStyle: 'DEFAULT',
                                      itemType: 'CONTAINER',
                                      layoutPos: {
                                        grow: 1,
                                        shrink: 1,
                                        layout: 'FLEX',
                                      },
                                      id: 'container11',
                                    },
                                    {
                                      actionType: 'UIACTION',
                                      buttonStyle: 'DEFAULT',
                                      buttonType: 'PANELBUTTON',
                                      uiactionId:
                                        'add_feedback_hr@hr_interview_feedback',
                                      renderMode: 'LINK',
                                      tooltip: '查看反馈',
                                      uiactionTarget: 'NONE',
                                      caption: '查看反馈',
                                      itemStyle: 'DEFAULT',
                                      itemType: 'BUTTON',
                                      layoutPos: {
                                        shrink: 1,
                                        layout: 'FLEX',
                                        spacingRight: 'OUTERMEDIUM',
                                      },
                                      sysCss: {
                                        cssName: 'add_feedback',
                                      },
                                      showCaption: true,
                                      id: 'button_link1',
                                    },
                                  ],
                                  layout: {
                                    dir: 'row',
                                    layout: 'FLEX',
                                  },
                                  dataRegionType: 'INHERIT',
                                  caption: '容器',
                                  itemStyle: 'DEFAULT',
                                  itemType: 'CONTAINER',
                                  layoutPos: {
                                    shrink: 1,
                                    layout: 'FLEX',
                                  },
                                  panelItemGroupLogics: [
                                    {
                                      logicCat: 'PANELVISIBLE',
                                      relatedItemNames: ['result_type'],
                                      groupOP: 'AND',
                                      panelItemLogics: [
                                        {
                                          condOp: 'ISNOTNULL',
                                          dstModelField: 'result_type',
                                          logicType: 'SINGLE',
                                          id: '逻辑项',
                                        },
                                      ],
                                      logicType: 'GROUP',
                                    },
                                  ],
                                  id: 'container9',
                                },
                                {
                                  actionGroupExtractMode: 'ITEM',
                                  panelItems: [
                                    {
                                      rawItem: {
                                        caption: '面试官链接',
                                        halign: 'LEFT',
                                        renderMode: 'TEXT',
                                        valign: 'MIDDLE',
                                        wrapMode: 'NOWRAP',
                                        contentType: 'RAW',
                                        predefinedType: 'STATIC_TEXT',
                                        rawItemWidth: 200,
                                        id: 'static_text5',
                                      },
                                      caption: '文本',
                                      contentWidth: 200,
                                      itemStyle: 'DEFAULT',
                                      itemType: 'RAWITEM',
                                      layoutPos: {
                                        shrink: 1,
                                        layout: 'FLEX',
                                        width: 200,
                                        widthMode: 'PX',
                                      },
                                      width: 200,
                                      showCaption: true,
                                      id: 'static_text5',
                                    },
                                    {
                                      editor: {
                                        halign: 'LEFT',
                                        renderMode: 'TEXT_DYNAMIC',
                                        valign: 'MIDDLE',
                                        wrapMode: 'NOWRAP',
                                        editorType: 'SPAN',
                                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                                        valueType: 'SIMPLE',
                                        editable: true,
                                        id: 'video_url',
                                      },
                                      viewFieldName: 'video_url',
                                      allowEmpty: true,
                                      caption: '文本(动态)',
                                      itemStyle: 'DEFAULT',
                                      itemType: 'FIELD',
                                      layoutPos: {
                                        shrink: 1,
                                        layout: 'FLEX',
                                      },
                                      id: 'video_url',
                                    },
                                  ],
                                  layout: {
                                    dir: 'row',
                                    layout: 'FLEX',
                                  },
                                  dataRegionType: 'INHERIT',
                                  caption: '容器',
                                  itemStyle: 'DEFAULT',
                                  itemType: 'CONTAINER',
                                  layoutPos: {
                                    shrink: 1,
                                    layout: 'FLEX',
                                    spacingBottom: 'OUTERMEDIUM',
                                  },
                                  id: 'container10',
                                },
                              ],
                              predefinedType: 'CONTAINER_MULTIDATA',
                              layout: {
                                layout: 'FLEX',
                              },
                              dataName: 'interview_feedbacks',
                              dataRegionType: 'MULTIDATA',
                              dataSourceType: 'ACTIVEDATAPARAM',
                              caption: '多项数据容器',
                              itemStyle: 'DEFAULT',
                              itemType: 'CONTAINER',
                              layoutPos: {
                                shrink: 1,
                                layout: 'FLEX',
                              },
                              id: 'container_multidata',
                            },
                          ],
                          layout: {
                            layout: 'FLEX',
                          },
                          dataRegionType: 'INHERIT',
                          caption: '容器',
                          itemStyle: 'DEFAULT',
                          itemType: 'CONTAINER',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'container6',
                        },
                      ],
                      layout: {
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'container5',
                    },
                  ],
                  layout: {
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container',
                },
              ],
              layoutPanel: true,
              codeName: 'usr0813095453',
              controlType: 'PANEL',
              logicName: '面试安排列表布局面板',
              appDataEntityId: 'web.hr_applicant_interview',
              controlParam: {},
              modelId: 'ed65fb5e50687e863fe1bd0bd34aa9d9',
              modelType: 'PSSYSVIEWPANEL',
              name: 'masterlayoutpanel',
              id: 'web.hr_applicant_interview.usr0813095453',
            },
            textAppDEFieldId: 'name',
            appDataEntityId: 'web.hr_applicant_interview',
            id: 'master',
          },
        ],
        navViewPos: 'NONE',
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main_calendar_view_calendar',
        controlType: 'CALENDAR',
        logicName: '面试安排日历视图_日历部件',
        appDataEntityId: 'web.hr_applicant_interview',
        controlParam: {
          id: 'calendar',
        },
        modelId: '3af1e65fe4948678e4e7488dc9e9de3c',
        modelType: 'PSSYSCALENDAR',
        name: 'calendar',
        id: 'web.hr_applicant_interview.main_calendar_view_calendar',
      },
      {
        xdataControlName: 'calendar',
        codeName: 'main_calendar_view_add_interview',
        controlType: 'TOOLBAR',
        logicName: '添加/预约面试',
        appDataEntityId: 'web.hr_applicant_interview',
        controlParam: {
          id: 'add_interview',
        },
        modelId: '2da602a0f5191d80818137d2d50223fe',
        modelType: 'PSDETOOLBAR',
        name: 'add_interview',
        id: 'main_calendar_view_add_interview',
      },
      {
        xdataControlName: 'calendar',
        codeName: 'main_calendar_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '添加/预约面试',
        appDataEntityId: 'web.hr_applicant_interview',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '2da602a0f5191d80818137d2d50223fe',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_calendar_view_toolbar',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'web.hr_applicant_interview',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        caption: '面试安排日历视图',
        codeName: 'main_calendar_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.hr_applicant_interview',
        controlParam: {},
        name: 'captionbar',
        id: 'main_calendar_view_captionbar',
      },
    ],
    codeName: 'usr1013789613',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'main_calendar_view日历视图布局面板',
    appDataEntityId: 'web.hr_applicant_interview',
    controlParam: {},
    modelId: 'ab45d5686267d09d414dd8ad81493d0f',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr1013789613',
  },
  title: '面试安排日历视图',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'c52cf013adf7536e9d2a85b8fdde4a58',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_applicant_interviewmain_calendar_view',
  id: 'web.hr_applicant_interview_main_calendar_view',
};
