export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'baseinfo_view',
  deviewId: 'be27772e625f51f236cb8620ca339632',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_APPLICANT',
  },
  caption: '候选人申请',
  codeName: 'hr_applicant_baseinfo_view',
  appDataEntityId: 'web.hr_applicant',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'baseinfo_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '候选人申请_基本信息页_工具栏',
      appDataEntityId: 'web.hr_applicant',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '1d248cb7e531cd4507ffb5cd32c7524b',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'baseinfo_view_toolbar',
    },
    {
      autoSaveMode: 1,
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.hr_applicant',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.hr_applicant',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.hr_applicant',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.hr_applicant',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.hr_applicant',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.hr_applicant',
        id: 'update',
      },
      enableAutoSave: true,
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 21,
                  enableCond: 3,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'description',
                  editor: {
                    editorParams: {
                      readonly: 'true',
                    },
                    editorType: 'HTMLEDITOR',
                    valueType: 'SIMPLE',
                    editable: true,
                    readOnly: true,
                    id: 'formitem',
                  },
                  allowEmpty: true,
                  emptyCaption: true,
                  codeName: 'formitem',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'formitem',
                },
              ],
              caption: '候选人申请基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'applicant_baseinfo_form',
      controlType: 'FORM',
      logicName: '候选人申请_基本信息页_表单',
      appDataEntityId: 'web.hr_applicant',
      controlParam: {
        id: 'form',
      },
      modelId: 'e58049b81a636560cd84d0de633daae3',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.hr_applicant.applicant_baseinfo_form',
    },
    {
      codeName: 'baseinfo_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.hr_applicant',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'baseinfo_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_APPLICANT',
      },
      caption: '候选人申请',
      codeName: 'baseinfo_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.hr_applicant',
      controlParam: {},
      name: 'captionbar',
      id: 'baseinfo_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.hr_applicant',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '候选人申请_基本信息页',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'd0c80e638c51bc1da94f3c4b729dc92c',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_applicantbaseinfo_view',
  id: 'web.hr_applicant_baseinfo_view',
};
