export default {
  xdataControlName: 'list',
  loadDefault: true,
  deviewCodeName: 'filter_list_view',
  deviewId: '5a8a03855bf4c777346b6d6816efe605',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_CANDIDATE_FILTER_DETAIL',
  },
  caption: '筛选候选人明细',
  codeName: 'hr_candidate_filter_detail_filter_list_view',
  appDataEntityId: 'web.hr_candidate_filter_detail',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'ListView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.hr_candidate_filter_detail_edit_view',
        },
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.hr_candidate_filter_detail_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'POPUPMODAL',
          refAppViewId: 'web.hr_candidate_filter_detail_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.hr_candidate_filter_detail_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '筛选候选人明细编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.HR_CANDIDATE_FILTER_DETAIL.EDITVIEW',
      },
      refAppViewId: 'web.hr_candidate_filter_detail_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'POPUPMODAL',
      realTitle: '筛选候选人明细编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.HR_CANDIDATE_FILTER_DETAIL.EDITVIEW',
      },
      refAppViewId: 'web.hr_candidate_filter_detail_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      xdataControlName: 'list',
      codeName: 'filter_list_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '筛选列表视图_工具栏',
      appDataEntityId: 'web.hr_candidate_filter_detail',
      controlParam: {
        id: 'toolbar',
      },
      modelId: 'a1d7f6e087f890cce30b7ab57623f71e',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'filter_list_view_toolbar',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'web.sysoperator',
                          editorStyle: 'PERSONNEL_INFO',
                          editorType: 'SPAN',
                          sysPFPluginId: 'personnel_info',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'user_name',
                        },
                        viewFieldName: 'user_name',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'user_name',
                      },
                      {
                        editor: {
                          editorType: 'HIDDEN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'status',
                        },
                        viewFieldName: 'status',
                        allowEmpty: true,
                        hidden: true,
                        caption: '文本(动态)',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'status',
                      },
                      {
                        rawItem: {
                          caption: '通过了该简历',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text1',
                        },
                        caption: '文本',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          halignSelf: 'CENTER',
                          layout: 'FLEX',
                          spacingLeft: 'OUTERSMALL',
                          valignSelf: 'MIDDLE',
                        },
                        panelItemGroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedItemNames: ['status'],
                            groupOP: 'AND',
                            panelItemLogics: [
                              {
                                condOp: 'EQ',
                                dstModelField: 'status',
                                value: '2',
                                logicType: 'SINGLE',
                                id: '逻辑项',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        showCaption: true,
                        id: 'static_text1',
                      },
                      {
                        rawItem: {
                          caption: '淘汰了该简历',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text2',
                        },
                        caption: '文本',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          halignSelf: 'CENTER',
                          layout: 'FLEX',
                          spacingLeft: 'OUTERSMALL',
                          valignSelf: 'MIDDLE',
                        },
                        panelItemGroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedItemNames: ['status'],
                            groupOP: 'AND',
                            panelItemLogics: [
                              {
                                condOp: 'EQ',
                                dstModelField: 'status',
                                value: '3',
                                logicType: 'SINGLE',
                                id: '逻辑项',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        showCaption: true,
                        id: 'static_text2',
                      },
                      {
                        rawItem: {
                          caption: '待处理',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text',
                        },
                        caption: '文本',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          halignSelf: 'CENTER',
                          layout: 'FLEX',
                          spacingLeft: 'OUTERSMALL',
                          valignSelf: 'MIDDLE',
                        },
                        panelItemGroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedItemNames: ['status'],
                            groupOP: 'AND',
                            panelItemLogics: [
                              {
                                condOp: 'EQ',
                                dstModelField: 'status',
                                value: '1',
                                logicType: 'SINGLE',
                                id: '逻辑项',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        showCaption: true,
                        id: 'static_text',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container1',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          editorParams: {
                            readonly: 'true',
                          },
                          editorType: 'HTMLEDITOR',
                          valueType: 'SIMPLE',
                          editable: true,
                          readOnly: true,
                          id: 'content',
                        },
                        viewFieldName: 'content',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'content',
                      },
                    ],
                    layout: {
                      align: 'flex-start',
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container3',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  spacingRight: 'OUTERSMALL',
                  widthMode: 'FULL',
                },
                id: 'container',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
              widthMode: 'FULL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'usr0812510347',
        controlType: 'PANEL',
        logicName: 'List_列表项面板',
        appDataEntityId: 'web.hr_candidate_filter_detail',
        controlParam: {},
        modelId: 'db8f9f3a162ea1b3b3df33c2aa9a1f0c',
        modelType: 'PSSYSVIEWPANEL',
        name: 'list_itempanel',
        id: 'web.hr_candidate_filter_detail.usr0812510347',
      },
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'applicant_id',
          dataType: 25,
          id: 'applicant_id',
        },
        {
          appDEFieldId: 'candidate_filter_id',
          dataType: 25,
          id: 'candidate_filter_id',
        },
        {
          appDEFieldId: 'user_id',
          dataType: 25,
          id: 'user_id',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.hr_candidate_filter_detail',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'web.hr_candidate_filter_detail',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.hr_candidate_filter_detail',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.hr_candidate_filter_detail',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.hr_candidate_filter_detail',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'filter_list_view_list',
      controlType: 'LIST',
      logicName: 'List',
      appDataEntityId: 'web.hr_candidate_filter_detail',
      controlParam: {
        id: 'list',
      },
      modelId: '7d2823ce17a23cc34feb3b9c74624916',
      modelType: 'PSDELIST',
      name: 'list',
      id: 'web.hr_candidate_filter_detail.filter_list_view_list',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.hr_candidate_filter_detail',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_CANDIDATE_FILTER_DETAIL',
      },
      caption: '筛选候选人明细',
      codeName: 'filter_list_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.hr_candidate_filter_detail',
      controlParam: {},
      name: 'captionbar',
      id: 'filter_list_view_captionbar',
    },
  ],
  sysCss: {
    cssName: 'filter_list_style',
  },
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDELISTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.hr_candidate_filter_detail',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '筛选列表视图',
  viewStyle: 'DEFAULT',
  viewType: 'DELISTVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '66d150d4f7e5d1a12bf47a7b84bd7cb3',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_candidate_filter_detailfilter_list_view',
  id: 'web.hr_candidate_filter_detail_filter_list_view',
};
