export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'recommend_department_option_view',
  deviewId: '6f58d812b076c20d816207d097e47e93',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_CANDIDATE_FILTER',
  },
  caption: '筛选候选人',
  codeName: 'hr_candidate_filter_recommend_department_option_view',
  height: 600,
  appDataEntityId: 'web.hr_candidate_filter',
  appViewNavParams: [
    {
      key: 'applicant_id',
      value: 'applicant_id',
      id: 'applicant_id',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'form',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionType: 'UIACTION',
            buttonStyle: 'PRIMARY',
            buttonType: 'PANELBUTTON',
            uiactionId: 'view_okaction',
            renderMode: 'BUTTON',
            tooltip: '推荐并进入用人部门筛选',
            caption: '推荐并进入用人部门筛选',
            itemStyle: 'PRIMARY',
            itemType: 'BUTTON',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'button_okaction',
          },
          {
            actionType: 'UIACTION',
            buttonStyle: 'INFO',
            buttonType: 'PANELBUTTON',
            uiactionId: 'view_cancelaction',
            renderMode: 'BUTTON',
            tooltip: '取消',
            caption: '取消',
            itemStyle: 'INFO',
            itemType: 'BUTTON',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'button_cancelaction',
          },
        ],
        layout: {
          dir: 'row-reverse',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_footer',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'OptionView',
        id: 'engine',
      },
    ],
    controls: [
      {
        createControlAction: {
          appDEMethodId: 'recommend_department',
          appDataEntityId: 'web.hr_candidate_filter',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'web.hr_candidate_filter',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'web.hr_candidate_filter',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.hr_candidate_filter',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.hr_candidate_filter',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'recommend_department',
          appDataEntityId: 'web.hr_candidate_filter',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 21,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'reviewer_user_ids',
                    editor: {
                      enablePickupView: true,
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_default',
                      appDataEntityId: 'web.hr_employee',
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'ADDRESSPICKUP',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'reviewer_user_ids',
                    },
                    caption: '推荐到',
                    codeName: 'reviewer_user_ids',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'reviewer_user_ids',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    itemHeight: 90,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'memo',
                    editor: {
                      maxLength: 2000,
                      showMaxLength: true,
                      editorHeight: 90,
                      editorType: 'TEXTAREA',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'memo',
                    },
                    allowEmpty: true,
                    caption: '告诉用人部门',
                    codeName: 'memo',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'memo',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'carboncopy_user_ids',
                    editor: {
                      enablePickupView: true,
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_default',
                      appDataEntityId: 'web.hr_employee',
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'ADDRESSPICKUP',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'carboncopy_user_ids',
                    },
                    allowEmpty: true,
                    caption: '抄送',
                    codeName: 'carboncopy_user_ids',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'carboncopy_user_ids',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'type',
                    editor: {
                      appCodeListId: 'web.hr__candidate_filter_type',
                      editorType: 'CHECKBOXLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'type',
                    },
                    allowEmpty: true,
                    needCodeListConfig: true,
                    caption: '推荐简历类型',
                    codeName: 'type',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'type',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    caption: '标识',
                    codeName: 'id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'id',
                  },
                  {
                    createDV: 'hr_applicant',
                    createDVT: 'APPDATA',
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'applicant_id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'applicant_id',
                    },
                    updateDV: 'hr_applicant',
                    updateDVT: 'APPDATA',
                    allowEmpty: true,
                    hidden: true,
                    caption: '候选人申请',
                    codeName: 'applicant_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'applicant_id',
                  },
                ],
                caption: '筛选候选人基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'recommend_department',
        controlType: 'FORM',
        logicName: '推荐给用人部门',
        appDataEntityId: 'web.hr_candidate_filter',
        controlParam: {
          id: 'form',
        },
        modelId: '4c67cb195bcead9108eed83b348edca9',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'web.hr_candidate_filter.recommend_department',
      },
      {
        codeName: 'recommend_department_option_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'web.hr_candidate_filter',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'recommend_department_option_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.HR_CANDIDATE_FILTER',
        },
        caption: '筛选候选人',
        codeName: 'recommend_department_option_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.hr_candidate_filter',
        controlParam: {},
        name: 'captionbar',
        id: 'recommend_department_option_view_captionbar',
      },
    ],
    codeName: 'usr0811561435',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'recommend_department_option_view选项操作视图布局面',
    appDataEntityId: 'web.hr_candidate_filter',
    controlParam: {},
    modelId: '02039487e4b48ca1e70baac7208f13c1',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0811561435',
  },
  title: '推荐给用人部门',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  width: 800,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f353587d4aa98480cd3446995bd719ca',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_candidate_filterrecommend_department_option_view',
  id: 'web.hr_candidate_filter_recommend_department_option_view',
};
