export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'hm_grid_view',
  deviewId: '3b4ba9841ca9a6933b4871885b4954b0',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_EXAM',
  },
  caption: '考试/评测',
  codeName: 'hr_exam_hm_grid_view',
  appDataEntityId: 'web.hr_exam',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '搜索表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'searchform',
                  },
                ],
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                id: 'view_searchform',
              },
              {
                caption: '搜索栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'searchbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表格',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'grid',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                id: 'view_content',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'web.hr_exam_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'web.hr_exam_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.hr_exam_hr_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.hr_exam_hr_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '考试/评测详情',
        refAppViewId: 'web.hr_exam_hr_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '考试/测评编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.HR_EXAM.EDITVIEW',
        },
        refAppViewId: 'web.hr_exam_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        xdataControlName: 'grid',
        codeName: 'hm_grid_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '考试/评测_工具栏',
        appDataEntityId: 'web.hr_exam',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '7c335ad1aa8f0b84eb1f116bf93293d7',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'hm_grid_view_toolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'candidate_display_name',
            excelCaption: '候选人名称',
            appDEFieldId: 'candidate_display_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '候选人名称',
            codeName: 'candidate_display_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'candidate_display_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'job_name',
            excelCaption: '应聘职位',
            appDEFieldId: 'job_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '应聘职位',
            codeName: 'job_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'job_name',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '考试/评测',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '考试/评测',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'type',
            excelCaption: '类型',
            appCodeListId: 'web.hr__exam_type',
            appDEFieldId: 'type',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '类型',
            codeName: 'type',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'type',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'create_time',
            excelCaption: '发起时间',
            appDEFieldId: 'create_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '发起时间',
            codeName: 'create_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'create_time',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'status',
            excelCaption: '考试状态',
            appCodeListId: 'web.hr__exam_status',
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '考试状态',
            codeName: 'status',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'status',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'finish_time',
            excelCaption: '完成时间',
            appDEFieldId: 'finish_time',
            valueFormat: 'YYYY-MM-DD HH:mm:ss',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '完成时间',
            codeName: 'finish_time',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'finish_time',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'result',
            excelCaption: '考试测评结果',
            appDEFieldId: 'result',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            caption: '考试测评结果',
            codeName: 'result',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'result',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'candidate_display_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'candidate_display_name',
          },
          {
            appDEFieldId: 'job_name',
            scriptCode:
              'return  `<span> <span style="color:#8599e2;padding: 5px;font-weight: 600;">社招</span>${data.job_name} </span>`',
            valueType: 'SIMPLE',
            customCode: true,
            dataType: 25,
            id: 'job_name',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'type',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'type',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'create_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'create_time',
          },
          {
            appDEFieldId: 'status',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'status',
          },
          {
            format: 'YYYY-MM-DD HH:mm:ss',
            appDEFieldId: 'finish_time',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'finish_time',
          },
          {
            appDEFieldId: 'result',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'result',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'applicant_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'applicant_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        singleSelect: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_hm_myself',
          appDataEntityId: 'web.hr_exam',
          id: 'fetch',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.hr_exam',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main2',
        controlType: 'GRID',
        logicName: '考试/评测_表格',
        appDataEntityId: 'web.hr_exam',
        controlParam: {
          id: 'grid',
        },
        modelId: 'e2b7a59f9919c26c5296d8096ac54eb3',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'web.hr_exam.main2',
      },
      {
        groupMode: 'SINGLE',
        appCounterRefId: 'e207617b297b7e3d454a90fb5f216ba6',
        searchBarGroups: [
          {
            defaultGroup: true,
            caption: '未完成',
            counterId: 'status_0',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"status","condop":"EQ","value":"10"}]}]}}',
            itemType: 'GROUP',
            id: 'status_0',
          },
          {
            caption: '已完成',
            counterId: 'status_1',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"status","condop":"EQ","value":"20"}]}]}}',
            itemType: 'GROUP',
            id: 'status_1',
          },
        ],
        enableGroup: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'my_interview_count_exam',
              counterType: 'DEDR',
              getAppDEActionId: 'my_interview_count',
              appDataEntityId: 'web.hr_exam',
              timer: 60000,
              uniqueTag: 'my_interview_count_exam',
              name: '用人经理-我的考试/测评-搜索栏计数器',
              id: 'web.my_interview_count_exam',
            },
            tag: 'e207617b297b7e3d454a90fb5f216ba6',
            uniqueTag: 'my_interview_count_exam',
            id: 'e207617b297b7e3d454a90fb5f216ba6',
          },
        ],
        codeName: 'grid_searchbar',
        controlStyle: 'CARD',
        controlType: 'SEARCHBAR',
        logicName: '考试/评测搜索栏',
        appDataEntityId: 'web.hr_exam',
        controlParam: {
          id: 'searchbar',
        },
        sysPFPluginId: 'card',
        modelId: '5071686da83f912ab10cef2ce0bd7e03',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'web.hr_exam.grid_searchbar',
      },
      {
        searchButtonStyle: 'NONE',
        enableAutoSearch: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'candidate_display_name',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_candidate_display_name_like',
                },
                allowEmpty: true,
                caption: '候选人名称',
                codeName: 'n_candidate_display_name_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 6,
                  colMD: 6,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_candidate_display_name_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'job_name',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_job_name_like',
                },
                allowEmpty: true,
                caption: '职位',
                codeName: 'n_job_name_like',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 6,
                  colMD: 6,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_job_name_like',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'type',
                editor: {
                  singleSelect: true,
                  appCodeListId: 'web.hr__exam_type',
                  editorType: 'DROPDOWNLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_type_eq',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '类型',
                codeName: 'n_type_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 6,
                  colMD: 6,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_type_eq',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'status',
                editor: {
                  singleSelect: true,
                  appCodeListId: 'web.hr__exam_status',
                  editorType: 'DROPDOWNLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_status_eq',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '考试状态',
                codeName: 'n_status_eq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 6,
                  colMD: 6,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'n_status_eq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main2',
        controlType: 'SEARCHFORM',
        logicName: '考试/评测_搜索表单',
        appDataEntityId: 'web.hr_exam',
        controlParam: {
          id: 'searchform',
        },
        modelId: 'e2b7a59f9919c26c5296d8096ac54eb3',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'web.hr_exam.main2',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.HR_EXAM',
        },
        caption: '考试/评测',
        codeName: 'hm_grid_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.hr_exam',
        controlParam: {},
        name: 'captionbar',
        id: 'hm_grid_view_captionbar',
      },
    ],
    codeName: 'usr0821847364',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'hm_grid_view表格视图布局',
    appDataEntityId: 'web.hr_exam',
    controlParam: {},
    modelId: '4f421b8f525115b1122181aa41d13274',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0821847364',
  },
  title: '考试/评测',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '34835fc105277c214d1d2248f8ae5dd3',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_examhm_grid_view',
  id: 'web.hr_exam_hm_grid_view',
};
