export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'create_View',
  deviewId: '8095bfa971fc65c838698020c64e7d7f',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_IDEA',
  },
  caption: '招聘需求新建',
  codeName: 'hr_idea_create_view',
  appDataEntityId: 'web.hr_idea',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'form',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-save',
              glyph: 'xf0c7@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'form',
        codeName: 'create_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '招聘需求新建视图_工具栏',
        appDataEntityId: 'web.hr_idea',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '62edbf12c0f1181914ed0a7acd203244',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'create_view_toolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.hr_idea',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'web.hr_idea',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'web.hr_idea',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.hr_idea',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.hr_idea',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.hr_idea',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'identifier',
                editor: {
                  maxLength: 100,
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'identifier',
                },
                caption: '需求编号',
                codeName: 'identifier',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'identifier',
              },
              {
                dataType: 9,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'need_number',
                editor: {
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'need_number',
                },
                caption: '需求人数',
                codeName: 'need_number',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'need_number',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'job_name',
                editor: {
                  maxLength: 100,
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'job_name',
                },
                caption: '职位名称',
                codeName: 'job_name',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'job_name',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'job_type',
                editor: {
                  appCodeListId: 'web.base__job_type',
                  editorType: 'RADIOBUTTONLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'job_type',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '职位性质',
                codeName: 'job_type',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'job_type',
              },
              {
                createDV: 'srforgsectorname',
                createDVT: 'SESSION',
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'department_code',
                editor: {
                  maxLength: 100,
                  editorType: 'TEXTBOX',
                  editorItems: [
                    {
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_default',
                      appDataEntityId: 'web.res_company',
                      id: 'department_code',
                    },
                  ],
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'department_code',
                },
                updateDV: 'srforgsectorname',
                updateDVT: 'SESSION',
                caption: '需求部门',
                codeName: 'department_code',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'department_code',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'manager_employee_ids',
                editor: {
                  singleSelect: true,
                  handlerType: 'PickupText',
                  appDEACModeId: 'default',
                  appDEDataSetId: 'fetch_default',
                  appDataEntityId: 'web.hr_employee',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  valueItemName: 'manager_employee_ids',
                  editorParams: {
                    AC: 'TRUE',
                    TRIGGER: 'TRUE',
                    PICKUPVIEW: 'FALSE',
                  },
                  editorType: 'PICKEREX_TRIGGER',
                  editorItems: [
                    {
                      id: 'manager_employee_ids',
                    },
                  ],
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'manager_employee_ids',
                },
                caption: '招聘需求负责人',
                codeName: 'manager_employee_ids',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'manager_employee_ids',
              },
              {
                dataType: 5,
                enableCond: 3,
                itemWidth: 872,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'date_from',
                editor: {
                  dateTimeFormat: 'YYYY-MM-DD',
                  editorParams: {
                    TIMEFMT: 'YYYY-MM-DD',
                  },
                  editorType: 'DATEPICKEREX_NOTIME',
                  editorWidth: 742,
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'date_from',
                },
                valueFormat: 'YYYY-MM-DD',
                caption: '招聘需求开始时间',
                codeName: 'date_from',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'date_from',
              },
              {
                dataType: 5,
                enableCond: 3,
                itemWidth: 872,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'date_to',
                editor: {
                  dateTimeFormat: 'YYYY-MM-DD',
                  editorParams: {
                    TIMEFMT: 'YYYY-MM-DD',
                  },
                  editorType: 'DATEPICKEREX_NOTIME',
                  editorWidth: 742,
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'date_to',
                },
                valueFormat: 'YYYY-MM-DD',
                allowEmpty: true,
                caption: '招聘需求结束时间',
                codeName: 'date_to',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'date_to',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'management_rank_ids',
                editor: {
                  maxLength: 100,
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'management_rank_ids',
                },
                allowEmpty: true,
                caption: '管理职级',
                codeName: 'management_rank_ids',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'management_rank_ids',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'professional_rank_ids',
                editor: {
                  maxLength: 100,
                  editorType: 'TEXTBOX',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'professional_rank_ids',
                },
                allowEmpty: true,
                caption: '专业职级',
                codeName: 'professional_rank_ids',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'professional_rank_ids',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'address_id',
                editor: {
                  enablePickupView: true,
                  singleSelect: true,
                  handlerType: 'PickupText',
                  appDEACModeId: 'default',
                  appDEDataSetId: 'fetch_default',
                  appDataEntityId: 'web.hr_work_location',
                  enableAC: true,
                  forceSelection: true,
                  showTrigger: true,
                  editorParams: {
                    AC: 'TRUE',
                    PICKUPVIEW: 'TRUE',
                  },
                  editorType: 'PICKER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'address_id',
                },
                allowEmpty: true,
                caption: '工作地点',
                codeName: 'address_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'address_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'education',
                editor: {
                  singleSelect: true,
                  appCodeListId: 'web.base__idea_education',
                  editorType: 'DROPDOWNLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'education',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '学历要求',
                codeName: 'education',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'education',
              },
              {
                dataType: 9,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'payment_method',
                editor: {
                  singleSelect: true,
                  appCodeListId: 'web.base__idea_paymentmethod',
                  editorType: 'DROPDOWNLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'paymentmethod',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '发薪方式',
                codeName: 'paymentmethod',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'paymentmethod',
              },
              {
                dataType: 9,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'salary_unit',
                editor: {
                  singleSelect: true,
                  appCodeListId: 'web.base__idea_salaryunit',
                  editorType: 'DROPDOWNLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'salary_unit',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '薪资单位',
                codeName: 'salary_unit',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'salary_unit',
              },
              {
                dataType: 9,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'pay_period',
                editor: {
                  editorType: 'NUMBER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'payperiod',
                },
                allowEmpty: true,
                caption: '发薪月数',
                codeName: 'payperiod',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'payperiod',
              },
              {
                dataType: 9,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'min_salary',
                editor: {
                  editorType: 'NUMBER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'min_salary',
                },
                allowEmpty: true,
                caption: '最低薪资',
                codeName: 'min_salary',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'min_salary',
              },
              {
                dataType: 9,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'max_salary',
                editor: {
                  editorType: 'NUMBER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'max_salary',
                },
                allowEmpty: true,
                caption: '最高薪资',
                codeName: 'max_salary',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'max_salary',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'status',
                editor: {
                  singleSelect: true,
                  appCodeListId: 'web.base__idea_status',
                  editorType: 'DROPDOWNLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'status',
                },
                needCodeListConfig: true,
                caption: '需求状态',
                codeName: 'status',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 12,
                  colMD: 12,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'status',
              },
              {
                dataType: 21,
                enableCond: 3,
                itemHeight: 220,
                labelPos: 'TOP',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'description',
                editor: {
                  maxLength: 1048576,
                  showMaxLength: true,
                  editorHeight: 200,
                  editorParams: {
                    HEIGHT: '200',
                  },
                  editorType: 'TEXTAREA_10',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'description',
                },
                allowEmpty: true,
                caption: '需求描述',
                codeName: 'description',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'description',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'create_view_form',
        controlType: 'FORM',
        logicName: '表单_新建招聘需求',
        appDataEntityId: 'web.hr_idea',
        controlParam: {
          id: 'form',
        },
        modelId: 'd6c8a8298b151b1ed0a2c5eaf42756bd',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'web.hr_idea.create_view_form',
      },
      {
        codeName: 'create_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'web.hr_idea',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'create_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.HR_IDEA',
        },
        caption: '招聘需求新建',
        codeName: 'create_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.hr_idea',
        controlParam: {},
        name: 'captionbar',
        id: 'create_view_captionbar',
      },
    ],
    codeName: 'usr0807503197',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'create_View编辑视图布局面板',
    appDataEntityId: 'web.hr_idea',
    controlParam: {},
    modelId: 'e9d94708293696d1451a4b9ddf6accee',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0807503197',
  },
  title: '招聘需求新建视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'a4462f42f988a960c4332fb3486edaa1',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_ideacreate_View',
  id: 'web.hr_idea_create_view',
};
