export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'myinterview_detail_calendar_view',
  deviewId: 'dd25fdaa327344b66463bf06f22cb382',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_INTERVIEW',
  },
  caption: '面试详情',
  codeName: 'hr_interview_myinterview_detail_calendar_view',
  appDataEntityId: 'web.hr_interview',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewNavParams: [
    {
      key: 'hr_interview_id',
      value: 'hr_interview',
      id: 'hr_interview_id',
    },
  ],
  controls: [
    {
      calendarStyle: 'TIMELINE',
      groupMode: 'NONE',
      legendPos: 'NONE',
      sysCalendarItems: [
        {
          beginTimeAppDEFieldId: 'start_date',
          endTimeAppDEFieldId: 'start_date',
          idAppDEFieldId: 'id',
          itemStyle: 'DEFAULT',
          itemType: 'master',
          appDEDataSetId: 'fetch_my_interview',
          layoutPanel: {
            layoutMode: 'FLEX',
            layout: {
              layout: 'FLEX',
            },
            rootPanelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-user',
                            glyph: 'xf007@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          predefinedType: 'STATIC_IMAGE',
                          rawItemHeight: 19,
                          id: 'static_image',
                        },
                        caption: '图片',
                        contentHeight: 19,
                        height: 19,
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          height: 19,
                          heightMode: 'PX',
                          layout: 'FLEX',
                          spacingRight: 'OUTERSMALL',
                        },
                        sysImage: {
                          cssClass: 'fa fa-user',
                          glyph: 'xf007@FontAwesome',
                        },
                        showCaption: true,
                        id: 'static_image',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'web.hr__interview_stage',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'stage_id',
                        },
                        viewFieldName: 'stage_id',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'stage_id',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 32,
                    height: 32,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      height: 32,
                      heightMode: 'PX',
                      layout: 'FLEX',
                      spacingBottom: 'OUTERMEDIUM',
                    },
                    id: 'container8',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          sysImage: {
                            cssClass: 'fa fa-video-camera',
                            glyph: 'xf03d@FontAwesome',
                          },
                          contentType: 'IMAGE',
                          predefinedType: 'STATIC_IMAGE',
                          id: 'static_image1',
                        },
                        caption: '图片',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingRight: 'OUTERSMALL',
                        },
                        sysImage: {
                          cssClass: 'fa fa-video-camera',
                          glyph: 'xf03d@FontAwesome',
                        },
                        showCaption: true,
                        id: 'static_image1',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'web.hr__interview_type',
                          editorType: 'SPAN',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'interview_type',
                        },
                        viewFieldName: 'interview_type',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingRight: 'OUTERSMALL',
                        },
                        id: 'interview_type',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'start_date',
                        },
                        viewFieldName: 'start_date',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingRight: 'OUTERSMALL',
                        },
                        id: 'start_date',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'web.hr__interview_start_time',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'start_time',
                        },
                        viewFieldName: 'start_time',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'start_time',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingBottom: 'OUTERMEDIUM',
                    },
                    id: 'container7',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '负责人',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text2',
                        },
                        caption: '文本',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingRight: 'OUTERSMALL',
                        },
                        showCaption: true,
                        id: 'static_text2',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'owner_name',
                        },
                        viewFieldName: 'owner_name',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'owner_name',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingBottom: 'OUTERMEDIUM',
                    },
                    id: 'container1',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '会议号',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text1',
                        },
                        caption: '文本',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingRight: 'OUTERSMALL',
                        },
                        showCaption: true,
                        id: 'static_text1',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'meeting_id',
                        },
                        viewFieldName: 'meeting_id',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'meeting_id',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingBottom: 'OUTERMEDIUM',
                    },
                    id: 'container3',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '候选人状态',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text3',
                        },
                        caption: '文本',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingRight: 'OUTERSMALL',
                        },
                        showCaption: true,
                        id: 'static_text3',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'candidate_status',
                        },
                        viewFieldName: 'candidate_status',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'candidate_status',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingBottom: 'OUTERMEDIUM',
                    },
                    id: 'container5',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          caption: '面试官',
                          halign: 'LEFT',
                          renderMode: 'TEXT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          predefinedType: 'STATIC_TEXT',
                          id: 'static_text4',
                        },
                        caption: '文本',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingBottom: 'OUTERSMALL',
                        },
                        showCaption: true,
                        id: 'static_text4',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                editor: {
                                  halign: 'LEFT',
                                  renderMode: 'TEXT_DYNAMIC',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  appCodeListId: 'web.sysoperator',
                                  editorStyle: 'PERSONNEL_INFO',
                                  editorType: 'SPAN',
                                  sysPFPluginId: 'personnel_info',
                                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'interviewer_name2',
                                },
                                viewFieldName: 'interviewer_name',
                                allowEmpty: true,
                                convertToCodeItemText: true,
                                caption: '文本(动态)',
                                itemStyle: 'DEFAULT',
                                itemType: 'FIELD',
                                layoutPos: {
                                  shrink: 1,
                                  layout: 'FLEX',
                                  spacingRight: 'OUTERMEDIUM',
                                },
                                id: 'interviewer_name2',
                              },
                              {
                                editor: {
                                  halign: 'LEFT',
                                  renderMode: 'TEXT_DYNAMIC',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  appCodeListId:
                                    'web.hr__interview_result_type',
                                  editorType: 'SPAN',
                                  predefinedType: 'FIELD_TEXT_DYNAMIC',
                                  valueType: 'SIMPLE',
                                  editable: true,
                                  id: 'result_type',
                                },
                                viewFieldName: 'result_type',
                                allowEmpty: true,
                                convertToCodeItemText: true,
                                caption: '文本(动态)',
                                cssStyle: 'line-height: 32px;',
                                itemStyle: 'DEFAULT',
                                itemType: 'FIELD',
                                layoutPos: {
                                  shrink: 1,
                                  layout: 'FLEX',
                                },
                                id: 'result_type',
                              },
                            ],
                            layout: {
                              dir: 'row',
                              layout: 'FLEX',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingBottom: 'OUTERMEDIUM',
                            },
                            id: 'container2',
                          },
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                rawItem: {
                                  caption: '面试链接',
                                  halign: 'LEFT',
                                  renderMode: 'TEXT',
                                  valign: 'MIDDLE',
                                  wrapMode: 'NOWRAP',
                                  contentType: 'RAW',
                                  cssStyle: 'line-height:32px;',
                                  predefinedType: 'STATIC_TEXT',
                                  id: 'static_text',
                                },
                                caption: '文本',
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  shrink: 1,
                                  layout: 'FLEX',
                                  spacingRight: 'OUTERMEDIUM',
                                },
                                showCaption: true,
                                id: 'static_text',
                              },
                              {
                                actionType: 'UIACTION',
                                buttonStyle: 'DEFAULT',
                                buttonType: 'PANELBUTTON',
                                uiactionId: 'start_interview@hr_interview',
                                renderMode: 'LINK',
                                tooltip: '进入面试',
                                uiactionTarget: 'SINGLEDATA',
                                caption: '进入面试',
                                itemStyle: 'DEFAULT',
                                itemType: 'BUTTON',
                                layoutPos: {
                                  shrink: 1,
                                  layout: 'FLEX',
                                },
                                sysCss: {
                                  cssName: 'into_interview',
                                },
                                sysImage: {
                                  cssClass: 'fa fa-video-camera',
                                  glyph: 'xf03d@FontAwesome',
                                },
                                showCaption: true,
                                id: 'button_link',
                              },
                            ],
                            layout: {
                              dir: 'row',
                              layout: 'FLEX',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingBottom: 'OUTERMEDIUM',
                            },
                            id: 'container4',
                          },
                        ],
                        predefinedType: 'CONTAINER_MULTIDATA',
                        layout: {
                          layout: 'FLEX',
                        },
                        dataName: 'interview_feedbacks',
                        dataRegionType: 'MULTIDATA',
                        dataSourceType: 'ACTIVEDATAPARAM',
                        caption: '多项数据容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'container_multidata',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container6',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
            ],
            layoutPanel: true,
            codeName: 'usr0813095454',
            controlType: 'PANEL',
            logicName: '面试详情列表布局面板',
            appDataEntityId: 'web.hr_interview',
            controlParam: {},
            modelId: '1701f039f459285c7cecbe068e94e7d5',
            modelType: 'PSSYSVIEWPANEL',
            name: 'masterlayoutpanel',
            id: 'web.hr_interview.usr0813095454',
          },
          textAppDEFieldId: 'name',
          appDataEntityId: 'web.hr_interview',
          name: '主数据',
          id: 'master',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'myinterview_detail_calendar_view_calendar',
      controlType: 'CALENDAR',
      logicName: '面试详情_日历部件',
      appDataEntityId: 'web.hr_interview',
      controlParam: {
        id: 'calendar',
      },
      modelId: 'e1974a38ed4016c123531d8624cab493',
      modelType: 'PSSYSCALENDAR',
      name: 'calendar',
      id: 'web.hr_interview.myinterview_detail_calendar_view_calendar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.hr_interview',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_INTERVIEW',
      },
      caption: '面试详情',
      codeName: 'myinterview_detail_calendar_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.hr_interview',
      controlParam: {},
      name: 'captionbar',
      id: 'myinterview_detail_calendar_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDARVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.hr_interview',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '面试详情',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '1b6a63be5ea1f53fd00a4519e5016c13',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_interviewmyinterview_detail_calendar_view',
  id: 'web.hr_interview_myinterview_detail_calendar_view',
};
