export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'INDEXVIEWTAB_POPUPMODAL',
  deviewCodeName: 'create_option_view',
  deviewId: '4d3bdbca59739d4036684f58b66b5658',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_INTERVIEW_SCHEDULE',
  },
  caption: '新建面试安排',
  codeName: 'hr_interview_schedule_create_option_view',
  appDataEntityId: 'web.hr_interview_schedule',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'OptionView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'web.hr_interview_schedule',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'web.hr_interview_schedule',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'web.hr_interview_schedule',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'web.hr_interview_schedule',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.hr_interview_schedule',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'web.hr_interview_schedule',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          createDVT: 'CURTIME',
                          dataType: 5,
                          enableCond: 3,
                          itemWidth: 330,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'start_date',
                          editor: {
                            dateTimeFormat: 'YYYY-MM-DD',
                            editorParams: {
                              TIMEFMT: 'YYYY-MM-DD',
                            },
                            editorType: 'DATEPICKEREX_NOTIME',
                            editorWidth: 200,
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'start_date',
                          },
                          valueFormat: 'YYYY-MM-DD',
                          allowEmpty: true,
                          caption: '面试日期',
                          codeName: 'start_date',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 8,
                            colMD: 8,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'start_date',
                        },
                        {
                          createDV: '1',
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'interview_type',
                          editor: {
                            singleSelect: true,
                            appCodeListId: 'web.hr__interview_type',
                            editorType: 'DROPDOWNLIST',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'interview_type',
                          },
                          allowEmpty: true,
                          needCodeListConfig: true,
                          caption: '面试类型',
                          codeName: 'interview_type',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 8,
                            colMD: 8,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'interview_type',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          appDEFieldId: 'interview_category',
                          editor: {
                            singleSelect: true,
                            appCodeListId: 'web.hr__interview_category',
                            editorType: 'DROPDOWNLIST',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'interview_category',
                          },
                          allowEmpty: true,
                          needCodeListConfig: true,
                          caption: '面试类型分类',
                          codeName: 'interview_category',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          defdgroupLogics: [
                            {
                              logicCat: 'PANELVISIBLE',
                              relatedDetailNames: ['interview_type'],
                              groupOP: 'AND',
                              defdlogics: [
                                {
                                  condOP: 'EQ',
                                  defdname: 'interview_type',
                                  value: '3',
                                  logicType: 'SINGLE',
                                },
                              ],
                              logicType: 'GROUP',
                            },
                          ],
                          layoutPos: {
                            colLG: 8,
                            colMD: 8,
                            layout: 'TABLE_24COL',
                          },
                          showCaption: true,
                          id: 'interview_category',
                        },
                      ],
                      codeName: 'grouppanel3',
                      detailStyle: 'DEFAULT',
                      detailType: 'GROUPPANEL',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      id: 'grouppanel3',
                    },
                    {
                      buildInActions: 7,
                      contentType: 'REPEATER',
                      fieldName: 'interviews',
                      layout: {
                        columnCount: 24,
                        layout: 'TABLE_24COL',
                      },
                      deformDetails: [
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          editor: {
                            singleSelect: true,
                            appCodeListId: 'web.hr__interview_stage',
                            editorType: 'DROPDOWNLIST',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'stage_id',
                          },
                          allowEmpty: true,
                          needCodeListConfig: true,
                          caption: '面试阶段',
                          codeName: 'stage_id',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 6,
                            colMD: 6,
                            layout: 'TABLE_24COL',
                          },
                          repeatContent: true,
                          showCaption: true,
                          id: 'stage_id',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          editor: {
                            singleSelect: true,
                            appCodeListId: 'web.hr__interview_start_time',
                            editorType: 'DROPDOWNLIST',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'start_time',
                          },
                          allowEmpty: true,
                          needCodeListConfig: true,
                          caption: '面试时间',
                          codeName: 'start_time',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 6,
                            colMD: 6,
                            layout: 'TABLE_24COL',
                          },
                          repeatContent: true,
                          showCaption: true,
                          id: 'start_time',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          editor: {
                            singleSelect: true,
                            appCodeListId: 'web.hr__interview_duration',
                            editorType: 'DROPDOWNLIST',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'duration',
                          },
                          allowEmpty: true,
                          needCodeListConfig: true,
                          caption: '面试时长',
                          codeName: 'duration',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 6,
                            colMD: 6,
                            layout: 'TABLE_24COL',
                          },
                          repeatContent: true,
                          showCaption: true,
                          id: 'duration',
                        },
                        {
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          editor: {
                            enablePickupView: true,
                            appDEACModeId: 'default',
                            appDEDataSetId: 'fetch_default',
                            appDataEntityId: 'web.hr_employee',
                            forceSelection: true,
                            showTrigger: true,
                            editorParams: {
                              PICKUPVIEW: 'TRUE',
                            },
                            editorType: 'ADDRESSPICKUP',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'interviewers',
                          },
                          allowEmpty: true,
                          caption: '面试官',
                          codeName: 'interviewers',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 6,
                            colMD: 6,
                            layout: 'TABLE_24COL',
                          },
                          repeatContent: true,
                          showCaption: true,
                          id: 'interviewers',
                        },
                        {
                          createDV: 'hr_applicant',
                          createDVT: 'APPDATA',
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          editor: {
                            editorType: 'HIDDEN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'applicant_ids',
                          },
                          updateDV: 'hr_applicant',
                          updateDVT: 'APPDATA',
                          allowEmpty: true,
                          hidden: true,
                          caption: 'applicant_ids',
                          codeName: 'applicant_ids',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 6,
                            colMD: 6,
                            layout: 'TABLE_24COL',
                          },
                          repeatContent: true,
                          id: 'applicant_ids',
                        },
                        {
                          createDV: 'owner_id',
                          createDVT: 'APPDATA',
                          dataType: 25,
                          enableCond: 3,
                          labelPos: 'LEFT',
                          labelWidth: 130,
                          noPrivDisplayMode: 1,
                          editor: {
                            editorType: 'HIDDEN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'owner_id',
                          },
                          updateDV: 'owner_id',
                          updateDVT: 'APPDATA',
                          allowEmpty: true,
                          hidden: true,
                          caption: 'owner_id',
                          codeName: 'owner_id',
                          detailStyle: 'DEFAULT',
                          detailType: 'FORMITEM',
                          layoutPos: {
                            colLG: 6,
                            colMD: 6,
                            layout: 'TABLE_24COL',
                          },
                          repeatContent: true,
                          id: 'owner_id',
                        },
                      ],
                      codeName: 'interviews',
                      detailStyle: 'DEFAULT',
                      detailType: 'MDCTRL',
                      layoutPos: {
                        colLG: 24,
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'interviews',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'address_id',
                      editor: {
                        enablePickupView: true,
                        singleSelect: true,
                        handlerType: 'PickupText',
                        appDEACModeId: 'default',
                        appDEDataSetId: 'fetch_default',
                        appDataEntityId: 'web.hr_work_location',
                        enableAC: true,
                        forceSelection: true,
                        showTrigger: true,
                        editorParams: {
                          AC: 'TRUE',
                          PICKUPVIEW: 'TRUE',
                        },
                        editorType: 'PICKER',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'address_id',
                      },
                      allowEmpty: true,
                      caption: '面试地点',
                      codeName: 'address_id',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'address_id',
                    },
                    {
                      createDV: '1',
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'resume_type',
                      editor: {
                        appCodeListId: 'web.hr__interview_resume_type',
                        editorType: 'RADIOBUTTONLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'resume_type',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      caption: '简历类型',
                      codeName: 'resume_type',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'resume_type',
                    },
                    {
                      createDV: '1',
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'is_send_email',
                      editor: {
                        appCodeListId: 'web.hr__interview_send_email',
                        editorType: 'CHECKBOXLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'is_send_email',
                      },
                      allowEmpty: true,
                      emptyCaption: true,
                      needCodeListConfig: true,
                      codeName: 'is_send_email',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'is_send_email',
                    },
                    {
                      createDV: '1',
                      dataType: 25,
                      enableCond: 3,
                      itemWidth: 230,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'email_template_id',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'web.hr__interview_email_template',
                        editorType: 'DROPDOWNLIST_100',
                        editorWidth: 100,
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'email_template_id',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      caption: '已选择模版',
                      codeName: 'email_template_id',
                      contentWidth: 250,
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                        width: 250,
                        widthMode: 'PX',
                      },
                      width: 250,
                      showCaption: true,
                      id: 'email_template_id',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      itemHeight: 350,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'email_content',
                      editor: {
                        editorHeight: 350,
                        editorType: 'HTMLEDITOR',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'email_content',
                      },
                      allowEmpty: true,
                      caption: '邮件内容',
                      codeName: 'email_content',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      defdgroupLogics: [
                        {
                          logicCat: 'PANELVISIBLE',
                          relatedDetailNames: ['is_send_email'],
                          groupOP: 'AND',
                          defdlogics: [
                            {
                              condOP: 'EQ',
                              defdname: 'is_send_email',
                              value: '1',
                              logicType: 'SINGLE',
                            },
                          ],
                          logicType: 'GROUP',
                        },
                      ],
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'email_content',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'attachment',
                      editor: {
                        editorParams: {
                          FILEEXTS: '',
                          MAXFILESIZE: '',
                          MINFILECNT: '',
                          MAXFILECNT: '',
                        },
                        editorType: 'FILEUPLOADER',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'attachment',
                      },
                      allowEmpty: true,
                      caption: '附件',
                      codeName: 'attachment',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'attachment',
                    },
                    {
                      createDV: '1',
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'is_send_sms',
                      editor: {
                        appCodeListId: 'web.hr__interview_send_sms',
                        editorType: 'CHECKBOXLIST',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'is_send_sms',
                      },
                      allowEmpty: true,
                      emptyCaption: true,
                      needCodeListConfig: true,
                      codeName: 'is_send_sms',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'is_send_sms',
                    },
                    {
                      createDV: '1',
                      dataType: 25,
                      enableCond: 3,
                      itemWidth: 230,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'sms_template_id',
                      editor: {
                        singleSelect: true,
                        appCodeListId: 'web.hr__interview_sms_template',
                        editorType: 'DROPDOWNLIST_100',
                        editorWidth: 100,
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'sms_template_id',
                      },
                      allowEmpty: true,
                      needCodeListConfig: true,
                      caption: '已选择模版',
                      codeName: 'sms_template_id',
                      contentWidth: 250,
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                        width: 250,
                        widthMode: 'PX',
                      },
                      width: 250,
                      showCaption: true,
                      id: 'sms_template_id',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      itemHeight: 200,
                      labelPos: 'LEFT',
                      labelWidth: 130,
                      noPrivDisplayMode: 1,
                      appDEFieldId: 'sms_content',
                      editor: {
                        maxLength: 280,
                        showMaxLength: true,
                        editorHeight: 200,
                        editorParams: {
                          maxlength: '280',
                          showlimit: 'true',
                          HEIGHT: '200',
                        },
                        editorType: 'TEXTAREA_10',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'sms_content',
                      },
                      allowEmpty: true,
                      caption: '短信内容',
                      codeName: 'sms_content',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      defdgroupLogics: [
                        {
                          logicCat: 'PANELVISIBLE',
                          relatedDetailNames: ['is_send_sms'],
                          groupOP: 'AND',
                          defdlogics: [
                            {
                              condOP: 'EQ',
                              defdname: 'is_send_sms',
                              value: '1',
                              logicType: 'SINGLE',
                            },
                          ],
                          logicType: 'GROUP',
                        },
                      ],
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'sms_content',
                    },
                  ],
                  codeName: 'grouppanel1',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 14,
                    colMD: 14,
                    layout: 'TABLE_24COL',
                  },
                  id: 'grouppanel1',
                },
                {
                  layout: {
                    columnCount: 24,
                    layout: 'TABLE_24COL',
                  },
                  deformDetails: [
                    {
                      maskMode: 0,
                      appViewId:
                        'web.hr_interview_schedule_interviewer_calendar_view',
                      parentDataJO: {
                        srfparentdename: 'HR_INTERVIEW_SCHEDULE',
                        SRFPARENTTYPE: 'CUSTOM',
                      },
                      codeName: 'druipart1',
                      detailStyle: 'DEFAULT',
                      detailType: 'DRUIPART',
                      layoutPos: {
                        colMD: 24,
                        layout: 'TABLE_24COL',
                      },
                      showCaption: true,
                      id: 'druipart1',
                    },
                  ],
                  codeName: 'grouppanel2',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colLG: 10,
                    colMD: 10,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'grouppanel2',
                },
              ],
              caption: '面试安排基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'create_option_view_form',
      controlType: 'FORM',
      logicName: '新建面试安排_表单',
      appDataEntityId: 'web.hr_interview_schedule',
      controlParam: {
        id: 'form',
      },
      modelId: '2205cc335f6f9b208242aba891f82a42',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'web.hr_interview_schedule.create_option_view_form',
    },
    {
      codeName: 'create_option_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'web.hr_interview_schedule',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'create_option_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_INTERVIEW_SCHEDULE',
      },
      caption: '新建面试安排',
      codeName: 'create_option_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.hr_interview_schedule',
      controlParam: {},
      name: 'captionbar',
      id: 'create_option_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEOPTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.hr_interview_schedule',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '新建面试安排',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '8ba0c155521d5ec1770c4cc30757807a',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_interview_schedulecreate_option_view',
  id: 'web.hr_interview_schedule_create_option_view',
};
