export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'calendar',
  loadDefault: true,
  deviewCodeName: 'interview_list_calendar_view',
  deviewId: '8a0c382a65daba0c91ebe07a14b603ae',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_INTERVIEW',
  },
  caption: '面试安排',
  codeName: 'hr_interview_interview_list_calendar_view',
  appDataEntityId: 'web.hr_interview',
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      calendarStyle: 'MONTH',
      groupMode: 'NONE',
      legendPos: 'NONE',
      sysCalendarItems: [
        {
          beginTimeAppDEFieldId: 'start_date',
          endTimeAppDEFieldId: 'start_date',
          idAppDEFieldId: 'id',
          itemStyle: 'DEFAULT',
          itemType: 'master',
          appDEDataSetId: 'fetch_default',
          layoutPanel: {
            layoutMode: 'FLEX',
            layout: {
              layout: 'FLEX',
            },
            rootPanelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'web.hr__interview_start_time',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'start_time',
                        },
                        viewFieldName: 'start_time',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingRight: 'OUTERSMALL',
                        },
                        id: 'start_time',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'owner_name',
                        },
                        viewFieldName: 'owner_name',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                          spacingRight: 'OUTERSMALL',
                        },
                        id: 'owner_name',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          appCodeListId: 'web.hr__interview_type',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'interview_type',
                        },
                        viewFieldName: 'interview_type',
                        allowEmpty: true,
                        convertToCodeItemText: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'interview_type',
                      },
                    ],
                    layout: {
                      dir: 'row',
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container',
                  },
                ],
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'page_container',
              },
            ],
            layoutPanel: true,
            codeName: 'usr0828447169',
            controlType: 'PANEL',
            logicName: '面试安排日历布局面板',
            appDataEntityId: 'web.hr_interview',
            controlParam: {},
            modelId: '7438a4db16626e7eb1b294c76988723b',
            modelType: 'PSSYSVIEWPANEL',
            name: 'masterlayoutpanel',
            id: 'web.hr_interview.usr0828447169',
          },
          textAppDEFieldId: 'name',
          appDataEntityId: 'web.hr_interview',
          name: '主数据',
          id: 'master',
        },
      ],
      navViewPos: 'NONE',
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'interview_list_calendar_view_calendar',
      controlType: 'CALENDAR',
      logicName: '面试安排_日历部件',
      appDataEntityId: 'web.hr_interview',
      controlParam: {
        id: 'calendar',
      },
      modelId: '72802623a9aadf2ab8422178494752cc',
      modelType: 'PSSYSCALENDAR',
      name: 'calendar',
      id: 'web.hr_interview.interview_list_calendar_view_calendar',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.hr_interview',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_INTERVIEW',
      },
      caption: '面试安排',
      codeName: 'interview_list_calendar_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.hr_interview',
      controlParam: {},
      name: 'captionbar',
      id: 'interview_list_calendar_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDECALENDARVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.hr_interview',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '面试安排',
  viewStyle: 'DEFAULT',
  viewType: 'DECALENDARVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '6ab26138650e3ff9fff5543bfe9028e3',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_interviewinterview_list_calendar_view',
  id: 'web.hr_interview_interview_list_calendar_view',
};
