export default {
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'work_bench_my_interview',
  deviewId: '3c1b618a5fe1ecf01b3051565a3cb60d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_INTERVIEW_FEEDBACK',
  },
  caption: '我的面试',
  codeName: 'hr_interview_feedback_work_bench_my_interview',
  appDataEntityId: 'web.hr_interview_feedback',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        caption: '搜索栏',
        itemStyle: 'DEFAULT',
        itemType: 'CTRLPOS',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'searchbar',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '数据视图',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'dataview',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_dataview',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'DataView',
        id: 'engine',
      },
      {
        engineCat: 'CTRL',
        engineType: 'CtrlLoadTrigger',
        params: [
          {
            ctrlName: 'searchbar',
            paramType: 'CTRL',
            name: 'CTRL',
            id: 'ctrl',
          },
          {
            ctrlName: 'dataview',
            paramType: 'CTRL',
            name: 'TRIGGER',
            id: 'trigger',
          },
        ],
        id: 'engine_searchbar_default',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.hr_interview_feedback_edit_view',
          },
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.hr_interview_feedback_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.hr_interview_feedback_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.hr_interview_feedback_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '面试反馈编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.HR_INTERVIEW_FEEDBACK.EDITVIEW',
        },
        refAppViewId: 'web.hr_interview_feedback_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '面试反馈编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.HR_INTERVIEW_FEEDBACK.EDITVIEW',
        },
        refAppViewId: 'web.hr_interview_feedback_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            buttonStyle: 'STYLE2',
            noPrivDisplayMode: 2,
            uiactionId: 'see_more@hr_interview_feedback',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '查看更多',
            itemType: 'DEUIACTION',
            sysCss: {
              cssName: 'swap_icon_text',
            },
            sysImage: {
              rawContent:
                '<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1732774437860" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="11278" width="12" height="12" xmlns:xlink="http://www.w3.org/1999/xlink"><path d="M767.369846 526.099692a47.261538 47.261538 0 0 0-13.705846-29.538461L328.940308 71.837538a47.419077 47.419077 0 1 0-67.032616 67.032616l391.640616 391.640615-391.640616 391.719385a47.419077 47.419077 0 1 0 66.953846 67.032615l424.802462-424.723692a47.261538 47.261538 0 0 0 13.705846-29.459692z" fill="#999999" p-id="11279"></path></svg>',
            },
            tooltip: '该功能暂未支持！',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'dataview',
        codeName: 'work_bench_my_interview_toolbar',
        controlType: 'TOOLBAR',
        logicName: '我的面试_工具栏',
        appDataEntityId: 'web.hr_interview_feedback',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '93e26a5cf9196d7177c14a6f6416940d',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'work_bench_my_interview_toolbar',
      },
      {
        cardWidth: 250,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'TABLE_24COL',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'candidate_display_name',
                      },
                      allowEmpty: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        spacingRight: 'OUTERSMALL',
                      },
                      id: 'candidate_display_name',
                    },
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        appCodeListId: 'web.hr__interview_stage',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'stage_id',
                      },
                      viewFieldName: 'stage_id',
                      allowEmpty: true,
                      convertToCodeItemText: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'stage_id',
                    },
                  ],
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container',
                },
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      editor: {
                        halign: 'LEFT',
                        renderMode: 'TEXT_DYNAMIC',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        predefinedType: 'FIELD_TEXT_DYNAMIC',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'job_name',
                      },
                      allowEmpty: true,
                      caption: '文本(动态)',
                      itemStyle: 'DEFAULT',
                      itemType: 'FIELD',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'job_name',
                    },
                  ],
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                    spacingBottom: 'OUTERMEDIUM',
                  },
                  id: 'container1',
                },
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          rawItem: {
                            sysImage: {
                              cssClass: 'fa fa-video-camera',
                              glyph: 'xf03d@FontAwesome',
                            },
                            contentType: 'IMAGE',
                            predefinedType: 'STATIC_IMAGE',
                            rawItemHeight: 14,
                            id: 'static_image',
                          },
                          caption: '图片',
                          contentHeight: 14,
                          height: 14,
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            height: 14,
                            heightMode: 'PX',
                            layout: 'FLEX',
                            spacingRight: 'OUTERSMALL',
                          },
                          sysImage: {
                            cssClass: 'fa fa-video-camera',
                            glyph: 'xf03d@FontAwesome',
                          },
                          showCaption: true,
                          id: 'static_image',
                        },
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            appCodeListId: 'web.hr__interview_type',
                            editorType: 'SPAN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'interview_type',
                          },
                          viewFieldName: 'interview_type',
                          allowEmpty: true,
                          convertToCodeItemText: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'interview_type',
                        },
                      ],
                      layout: {
                        dir: 'row',
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        spacingRight: 'OUTERMEDIUM',
                      },
                      id: 'container4',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          actionType: 'UIACTION',
                          buttonStyle: 'DEFAULT',
                          buttonType: 'PANELBUTTON',
                          uiactionId: 'open_edit@hr_interview_feedback',
                          renderMode: 'LINK',
                          tooltip: '查看面试',
                          uiactionTarget: 'SINGLEDATA',
                          caption: '查看面试',
                          itemStyle: 'DEFAULT',
                          itemType: 'BUTTON',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          sysCss: {
                            cssName: 'into_interview',
                          },
                          showCaption: true,
                          id: 'button_link',
                        },
                      ],
                      layout: {
                        layout: 'FLEX',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'container3',
                    },
                  ],
                  layout: {
                    align: 'space-between',
                    dir: 'row',
                    layout: 'FLEX',
                    valign: 'center',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container2',
                },
              ],
              layout: {
                dir: 'column',
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'page_container',
            },
          ],
          codeName: 'usr0901336320',
          controlType: 'PANEL',
          logicName: '我的面试_卡片视图_卡片面板',
          appDataEntityId: 'web.hr_interview_feedback',
          controlParam: {},
          modelId: 'a7c74c70b975aa7b3a84024737cfe814',
          modelType: 'PSSYSVIEWPANEL',
          name: 'itemlayoutpanel',
          id: 'web.hr_interview_feedback.usr0901336320',
        },
        dedataViewDataItems: [
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
          {
            appDEFieldId: 'interview_id',
            dataType: 25,
            id: 'interview_id',
          },
          {
            appDEFieldId: 'interviewer_id',
            dataType: 25,
            id: 'interviewer_id',
          },
          {
            appDEFieldId: 'interview_user_id',
            dataType: 25,
            id: 'interview_user_id',
          },
          {
            appDEFieldId: 'applicant_id',
            dataType: 25,
            id: 'applicant_id',
          },
        ],
        pagingSize: 1000,
        appendDEItems: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.hr_interview_feedback',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_interview_myself',
          appDataEntityId: 'web.hr_interview_feedback',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.hr_interview_feedback',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.hr_interview_feedback',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.hr_interview_feedback',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'manager_my_interview_data_view',
        controlType: 'DATAVIEW',
        logicName: '我的面试_卡片视图',
        appDataEntityId: 'web.hr_interview_feedback',
        controlParam: {
          id: 'dataview',
        },
        modelId: '464b4dc97083d1f2c43b9075b4b5e6dd',
        modelType: 'PSDEDATAVIEW',
        name: 'dataview',
        id: 'web.hr_interview_feedback.manager_my_interview_data_view',
      },
      {
        groupMode: 'SINGLE',
        appCounterRefId: '94645f5a7e0b966288d431f9d50562bb',
        searchBarGroups: [
          {
            caption: '今天',
            counterId: 'current',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"daycalc","condop":"EQ","value":"0"}]}]}}',
            itemType: 'GROUP',
            id: 'current',
          },
          {
            caption: '明天及以后',
            counterId: 'after',
            data: '{"theme_model":{"searchconds":[{"condtype":"GROUP","condop":"AND","bnotmode":false,"searchconds":[{"condtype":"DEFIELD","fieldname":"daycalc","condop":"GT","value":"0"}]}]}}',
            itemType: 'GROUP',
            id: 'after',
          },
        ],
        enableGroup: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'workspace_my_interview_count',
              counterType: 'DEDR',
              getAppDEActionId: 'get_my_interview_count',
              appDataEntityId: 'web.hr_candidate',
              timer: 60000,
              uniqueTag: 'workspace_my_interview_count',
              name: '用人经理-工作台-我的面试计数器',
              id: 'web.workspace_my_interview_count',
            },
            tag: '94645f5a7e0b966288d431f9d50562bb',
            uniqueTag: 'workspace_my_interview_count',
            id: '94645f5a7e0b966288d431f9d50562bb',
          },
        ],
        codeName: 'work_bench_my_interview',
        controlType: 'SEARCHBAR',
        height: 40,
        logicName: '用人经理工作台-我的面试',
        appDataEntityId: 'web.hr_interview_feedback',
        controlParam: {
          id: 'searchbar',
        },
        sysCss: {
          cssName: 'applicant_baseinfo_count',
        },
        modelId: '3c1b618a5fe1ecf01b3051565a3cb60d',
        modelType: 'PSSYSSEARCHBAR',
        name: 'searchbar',
        id: 'web.hr_interview_feedback.work_bench_my_interview',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.HR_INTERVIEW_FEEDBACK',
        },
        caption: '我的面试',
        codeName: 'work_bench_my_interview_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.hr_interview_feedback',
        controlParam: {},
        name: 'captionbar',
        id: 'work_bench_my_interview_captionbar',
      },
    ],
    codeName: 'usr0901802667',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'work_bench_my_interview卡片视图布局面',
    appDataEntityId: 'web.hr_interview_feedback',
    controlParam: {},
    modelId: 'd4bf006d7abb4b15e899eae741fde416',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0901802667',
  },
  title: '我的面试',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'aa3d455b1935c7528039b0adc72b4f4d',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_interview_feedbackwork_bench_my_interview',
  id: 'web.hr_interview_feedback_work_bench_my_interview',
};
