export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: 'c77983d115f48382adbebb87ecd43da0',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_JOB',
  },
  caption: '招聘职位',
  codeName: 'hr_job_pickup_view',
  appDataEntityId: 'web.hr_job',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'web.hr_job_pickup_grid_view',
      codeName: 'pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'web.hr_job',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickup_view_pickupviewpanel',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_JOB',
      },
      caption: '招聘职位',
      codeName: 'pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.hr_job',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.hr_job',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作岗位数据选择视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.HR_JOB.PICKUPVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'dbbed64fb0599d9ea233619e2e75bbc1',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_jobPickupView',
  id: 'web.hr_job_pickup_view',
};
