export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'card_data_view',
  deviewId: '76e74326732fc1f87adc77b0da6a3511',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_JOB_PLATFORM',
  },
  caption: '招聘平台',
  codeName: 'hr_job_platform_card_data_view',
  appDataEntityId: 'web.hr_job_platform',
  appViewNavParams: [
    {
      key: 'hr_job_id',
      value: 'hr_job',
      id: 'hr_job_id',
    },
  ],
  sysCss: {
    cssName: 'channel_style',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '数据视图',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'dataview',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_dataview',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'DataView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.hr_job_platform_edit_view',
          },
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.hr_job_platform_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            openMode: 'POPUPMODAL',
            refAppViewId: 'web.hr_job_platform_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              openMode: 'POPUPMODAL',
              refAppViewId: 'web.hr_job_platform_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '招聘平台编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.HR_JOB_PLATFORM.EDITVIEW',
        },
        refAppViewId: 'web.hr_job_platform_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realOpenMode: 'POPUPMODAL',
        realTitle: '招聘平台编辑视图',
        realTitleLanguageRes: {
          lanResTag: 'PAGE.TITLE.HR_JOB_PLATFORM.EDITVIEW',
        },
        refAppViewId: 'web.hr_job_platform_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        xdataControlName: 'dataview',
        codeName: 'card_data_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '招聘网站管理_工具栏',
        appDataEntityId: 'web.hr_job_platform',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'ea35fa9d4843e409e6799e69f8b32127',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'card_data_view_toolbar',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'card_data_view_search_form',
        controlType: 'SEARCHFORM',
        logicName: '招聘网站管理_搜索表单',
        appDataEntityId: 'web.hr_job_platform',
        controlParam: {
          id: 'searchform',
        },
        modelId: '1d6f302f51637a4424a54630e9032052',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'web.hr_job_platform.card_data_view_search_form',
      },
      {
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        itemLayoutPanel: {
          layoutMode: 'TABLE_24COL',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          rootPanelItems: [
            {
              actionGroupExtractMode: 'ITEM',
              panelItems: [
                {
                  actionGroupExtractMode: 'ITEM',
                  panelItems: [
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            appCodeListId: 'web.hr__hr_platform_publish_status',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'publish_status',
                          },
                          viewFieldName: 'publish_status',
                          allowEmpty: true,
                          convertToCodeItemText: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'publish_status',
                        },
                      ],
                      layout: {
                        align: 'flex-end',
                        dir: 'row-reverse',
                        layout: 'FLEX',
                        valign: 'center',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      sysCss: {
                        cssName: 'platform_acc',
                      },
                      id: 'container3',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          editor: {
                            editorType: 'HIDDEN',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'name',
                          },
                          viewFieldName: 'name',
                          allowEmpty: true,
                          hidden: true,
                          caption: '文本(动态)',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          id: 'name',
                        },
                        {
                          fieldStates: 1,
                          editor: {
                            maxFileCount: 1,
                            editorHeight: 133,
                            editorParams: {
                              readonly: 'true',
                              autoPreview: 'false',
                              MAXCOUNT: '1',
                              STOPPROPAGATION: 'false',
                              READONLY: 'TRUE',
                            },
                            editorType: 'PICTURE_ONE',
                            editorWidth: 133,
                            predefinedType: 'FIELD_IMAGE',
                            valueType: 'SIMPLE',
                            editable: true,
                            readOnly: true,
                            id: 'image',
                          },
                          viewFieldName: 'image',
                          allowEmpty: true,
                          caption: '图片(动态)',
                          contentHeight: 133,
                          contentWidth: 133,
                          height: 133,
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            height: 133,
                            heightMode: 'PX',
                            layout: 'FLEX',
                            width: 133,
                            widthMode: 'PX',
                          },
                          width: 133,
                          id: 'image',
                        },
                      ],
                      layout: {
                        align: 'center',
                        dir: 'row-reverse',
                        layout: 'FLEX',
                        valign: 'center',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'container',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          rawItem: {
                            caption: '已授权',
                            halign: 'LEFT',
                            renderMode: 'TEXT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            contentType: 'RAW',
                            predefinedType: 'STATIC_TEXT',
                            id: 'static_text1',
                          },
                          caption: '文本',
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          showCaption: true,
                          id: 'static_text1',
                        },
                        {
                          editor: {
                            halign: 'LEFT',
                            renderMode: 'TEXT_DYNAMIC',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            editorType: 'SPAN',
                            predefinedType: 'FIELD_TEXT_DYNAMIC',
                            valueType: 'SIMPLE',
                            editable: true,
                            id: 'platform_account_count',
                          },
                          viewFieldName: 'platform_account_count',
                          allowEmpty: true,
                          caption: '文本(动态)',
                          itemStyle: 'DEFAULT',
                          itemType: 'FIELD',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                            spacingLeft: 'OUTERSMALL',
                            spacingRight: 'OUTERSMALL',
                          },
                          id: 'platform_account_count',
                        },
                        {
                          rawItem: {
                            caption: '账号',
                            halign: 'LEFT',
                            renderMode: 'TEXT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            contentType: 'RAW',
                            predefinedType: 'STATIC_TEXT',
                            id: 'static_text',
                          },
                          caption: '文本',
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          showCaption: true,
                          id: 'static_text',
                        },
                      ],
                      layout: {
                        align: 'flex-start',
                        dir: 'row',
                        layout: 'FLEX',
                        valign: 'center',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      panelItemGroupLogics: [
                        {
                          logicCat: 'PANELVISIBLE',
                          relatedItemNames: ['platform_account_count'],
                          groupOP: 'AND',
                          panelItemLogics: [
                            {
                              condOp: 'GT',
                              dstModelField: 'platform_account_count',
                              value: '0',
                              logicType: 'SINGLE',
                              id: '逻辑项',
                            },
                          ],
                          logicType: 'GROUP',
                        },
                      ],
                      sysCss: {
                        cssName: 'platform_acc',
                      },
                      id: 'container2',
                    },
                    {
                      actionGroupExtractMode: 'ITEM',
                      panelItems: [
                        {
                          rawItem: {
                            caption: '无授权账号',
                            halign: 'LEFT',
                            renderMode: 'TEXT',
                            valign: 'MIDDLE',
                            wrapMode: 'NOWRAP',
                            contentType: 'RAW',
                            predefinedType: 'STATIC_TEXT',
                            id: 'static_text2',
                          },
                          caption: '文本',
                          itemStyle: 'DEFAULT',
                          itemType: 'RAWITEM',
                          layoutPos: {
                            shrink: 1,
                            layout: 'FLEX',
                          },
                          panelItemGroupLogics: [
                            {
                              logicCat: 'PANELVISIBLE',
                              relatedItemNames: ['platform_account_count'],
                              groupOP: 'AND',
                              panelItemLogics: [
                                {
                                  condOp: 'EQ',
                                  dstModelField: 'platform_account_count',
                                  value: '0',
                                  logicType: 'SINGLE',
                                  id: '逻辑项',
                                },
                              ],
                              logicType: 'GROUP',
                            },
                          ],
                          showCaption: true,
                          id: 'static_text2',
                        },
                      ],
                      layout: {
                        align: 'flex-start',
                        dir: 'row',
                        layout: 'FLEX',
                        valign: 'center',
                      },
                      dataRegionType: 'INHERIT',
                      caption: '容器',
                      itemStyle: 'DEFAULT',
                      itemType: 'CONTAINER',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      panelItemGroupLogics: [
                        {
                          logicCat: 'PANELVISIBLE',
                          relatedItemNames: ['platform_account_count'],
                          groupOP: 'AND',
                          panelItemLogics: [
                            {
                              condOp: 'EQ',
                              dstModelField: 'platform_account_count',
                              value: '0',
                              logicType: 'SINGLE',
                              id: '逻辑项',
                            },
                          ],
                          logicType: 'GROUP',
                        },
                      ],
                      sysCss: {
                        cssName: 'platform_acc',
                      },
                      id: 'container4',
                    },
                  ],
                  layout: {
                    align: 'center',
                    dir: 'column',
                    layout: 'FLEX',
                    valign: 'center',
                  },
                  dataRegionType: 'INHERIT',
                  caption: '容器',
                  itemStyle: 'DEFAULT',
                  itemType: 'CONTAINER',
                  layoutPos: {
                    shrink: 1,
                    layout: 'FLEX',
                  },
                  id: 'container1',
                },
              ],
              layout: {
                dir: 'column',
                layout: 'FLEX',
              },
              dataRegionType: 'INHERIT',
              itemStyle: 'DEFAULT',
              itemType: 'CONTAINER',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'page_container',
            },
          ],
          codeName: 'usr0808709833',
          controlType: 'PANEL',
          logicName: '招聘网站管理_卡片视图_卡片面板',
          appDataEntityId: 'web.hr_job_platform',
          controlLogics: [
            {
              eventNames: 'onClick',
              itemName: 'page_container',
              logicTag: 'itemlayoutpanel',
              logicType: 'APPDEUIACTION',
              appDEUIActionId: 'open_accout_list@hr_job_platform',
              triggerType: 'CTRLEVENT',
              id: 'logic',
            },
          ],
          controlParam: {},
          modelId: 'a8838c3c82fa3fcd0c95150694a76874',
          modelType: 'PSSYSVIEWPANEL',
          name: 'itemlayoutpanel',
          id: 'web.hr_job_platform.usr0808709833',
        },
        dedataViewDataItems: [
          {
            appDEFieldId: 'id',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'name',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        pagingSize: 1000,
        appendDEItems: true,
        singleSelect: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'web.hr_job_platform',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_job_platform',
          appDataEntityId: 'web.hr_job_platform',
          id: 'fetch',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'web.hr_job_platform',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'web.hr_job_platform',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'web.hr_job_platform',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'card_data_view_data_view',
        controlType: 'DATAVIEW',
        logicName: '招聘网站管理_卡片视图',
        appDataEntityId: 'web.hr_job_platform',
        controlParam: {
          id: 'dataview',
        },
        modelId: 'a8685d5272bf145f137ddd0fb6d19e40',
        modelType: 'PSDEDATAVIEW',
        name: 'dataview',
        id: 'web.hr_job_platform.card_data_view_data_view',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'web.hr_job_platform',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.HR_JOB_PLATFORM',
        },
        caption: '招聘平台',
        codeName: 'card_data_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.hr_job_platform',
        controlParam: {},
        name: 'captionbar',
        id: 'card_data_view_captionbar',
      },
    ],
    codeName: 'usr0910655554',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'card_data_view卡片视图布局面',
    appDataEntityId: 'web.hr_job_platform',
    controlParam: {},
    modelId: '1433c261047c27dc35de017a081adf48',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0910655554',
  },
  title: '招聘网站管理',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '1633b8f8f6eab734b6e37555b0802c56',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_job_platformcard_data_view',
  id: 'web.hr_job_platform_card_data_view',
};
