export default {
  appSwitchMode: 1,
  mainMenuAlign: 'TOP',
  enableAppSwitch: true,
  caption: '招聘',
  codeName: 'odoo_index',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          predefinedType: 'NAV_BREADCRUMB',
                          id: 'nav_breadcrumb',
                        },
                        caption: '面包屑导航',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'nav_breadcrumb',
                      },
                      {
                        rawItem: {
                          predefinedType: 'NAV_POS_INDEX',
                          id: 'nav_pos_index',
                        },
                        caption: '导航区占位',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          grow: 1,
                          shrink: 1,
                          heightMode: 'FULL',
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'nav_pos_index',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 100,
                    height: 100,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      height: 100,
                      heightMode: 'FULL',
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container4_all',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                },
                id: 'container6_all',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentWidth: 100,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
              width: 100,
              widthMode: 'PERCENTAGE',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              contentType: 'USER',
                              rawItemParams: [
                                {
                                  key: 'sourcetype',
                                  value: 'UTIL',
                                },
                              ],
                              predefinedType: 'APP_SWITCH',
                              id: 'app_switch',
                            },
                            caption: '应用切换器',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingLeft: 'OUTERMEDIUM',
                            },
                            showCaption: true,
                            id: 'app_switch',
                          },
                          {
                            caption: '首页菜单',
                            contentHeight: 60,
                            contentWidth: 1200,
                            height: 60,
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              grow: 1,
                              shrink: 1,
                              height: 60,
                              heightMode: 'PX',
                              layout: 'FLEX',
                              width: 1200,
                              widthMode: 'PX',
                            },
                            width: 1200,
                            showCaption: true,
                            id: 'appmenu',
                          },
                        ],
                        layout: {
                          align: 'flex-start',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        id: 'container2',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              caption: '文本内容',
                              halign: 'LEFT',
                              renderMode: 'TEXT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              predefinedType: 'INDEX_VIEW_SEARCH',
                              id: 'index_view_search',
                            },
                            caption: '搜索栏',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'index_view_search',
                          },
                        ],
                        layout: {
                          align: 'center',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentHeight: 52,
                        height: 52,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          height: 52,
                          heightMode: 'PX',
                          layout: 'FLEX',
                        },
                        id: 'container',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                rawItem: {
                                  contentType: 'IMAGE',
                                  predefinedType: 'USERMESSAGE',
                                  id: 'usermessage',
                                },
                                caption: '消息通知',
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  shrink: 1,
                                  heightMode: 'FULL',
                                  layout: 'FLEX',
                                  widthMode: 'FULL',
                                },
                                showCaption: true,
                                id: 'usermessage',
                              },
                            ],
                            layout: {
                              layout: 'FLEX',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            contentHeight: 48,
                            contentWidth: 48,
                            height: 48,
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              height: 48,
                              heightMode: 'PX',
                              layout: 'FLEX',
                              width: 48,
                              widthMode: 'PX',
                            },
                            width: 48,
                            id: 'container1',
                          },
                          {
                            rawItem: {
                              rawItemParams: [
                                {
                                  key: 'AVATAR',
                                  value: 'avatar',
                                },
                                {
                                  key: 'TITLE',
                                  value: 'srfusername',
                                },
                                {
                                  key: 'SUBTITLE',
                                  value: 'loginname',
                                },
                                {
                                  key: 'NAVVIEWNAME',
                                  value: 'res_users_info_custom_view',
                                },
                              ],
                              predefinedType: 'AUTH_USERINFO',
                              rawItemHeight: 60,
                              id: 'auth_userinfo',
                            },
                            caption: '用户信息',
                            contentHeight: 60,
                            height: 60,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 0,
                              height: 60,
                              heightMode: 'PX',
                              layout: 'FLEX',
                            },
                            sysPFPluginId: 'custom_auth_userinfo',
                            showCaption: true,
                            id: 'auth_userinfo',
                          },
                        ],
                        predefinedType: 'INDEX_ACTIONS',
                        layout: {
                          align: 'space-between',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        id: 'indexactions',
                      },
                    ],
                    layout: {
                      align: 'space-between',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container7',
                  },
                ],
                predefinedType: 'AppHeader',
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                  widthMode: 'FULL',
                },
                id: 'app_header',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_HEADER',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentHeight: 60,
            height: 60,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'NORTH',
              height: 60,
              heightMode: 'PX',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_header',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll1',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        layoutMode: 'TABLE_24COL',
        appMenuItems: [
          {
            accUserMode: 2,
            itemType: 'MENUITEM',
            appFuncId: 'usrappfunc0827955364',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            openDefault: true,
            valid: true,
            caption: '招聘总览',
            tooltip: '招聘总览',
            id: 'menuitem9',
          },
          {
            accUserMode: 2,
            itemType: 'MENUITEM',
            appFuncId: 'appfunc3',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '候选人管理',
            tooltip: '候选人管理',
            id: 'menuitem1',
          },
          {
            accUserMode: 2,
            itemType: 'MENUITEM',
            appFuncId: 'usrappfunc0826476593',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '面试安排',
            tooltip: '面试安排',
            id: 'menuitem3',
          },
          {
            accUserMode: 2,
            itemType: 'MENUITEM',
            appFuncId: 'usrappfunc0806841809',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '职位管理',
            tooltip: '职位管理',
            id: 'menuitem2',
          },
          {
            accUserMode: 2,
            itemType: 'MENUITEM',
            appFuncId: 'usrappfunc0821386148',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '人才库',
            tooltip: '人才库',
            id: 'menuitem11',
          },
          {
            itemType: 'MENUITEM',
            appMenuItems: [
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0912315937',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '我的工作',
                tooltip: '我的工作',
                id: 'menuitem6',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0813630705',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '简历筛选',
                tooltip: '简历筛选',
                id: 'menuitem7',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0829399946',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '我的面试',
                tooltip: '我的面试',
                id: 'menuitem8',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'appfunc',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '考试/评测',
                tooltip: '考试/评测',
                id: 'menuitem13',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0822244697',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: 'Offer审批',
                tooltip: 'Offer审批',
                id: 'menuitem14',
              },
              {
                itemType: 'MENUITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                hidden: true,
                valid: true,
                caption: '招聘进展',
                tooltip: '招聘进展',
                id: 'menuitem15',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '我的招聘',
            tooltip: '我的招聘',
            expanded: true,
            id: 'menuitem5',
          },
          {
            accUserMode: 2,
            itemType: 'MENUITEM',
            appFuncId: 'usrappfunc0815029160',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '招聘设置',
            tooltip: '招聘设置',
            id: 'menuitem10',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'usr1010174380_menu',
        controlType: 'APPMENU',
        logicName: '应用首页视图菜单',
        controlParam: {},
        modelId: '0b944c5efd5724ed46af57bfb27988cd',
        modelType: 'PSAPPMENU',
        name: 'appmenu',
        id: 'usr1010174380_menu',
      },
      {
        caption: '招聘',
        subCaption: '招聘',
        codeName: 'captionbar',
        controlType: 'CAPTIONBAR',
        controlParam: {},
        id: 'captionbar',
      },
    ],
    codeName: 'usr1010589568',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'odoo_index',
    controlParam: {},
    modelId: '7ed85e0e1c62f8a446e55709699a1fb8',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr1010589568',
  },
  subCaption: '招聘',
  title: '招聘',
  viewStyle: 'DEFAULT',
  viewType: 'APPINDEXVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '4ab423aef0f76902df89614ed349334e',
  modelType: 'PSAPPINDEXVIEW',
  name: 'odoo_index',
  id: 'web.odoo_index',
};
