export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'InstalledGridView',
  deviewId: '2a079c78777cc3a3988b6e902881e0ba',
  accUserMode: 2,
  caption: '核心产品功能',
  codeName: 'ps_core_prd_func_installed_grid_view',
  appDataEntityId: 'web.pscoreprdfunc',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'web.ps_core_prd_func_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'web.ps_core_prd_func_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'web.ps_core_prd_func_redirect_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'web.ps_core_prd_func_redirect_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewNavParams: [
    {
      rawValue: true,
      key: 'n_funcstate_eq',
      value: '1',
      id: 'n_funcstate_eq',
    },
    {
      key: 'n_pscoreprdid_eq',
      value: 'srfsystemid',
      id: 'n_pscoreprdid_eq',
    },
  ],
  appViewRefs: [
    {
      realTitle: '核心产品功能数据重定向视图',
      refAppViewId: 'web.ps_core_prd_func_redirect_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '核心产品功能编辑视图',
      refAppViewId: 'web.ps_core_prd_func_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      xdataControlName: 'grid',
      codeName: 'installed_grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '已安装应用_工具栏',
      appDataEntityId: 'web.pscoreprdfunc',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '1e47fa41e0c848cb8e635cae667d2f2d',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'installed_grid_view_toolbar',
    },
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'ordervalue',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'pscoreprdfuncname',
          excelCaption: '应用名称',
          appDEFieldId: 'pscoreprdfuncname',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '应用名称',
          codeName: 'pscoreprdfuncname',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'pscoreprdfuncname',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'updateman',
          excelCaption: '更新人',
          appCodeListId: 'web.sysoperator',
          appDEFieldId: 'updateman',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '更新人',
          codeName: 'updateman',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'updateman',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'updatedate',
          excelCaption: '更新时间',
          appDEFieldId: 'updatedate',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '更新时间',
          codeName: 'updatedate',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 150,
          widthUnit: 'PX',
          enableSort: true,
          id: 'updatedate',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'pscoreprdfuncname',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'pscoreprdfuncname',
        },
        {
          appDEFieldId: 'updateman',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'updateman',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'updatedate',
          valueType: 'SIMPLE',
          dataType: 5,
          id: 'updatedate',
        },
        {
          appDEFieldId: 'pscoreprdfuncid',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'pscoreprdfuncid',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'pscoreprdfuncname',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmstag',
        },
      ],
      degridEditItems: [
        {
          caption: '核心产品功能标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'pscoreprdfuncid',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetchdefault',
        appDataEntityId: 'web.pscoreprdfunc',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'web.pscoreprdfunc',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'installed_grid_view_grid',
      controlType: 'GRID',
      logicName: '已安装应用_表格',
      appDataEntityId: 'web.pscoreprdfunc',
      controlParam: {
        id: 'grid',
      },
      modelId: '8a86471f6ee774b676b481a3a1b43eef',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'web.pscoreprdfunc.installed_grid_view_grid',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'installed_grid_view_search_form',
      controlType: 'SEARCHFORM',
      logicName: '已安装应用_搜索表单',
      appDataEntityId: 'web.pscoreprdfunc',
      controlParam: {
        id: 'searchform',
      },
      modelId: '7190ec0d1cfaf086ad1f556c0146f542',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'web.pscoreprdfunc.installed_grid_view_search_form',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.pscoreprdfunc',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '核心产品功能',
      codeName: 'installed_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.pscoreprdfunc',
      controlParam: {},
      name: 'captionbar',
      id: 'installed_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.pscoreprdfunc',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '已安装应用',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '60bd8e7d25724e027b29419875bb6916',
  modelType: 'PSAPPDEVIEW',
  name: 'PSCorePrdFuncInstalledGridView',
  id: 'web.ps_core_prd_func_installed_grid_view',
};
