export default {
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'tree_exp_view',
  deviewId: '797b5c2573846950a6ec95cb64c8d32d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.SYSTEM_SETTING',
  },
  caption: '设置',
  codeName: 'system_setting_tree_exp_view',
  appDataEntityId: 'web.system_setting',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'TreeExpView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        editMode: true,
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  controls: [
    {
      xdataControlName: 'treeexpbar_tree',
      enableCounter: true,
      showTitleBar: true,
      autoLoad: true,
      showBusyIndicator: true,
      appViewRefs: [
        {
          realTitle: '招聘平台列表视图',
          refAppViewId: 'web.hr_job_platform_platform_list_view',
          name: 'EXPITEM:node_11',
          id: 'expitem:node_11',
        },
        {
          realTitle: '招聘平台账号基础表格信息',
          refAppViewId: 'web.hr_job_platform_account_platform_account_info',
          name: 'EXPITEM:node_12',
          id: 'expitem:node_12',
        },
        {
          realTitle: '招聘流程设置',
          refAppViewId: 'web.hr_recruitment_progress_grid_view',
          name: 'EXPITEM:node_15',
          id: 'expitem:node_15',
        },
        {
          realTitle: '招聘阶段设置',
          refAppViewId: 'web.hr_recruitment_stage_grid_view',
          name: 'EXPITEM:node_16',
          id: 'expitem:node_16',
        },
      ],
      controls: [
        {
          detreeNodeRSs: [
            {
              childDETreeNodeId: 'node',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 基本信息',
            },
            {
              childDETreeNodeId: 'node_14',
              parentDETreeNodeId: 'node_13',
              parentValueLevel: 1,
              searchMode: 3,
              id: '招聘提速 - 招聘流程管理',
            },
            {
              childDETreeNodeId: 'node_16',
              parentDETreeNodeId: 'node_14',
              parentValueLevel: 1,
              searchMode: 3,
              id: '招聘流程管理 - 招聘阶段设置',
            },
            {
              childDETreeNodeId: 'node_11',
              parentDETreeNodeId: 'node_3',
              parentValueLevel: 1,
              searchMode: 3,
              id: '渠道管理 - 渠道信息',
            },
            {
              childDETreeNodeId: 'node_3',
              parentDETreeNodeId: 'node_1',
              parentValueLevel: 1,
              searchMode: 3,
              id: '渠道 - 渠道管理',
            },
            {
              childDETreeNodeId: 'node_6',
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              id: '招聘过程管理 - 候选人信息管理',
            },
            {
              childDETreeNodeId: 'node_4',
              parentDETreeNodeId: 'node_1',
              parentValueLevel: 1,
              searchMode: 3,
              id: '渠道 - 猎头设置',
            },
            {
              childDETreeNodeId: 'node_7',
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              id: '招聘过程管理 - 职位信息管理',
            },
            {
              childDETreeNodeId: 'node_5',
              parentDETreeNodeId: 'node_1',
              parentValueLevel: 1,
              searchMode: 3,
              id: '渠道 - 内推设置',
            },
            {
              childDETreeNodeId: 'node_8',
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              id: '招聘过程管理 - 招聘需求管理',
            },
            {
              childDETreeNodeId: 'node_1',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 渠道',
            },
            {
              childDETreeNodeId: 'node_9',
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              id: '招聘过程管理 - 面试管理',
            },
            {
              childDETreeNodeId: 'node_15',
              parentDETreeNodeId: 'node_14',
              parentValueLevel: 1,
              searchMode: 3,
              id: '招聘流程管理 - 招聘流程设置',
            },
            {
              childDETreeNodeId: 'node_10',
              parentDETreeNodeId: 'node_2',
              parentValueLevel: 1,
              searchMode: 3,
              name: '招聘过程管理 - Offer管理',
              id: '招聘过程管理 - offer管理',
            },
            {
              childDETreeNodeId: 'node_12',
              parentDETreeNodeId: 'node_3',
              parentValueLevel: 1,
              searchMode: 3,
              id: '渠道管理 - 渠道账号',
            },
            {
              childDETreeNodeId: 'node_2',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 招聘过程管理',
            },
            {
              childDETreeNodeId: 'node_13',
              parentDETreeNodeId: 'root',
              parentValueLevel: 1,
              searchMode: 3,
              id: '默认根节点 - 招聘提速',
            },
          ],
          detreeNodes: [
            {
              nodeValue: 'root',
              text: '默认根节点',
              nodeType: 'ROOT',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              rootNode: true,
              name: '默认根节点',
              id: 'root',
            },
            {
              text: '系统设置',
              nodeType: 'node',
              treeNodeType: 'STATIC',
              name: '系统设置',
              id: 'node',
            },
            {
              text: '渠道',
              nodeType: 'node_1',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '渠道',
              id: 'node_1',
            },
            {
              text: 'Offer管理',
              nodeType: 'node_10',
              treeNodeType: 'STATIC',
              name: 'Offer管理',
              id: 'node_10',
            },
            {
              text: '渠道信息',
              navAppViewId: 'web.hr_job_platform_platform_list_view',
              nodeType: 'node_11',
              treeNodeType: 'STATIC',
              name: '渠道信息',
              id: 'node_11',
            },
            {
              text: '渠道账号',
              navAppViewId: 'web.hr_job_platform_account_platform_account_info',
              nodeType: 'node_12',
              treeNodeType: 'STATIC',
              name: '渠道账号',
              id: 'node_12',
            },
            {
              text: '招聘提速',
              nodeType: 'node_13',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '招聘提速',
              id: 'node_13',
            },
            {
              text: '招聘流程管理',
              nodeType: 'node_14',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '招聘流程管理',
              id: 'node_14',
            },
            {
              text: '招聘流程设置',
              navAppViewId: 'web.hr_recruitment_progress_grid_view',
              nodeType: 'node_15',
              treeNodeType: 'STATIC',
              name: '招聘流程设置',
              id: 'node_15',
            },
            {
              text: '招聘阶段设置',
              navAppViewId: 'web.hr_recruitment_stage_grid_view',
              nodeType: 'node_16',
              treeNodeType: 'STATIC',
              name: '招聘阶段设置',
              id: 'node_16',
            },
            {
              text: '招聘过程管理',
              nodeType: 'node_2',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '招聘过程管理',
              id: 'node_2',
            },
            {
              text: '渠道管理',
              nodeType: 'node_3',
              treeNodeType: 'STATIC',
              hasDETreeNodeRSs: true,
              expanded: true,
              name: '渠道管理',
              id: 'node_3',
            },
            {
              text: '猎头设置',
              nodeType: 'node_4',
              treeNodeType: 'STATIC',
              name: '猎头设置',
              id: 'node_4',
            },
            {
              text: '内推设置',
              nodeType: 'node_5',
              treeNodeType: 'STATIC',
              name: '内推设置',
              id: 'node_5',
            },
            {
              text: '候选人信息管理',
              nodeType: 'node_6',
              treeNodeType: 'STATIC',
              name: '候选人信息管理',
              id: 'node_6',
            },
            {
              text: '职位信息管理',
              nodeType: 'node_7',
              treeNodeType: 'STATIC',
              name: '职位信息管理',
              id: 'node_7',
            },
            {
              text: '招聘需求管理',
              nodeType: 'node_8',
              treeNodeType: 'STATIC',
              name: '招聘需求管理',
              id: 'node_8',
            },
            {
              text: '面试管理',
              nodeType: 'node_9',
              treeNodeType: 'STATIC',
              name: '面试管理',
              id: 'node_9',
            },
          ],
          outputIconDefault: true,
          navViewPos: 'NONE',
          createControlAction: {
            appDEMethodId: 'create',
            appDataEntityId: 'web.system_setting',
            id: 'create',
          },
          fetchControlAction: {
            appDataEntityId: 'web.system_setting',
            id: 'fetch',
          },
          getControlAction: {
            appDEMethodId: 'get',
            appDataEntityId: 'web.system_setting',
            id: 'load',
          },
          removeControlAction: {
            appDEMethodId: 'remove',
            appDataEntityId: 'web.system_setting',
            id: 'remove',
          },
          updateControlAction: {
            appDEMethodId: 'update',
            appDataEntityId: 'web.system_setting',
            id: 'update',
          },
          autoLoad: true,
          showBusyIndicator: true,
          codeName: 'tree_exp_view_tree_view',
          controlStyle: 'LIST_TREE',
          controlType: 'TREEVIEW',
          logicName: '设置_树视图',
          appDataEntityId: 'web.system_setting',
          controlLogics: [
            {
              eventNames: 'SELECTIONCHANGE',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_selectionchange',
            },
            {
              eventNames: 'LOAD',
              logicTag: 'treeexpbar_tree',
              logicType: 'CUSTOM',
              triggerType: 'CTRLEVENT',
              id: 'treeexpbar_load',
            },
          ],
          controlParam: {
            id: 'treeexpbar_tree',
          },
          sysPFPluginId: 'list_tree',
          modelId: 'e15707addd4be29bbfabf7e78f15c81f',
          modelType: 'PSDETREEVIEW',
          name: 'treeexpbar_tree',
          id: 'web.system_setting.tree_exp_view_tree_view',
        },
      ],
      codeName: 'tree_exp_view_treeexpbar',
      controlType: 'TREEEXPBAR',
      appDataEntityId: 'web.system_setting',
      controlParam: {
        id: 'treeexpbar',
      },
      modelId: '0d74e2c2bd84f16e2bbf781051cec9e6_treeexpbar',
      modelType: 'PSEXPBAR',
      name: 'treeexpbar',
      id: 'tree_exp_view_treeexpbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'web.system_setting',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.SYSTEM_SETTING',
      },
      caption: '设置',
      codeName: 'tree_exp_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'web.system_setting',
      controlParam: {},
      name: 'captionbar',
      id: 'tree_exp_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDETREEEXPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'web.system_setting',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '设置',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '0d74e2c2bd84f16e2bbf781051cec9e6',
  modelType: 'PSAPPDEVIEW',
  name: 'system_settingtree_exp_view',
  id: 'web.system_setting_tree_exp_view',
};
