export default {
  deviewCodeName: 'manager_index_view',
  deviewId: '3e0aacf525c90ace789dafdb68b3cb57',
  accUserMode: 2,
  caption: '工作台',
  codeName: 'workspace_manager_index_view',
  appDataEntityId: 'web.workspace',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '实体部件',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                },
                showCaption: true,
                id: 'control3',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentWidth: 30,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
              width: 30,
              widthMode: 'PERCENTAGE',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            caption: '实体部件',
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'control1',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          colMD: 24,
                          heightMode: 'FULL',
                          layout: 'TABLE_24COL',
                        },
                        id: 'container2',
                      },
                    ],
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '面板容器',
                    contentHeight: 50,
                    height: 50,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      height: 50,
                      heightMode: 'PERCENTAGE',
                      layout: 'SIMPLEFLEX',
                    },
                    id: 'container',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            caption: '实体部件',
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'control2',
                          },
                        ],
                        layout: {
                          layout: 'FLEX',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          colMD: 24,
                          heightMode: 'FULL',
                          layout: 'TABLE_24COL',
                        },
                        id: 'container3',
                      },
                    ],
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '面板容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'SIMPLEFLEX',
                    },
                    id: 'container1',
                  },
                ],
                predefinedType: 'CONTAINER_V_SPLIT',
                layout: {
                  layout: 'SIMPLEFLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '分割容器(上下)',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                },
                id: 'container_v_split',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_LEFT',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentWidth: 70,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'WEST',
              layout: 'BORDER',
              width: 70,
              widthMode: 'PERCENTAGE',
            },
            width: 70,
            showCaption: true,
            id: 'container_scroll_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '实体部件',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'control',
                  },
                ],
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  layout: 'BORDER',
                  spacingTop: 'OUTERMEDIUM',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_HEADER',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentHeight: 70,
            height: 70,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'NORTH',
              height: 70,
              heightMode: 'PX',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_header',
          },
          {
            actionGroupExtractMode: 'ITEM',
            predefinedType: 'CONTAINER_SCROLL_BOTTOM',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentHeight: 80,
            height: 80,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'SOUTH',
              height: 80,
              heightMode: 'PX',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_bottom',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        embeddedAppDEViewId: 'web.workspace_my_attention_tab_exp_view',
        codeName: 'manager_index_view_control3',
        controlType: 'VIEWPANEL',
        appDataEntityId: 'web.workspace',
        controlParam: {},
        name: 'control3',
        id: 'manager_index_view_control3',
      },
      {
        embeddedAppDEViewId:
          'web.hr_interview_feedback_work_bench_my_interview',
        codeName: 'manager_index_view_control1',
        controlType: 'VIEWPANEL',
        appDataEntityId: 'web.workspace',
        controlParam: {},
        name: 'control1',
        id: 'manager_index_view_control1',
      },
      {
        embeddedAppDEViewId: 'web.workspace_my_summary_tab_exp_view',
        codeName: 'manager_index_view_control2',
        controlType: 'VIEWPANEL',
        appDataEntityId: 'web.workspace',
        controlParam: {},
        name: 'control2',
        id: 'manager_index_view_control2',
      },
      {
        embeddedAppDEViewId: 'web.workspace_welcome_custom_view',
        codeName: 'manager_index_view_control',
        controlType: 'VIEWPANEL',
        appDataEntityId: 'web.workspace',
        controlParam: {},
        name: 'control',
        id: 'manager_index_view_control',
      },
      {
        caption: '工作台',
        codeName: 'manager_index_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'web.workspace',
        controlParam: {},
        name: 'captionbar',
        id: 'manager_index_view_captionbar',
      },
    ],
    codeName: 'usr0912368690',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '用人经理-欢迎布局面板',
    appDataEntityId: 'web.workspace',
    controlParam: {},
    modelId: '133e2fed61f82042168e29d587ccd853',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0912368690',
  },
  title: '工作台',
  viewStyle: 'DEFAULT',
  viewType: 'DECUSTOMVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f0d599c8a937fa4e48b32f30382e6271',
  modelType: 'PSAPPDEVIEW',
  name: 'workspacemanager_index_view',
  id: 'web.workspace_manager_index_view',
};
