export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'main_view',
  deviewId: 'beb5aa1ec65959244498e1c72aadf303',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_DEPARTMENT',
  },
  caption: '部门',
  codeName: 'hr_departmentmain_view',
  appDataEntityId: 'ehrapp.hr_department',
  sysCss: {
    cssName: 'main-info-common-view',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container2',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'identifier',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 0,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'view_content',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 8,
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '实体部件',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      heightMode: 'FULL',
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'control',
                  },
                ],
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  heightMode: 'FULL',
                  layout: 'TABLE_24COL',
                },
                id: 'mail_thread_panel',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 4,
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container1',
          },
        ],
        predefinedType: 'CONTAINER_GRID',
        layout: {
          layout: 'SIMPLEFLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '栅格容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_grid',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ehrapp.hr_department',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ehrapp.hr_department',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ehrapp.hr_department',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ehrapp.hr_department',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ehrapp.hr_department',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ehrapp.hr_department',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.HR_DEPARTMENT.NAME',
                    },
                    caption: '名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 60,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'manager_name',
                    editor: {
                      linkAppViewId: 'ehrapp.hr_employeemain_view',
                      singleSelect: true,
                      handlerType: 'PickupText',
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_default',
                      appDataEntityId: 'ehrapp.hr_employee',
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      valueItemName: 'manager_id',
                      editorParams: {
                        ISSHOWTAB: 'false',
                        userauthentity: 'ibizehrapp.hr_employee',
                        AC: 'TRUE',
                        TRIGGER: 'TRUE',
                        URL: '/hr_employees/fetch_simple',
                        PICKUPVIEW: 'FALSE',
                        'srfnavctx.hr_department': '',
                        USERMETHOD: 'post',
                        'srfnavparam.hr_department': '',
                        USERMAP: '{"id":"id","name":"name","avatar":"avatar"}',
                      },
                      editorStyle: 'PERSONEL_SELECT_EMP',
                      editorType: 'PICKEREX_TRIGGER',
                      editorItems: [
                        {
                          id: 'manager_id',
                        },
                      ],
                      sysPFPluginId: 'person_select',
                      valueType: 'SIMPLE',
                      editable: true,
                      navigateContexts: [
                        {
                          key: 'HR_DEPARTMENT',
                          rawValue: true,
                          name: 'HR_DEPARTMENT',
                          id: 'hr_department',
                        },
                      ],
                      navigateParams: [
                        {
                          key: 'hr_department',
                          rawValue: true,
                          id: 'hr_department',
                        },
                      ],
                      id: 'manager_name',
                    },
                    allowEmpty: true,
                    caption: '管理员',
                    codeName: 'manager_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 21,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'manager_name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 72,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'parent_name',
                    editor: {
                      linkAppViewId: 'ehrapp.hr_departmentmain_view',
                      enablePickupView: true,
                      singleSelect: true,
                      pickupAppViewId: 'ehrapp.hr_departmentpickupview',
                      handlerType: 'PickupText',
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_default',
                      appDataEntityId: 'ehrapp.hr_department',
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      valueItemName: 'parent_id',
                      editorParams: {
                        AC: 'TRUE',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'PICKER',
                      editorItems: [
                        {
                          id: 'parent_id',
                        },
                      ],
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'parent_name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.HR_DEPARTMENT.PARENT_ID',
                    },
                    caption: '上级部门',
                    codeName: 'parent_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'parent_name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 60,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'company_name',
                    editor: {
                      linkAppViewId: 'ehrapp.res_companymain_view',
                      enablePickupView: true,
                      singleSelect: true,
                      pickupAppViewId: 'ehrapp.res_companypickupview',
                      handlerType: 'PickupText',
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_default',
                      appDataEntityId: 'ehrapp.res_company',
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      valueItemName: 'company_id',
                      editorParams: {
                        AC: 'TRUE',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'PICKER',
                      editorItems: [
                        {
                          id: 'company_id',
                        },
                      ],
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'company_name',
                    },
                    allowEmpty: true,
                    caption: '公司',
                    codeName: 'company_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'company_name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 60,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'color',
                    editor: {
                      editorType: 'COLORPICKER',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'color',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.HR_DEPARTMENT.COLOR',
                    },
                    caption: '颜色',
                    codeName: 'color',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'color',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'manager_id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'manager_id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    caption: '管理员',
                    codeName: 'manager_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'manager_id',
                  },
                ],
                caption: '部门基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 16,
                  colMD: 16,
                  colSM: 24,
                  colXS: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    appViewId: 'ehrapp.hr_departmentdepartment_hierarchy_view',
                    navigateParams: [
                      {
                        key: 'department',
                        value: 'hr_department',
                        id: 'department',
                      },
                      {
                        key: 'parent_path',
                        value: 'parent_path',
                        id: 'parent_path',
                      },
                    ],
                    parentDataJO: {
                      srfparentdename: 'HR_DEPARTMENT',
                      SRFPARENTTYPE: 'CUSTOM',
                    },
                    codeName: 'druipart1',
                    contentHeight: 450,
                    detailStyle: 'DEFAULT',
                    detailType: 'DRUIPART',
                    height: 450,
                    layoutPos: {
                      colMD: 24,
                      height: 450,
                      heightMode: 'PX',
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'druipart1',
                  },
                ],
                caption: '组织架构',
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colLG: 8,
                  colMD: 8,
                  colSM: 24,
                  colXS: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'company_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'company_id',
                },
                allowEmpty: true,
                hidden: true,
                caption: '公司',
                codeName: 'company_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'company_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'parent_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'parent_id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.HR_DEPARTMENT.PARENT_ID',
                },
                caption: '上级部门',
                codeName: 'parent_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'parent_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.HR_DEPARTMENT.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'Main',
        controlType: 'FORM',
        logicName: '部门实体主视图_表单',
        appDataEntityId: 'ehrapp.hr_department',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: '24fc3f6ebd26fe16e29b14a9b592d636',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ehrapp.hr_department.main',
      },
      {
        dedrbarGroups: [
          {
            caption: '默认',
            name: '默认',
            id: 'aa549a0c33c9c1ef2b2',
          },
        ],
        showTitle: true,
        dataRelationTag: 'DataRelation',
        editItemCapLanguageRes: {
          lanResTag: 'DE.LNAME.HR_DEPARTMENT',
        },
        editItemCaption: '部门',
        appCounterRefId: '0ab785719bf37000a555da8272bb4425',
        dedrctrlItems: [
          {
            dedrbarGroupId: 'aa549a0c33c9c1ef2b2',
            caption: '员工',
            counterId: 'total_employee',
            appViewId: 'ehrapp.hr_employeemulti_data_view',
            sysImage: {
              cssClass: 'fa fa-users',
              glyph: 'xf0c0@FontAwesome',
            },
            id: 'emp_info',
          },
          {
            dedrbarGroupId: 'aa549a0c33c9c1ef2b2',
            caption: '计划',
            counterId: 'plans_count',
            appViewId: 'ehrapp.mail_activity_planmulti_data_view',
            sysImage: {
              cssClass: 'fa fa-list-ul',
              glyph: 'xf0ca@FontAwesome',
            },
            id: 'plan_info',
          },
        ],
        uniqueTag: 'hr_departmentmain_view__drbar',
        hideEditItem: true,
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'department_counter',
              counterType: 'DEDR',
              getAppDEActionId: 'department_counter',
              appDataEntityId: 'ehrapp.hr_department',
              timer: 60000,
              uniqueTag: 'department_counter',
              name: '部门关系数据栏计数器',
              id: 'ehrapp.department_counter',
            },
            refMode: {
              srfdeid: 'HR_DEPARTMENT',
            },
            tag: '0ab785719bf37000a555da8272bb4425',
            uniqueTag: 'department_counter',
            id: '0ab785719bf37000a555da8272bb4425',
          },
        ],
        codeName: 'DataRelation',
        controlStyle: 'ODOO_DRBAR',
        controlType: 'DRBAR',
        height: 50,
        appDataEntityId: 'ehrapp.hr_department',
        controlParam: {
          id: 'drbar',
        },
        sysPFPluginId: 'odoo_drbar',
        modelId: '9dbb2d4c3b565d7c7c00d1d8ed4a8020',
        modelType: 'PSDEDRBAR',
        name: 'drbar',
        id: 'datarelation',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                groupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      capLanguageRes: {
                        lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                      },
                      caption: '删除并关闭',
                      detailType: 'DEUIACTION',
                      uiactionId: 'editview_removeandexitaction',
                      tooltipLanguageRes: {
                        lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                      },
                      showCaption: true,
                      showIcon: true,
                      sysImage: {
                        cssClass: 'fa fa-remove',
                        glyph: 'xf00d@FontAwesome',
                      },
                      id: 'ub3c0a37',
                    },
                  ],
                  name: '通用编辑页面删除界面行为组',
                  id: 'auto94538916',
                },
                valid: true,
                itemType: 'ITEMS',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            caption: '更多',
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-cog',
              glyph: 'xf013@FontAwesome',
            },
            tooltip: '更多',
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_viewtoolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'ehrapp.hr_department',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_viewtoolbar',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveandnewaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'sx-tb-saveandnew',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_viewtoolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'ehrapp.hr_department',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'main_viewtoolbar1',
      },
      {
        embeddedAppDEViewId: 'ehrapp.mail_thread_component_view',
        codeName: 'main_viewcontrol',
        controlType: 'VIEWPANEL',
        appDataEntityId: 'ehrapp.hr_department',
        controlParam: {},
        name: 'control',
        id: 'main_viewcontrol',
      },
      {
        codeName: 'main_viewdatainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ehrapp.hr_department',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_viewdatainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.HR_DEPARTMENT',
        },
        caption: '部门',
        codeName: 'main_viewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ehrapp.hr_department',
        controlParam: {},
        name: 'captionbar',
        id: 'main_viewcaptionbar',
      },
    ],
    codeName: 'main_view_layout_new',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_new',
    appDataEntityId: 'ehrapp.hr_department',
    controlLogics: [
      {
        eventNames: 'onMounted',
        itemName: 'DRBAR',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", (state, isTrusted )=> {\r\n    console.log("");\r\n    const data = view.getController("form").getData()[0];\r\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\r\n});\r\n\r\nconst topContext = view.context;\r\nconst appEntityId = view.model.appDataEntityId;\r\nconst entityName = appEntityId.split(\'.\').pop();\r\nconst bExist = topContext[entityName];\r\nconst drbar = view.getCtrl("DRBAR", "drbar");\r\nif(!bExist){\r\n    drbar.disabled({ mode: \'BLANK\' })\r\n    //  drbar.disabled({ mode: \'MASK\' })\r\n\r\n}\r\n\r\n',
        triggerType: 'CTRLEVENT',
        id: 'drbar_draft_state',
      },
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onRegister',
        itemName: 'DRBAR',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode: "console.log('部件onRegister执行了');",
        triggerType: 'CTRLEVENT',
        id: 'logic1',
      },
      {
        eventNames: 'onCreated',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "view.ctx.evt.on('onRegister', (name, ctrl) => {\r\n   if (name === 'drbar') {\r\n      const topContext = view.context;\r\n      const appEntityId = view.model.appDataEntityId;\r\n      const entityName = appEntityId.split('.').pop();\r\n      const bExist = topContext[entityName];\r\n      if(!bExist){\r\n         ctrl?.disableCounter()\r\n      }\r\n   }\r\n})",
        triggerType: 'CTRLEVENT',
        id: 'logic2',
      },
    ],
    controlParam: {},
    modelId: '31fa7086ff6a353ca3fdf381a934b594',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout_new',
  },
  title: '部门',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'dc74116c20c80481f19c6d9c46196786',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_departmentmain_view',
  id: 'ehrapp.hr_departmentmain_view',
};
