export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: 'db00856307064b390a30bb68b5eb3746',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_JOB',
  },
  caption: '工作岗位',
  codeName: 'hr_jobPickupGridView',
  appDataEntityId: 'ehrapp.hr_job',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      orderValueAppDEFieldId: 'sequence',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '工作岗位',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.HR_JOB.NAME',
          },
          caption: '工作岗位',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'department_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'department_id',
        },
        {
          appDEFieldId: 'company_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'company_id',
        },
        {
          appDEFieldId: 'contract_type_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'contract_type_id',
        },
        {
          appDEFieldId: 'industry_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'industry_id',
        },
        {
          appDEFieldId: 'manager_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'manager_id',
        },
        {
          appDEFieldId: 'address_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'address_id',
        },
        {
          appDEFieldId: 'user_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'user_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ehrapp.hr_job',
        id: 'fetch',
      },
      moveControlAction: {
        appDEMethodId: 'move_order',
        appDataEntityId: 'ehrapp.hr_job',
        id: 'move',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ehrapp.hr_job',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ehrapp.hr_job',
      controlParam: {
        id: 'grid',
      },
      modelId: '714cead397e6c3154f5c121d665ec1e1',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ehrapp.hr_job.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag: 'CONTROL.DEFORM.HR_JOB.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ehrapp.hr_job',
      controlParam: {
        id: 'searchform',
      },
      modelId: '8d4d9216ff87a6a61771034172a5d4d6',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ehrapp.hr_job.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ehrapp.hr_job',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_JOB',
      },
      caption: '工作岗位',
      codeName: 'PickupGridViewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ehrapp.hr_job',
      controlParam: {},
      name: 'captionbar',
      id: 'pickupgridviewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ehrapp.hr_job',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作岗位选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '5f8cd7403f7075bd008a8e7218831be5',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_jobPickupGridView',
  id: 'ehrapp.hr_jobpickupgridview',
};
