export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: '0cca8935811014d34137a4ce44fe7219',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_WORK_LOCATION',
  },
  caption: '工作地点',
  codeName: 'hr_work_locationPickupGridView',
  appDataEntityId: 'ehrapp.hr_work_location',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '工作地点',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.HR_WORK_LOCATION.NAME',
          },
          caption: '工作地点',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'location_type',
          excelCaption: '封面图片',
          appCodeListId: 'ehrapp.hr__hr_work_location_location_type',
          appDEFieldId: 'location_type',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.HR_WORK_LOCATION.LOCATION_TYPE',
          },
          caption: '封面图片',
          codeName: 'location_type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'location_type',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'company_name',
          excelCaption: '公司',
          appDEFieldId: 'company_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.HR_WORK_LOCATION.COMPANY_ID',
          },
          caption: '公司',
          codeName: 'company_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'company_name',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'location_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'location_type',
        },
        {
          appDEFieldId: 'company_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'company_name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'company_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'company_id',
        },
        {
          appDEFieldId: 'address_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'address_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ehrapp.hr_work_location',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ehrapp.hr_work_location',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ehrapp.hr_work_location',
      controlParam: {
        id: 'grid',
      },
      modelId: 'd8d5bec2c20b0b15e4d9bb63111e6fb3',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ehrapp.hr_work_location.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.HR_WORK_LOCATION.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ehrapp.hr_work_location',
      controlParam: {
        id: 'searchform',
      },
      modelId: '6ab445db75fec75478a0cf42f0ff3108',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ehrapp.hr_work_location.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ehrapp.hr_work_location',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.HR_WORK_LOCATION',
      },
      caption: '工作地点',
      codeName: 'PickupGridViewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ehrapp.hr_work_location',
      controlParam: {},
      name: 'captionbar',
      id: 'pickupgridviewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ehrapp.hr_work_location',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作地点选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '18a07c77ec5102d0d676e34ef9054674',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_work_locationPickupGridView',
  id: 'ehrapp.hr_work_locationpickupgridview',
};
