export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'EditView',
  deviewId: '597162510b223ab96ff7086a79ca1a17',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.IR_MODULE_CATEGORY',
  },
  caption: '应用',
  codeName: 'ir_module_categoryEditView',
  appDataEntityId: 'ehrapp.ir_module_category',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  controls: [
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'editview_saveaction',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.SAVE',
          },
          caption: '保存',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-save',
            glyph: 'xf0c7@FontAwesome',
          },
          tooltip: '保存',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.SAVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'tbitem1',
        },
      ],
      xdataControlName: 'form',
      codeName: 'EditViewtoolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（嵌入编辑表单，只有一个保存按钮）',
      appDataEntityId: 'ehrapp.ir_module_category',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '25823041a044e2dfc60cdebdb06ebd82',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'editviewtoolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'ehrapp.ir_module_category',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'ehrapp.ir_module_category',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'ehrapp.ir_module_category',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'ehrapp.ir_module_category',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ehrapp.ir_module_category',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'ehrapp.ir_module_category',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'name',
                  editor: {
                    maxLength: 200,
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.IR_MODULE_CATEGORY.NAME',
                  },
                  caption: '名称',
                  codeName: 'name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'name',
                },
                {
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'parent_name',
                  editor: {
                    enablePickupView: true,
                    singleSelect: true,
                    pickupAppViewId: 'ehrapp.ir_module_categorypickupview',
                    handlerType: 'PickupText',
                    appDEACModeId: 'default',
                    appDEDataSetId: 'fetch_default',
                    appDataEntityId: 'ehrapp.ir_module_category',
                    enableAC: true,
                    forceSelection: true,
                    showTrigger: true,
                    valueItemName: 'parent_id',
                    editorParams: {
                      AC: 'TRUE',
                      PICKUPVIEW: 'TRUE',
                    },
                    editorType: 'PICKER',
                    editorItems: [
                      {
                        id: 'parent_id',
                      },
                    ],
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'parent_name',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.IR_MODULE_CATEGORY.PARENT_ID',
                  },
                  caption: '父应用名称',
                  codeName: 'parent_name',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'parent_name',
                },
                {
                  dataType: 9,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'sequence',
                  editor: {
                    editorType: 'TEXTBOX',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'sequence',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.IR_MODULE_CATEGORY.SEQUENCE',
                  },
                  caption: '序列',
                  codeName: 'sequence',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'sequence',
                },
                {
                  dataType: 21,
                  enableCond: 3,
                  itemHeight: 200,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'description',
                  editor: {
                    maxLength: 1048576,
                    showMaxLength: true,
                    editorHeight: 200,
                    editorParams: {
                      HEIGHT: '200',
                    },
                    editorType: 'TEXTAREA_10',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'description',
                  },
                  allowEmpty: true,
                  capLanguageRes: {
                    lanResTag: 'DEF.LNAME.IR_MODULE_CATEGORY.DESCRIPTION',
                  },
                  caption: '描述',
                  codeName: 'description',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'description',
                },
              ],
              capLanguageRes: {
                lanResTag:
                  'CONTROL.DEFORM.IR_MODULE_CATEGORY.MAIN.GROUPPANEL.GROUP1',
              },
              caption: '应用基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'parent_id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'parent_id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.IR_MODULE_CATEGORY.PARENT_ID',
              },
              caption: '父应用',
              codeName: 'parent_id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'parent_id',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.IR_MODULE_CATEGORY.ID',
              },
              caption: '标识',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.IR_MODULE_CATEGORY.MAIN.FORMPAGE.FORMPAGE1',
          },
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Main',
      controlType: 'FORM',
      logicName: '主编辑表单',
      appDataEntityId: 'ehrapp.ir_module_category',
      controlParam: {
        ctrlParams: {
          EDITMODE: 'hover',
        },
        id: 'form',
      },
      modelId: '1c9857c5663d999f871f53fee192d548',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'ehrapp.ir_module_category.main',
    },
    {
      codeName: 'EditViewdatainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'ehrapp.ir_module_category',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'editviewdatainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.IR_MODULE_CATEGORY',
      },
      caption: '应用',
      codeName: 'EditViewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ehrapp.ir_module_category',
      controlParam: {},
      name: 'captionbar',
      id: 'editviewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ehrapp.ir_module_category',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '应用编辑视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '1707d9189e622afe8bbc0fe6c4daabf5',
  modelType: 'PSAPPDEVIEW',
  name: 'ir_module_categoryEditView',
  id: 'ehrapp.ir_module_categoryeditview',
};
