export default {
  showDataInfoBar: true,
  loadDefault: true,
  deviewCodeName: 'TreeExpView',
  deviewId: '397c5d86c471e49b544364f496120aeb',
  accUserMode: 2,
  caption: '应用市场',
  codeName: 'PSCorePrdFuncTreeExpView',
  appDataEntityId: 'ehrapp.pscoreprdfunc',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '树导航栏',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'treeexpbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentWidth: 300,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
              width: 300,
              widthMode: 'PX',
            },
            width: 300,
            id: 'view_content_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  predefinedType: 'NAV_POS',
                  id: 'nav_pos',
                },
                caption: '面包屑导航区占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  grow: 1,
                  shrink: 1,
                  layout: 'FLEX',
                },
                sysPFPluginId: 'breadcrumb_nav_pos',
                showCaption: true,
                id: 'nav_pos',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_content_right',
          },
        ],
        predefinedType: 'CONTAINER_H_SPLIT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_exp_split',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'TreeExpView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          editMode: true,
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    controls: [
      {
        xdataControlName: 'treeexpbar_tree',
        enableCounter: true,
        autoLoad: true,
        showBusyIndicator: true,
        appViewRefs: [
          {
            realTitle: '已安装应用',
            refAppViewId: 'ehrapp.pscoreprdfuncinstalledgridview',
            name: 'EXPITEM:installedApp',
            id: 'expitem:installedapp',
          },
          {
            realTitle: '应用市场',
            refAppViewId: 'ehrapp.pscoreprdfuncmarketapplicationview',
            name: 'EXPITEM:market',
            id: 'expitem:market',
          },
          {
            realTitle: '应用市场',
            refAppViewId: 'ehrapp.pscoreprdmarketapplicationview',
            name: 'EXPITEM:node_1',
            id: 'expitem:node_1',
          },
          {
            realTitle: '应用市场',
            refAppViewId: 'ehrapp.pscoreprdmarketapplicationview',
            name: 'EXPITEM:node_2',
            id: 'expitem:node_2',
          },
          {
            realTitle: '应用市场',
            refAppViewId: 'ehrapp.pscoreprdmarketapplicationview',
            name: 'EXPITEM:node_3',
            id: 'expitem:node_3',
          },
        ],
        controls: [
          {
            detreeNodeRSs: [
              {
                childDETreeNodeId: 'node',
                parentDETreeNodeId: 'root',
                parentValueLevel: 1,
                searchMode: 3,
                id: '默认根节点 - 发现',
              },
              {
                childDETreeNodeId: 'node_3',
                navigateParams: [
                  {
                    key: 'n_ppscoreprdcatid_eq',
                    value: 'pscoreprdcatid',
                    id: 'n_ppscoreprdcatid_eq',
                  },
                ],
                parentDETreeNodeId: 'node_2',
                parentValueLevel: 1,
                searchMode: 3,
                id: '产品根目录（动态） - 产品子目录',
              },
              {
                childDETreeNodeId: 'node_3',
                navigateParams: [
                  {
                    key: 'n_ppscoreprdcatid_eq',
                    value: 'pscoreprdcatid',
                    id: 'n_ppscoreprdcatid_eq',
                  },
                ],
                parentDETreeNodeId: 'node_3',
                parentValueLevel: 1,
                searchMode: 3,
                id: '产品子目录 - 产品子目录',
              },
              {
                childDETreeNodeId: 'market',
                parentDETreeNodeId: 'node',
                parentValueLevel: 1,
                searchMode: 3,
                id: '发现 - 应用市场',
              },
              {
                childDETreeNodeId: 'installedapp',
                parentDETreeNodeId: 'node',
                parentValueLevel: 1,
                searchMode: 3,
                id: '发现 - 已安装应用',
              },
            ],
            detreeNodes: [
              {
                nodeValue: 'root',
                text: '默认根节点',
                nodeType: 'ROOT',
                treeNodeType: 'STATIC',
                hasDETreeNodeRSs: true,
                rootNode: true,
                name: '默认根节点',
                id: 'root',
              },
              {
                text: '已安装应用',
                navAppViewId: 'ehrapp.pscoreprdfuncinstalledgridview',
                nodeType: 'installedApp',
                treeNodeType: 'STATIC',
                name: '已安装应用',
                id: 'installedapp',
              },
              {
                text: '应用市场',
                navAppViewId: 'ehrapp.pscoreprdfuncmarketapplicationview',
                nodeType: 'market',
                treeNodeType: 'STATIC',
                expanded: true,
                name: '应用市场',
                id: 'market',
              },
              {
                text: '发现',
                nodeType: 'node',
                treeNodeType: 'STATIC',
                hasDETreeNodeRSs: true,
                expanded: true,
                userTag: 'NO_NAV',
                name: '发现',
                id: 'node',
              },
              {
                text: '全部应用',
                navAppViewId: 'ehrapp.pscoreprdmarketapplicationview',
                nodeType: 'node_1',
                treeNodeType: 'STATIC',
                name: '全部应用',
                id: 'node_1',
              },
              {
                dataSourceType: 'DEDATASET',
                navAppViewId: 'ehrapp.pscoreprdmarketapplicationview',
                nodeType: 'node_2',
                navigateParams: [
                  {
                    key: 'n_pscoreprdcatid_eq',
                    value: 'pscoreprdcatid',
                    id: 'n_pscoreprdcatid_eq',
                  },
                ],
                treeNodeType: 'DE',
                hasDETreeNodeRSs: true,
                name: '产品根目录（动态）',
                id: 'node_2',
              },
              {
                dataSourceType: 'DEDATASET',
                navAppViewId: 'ehrapp.pscoreprdmarketapplicationview',
                nodeType: 'node_3',
                navigateParams: [
                  {
                    key: 'n_pscoreprdcatid_eq',
                    value: 'pscoreprdcatid',
                    id: 'n_pscoreprdcatid_eq',
                  },
                ],
                treeNodeType: 'DE',
                hasDETreeNodeRSs: true,
                name: '产品子目录',
                id: 'node_3',
              },
            ],
            outputIconDefault: true,
            navViewPos: 'NONE',
            createControlAction: {
              appDEMethodId: 'create',
              appDataEntityId: 'ehrapp.pscoreprdfunc',
              id: 'create',
            },
            fetchControlAction: {
              appDataEntityId: 'ehrapp.pscoreprdfunc',
              id: 'fetch',
            },
            getControlAction: {
              appDEMethodId: 'get',
              appDataEntityId: 'ehrapp.pscoreprdfunc',
              id: 'load',
            },
            removeControlAction: {
              appDEMethodId: 'remove',
              appDataEntityId: 'ehrapp.pscoreprdfunc',
              id: 'remove',
            },
            updateControlAction: {
              appDEMethodId: 'update',
              appDataEntityId: 'ehrapp.pscoreprdfunc',
              id: 'update',
            },
            autoLoad: true,
            showBusyIndicator: true,
            codeName: 'TreeExpView_TreeView',
            controlStyle: 'LIST_TREE',
            controlType: 'TREEVIEW',
            logicName: '应用管理_树视图',
            appDataEntityId: 'ehrapp.pscoreprdfunc',
            controlLogics: [
              {
                eventNames: 'SELECTIONCHANGE',
                logicTag: 'treeexpbar_tree',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'treeexpbar_selectionchange',
              },
              {
                eventNames: 'LOAD',
                logicTag: 'treeexpbar_tree',
                logicType: 'CUSTOM',
                triggerType: 'CTRLEVENT',
                id: 'treeexpbar_load',
              },
            ],
            controlParam: {
              id: 'treeexpbar_tree',
            },
            sysPFPluginId: 'list_tree',
            modelId: '9d269ae87a5cc617da938141c562b2c6',
            modelType: 'PSDETREEVIEW',
            name: 'treeexpbar_tree',
            id: 'ehrapp.pscoreprdfunc.treeexpview_treeview',
          },
        ],
        codeName: 'TreeExpViewtreeexpbar',
        controlType: 'TREEEXPBAR',
        appDataEntityId: 'ehrapp.pscoreprdfunc',
        controlParam: {
          id: 'treeexpbar',
        },
        modelId: '26006b4bbb220608b64f3249f9239341_treeexpbar',
        modelType: 'PSEXPBAR',
        name: 'treeexpbar',
        id: 'treeexpviewtreeexpbar',
      },
      {
        groupMode: 'SINGLE',
        quickSearchMode: 1,
        enableQuickSearch: true,
        controlType: 'SEARCHBAR',
        appDataEntityId: 'ehrapp.pscoreprdfunc',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        caption: '应用市场',
        codeName: 'TreeExpViewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ehrapp.pscoreprdfunc',
        controlParam: {},
        name: 'captionbar',
        id: 'treeexpviewcaptionbar',
      },
    ],
    codeName: 'Usr1206423734',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'TreeExpView实体树导航视图布局面板',
    appDataEntityId: 'ehrapp.pscoreprdfunc',
    controlParam: {},
    modelId: '50bbdc014c8c866ca6df9766703c9c37',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr1206423734',
  },
  priority: 30,
  title: '应用管理',
  viewStyle: 'DEFAULT',
  viewType: 'DETREEEXPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '26006b4bbb220608b64f3249f9239341',
  modelType: 'PSAPPDEVIEW',
  name: 'PSCorePrdFuncTreeExpView',
  id: 'ehrapp.pscoreprdfunctreeexpview',
};
