export default {
  mdctrlActiveMode: 2,
  xdataControlName: 'dataview',
  loadDefault: true,
  deviewCodeName: 'MarketApplicationView',
  deviewId: 'a251668a42019ad72091c61b1e9a1029',
  accUserMode: 2,
  caption: '核心产品',
  codeName: 'PSCorePrdMarketApplicationView',
  appDataEntityId: 'ehrapp.pscoreprd',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'DataView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          openMode: 'INDEXVIEWTAB_POPUPMODAL',
          refAppViewId: 'ehrapp.pscoreprdinfoview',
        },
        appUILogicRefViews: [
          {
            openMode: 'INDEXVIEWTAB_POPUPMODAL',
            refAppViewId: 'ehrapp.pscoreprdinfoview',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          openMode: 'INDEXVIEWTAB_POPUPMODAL',
          refAppViewId: 'ehrapp.pscoreprdinfoview',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            openMode: 'INDEXVIEWTAB_POPUPMODAL',
            refAppViewId: 'ehrapp.pscoreprdinfoview',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '应用',
      refAppViewId: 'ehrapp.pscoreprdinfoview',
      name: 'OPENDATA',
      id: 'opendata',
    },
    {
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '应用',
      refAppViewId: 'ehrapp.pscoreprdinfoview',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realOpenMode: 'INDEXVIEWTAB_POPUPMODAL',
      realTitle: '应用',
      refAppViewId: 'ehrapp.pscoreprdinfoview',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      xdataControlName: 'dataview',
      codeName: 'MarketApplicationViewtoolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（只有一个实体界面行为组）',
      appDataEntityId: 'ehrapp.pscoreprd',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '97b647cbe00cc608f9a368e2d0874c1e',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'marketapplicationviewtoolbar',
    },
    {
      cardHeight: 250,
      cardWidth: 420,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      itemLayoutPanel: {
        layoutMode: 'TABLE_24COL',
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          maxFileCount: 1,
                          editorParams: {
                            readonly: 'true',
                            MAXCOUNT: '1',
                          },
                          editorType: 'PICTURE_ONE',
                          predefinedType: 'FIELD_IMAGE',
                          valueType: 'SIMPLE',
                          editable: true,
                          readOnly: true,
                          id: 'avatarurl',
                        },
                        viewFieldName: 'AVATARURL',
                        allowEmpty: true,
                        caption: '图片(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'avatarurl',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'container2',
                  },
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'pscoreprdname',
                        },
                        viewFieldName: 'PSCOREPRDNAME',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'pscoreprdname',
                      },
                      {
                        editor: {
                          halign: 'LEFT',
                          renderMode: 'TEXT_DYNAMIC',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          editorType: 'SPAN',
                          predefinedType: 'FIELD_TEXT_DYNAMIC',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'memo',
                        },
                        viewFieldName: 'MEMO',
                        allowEmpty: true,
                        caption: '文本(动态)',
                        itemStyle: 'DEFAULT',
                        itemType: 'FIELD',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'memo',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      spacingLeft: 'OUTERMEDIUM',
                    },
                    id: 'container1',
                  },
                ],
                layout: {
                  align: 'flex-start',
                  dir: 'row',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  spacingLeft: 'OUTERMEDIUM',
                  spacingRight: 'OUTERMEDIUM',
                },
                id: 'container',
              },
            ],
            layout: {
              dir: 'column',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            id: 'page_container',
          },
        ],
        codeName: 'Usr0715754331',
        controlType: 'PANEL',
        logicName: '应用市场_卡片视图_卡片面板',
        appDataEntityId: 'ehrapp.pscoreprd',
        controlParam: {},
        modelId: '9c3447d04993c6ad8eb7c7b63014b2ba',
        modelType: 'PSSYSVIEWPANEL',
        name: 'itemlayoutpanel',
        id: 'ehrapp.pscoreprd.usr0715754331',
      },
      dedataViewDataItems: [
        {
          dataType: 25,
          id: 'memo',
        },
        {
          dataType: 25,
          id: 'pscoreprdname',
        },
        {
          dataType: 25,
          id: 'avatarurl',
        },
        {
          appDEFieldId: 'pscoreprdid',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'pscoreprdname',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      dedataViewItems: [
        {
          caption: '备注',
          dataItemName: 'memo',
          itemType: 'DATAITEM',
          appDEFieldId: 'memo',
          enableSort: true,
          name: 'MEMO',
          id: 'memo',
        },
        {
          caption: '产品名称',
          dataItemName: 'pscoreprdname',
          itemType: 'DATAITEM',
          appDEFieldId: 'pscoreprdname',
          enableSort: true,
          name: 'PSCOREPRDNAME',
          id: 'pscoreprdname',
        },
        {
          caption: '图标路径',
          dataItemName: 'avatarurl',
          itemType: 'DATAITEM',
          appDEFieldId: 'avatarurl',
          enableSort: true,
          name: 'AVATARURL',
          id: 'avatarurl',
        },
      ],
      pagingSize: 1000,
      appendDEItems: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDataEntityId: 'ehrapp.pscoreprd',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetchdefault',
        appDataEntityId: 'ehrapp.pscoreprd',
        id: 'fetch',
      },
      getControlAction: {
        appDataEntityId: 'ehrapp.pscoreprd',
        id: 'load',
      },
      removeControlAction: {
        appDataEntityId: 'ehrapp.pscoreprd',
        id: 'remove',
      },
      updateControlAction: {
        appDataEntityId: 'ehrapp.pscoreprd',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'MarketApplicationView_DataView',
      controlType: 'DATAVIEW',
      logicName: '应用市场_卡片视图',
      appDataEntityId: 'ehrapp.pscoreprd',
      controlParam: {
        id: 'dataview',
      },
      modelId: '7cd2cd8230bc403304a20d6695137fab',
      modelType: 'PSDEDATAVIEW',
      name: 'dataview',
      id: 'ehrapp.pscoreprd.marketapplicationview_dataview',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ehrapp.pscoreprd',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '核心产品',
      codeName: 'MarketApplicationViewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ehrapp.pscoreprd',
      controlParam: {},
      name: 'captionbar',
      id: 'marketapplicationviewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEDATAVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ehrapp.pscoreprd',
    controlParam: {},
    id: 'layoutpanel',
  },
  priority: 30,
  title: '应用市场',
  viewStyle: 'DEFAULT',
  viewType: 'DEDATAVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'ef5ddfece62dd07cc99ff969f48d1d03',
  modelType: 'PSAPPDEVIEW',
  name: 'PSCorePrdMarketApplicationView',
  id: 'ehrapp.pscoreprdmarketapplicationview',
};
