export default {
  funcViewMode: 'PICKUPVIEW',
  deviewCodeName: 'PickupView',
  deviewId: 'dbc4768fb04ba17196fafa386029a5ae',
  accUserMode: 2,
  caption: '公司',
  codeName: 'res_companyPickupView',
  appDataEntityId: 'ehrapp.res_company',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupView',
      id: 'engine',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'ehrapp.res_companypickupgridview',
      codeName: 'PickupViewpickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'ehrapp.res_company',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'pickupviewpickupviewpanel',
    },
    {
      caption: '公司',
      codeName: 'PickupViewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ehrapp.res_company',
      controlParam: {},
      name: 'captionbar',
      id: 'pickupviewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ehrapp.res_company',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '公司数据选择视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e97eea33132d35dcfbfa048c0eb80088',
  modelType: 'PSAPPDEVIEW',
  name: 'res_companyPickupView',
  id: 'ehrapp.res_companypickupview',
};
