export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'main_view',
  deviewId: '4359d9c1819560392c2d9b5f21695a6f',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_GROUPS',
  },
  caption: '群组',
  codeName: 'res_groupsmain_view',
  appDataEntityId: 'ehrapp.res_groups',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'name',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 8,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container3',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                groupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      capLanguageRes: {
                        lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                      },
                      caption: '删除并关闭',
                      detailType: 'DEUIACTION',
                      uiactionId: 'editview_removeandexitaction',
                      tooltipLanguageRes: {
                        lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                      },
                      showCaption: true,
                      showIcon: true,
                      sysImage: {
                        cssClass: 'fa fa-remove',
                        glyph: 'xf00d@FontAwesome',
                      },
                      id: 'ub3c0a37',
                    },
                  ],
                  name: '通用编辑页面删除界面行为组',
                  id: 'auto94538916',
                },
                valid: true,
                itemType: 'ITEMS',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            caption: '更多',
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-cog',
              glyph: 'xf013@FontAwesome',
            },
            tooltip: '更多',
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_viewtoolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'ehrapp.res_groups',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_viewtoolbar',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ehrapp.res_groups',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ehrapp.res_groups',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ehrapp.res_groups',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ehrapp.res_groups',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ehrapp.res_groups',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ehrapp.res_groups',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'category_name',
                    editor: {
                      linkAppViewId: 'ehrapp.ir_module_categoryeditview',
                      enablePickupView: true,
                      singleSelect: true,
                      pickupAppViewId: 'ehrapp.ir_module_categorypickupview',
                      handlerType: 'PickupText',
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_default',
                      appDataEntityId: 'ehrapp.ir_module_category',
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      valueItemName: 'category_id',
                      editorParams: {
                        AC: 'TRUE',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'PICKER',
                      editorItems: [
                        {
                          id: 'category_id',
                        },
                      ],
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'category_name',
                    },
                    allowEmpty: true,
                    caption: '应用',
                    codeName: 'category_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'category_name',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.RES_GROUPS.NAME',
                    },
                    caption: '名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'name',
                  },
                  {
                    dataType: 9,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'share',
                    editor: {
                      editorType: 'CHECKBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'share',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.RES_GROUPS.SHARE',
                    },
                    caption: '共享组',
                    codeName: 'share',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'share',
                  },
                  {
                    dataType: 7,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 180,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'api_key_duration',
                    editor: {
                      editorType: 'NUMBER',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'api_key_duration',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.RES_GROUPS.API_KEY_DURATION',
                    },
                    caption: 'API 密钥最长有效期（天）',
                    codeName: 'api_key_duration',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'api_key_duration',
                  },
                ],
                caption: '基本信息',
                codeName: 'basic_info',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'basic_info',
              },
              {
                deformTabPages: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            maskMode: 0,
                            appViewId: 'ehrapp.res_groups_users_relgridview',
                            parentDataJO: {
                              SRFPARENTTYPE: 'DER1N',
                              srfparentdename: 'RES_GROUPS',
                              srfparentmode:
                                'DER1N_RES_GROUPS_USERS_REL_RES_GROUPS_GID',
                              srfparentdefname: 'GID',
                              SRFDER1NID:
                                'DER1N_RES_GROUPS_USERS_REL_RES_GROUPS_GID',
                            },
                            codeName: 'druipart4',
                            contentHeight: 500,
                            detailStyle: 'DEFAULT',
                            detailType: 'DRUIPART',
                            height: 500,
                            layoutPos: {
                              colMD: 24,
                              height: 500,
                              heightMode: 'PX',
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'druipart4',
                          },
                        ],
                        codeName: 'grouppanel3',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel3',
                      },
                    ],
                    caption: '用户',
                    codeName: 'users',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'users',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        rawItem: {
                          caption:
                            '添加到本权限组的用户也将自动加入以下权限组。',
                          halign: 'LEFT',
                          valign: 'MIDDLE',
                          wrapMode: 'NOWRAP',
                          contentType: 'RAW',
                          id: 'rawitem1',
                        },
                        codeName: 'rawitem1',
                        detailStyle: 'DEFAULT',
                        detailType: 'RAWITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'rawitem1',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            maskMode: 0,
                            appViewId: 'ehrapp.res_groups_implied_relgridview',
                            parentDataJO: {
                              SRFPARENTTYPE: 'DER1N',
                              srfparentdename: 'RES_GROUPS',
                              srfparentmode:
                                'DER1N_RES_GROUPS_IMPLIED_REL_RES_GROUPS_GID',
                              srfparentdefname: 'GID',
                              SRFDER1NID:
                                'DER1N_RES_GROUPS_IMPLIED_REL_RES_GROUPS_GID',
                            },
                            codeName: 'druipart1',
                            contentHeight: 500,
                            detailStyle: 'DEFAULT',
                            detailType: 'DRUIPART',
                            height: 500,
                            layoutPos: {
                              colMD: 24,
                              height: 500,
                              heightMode: 'PX',
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'druipart1',
                          },
                        ],
                        codeName: 'grouppanel1',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel1',
                      },
                    ],
                    caption: '继承',
                    codeName: 'inheritance',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'inheritance',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        maskMode: 0,
                        appViewId:
                          'ehrapp.unires_group_relnested_group_grid_view',
                        parentDataJO: {
                          SRFPARENTTYPE: 'DER1N',
                          srfparentdename: 'RES_GROUPS',
                          srfparentmode:
                            'DER1N_UNIRES_GROUP_REL_RES_GROUPS_GID',
                          srfparentdefname: 'GID',
                          SRFDER1NID: 'DER1N_UNIRES_GROUP_REL_RES_GROUPS_GID',
                        },
                        codeName: 'druipart5',
                        contentHeight: 500,
                        detailStyle: 'DEFAULT',
                        detailType: 'DRUIPART',
                        height: 500,
                        layoutPos: {
                          colMD: 24,
                          height: 500,
                          heightMode: 'PX',
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'druipart5',
                      },
                    ],
                    caption: '统一资源',
                    codeName: 'menu',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'menu',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            maskMode: 0,
                            appViewId: 'ehrapp.ir_model_accessgridview',
                            parentDataJO: {
                              SRFPARENTTYPE: 'DER1N',
                              srfparentdename: 'RES_GROUPS',
                              srfparentmode:
                                'DER1N_IR_MODEL_ACCESS_RES_GROUPS_GROUP_ID',
                              srfparentdefname: 'GROUP_ID',
                              SRFDER1NID:
                                'DER1N_IR_MODEL_ACCESS_RES_GROUPS_GROUP_ID',
                            },
                            codeName: 'druipart2',
                            contentHeight: 500,
                            detailStyle: 'DEFAULT',
                            detailType: 'DRUIPART',
                            height: 500,
                            layoutPos: {
                              colMD: 24,
                              height: 500,
                              heightMode: 'PX',
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'druipart2',
                          },
                        ],
                        caption: '权限设置',
                        codeName: 'access_group',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'access_group',
                      },
                    ],
                    caption: '访问权限',
                    codeName: 'access',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'access',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            maskMode: 0,
                            appViewId:
                              'ehrapp.rule_group_relnested_group_grid_view',
                            parentDataJO: {
                              SRFPARENTTYPE: 'DER1N',
                              srfparentdename: 'RES_GROUPS',
                              srfparentmode:
                                'DER1N_RULE_GROUP_REL_RES_GROUPS_GID',
                              srfparentdefname: 'GID',
                              SRFDER1NID: 'DER1N_RULE_GROUP_REL_RES_GROUPS_GID',
                            },
                            codeName: 'druipart3',
                            contentHeight: 500,
                            detailStyle: 'DEFAULT',
                            detailType: 'DRUIPART',
                            height: 500,
                            layoutPos: {
                              colMD: 24,
                              height: 500,
                              heightMode: 'PX',
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'druipart3',
                          },
                        ],
                        codeName: 'grouppanel2',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel2',
                      },
                    ],
                    caption: '记录规则',
                    codeName: 'record_rules',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'record_rules',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 21,
                        enableCond: 3,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'comment',
                        editor: {
                          maxLength: 1048576,
                          showMaxLength: true,
                          editorType: 'TEXTAREA',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'comment',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.RES_GROUPS.COMMENT',
                        },
                        caption: '评论',
                        codeName: 'comment',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'comment',
                      },
                    ],
                    caption: '备注',
                    codeName: 'notes',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'notes',
                  },
                ],
                codeName: 'tabpanel1',
                detailStyle: 'DEFAULT',
                detailType: 'TABPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'tabpanel1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'category_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'category_id',
                },
                allowEmpty: true,
                hidden: true,
                caption: '应用',
                codeName: 'category_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'category_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.RES_GROUPS.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '群组管理',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'Main',
        controlType: 'FORM',
        logicName: '权限组主编辑表单',
        appDataEntityId: 'ehrapp.res_groups',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: '0e10ff51246a5e888f0b57d352a96b56',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ehrapp.res_groups.main',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveandnewaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'sx-tb-saveandnew',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_viewtoolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'ehrapp.res_groups',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'main_viewtoolbar1',
      },
      {
        codeName: 'main_viewdatainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ehrapp.res_groups',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_viewdatainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.RES_GROUPS',
        },
        caption: '群组',
        codeName: 'main_viewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ehrapp.res_groups',
        controlParam: {},
        name: 'captionbar',
        id: 'main_viewcaptionbar',
      },
    ],
    codeName: 'main_view_layout_nocomment',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_无讨论',
    appDataEntityId: 'ehrapp.res_groups',
    controlLogics: [
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", (state, isTrusted )=> {\r\n    console.log("");\r\n    const data = view.getController("form").getData()[0];\r\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\r\n});',
        triggerType: 'CTRLEVENT',
        id: 'init_domain_state_change',
      },
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
    ],
    controlParam: {},
    modelId: 'ef3f9bc56161de3135f01329747f91a3',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout_nocomment',
  },
  title: '权限组信息',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.RES_GROUPS.MAIN_VIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f699f8cdd85db18971eb3b36bcdcf23e',
  modelType: 'PSAPPDEVIEW',
  name: 'res_groupsmain_view',
  id: 'ehrapp.res_groupsmain_view',
};
