export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  deviewCodeName: 'main_view',
  deviewId: '51103ebd3a5f7412365c95bd585f967e',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RES_USERS',
  },
  caption: '用户',
  codeName: 'res_usersmain_view',
  appDataEntityId: 'ehrapp.res_users',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'name',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar2',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 8,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container3',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                groupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      capLanguageRes: {
                        lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                      },
                      caption: '删除并关闭',
                      detailType: 'DEUIACTION',
                      uiactionId: 'editview_removeandexitaction',
                      tooltipLanguageRes: {
                        lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                      },
                      addSeparator: true,
                      showCaption: true,
                      showIcon: true,
                      sysImage: {
                        cssClass: 'fa fa-remove',
                        glyph: 'xf00d@FontAwesome',
                      },
                      id: 'uc332aaf',
                    },
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      caption: '修改密码',
                      detailType: 'DEUIACTION',
                      uiactionId: 'open_chg_pwd_view@res_users',
                      showCaption: true,
                      showIcon: true,
                      id: 'u4fbe170',
                    },
                  ],
                  appDataEntityId: 'ehrapp.res_users',
                  uniqueTag: 'res_users__Auto12032820',
                  name: '用户实体主视图界面行为组',
                  id: 'auto12032820',
                },
                valid: true,
                itemType: 'ITEMS',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            caption: '更多',
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-cog',
              glyph: 'xf013@FontAwesome',
            },
            tooltip: '更多',
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'FORM',
        codeName: 'main_viewtoolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'ehrapp.res_users',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_viewtoolbar',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveandnewaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'sx-tb-saveandnew',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'FORM',
        codeName: 'main_viewtoolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'ehrapp.res_users',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'main_viewtoolbar1',
      },
      {
        dedrbarGroups: [
          {
            caption: '主视图',
            name: '主视图',
            id: 'af1610e8f121d6b4dc0',
          },
        ],
        showTitle: true,
        dataRelationTag: 'DataRelation',
        editItemCapLanguageRes: {
          lanResTag: 'DE.LNAME.RES_USERS',
        },
        editItemCaption: '用户',
        appCounterRefId: '19d56d3b9adced3ba6d1adbfedd632e8',
        dedrctrlItems: [
          {
            dedrbarGroupId: 'af1610e8f121d6b4dc0',
            caption: '群组',
            counterId: 'groups_count',
            appViewId: 'ehrapp.res_groupsmulti_data_view_user',
            navigateParams: [
              {
                key: 'user_id',
                value: 'res_users',
                id: 'user_id',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-users',
              glyph: 'xf0c0@FontAwesome',
            },
            id: 'groups',
          },
          {
            dedrbarGroupId: 'af1610e8f121d6b4dc0',
            caption: '模型访问',
            appViewId: 'ehrapp.ir_model_accessmulti_data_view',
            sysImage: {
              cssClass: 'fa fa-list-ul',
              glyph: 'xf0ca@FontAwesome',
            },
            id: 'model_access',
          },
          {
            dedrbarGroupId: 'af1610e8f121d6b4dc0',
            caption: '记录规则',
            appViewId: 'ehrapp.ir_rulemulti_data_view',
            sysImage: {
              cssClass: 'fa fa-list-ul',
              glyph: 'xf0ca@FontAwesome',
            },
            id: 'rules',
          },
          {
            dedrbarGroupId: 'af1610e8f121d6b4dc0',
            caption: '员工',
            appViewId: 'ehrapp.hr_employeemain_view',
            sysImage: {
              cssClass: 'fa fa-users',
              glyph: 'xf0c0@FontAwesome',
            },
            id: 'emp',
          },
        ],
        uniqueTag: 'res_usersmain_view__drbar',
        hideEditItem: true,
        autoLoad: true,
        showBusyIndicator: true,
        appCounterRefs: [
          {
            appCounter: {
              codeName: 'user_counter',
              counterType: 'DEDR',
              getAppDEActionId: 'user_counter',
              appDataEntityId: 'ehrapp.res_users',
              timer: 60000,
              uniqueTag: 'user_counter',
              name: '用户计数器',
              id: 'ehrapp.user_counter',
            },
            refMode: {
              srfdeid: 'RES_USERS',
            },
            tag: '19d56d3b9adced3ba6d1adbfedd632e8',
            uniqueTag: 'user_counter',
            id: '19d56d3b9adced3ba6d1adbfedd632e8',
          },
        ],
        codeName: 'DataRelation',
        controlStyle: 'ODOO_DRBAR',
        controlType: 'DRBAR',
        appDataEntityId: 'ehrapp.res_users',
        controlParam: {
          id: 'drbar',
        },
        sysPFPluginId: 'odoo_drbar',
        modelId: '655b891a1ea2964bb3de010f3dfe4b07',
        modelType: 'PSDEDRBAR',
        name: 'drbar',
        id: 'datarelation',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ehrapp.res_users',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ehrapp.res_users',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ehrapp.res_users',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ehrapp.res_users',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ehrapp.res_users',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ehrapp.res_users',
          id: 'update',
        },
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'TOP',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'name',
                        editor: {
                          maxLength: 200,
                          showMaxLength: true,
                          editorParams: {
                            ISAUTO: 'true',
                          },
                          editorType: 'TEXTAREA',
                          placeHolder: 'e.g. John Doe',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'name',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.RES_USERS.NAME',
                        },
                        caption: '名称',
                        codeName: 'name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'name',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        inputTip: '登录系统用户名',
                        labelPos: 'TOP',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'login',
                        editor: {
                          maxLength: 500,
                          editorType: 'TEXTBOX',
                          placeHolder: '例如：email@yourcompany.com',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'login',
                        },
                        enableInputTip: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.RES_USERS.LOGIN',
                        },
                        caption: '电子邮件地址',
                        codeName: 'login',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'login',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 100,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'partner_name',
                        editor: {
                          linkAppViewId: 'ehrapp.res_partnermain_view',
                          enableLinkView: true,
                          singleSelect: true,
                          forceSelection: true,
                          valueItemName: 'partner_id',
                          editorParams: {
                            EDITABLE: 'FALSE',
                            LINKVIEW: 'TRUE',
                            AC: 'FALSE',
                            TRIGGER: 'FALSE',
                            PICKUPVIEW: 'FALSE',
                          },
                          editorType: 'PICKEREX_LINKONLY',
                          editorItems: [
                            {
                              id: 'partner_id',
                            },
                          ],
                          valueType: 'SIMPLE',
                          id: 'partner_name',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.RES_USERS.PARTNER_ID',
                        },
                        caption: '相关合作伙伴',
                        codeName: 'partner_name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['partner_id'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'ISNOTNULL',
                                defdname: 'partner_id',
                                logicType: 'SINGLE',
                                name: 'partner_id值不为空(NotNil)',
                                id: 'partner_id值不为空(notnil)',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'partner_name',
                      },
                    ],
                    codeName: 'grouppanel14',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 16,
                      colMD: 16,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel14',
                  },
                  {
                    layout: {
                      dir: 'row-reverse',
                      layout: 'FLEX',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        itemHeight: 120,
                        itemWidth: 120,
                        labelPos: 'NONE',
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'avatar',
                        editor: {
                          maxFileCount: 1,
                          editorHeight: 120,
                          editorParams: {
                            cutShape: 'SQUARE',
                            MAXCOUNT: '1',
                          },
                          editorStyle: 'AVATAR_UPLOAD',
                          editorType: 'PICTURE_ONE',
                          editorWidth: 120,
                          sysPFPluginId: 'avatar_upload',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'avatar',
                        },
                        allowEmpty: true,
                        caption: '头像',
                        codeName: 'avatar',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        id: 'avatar',
                      },
                    ],
                    codeName: 'grouppanel15',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 8,
                      colMD: 8,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel15',
                  },
                ],
                caption: '用户身份',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
              {
                deformTabPages: [
                  {
                    layout: {
                      align: 'flex-start',
                      dir: 'column',
                      layout: 'FLEX',
                    },
                    deformDetails: [
                      {
                        layout: {
                          layout: 'FLEX',
                        },
                        caption: '多家公司',
                        codeName: 'grouppanel1',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'grouppanel1',
                      },
                      {
                        layout: {
                          layout: 'FLEX',
                        },
                        deformDetails: [
                          {
                            appViewId:
                              'ehrapp.res_groups_users_reluser_group_mgr_view',
                            parentDataJO: {
                              srfparentdename: 'RES_USERS',
                              SRFPARENTTYPE: 'CUSTOM',
                            },
                            codeName: 'druipart1',
                            detailStyle: 'DEFAULT',
                            detailType: 'DRUIPART',
                            layoutPos: {
                              grow: 1,
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'druipart1',
                          },
                        ],
                        caption: '权限组',
                        codeName: 'grouppanel2',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'grouppanel2',
                      },
                    ],
                    caption: '访问权限',
                    codeName: 'tabpage1',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'tabpage1',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'tz',
                            editor: {
                              singleSelect: true,
                              appCodeListId: 'ehrapp.base__res_partner_tz',
                              editorType: 'DROPDOWNLIST',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'tz',
                            },
                            allowEmpty: true,
                            needCodeListConfig: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.RES_USERS.TZ',
                            },
                            caption: '时区',
                            codeName: 'tz',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'tz',
                          },
                          {
                            dataType: 9,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'tour_enabled',
                            editor: {
                              editorType: 'SWITCH',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'tour_enabled',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.RES_USERS.TOUR_ENABLED',
                            },
                            caption: '新手入门',
                            codeName: 'tour_enabled',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'tour_enabled',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'notification_type',
                            editor: {
                              appCodeListId:
                                'ehrapp.base__res_users_notification_type',
                              editorType: 'CHECKBOXLIST',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'notification_type',
                            },
                            needCodeListConfig: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.RES_USERS.NOTIFICATION_TYPE',
                            },
                            caption: '通知',
                            codeName: 'notification_type',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'notification_type',
                          },
                          {
                            dataType: 25,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'odoobot_state',
                            editor: {
                              singleSelect: true,
                              appCodeListId:
                                'ehrapp.base__res_users_odoobot_state',
                              editorType: 'DROPDOWNLIST',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'odoobot_state',
                            },
                            allowEmpty: true,
                            needCodeListConfig: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.RES_USERS.ODOOBOT_STATE',
                            },
                            caption: '小秘书状态',
                            codeName: 'odoobot_state',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'odoobot_state',
                          },
                          {
                            dataType: 21,
                            enableCond: 3,
                            itemHeight: 200,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'signature',
                            editor: {
                              editorHeight: 200,
                              editorType: 'HTMLEDITOR',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'signature',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.RES_USERS.SIGNATURE',
                            },
                            caption: '电子邮件签名',
                            codeName: 'signature',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'signature',
                          },
                          {
                            dataType: 25,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'calendar_default_privacy',
                            editor: {
                              singleSelect: true,
                              appCodeListId:
                                'ehrapp.base__res_users_calendar_default_privacy',
                              editorType: 'DROPDOWNLIST',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'calendar_default_privacy',
                            },
                            allowEmpty: true,
                            needCodeListConfig: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.RES_USERS.CALENDAR_DEFAULT_PRIVACY',
                            },
                            caption: '日历默认隐私',
                            codeName: 'calendar_default_privacy',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'calendar_default_privacy',
                          },
                        ],
                        caption: '本地化',
                        codeName: 'group3',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'group3',
                      },
                    ],
                    caption: '首选项',
                    codeName: 'tabpage2',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'tabpage2',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    caption: 'Oauth',
                    codeName: 'tabpage3',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'tabpage3',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            dataType: 9,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'totp_enabled',
                            editor: {
                              editorType: 'SWITCH',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'totp_enabled',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag: 'DEF.LNAME.RES_USERS.TOTP_ENABLED',
                            },
                            caption: '双重身份验证',
                            codeName: 'totp_enabled',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 20,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'totp_enabled',
                          },
                          {
                            actionType: 'UIACTION',
                            buttonStyle: 'DEFAULT',
                            uiactionId: 'editview_refreshaction',
                            tooltip: '邀请使用2FA',
                            uiactionTarget: 'SINGLEKEY',
                            caption: '邀请使用2FA',
                            codeName: 'button1',
                            detailStyle: 'DEFAULT',
                            detailType: 'BUTTON',
                            layoutPos: {
                              colLG: 4,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            sysImage: {
                              cssClass: 'fa fa-refresh',
                              glyph: 'xf021@FontAwesome',
                            },
                            showCaption: true,
                            id: 'button1',
                          },
                          {
                            rawItem: {
                              caption:
                                '双因素认证（“2FA”）是一种双重认证系统 第一个是您的密码，第二个是您从一个专门的移动应用程序获得的代码。 常用的包括 Authy、Google Authenticator 或 Microsoft Authenticator。',
                              halign: 'LEFT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              id: 'rawitem1',
                            },
                            codeName: 'rawitem1',
                            detailStyle: 'DEFAULT',
                            detailType: 'RAWITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'rawitem1',
                          },
                        ],
                        codeName: 'group5',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'group5',
                      },
                    ],
                    caption: '账户安全',
                    codeName: 'tabpage4',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'tabpage4',
                  },
                ],
                codeName: 'tabpanel1',
                detailStyle: 'DEFAULT',
                detailType: 'TABPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'tabpanel1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'partner_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'partner_id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.RES_USERS.PARTNER_ID',
                },
                caption: '相关合作伙伴',
                codeName: 'partner_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'partner_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.RES_USERS.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '用户信息',
            codeName: 'formpage_all',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage_all',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'Main',
        controlType: 'FORM',
        logicName: '用户实体主视图_表单',
        appDataEntityId: 'ehrapp.res_users',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: 'd6e385cf038daf90c9e0c0ae09ed3a7b',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ehrapp.res_users.main',
      },
      {
        codeName: 'main_viewdatainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ehrapp.res_users',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_viewdatainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.RES_USERS',
        },
        caption: '用户',
        codeName: 'main_viewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ehrapp.res_users',
        controlParam: {},
        name: 'captionbar',
        id: 'main_viewcaptionbar',
      },
    ],
    codeName: 'main_view_layout1',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_new_没有评论区',
    appDataEntityId: 'ehrapp.res_users',
    controlLogics: [
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", async  (state, isTrusted )=> {\r\n    console.log("");\r\n    const data = view.getController("form").getData()[0];\r\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\r\n});\r\n\r\nconst topContext = view.context;\r\nconst appEntityId = view.model.appDataEntityId;\r\nconst entityName = appEntityId.split(\'.\').pop();\r\nconst bExist = topContext[entityName];\r\nconst drbar = view.getCtrl("DRBAR", "drbar");\r\nif(!bExist){\r\n    drbar.disabled({ mode: \'BLANK\' })\r\n    //  drbar.disabled({ mode: \'MASK\' })\r\n\r\n}\r\n\r\n',
        triggerType: 'CTRLEVENT',
        id: 'logic1',
      },
      {
        eventNames: 'onCreated',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "view.ctx.evt.on('onRegister', (name, ctrl) => {\r\n   if (name === 'drbar') {\r\n      const topContext = view.context;\r\n      const appEntityId = view.model.appDataEntityId;\r\n      const entityName = appEntityId.split('.').pop();\r\n      const bExist = topContext[entityName];\r\n      if(!bExist){\r\n         ctrl?.disableCounter()\r\n      }\r\n   }\r\n})",
        triggerType: 'CTRLEVENT',
        id: 'logic2',
      },
    ],
    controlParam: {},
    modelId: '3ea3e353274bcb7a2bf0fee66c7d91cf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout1',
  },
  title: '用户信息',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'f14e8c2e72d048a6655978ccc0b703db',
  modelType: 'PSAPPDEVIEW',
  name: 'res_usersmain_view',
  id: 'ehrapp.res_usersmain_view',
};
