export default {
  gridRowActiveMode: 2,
  enableRowEdit: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'grid_view_nested',
  deviewId: '11b6f763fa23987232cf19f8cde449ba',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RESOURCE_CALENDAR_ATTENDANCE',
  },
  caption: '工作细节',
  codeName: 'resource_calendar_attendancegrid_view_nested',
  appDataEntityId: 'ehrapp.resource_calendar_attendance',
  viewLayoutPanel: {
    layoutBodyOnly: true,
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                  spacingLeft: 'OUTERLARGE',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'ehrapp.resource_calendar_attendanceeditview',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'ehrapp.resource_calendar_attendanceeditview',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'ehrapp.resource_calendar_attendanceeditview',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'ehrapp.resource_calendar_attendanceeditview',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '工作细节编辑视图',
        refAppViewId: 'ehrapp.resource_calendar_attendanceeditview',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '工作细节编辑视图',
        refAppViewId: 'ehrapp.resource_calendar_attendanceeditview',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'name',
            excelCaption: '名称',
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_ATTENDANCE.NAME',
            },
            caption: '名称',
            codeName: 'name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 300,
            widthUnit: 'PX',
            enableSort: true,
            id: 'name',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'dayofweek',
            excelCaption: '星期',
            appCodeListId:
              'ehrapp.resource__resource_calendar_attendance_dayofweek',
            appDEFieldId: 'dayofweek',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_ATTENDANCE.DAYOFWEEK',
            },
            caption: '星期',
            codeName: 'dayofweek',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 1,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'dayofweek',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'day_period',
            excelCaption: '日期',
            appCodeListId:
              'ehrapp.resource__resource_calendar_attendance_day_period',
            appDEFieldId: 'day_period',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_ATTENDANCE.DAY_PERIOD',
            },
            caption: '日期',
            codeName: 'day_period',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            id: 'day_period',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'hour_from',
            excelCaption: '工作起始',
            appDEFieldId: 'hour_from',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_ATTENDANCE.HOUR_FROM',
            },
            caption: '工作起始',
            codeName: 'hour_from',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'hour_from',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'hour_to',
            excelCaption: '工作截止',
            appDEFieldId: 'hour_to',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_ATTENDANCE.HOUR_TO',
            },
            caption: '工作截止',
            codeName: 'hour_to',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            id: 'hour_to',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'duration_days',
            excelCaption: '持续时间 (天)',
            appDEFieldId: 'duration_days',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_ATTENDANCE.DURATION_DAYS',
            },
            caption: '持续时间 (天)',
            codeName: 'duration_days',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            hideDefault: true,
            id: 'duration_days',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'date_from',
            excelCaption: '起始日期',
            appDEFieldId: 'date_from',
            valueFormat: 'YYYY-MM-DD',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_ATTENDANCE.DATE_FROM',
            },
            caption: '起始日期',
            codeName: 'date_from',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            hideDefault: true,
            id: 'date_from',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'date_to',
            excelCaption: '结束日期',
            appDEFieldId: 'date_to',
            valueFormat: 'YYYY-MM-DD',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_ATTENDANCE.DATE_TO',
            },
            caption: '结束日期',
            codeName: 'date_to',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            hideDefault: true,
            id: 'date_to',
          },
          {
            clconvertMode: 'FRONT',
            dataItemName: 'week_type',
            excelCaption: '周数',
            appCodeListId:
              'ehrapp.resource__resource_calendar_attendance_week_type',
            appDEFieldId: 'week_type',
            valueType: 'SIMPLE',
            enableRowEdit: true,
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR_ATTENDANCE.WEEK_TYPE',
            },
            caption: '周数',
            codeName: 'week_type',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            enableSort: true,
            hideDefault: true,
            id: 'week_type',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'name',
          },
          {
            appDEFieldId: 'dayofweek',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'dayofweek',
          },
          {
            appDEFieldId: 'day_period',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'day_period',
          },
          {
            appDEFieldId: 'hour_from',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'hour_from',
          },
          {
            appDEFieldId: 'hour_to',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'hour_to',
          },
          {
            appDEFieldId: 'duration_days',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'duration_days',
          },
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'date_from',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'date_from',
          },
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'date_to',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'date_to',
          },
          {
            appDEFieldId: 'week_type',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'week_type',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'calendar_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'calendar_id',
          },
          {
            appDEFieldId: 'resource_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'resource_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '名称',
            codeName: 'name',
            enableCond: 3,
            appDEFieldId: 'name',
            editor: {
              maxLength: 200,
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'name',
            },
            allowEmpty: true,
            id: 'name',
          },
          {
            caption: '星期',
            codeName: 'dayofweek',
            enableCond: 3,
            appDEFieldId: 'dayofweek',
            editor: {
              singleSelect: true,
              appCodeListId:
                'ehrapp.resource__resource_calendar_attendance_dayofweek',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'dayofweek',
            },
            needCodeListConfig: true,
            id: 'dayofweek',
          },
          {
            caption: '日期',
            codeName: 'day_period',
            enableCond: 3,
            appDEFieldId: 'day_period',
            editor: {
              singleSelect: true,
              appCodeListId:
                'ehrapp.resource__resource_calendar_attendance_day_period',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'day_period',
            },
            needCodeListConfig: true,
            id: 'day_period',
          },
          {
            caption: '工作起始',
            codeName: 'hour_from',
            enableCond: 3,
            appDEFieldId: 'hour_from',
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'hour_from',
            },
            id: 'hour_from',
          },
          {
            caption: '工作截止',
            codeName: 'hour_to',
            enableCond: 3,
            appDEFieldId: 'hour_to',
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'hour_to',
            },
            id: 'hour_to',
          },
          {
            caption: '持续时间 (天)',
            codeName: 'duration_days',
            enableCond: 3,
            appDEFieldId: 'duration_days',
            editor: {
              editorType: 'TEXTBOX',
              valueType: 'SIMPLE',
              editable: true,
              id: 'duration_days',
            },
            allowEmpty: true,
            id: 'duration_days',
          },
          {
            caption: '起始日期',
            codeName: 'date_from',
            enableCond: 3,
            appDEFieldId: 'date_from',
            editor: {
              dateTimeFormat: 'YYYY-MM-DD',
              editorParams: {
                TIMEFMT: 'YYYY-MM-DD',
              },
              editorType: 'DATEPICKEREX_NOTIME',
              valueType: 'SIMPLE',
              editable: true,
              id: 'date_from',
            },
            allowEmpty: true,
            id: 'date_from',
          },
          {
            caption: '结束日期',
            codeName: 'date_to',
            enableCond: 3,
            appDEFieldId: 'date_to',
            editor: {
              dateTimeFormat: 'YYYY-MM-DD',
              editorParams: {
                TIMEFMT: 'YYYY-MM-DD',
              },
              editorType: 'DATEPICKEREX_NOTIME',
              valueType: 'SIMPLE',
              editable: true,
              id: 'date_to',
            },
            allowEmpty: true,
            id: 'date_to',
          },
          {
            caption: '周数',
            codeName: 'week_type',
            enableCond: 3,
            appDEFieldId: 'week_type',
            editor: {
              singleSelect: true,
              appCodeListId:
                'ehrapp.resource__resource_calendar_attendance_week_type',
              editorType: 'DROPDOWNLIST',
              valueType: 'SIMPLE',
              editable: true,
              id: 'week_type',
            },
            allowEmpty: true,
            needCodeListConfig: true,
            id: 'week_type',
          },
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enableRowEdit: true,
        enableRowEditOrder: true,
        enableRowNew: true,
        singleSelect: true,
        navViewPos: 'NONE',
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ehrapp.resource_calendar_attendance',
          id: 'create',
        },
        fetchControlAction: {
          appDEMethodId: 'fetch_default',
          appDataEntityId: 'ehrapp.resource_calendar_attendance',
          id: 'fetch',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ehrapp.resource_calendar_attendance',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ehrapp.resource_calendar_attendance',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ehrapp.resource_calendar_attendance',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ehrapp.resource_calendar_attendance',
          id: 'update',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'EditMain',
        controlType: 'GRID',
        logicName: '行编辑主表格',
        appDataEntityId: 'ehrapp.resource_calendar_attendance',
        controlLogics: [
          {
            eventNames: 'onMounted',
            logicTag: 'grid',
            logicType: 'SCRIPT',
            scriptCode:
              'var gridCtrl = view.getCtrl("GRID", "grid");\nif (gridCtrl) {\n  gridCtrl.state.rowEditOpen=true;\n}',
            triggerType: 'CTRLEVENT',
            id: 'logic_row_edit_open',
          },
        ],
        controlParam: {
          id: 'grid',
        },
        modelId: '60b7da8ec861e6df5d2b3f055260fa97',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'ehrapp.resource_calendar_attendance.editmain',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'gridview_newrowaction',
            valid: true,
            caption: '添加行',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-plus',
              glyph: 'xf067@FontAwesome',
            },
            tooltip: '添加行',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'grid_view_nestedtoolbar',
        controlType: 'TOOLBAR',
        logicName: '工作细节实体表格视图(嵌套资源工作时间实体)_工具栏',
        appDataEntityId: 'ehrapp.resource_calendar_attendance',
        controlParam: {
          id: 'toolbar',
        },
        modelId: 'd3efa0a306621715749a23d7a35fc649',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'grid_view_nestedtoolbar',
      },
      {
        searchButtonStyle: 'DEFAULT',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'Main2',
        controlType: 'SEARCHFORM',
        logicName: '工作细节实体表格视图(嵌套资源工作时间实体)_搜索表单',
        appDataEntityId: 'ehrapp.resource_calendar_attendance',
        controlParam: {
          id: 'searchform',
        },
        modelId: '7492d79fc9eaa95c88f2c72f25c90f58',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'ehrapp.resource_calendar_attendance.main2',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'ehrapp.resource_calendar_attendance',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.RESOURCE_CALENDAR_ATTENDANCE',
        },
        caption: '工作细节',
        codeName: 'grid_view_nestedcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ehrapp.resource_calendar_attendance',
        controlParam: {},
        name: 'captionbar',
        id: 'grid_view_nestedcaptionbar',
      },
    ],
    codeName: 'Auto94410878',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '表格视图布局_工具栏置底部',
    appDataEntityId: 'ehrapp.resource_calendar_attendance',
    controlParam: {},
    modelId: 'a13eeb1a845a3db03d246911b7ccb2bf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'auto94410878',
  },
  title: '工作细节',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: 'e7a9014be4ef0a5fbf7c4f611932cd6f',
  modelType: 'PSAPPDEVIEW',
  name: 'resource_calendar_attendancegrid_view_nested',
  id: 'ehrapp.resource_calendar_attendancegrid_view_nested',
};
