export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'main_view',
  deviewId: 'd355249a6f9094a3a3d0351ec6d88064',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RESOURCE_CALENDAR',
  },
  caption: '工作时间表',
  codeName: 'resource_calendarmain_view',
  appDataEntityId: 'ehrapp.resource_calendar',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'name',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar2',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 8,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container3',
              },
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                dataRegionType: 'INHERIT',
                caption: '面板容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  grow: 4,
                  shrink: 1,
                  layout: 'SIMPLEFLEX',
                },
                id: 'container4',
              },
            ],
            predefinedType: 'CONTAINER_GRID',
            layout: {
              layout: 'SIMPLEFLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '栅格容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container_grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_viewtoolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'ehrapp.resource_calendar',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_viewtoolbar',
      },
      {
        dedrbarGroups: [
          {
            caption: '默认',
            name: '默认',
            id: 'a00e132c6e7249ed96b',
          },
        ],
        showTitle: true,
        dataRelationTag: 'DataRelation',
        editItemCapLanguageRes: {
          lanResTag: 'DE.LNAME.RESOURCE_CALENDAR',
        },
        editItemCaption: '资源工作时间',
        dedrctrlItems: [
          {
            dedrbarGroupId: 'a00e132c6e7249ed96b',
            caption: '公开到',
            sysImage: {
              cssClass: 'fa fa-sun-o',
              glyph: 'xf185@FontAwesome',
            },
            id: 'leaves_info',
          },
          {
            dedrbarGroupId: 'a00e132c6e7249ed96b',
            caption: '休息时间',
            sysImage: {
              cssClass: 'fa fa-plane',
              glyph: 'xf072@FontAwesome',
            },
            id: 'leaves_info1',
          },
          {
            dedrbarGroupId: 'a00e132c6e7249ed96b',
            caption: '工作资源',
            appViewId: 'ehrapp.resource_resourcemulti_data_view',
            sysImage: {
              cssClass: 'fa fa-cogs',
              glyph: 'xf085@FontAwesome',
            },
            id: 'resources_info',
          },
        ],
        uniqueTag: 'resource_calendarmain_view__drbar',
        hideEditItem: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'DataRelation',
        controlStyle: 'ODOO_DRBAR',
        controlType: 'DRBAR',
        appDataEntityId: 'ehrapp.resource_calendar',
        controlParam: {
          id: 'drbar',
        },
        sysPFPluginId: 'odoo_drbar',
        modelId: '6d758b32938785acb243e3e68f07ee1e',
        modelType: 'PSDEDRBAR',
        name: 'drbar',
        id: 'datarelation',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'ehrapp.resource_calendar',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'ehrapp.resource_calendar',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'ehrapp.resource_calendar',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'ehrapp.resource_calendar',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'ehrapp.resource_calendar',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'ehrapp.resource_calendar',
          id: 'update',
        },
        deformItemUpdates: [
          {
            codeName: 'update_hours_per_day',
            defiupdateDetails: [
              {
                id: 'hours_per_day',
              },
            ],
            scriptCode:
              'if(data.flexible_hours == 1){\r\n    return;\r\n}\r\n// 获取应用实例\r\nconst app = ibiz.hub.getApp(context.srfappid);\r\n// 获取指定实体服务\r\nconst deService = await app.deService.getService(\r\n    context,\r\n    "ehrapp.resource_calendar_attendance", // 实体标识\r\n);\r\n// 获取实体所有缓存数据\r\nvar list = deService.local.getList();\r\n//过滤满足业务的数据\r\nvar list1=list.filter(attendance => \r\n             attendance.day_period !== \'lunch\' &&\r\n            !attendance.date_from && !attendance.date_to &&\r\n            !attendance.resource_id && !attendance.display_type);\r\n\r\nif(list1.length == 0){\r\n    data.hours_per_day=0;\r\n}else{\r\n    let hourCount = 0;\r\n    //总小时数\r\n    for (const attendance of list1) {\r\n        hourCount += attendance.hour_to - attendance.hour_from;\r\n    }\r\n   //总天数\r\n    let numberOfDays;\r\n    if (data.two_weeks_calendar) {\r\n        // 初始化一个对象来存储每周类型对应的天数\r\n        const weekTypeGroups = {};\r\n        // 遍历所有日历项\r\n        for (const cal of list1) {\r\n            // 如果该周类型不存在则初始化空集合\r\n            if (!weekTypeGroups[cal.week_type]) {\r\n                weekTypeGroups[cal.week_type] = new Set();\r\n            }\r\n            // 添加当前日期到对应周类型的集合\r\n            weekTypeGroups[cal.week_type].add(cal.dayofweek);\r\n        }\r\n        \r\n        // 计算所有周类型的总天数\r\n        let totalDays = 0;\r\n        for (const type in weekTypeGroups) {\r\n            totalDays += weekTypeGroups[type].size;\r\n        }\r\n        numberOfDays = totalDays;\r\n    } else {\r\n            numberOfDays = new Set(list1.map(cal => cal.dayofweek)).size;\r\n    }   \r\n    if (numberOfDays === 0) {\r\n        data.hours_per_day=0;\r\n    }\r\n    const average = hourCount / numberOfDays;\r\n    data.hours_per_day=average;\r\n}',
            customCode: true,
            showBusyIndicator: true,
            id: 'update_hours_per_day',
          },
        ],
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'name',
                    editor: {
                      maxLength: 200,
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR.NAME',
                    },
                    caption: '名称',
                    codeName: 'name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'name',
                  },
                  {
                    createDV: '0',
                    dataType: 9,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'flexible_hours',
                    deformItemUpdateId: 'update_hours_per_day',
                    editor: {
                      editorType: 'CHECKBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'flexible_hours',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR.FLEXIBLE_HOURS',
                    },
                    caption: '灵活时间',
                    codeName: 'flexible_hours',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'flexible_hours',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'company_name',
                    editor: {
                      linkAppViewId: 'ehrapp.res_companymain_view',
                      enablePickupView: true,
                      singleSelect: true,
                      pickupAppViewId: 'ehrapp.res_companypickupview',
                      handlerType: 'PickupText',
                      appDEACModeId: 'default',
                      appDEDataSetId: 'fetch_default',
                      appDataEntityId: 'ehrapp.res_company',
                      enableAC: true,
                      forceSelection: true,
                      showTrigger: true,
                      valueItemName: 'company_id',
                      editorParams: {
                        AC: 'TRUE',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'PICKER',
                      editorItems: [
                        {
                          id: 'company_id',
                        },
                      ],
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'company_name',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR.COMPANY_ID',
                    },
                    caption: '公司',
                    codeName: 'company_name',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'company_name',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 7,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'full_time_required_hours',
                        editor: {
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'full_time_required_hours1',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag:
                            'DEF.LNAME.RESOURCE_CALENDAR.FULL_TIME_REQUIRED_HOURS',
                        },
                        caption: '公司全职',
                        codeName: 'full_time_required_hours1',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['flexible_hours'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'flexible_hours',
                                value: '0',
                                logicType: 'SINGLE',
                                id: 'flexible_hours等于(=) 0',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'full_time_required_hours1',
                      },
                      {
                        dataType: 7,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'full_time_required_hours',
                        editor: {
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'full_time_required_hours',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag:
                            'DEF.LNAME.RESOURCE_CALENDAR.FULL_TIME_REQUIRED_HOURS',
                        },
                        caption: '周小时／周',
                        codeName: 'full_time_required_hours',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        defdgroupLogics: [
                          {
                            logicCat: 'PANELVISIBLE',
                            relatedDetailNames: ['flexible_hours'],
                            groupOP: 'AND',
                            defdlogics: [
                              {
                                condOP: 'EQ',
                                defdname: 'flexible_hours',
                                value: '1',
                                logicType: 'SINGLE',
                                id: 'flexible_hours等于(=) 1',
                              },
                            ],
                            logicType: 'GROUP',
                          },
                        ],
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'full_time_required_hours',
                      },
                    ],
                    codeName: 'grouppanel2',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 4,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel2',
                  },
                  {
                    rawItem: {
                      caption: '小时/周',
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      contentType: 'RAW',
                      id: 'rawitem3',
                    },
                    codeName: 'rawitem3',
                    detailStyle: 'DEFAULT',
                    detailType: 'RAWITEM',
                    layoutPos: {
                      colLG: 8,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'rawitem3',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    editor: {
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'formitem1',
                    },
                    allowEmpty: true,
                    caption: '时区',
                    codeName: 'formitem1',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'formitem1',
                  },
                  {
                    dataType: 7,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'hours_per_day',
                    editor: {
                      editorType: 'TEXTBOX',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'hours_per_day',
                    },
                    allowEmpty: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR.HOURS_PER_DAY',
                    },
                    caption: '每天平均小时数',
                    codeName: 'hours_per_day',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    defdgroupLogics: [
                      {
                        logicCat: 'ITEMENABLE',
                        relatedDetailNames: ['flexible_hours'],
                        groupOP: 'AND',
                        defdlogics: [
                          {
                            condOP: 'EQ',
                            defdname: 'flexible_hours',
                            value: '1',
                            logicType: 'SINGLE',
                            id: 'flexible_hours等于(=) 1',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    layoutPos: {
                      colLG: 12,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'hours_per_day',
                  },
                ],
                caption: '资源工作时间基本信息',
                codeName: 'group1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group1',
              },
              {
                deformTabPages: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        maskMode: 0,
                        appViewId:
                          'ehrapp.resource_calendar_attendancegrid_view_nested',
                        deformItemUpdateId: 'update_hours_per_day',
                        parentDataJO: {
                          SRFPARENTTYPE: 'DER1N',
                          srfparentdename: 'RESOURCE_CALENDAR',
                          srfparentmode:
                            'DER1N_RESOURCE_CALENDAR_ATTENDANCE_RESOURCE_CALENDAR_CALENDAR_ID',
                          srfparentdefname: 'CALENDAR_ID',
                          SRFDER1NID:
                            'DER1N_RESOURCE_CALENDAR_ATTENDANCE_RESOURCE_CALENDAR_CALENDAR_ID',
                        },
                        codeName: 'druipart1',
                        detailStyle: 'DEFAULT',
                        detailType: 'DRUIPART',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'druipart1',
                      },
                    ],
                    caption: '工作时间',
                    codeName: 'tabpage1',
                    detailStyle: 'DEFAULT',
                    detailType: 'TABPAGE',
                    showCaption: true,
                    id: 'tabpage1',
                  },
                ],
                codeName: 'tabpanel1',
                detailStyle: 'DEFAULT',
                detailType: 'TABPANEL',
                defdgroupLogics: [
                  {
                    logicCat: 'PANELVISIBLE',
                    relatedDetailNames: ['flexible_hours'],
                    groupOP: 'AND',
                    defdlogics: [
                      {
                        condOP: 'EQ',
                        defdname: 'flexible_hours',
                        value: '0',
                        logicType: 'SINGLE',
                        id: 'flexible_hours等于(=) 0',
                      },
                    ],
                    logicType: 'GROUP',
                  },
                ],
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'tabpanel1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'company_id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'company_id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR.COMPANY_ID',
                },
                caption: '公司',
                codeName: 'company_id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'company_id',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '基本信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'Main',
        controlType: 'FORM',
        logicName: '资源工作时间实体主视图_表单',
        appDataEntityId: 'ehrapp.resource_calendar',
        controlParam: {
          ctrlParams: {
            EDITMODE: 'hover',
          },
          id: 'form',
        },
        modelId: '6d385f924a494c5b24b9e0813228f236',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'ehrapp.resource_calendar.main',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveandnewaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.EDITVIEW.SAVEANDNEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'sx-tb-saveandnew',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.EDITVIEW.SAVEANDNEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_viewtoolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'ehrapp.resource_calendar',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'main_viewtoolbar1',
      },
      {
        codeName: 'main_viewdatainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'ehrapp.resource_calendar',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_viewdatainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.RESOURCE_CALENDAR',
        },
        caption: '工作时间表',
        codeName: 'main_viewcaptionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'ehrapp.resource_calendar',
        controlParam: {},
        name: 'captionbar',
        id: 'main_viewcaptionbar',
      },
    ],
    codeName: 'main_view_layout1',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_new_没有评论区',
    appDataEntityId: 'ehrapp.resource_calendar',
    controlLogics: [
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
      {
        eventNames: 'onMounted',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", async  (state, isTrusted )=> {\r\n    console.log("");\r\n    const data = view.getController("form").getData()[0];\r\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\r\n});\r\n\r\nconst topContext = view.context;\r\nconst appEntityId = view.model.appDataEntityId;\r\nconst entityName = appEntityId.split(\'.\').pop();\r\nconst bExist = topContext[entityName];\r\nconst drbar = view.getCtrl("DRBAR", "drbar");\r\nif(!bExist){\r\n    drbar.disabled({ mode: \'BLANK\' })\r\n    //  drbar.disabled({ mode: \'MASK\' })\r\n\r\n}\r\n\r\n',
        triggerType: 'CTRLEVENT',
        id: 'logic1',
      },
      {
        eventNames: 'onCreated',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "view.ctx.evt.on('onRegister', (name, ctrl) => {\r\n   if (name === 'drbar') {\r\n      const topContext = view.context;\r\n      const appEntityId = view.model.appDataEntityId;\r\n      const entityName = appEntityId.split('.').pop();\r\n      const bExist = topContext[entityName];\r\n      if(!bExist){\r\n         ctrl?.disableCounter()\r\n      }\r\n   }\r\n})",
        triggerType: 'CTRLEVENT',
        id: 'logic2',
      },
    ],
    controlParam: {},
    modelId: '3ea3e353274bcb7a2bf0fee66c7d91cf',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout1',
  },
  title: '资源工作时间',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'e394c42feea0a115703d7517edf5eccc',
  modelType: 'PSAPPDEVIEW',
  name: 'resource_calendarmain_view',
  id: 'ehrapp.resource_calendarmain_view',
};
