export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: '78815e91a0f8a2193391b32aeafc84cc',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.RESOURCE_CALENDAR',
  },
  caption: '资源工作时间',
  codeName: 'resource_calendarPickupGridView',
  appDataEntityId: 'ehrapp.resource_calendar',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '工时',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR.NAME',
          },
          caption: '工时',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'company_name',
          excelCaption: '公司',
          appDEFieldId: 'company_name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.RESOURCE_CALENDAR.COMPANY_ID',
          },
          caption: '公司',
          codeName: 'company_name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 1,
          widthUnit: 'PX',
          enableSort: true,
          id: 'company_name',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'company_name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'company_name',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'company_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'company_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'ehrapp.resource_calendar',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'ehrapp.resource_calendar',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'ehrapp.resource_calendar',
      controlParam: {
        id: 'grid',
      },
      modelId: '6d385f924a494c5b24b9e0813228f236',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'ehrapp.resource_calendar.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.RESOURCE_CALENDAR.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'Default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'ehrapp.resource_calendar',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'b676606022d6ec1d44be4797a9c06203',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'ehrapp.resource_calendar.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'ehrapp.resource_calendar',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.RESOURCE_CALENDAR',
      },
      caption: '资源工作时间',
      codeName: 'PickupGridViewcaptionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'ehrapp.resource_calendar',
      controlParam: {},
      name: 'captionbar',
      id: 'pickupgridviewcaptionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'ehrapp.resource_calendar',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '资源工作时间选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'acba6428082ca18e3c8f017f12141c84',
  modelType: 'PSAPPDEVIEW',
  name: 'resource_calendarPickupGridView',
  id: 'ehrapp.resource_calendarpickupgridview',
};
