package cn.ibizlab.hr.logic.hr_candidate_filter_detaillogic.filter_count;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_candidate_filter_detail hr_candidate_filter_detailfilter_countdefault;
        global cn.ibizlab.core.hr.service.Ihr_candidate_filter_detailService iBzSysHr_candidate_filter_detailDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_candidate_filter_detailfilter_countbegin"
            when
            then
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "hr_candidate_filter_detailfilter_countrawsfcode1"
            when
            then
                        update(hr_candidate_filter_detailfilter_countdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "hr_candidate_filter_detailfilter_countend1"
            when
            then
                        update(hr_candidate_filter_detailfilter_countdefault);//更新fact中变量值
            end