package cn.ibizlab.attendance.logic.attendance_clock_in_recordlogic.record;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_clock_in_record attendance_clock_in_recordrecorddefault;
                global cn.ibizlab.core.employee_management.domain.employee attendance_clock_in_recordrecordemp_page;
                global cn.ibizlab.core.employee_management.domain.employee attendance_clock_in_recordrecordemp_temp;
                global cn.ibizlab.core.attendance.domain.attendance_clock_in_record attendance_clock_in_recordrecordnewrecords;
                    global cn.ibizlab.core.employee_management.service.IemployeeService employeeservice;
        global cn.ibizlab.core.attendance.service.Iattendance_clock_in_recordService iBzSysAttendance_clock_in_recordDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_clock_in_recordrecordbegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam_01"
            ruleflow-group "attendance_clock_in_recordrecorddebugparam_01"
            when
            then
                        update(attendance_clock_in_recordrecorddefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_page);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_temp);//更新fact中变量值
                        update(attendance_clock_in_recordrecordnewrecords);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "attendance_clock_in_recordrecordrawsfcode_01"
            when
            then
                        update(attendance_clock_in_recordrecorddefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_page);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_temp);//更新fact中变量值
                        update(attendance_clock_in_recordrecordnewrecords);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "attendance_clock_in_recordrecordend_01"
            when
            then
                        update(attendance_clock_in_recordrecorddefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_page);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_temp);//更新fact中变量值
                        update(attendance_clock_in_recordrecordnewrecords);//更新fact中变量值
            end

            //逻辑处理节点[解析搜索条件]
            rule "rawsfcode2"
            ruleflow-group "attendance_clock_in_recordrecordrawsfcode2"
            when
            then
                        update(attendance_clock_in_recordrecorddefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_page);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_temp);//更新fact中变量值
                        update(attendance_clock_in_recordrecordnewrecords);//更新fact中变量值
            end

            //逻辑处理节点[查询人员]
            rule "dedataset1"
            ruleflow-group "attendance_clock_in_recordrecorddedataset1"
            when
            then
                        update(attendance_clock_in_recordrecorddefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_page);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_temp);//更新fact中变量值
                        update(attendance_clock_in_recordrecordnewrecords);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "attendance_clock_in_recordrecordloopsubcall1"
            when
            then
                        update(attendance_clock_in_recordrecorddefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_page);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_temp);//更新fact中变量值
                        update(attendance_clock_in_recordrecordnewrecords);//更新fact中变量值
            end

            //逻辑处理节点[获取打卡记录]
            rule "rawsfcode1"
            ruleflow-group "attendance_clock_in_recordrecordrawsfcode1"
            when
            then
                        update(attendance_clock_in_recordrecorddefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_page);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_temp);//更新fact中变量值
                        update(attendance_clock_in_recordrecordnewrecords);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "attendance_clock_in_recordrecordend1"
            when
            then
                        update(attendance_clock_in_recordrecorddefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_page);//更新fact中变量值
                        update(attendance_clock_in_recordrecordemp_temp);//更新fact中变量值
                        update(attendance_clock_in_recordrecordnewrecords);//更新fact中变量值
            end