package cn.ibizlab.attendance.logic.attendance_clock_in_recordlogic.record_list;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_clock_in_record attendance_clock_in_recordrecord_listdefault;
                global cn.ibizlab.core.attendance.domain.attendance_clock_in_record attendance_clock_in_recordrecord_listpage;
                    global cn.ibizlab.core.attendance.service.Iattendance_clock_in_recordService attendance_clock_in_recordservice;
        global cn.ibizlab.core.attendance.service.Iattendance_clock_in_recordService iBzSysAttendance_clock_in_recordDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_clock_in_recordrecord_listbegin"
            when
            then
            end

            //逻辑处理节点[解析搜索条件]
            rule "rawsfcode1"
            ruleflow-group "attendance_clock_in_recordrecord_listrawsfcode1"
            when
            then
                        update(attendance_clock_in_recordrecord_listdefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecord_listpage);//更新fact中变量值
            end

            //逻辑处理节点[获取打卡记录]
            rule "dedataset1"
            ruleflow-group "attendance_clock_in_recordrecord_listdedataset1"
            when
            then
                        update(attendance_clock_in_recordrecord_listdefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecord_listpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "attendance_clock_in_recordrecord_listend1"
            when
            then
                        update(attendance_clock_in_recordrecord_listdefault);//更新fact中变量值
                        update(attendance_clock_in_recordrecord_listpage);//更新fact中变量值
            end