package cn.ibizlab.hr.logic.hr_applicantlogic.applicant_read;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_applicant hr_applicantapplicant_readdefault;
                    global cn.ibizlab.core.hr.service.Ihr_applicantService hr_applicantservice;
        global cn.ibizlab.core.hr.service.Ihr_applicantService iBzSysHr_applicantDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_applicantapplicant_readbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "hr_applicantapplicant_readend1"
            when
            then
                        update(hr_applicantapplicant_readdefault);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "hr_applicantapplicant_readprepareparam1"
            when
            then
                            hr_applicantapplicant_readdefault.set("activation_status","1");
                        update(hr_applicantapplicant_readdefault);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "hr_applicantapplicant_readdeaction1"
            when
            then
                        hr_applicantservice.update(hr_applicantapplicant_readdefault);
                        update(hr_applicantapplicant_readdefault);//更新fact中变量值
            end