package cn.ibizlab.hr.logic.hr_applicantlogic.favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_applicant hr_applicantfavoritedefault;
                global cn.ibizlab.core.base.domain.favorite hr_applicantfavoritefavorite;
                    global cn.ibizlab.core.base.service.IfavoriteService favoriteservice;
        global cn.ibizlab.core.hr.service.Ihr_applicantService iBzSysHr_applicantDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_applicantfavoritebegin"
            when
            then
            end

            //逻辑处理节点[填充用户标识和收藏业务对象标识]
            rule "prepareparam1"
            ruleflow-group "hr_applicantfavoriteprepareparam1"
            when
            then
                                hr_applicantfavoritefavorite.set("createman",curuser.getSessionParams().get("srfpersonid"));
                            hr_applicantfavoritefavorite.set("ownertype","hr_applicant");
                            hr_applicantfavoritefavorite.set("ownerid",hr_applicantfavoritedefault.get("id"));
                        update(hr_applicantfavoritedefault);//更新fact中变量值
                        update(hr_applicantfavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[生成收藏数据]
            rule "deaction1"
            ruleflow-group "hr_applicantfavoritedeaction1"
            when
            then
                        favoriteservice.save(hr_applicantfavoritefavorite);
                        update(hr_applicantfavoritedefault);//更新fact中变量值
                        update(hr_applicantfavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "hr_applicantfavoriteend1"
            when
            then
                        update(hr_applicantfavoritedefault);//更新fact中变量值
                        update(hr_applicantfavoritefavorite);//更新fact中变量值
            end