package cn.ibizlab.hr.logic.hr_recruitment_stagelogic.disable;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_recruitment_stage hr_recruitment_stagedisabledefault;
                    global cn.ibizlab.core.hr.service.Ihr_recruitment_stageService hr_recruitment_stageservice;
        global cn.ibizlab.core.hr.service.Ihr_recruitment_stageService iBzSysHr_recruitment_stageDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_recruitment_stagedisablebegin"
            when
            then
            end

            //逻辑处理节点[设置状态为停用]
            rule "prepareparam1"
            ruleflow-group "hr_recruitment_stagedisableprepareparam1"
            when
            then
                            hr_recruitment_stagedisabledefault.set("status","0");
                        update(hr_recruitment_stagedisabledefault);//更新fact中变量值
            end

            //逻辑处理节点[更新状态]
            rule "deaction1"
            ruleflow-group "hr_recruitment_stagedisabledeaction1"
            when
            then
                        hr_recruitment_stageservice.update(hr_recruitment_stagedisabledefault);
                        update(hr_recruitment_stagedisabledefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "hr_recruitment_stagedisableend1"
            when
            then
                        update(hr_recruitment_stagedisabledefault);//更新fact中变量值
            end