package cn.ibizlab.hr.logic.hr_examlogic.my_interview_count;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_exam hr_exammy_interview_countdefault;
                global java.util.Map hr_exammy_interview_countresult;
        global cn.ibizlab.core.hr.service.Ihr_examService iBzSysHr_examDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_exammy_interview_countbegin"
            when
            then
            end

            //逻辑处理节点[未完成]
            rule "rawsqlcall_01"
            ruleflow-group "hr_exammy_interview_countrawsqlcall_01"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
    String strSql="select 	COUNT(1) as status_0 from 	hr_exam he where 	he.STATUS = 10 	and he.CREATE_UID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysHr_examDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                hr_exammy_interview_countresult.putAll(entity);
                            }
                        update(hr_exammy_interview_countdefault);//更新fact中变量值
                        update(hr_exammy_interview_countresult);//更新fact中变量值
            end

            //逻辑处理节点[已完成]
            rule "rawsqlcall_02"
            ruleflow-group "hr_exammy_interview_countrawsqlcall_02"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
    String strSql="SELECT COUNT(1) as status_1 FROM hr_exam he  WHERE he.STATUS = 20 and he.CREATE_UID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysHr_examDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                hr_exammy_interview_countresult.putAll(entity);
                            }
                        update(hr_exammy_interview_countdefault);//更新fact中变量值
                        update(hr_exammy_interview_countresult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "hr_exammy_interview_countend_01"
            when
            then
                        update(hr_exammy_interview_countdefault);//更新fact中变量值
                        update(hr_exammy_interview_countresult);//更新fact中变量值
            end