package cn.ibizlab.base.logic.reportlogic.remove_bi_report;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.report reportremove_bi_reportdefault;
                global cn.ibizlab.core.extension.domain.PSSysBIReport reportremove_bi_reportbi_report;
                    global cn.ibizlab.core.extension.service.IPSSysBIReportService pssysbireportservice;
        global cn.ibizlab.core.base.service.IreportService iBzSysReportDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "reportremove_bi_reportbegin"
            when
            then
            end

            //逻辑处理节点[设置id]
            rule "prepareparam1"
            ruleflow-group "reportremove_bi_reportprepareparam1"
            when
            then
                            reportremove_bi_reportbi_report.set("pssysbireportid",reportremove_bi_reportdefault.get("id"));
                        update(reportremove_bi_reportdefault);//更新fact中变量值
                        update(reportremove_bi_reportbi_report);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "reportremove_bi_reportend1"
            when
            then
                        update(reportremove_bi_reportdefault);//更新fact中变量值
                        update(reportremove_bi_reportbi_report);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "reportremove_bi_reportdeaction1"
            when
            then
                        pssysbireportservice.remove(reportremove_bi_reportbi_report.getPssysbireportid());
                        update(reportremove_bi_reportdefault);//更新fact中变量值
                        update(reportremove_bi_reportbi_report);//更新fact中变量值
            end