package cn.ibizlab.resource.logic.resource_calendar_leaveslogic.calcholiday;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.resource.domain.resource_calendar_leaves resource_calendar_leavescalcholidaydefault;
        global cn.ibizlab.core.resource.service.Iresource_calendar_leavesService iBzSysResource_calendar_leavesDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "resource_calendar_leavescalcholidaybegin"
            when
            then
            end