package cn.ibizlab.mail.logic.mail_threadlogic.message_post;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.mail.domain.mail_thread mail_threadmessage_postdefault;
        global cn.ibizlab.core.mail.service.Imail_threadService iBzSysMail_threadDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop