package cn.ibizlab.attendance.logic.attendance_schedulelogic.attendance_schedules;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_schedule attendance_scheduleattendance_schedulesdefault;
                global cn.ibizlab.core.attendance.domain.attendance_schedule attendance_scheduleattendance_schedulesfilter;
                global cn.ibizlab.core.attendance.domain.attendance_schedule attendance_scheduleattendance_schedulesattendance_schedules;
                global cn.ibizlab.core.attendance.domain.attendance_schedule attendance_scheduleattendance_schedulesdata;
                global cn.ibizlab.core.attendance.domain.attendance_schedule attendance_scheduleattendance_schedulestemp;
                    global cn.ibizlab.core.attendance.service.Iattendance_scheduleService attendance_scheduleservice;
        global cn.ibizlab.core.attendance.service.Iattendance_scheduleService iBzSysAttendance_scheduleDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_scheduleattendance_schedulesbegin"
            when
            then
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset_01"
            ruleflow-group "attendance_scheduleattendance_schedulesdedataset_01"
            when
            then
                        update(attendance_scheduleattendance_schedulesdefault);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesfilter);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesattendance_schedules);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesdata);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulestemp);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall_01"
            ruleflow-group "attendance_scheduleattendance_schedulesloopsubcall_01"
            when
            then
                        update(attendance_scheduleattendance_schedulesdefault);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesfilter);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesattendance_schedules);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesdata);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulestemp);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "attendance_scheduleattendance_schedulesend_01"
            when
            then
                        update(attendance_scheduleattendance_schedulesdefault);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesfilter);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesattendance_schedules);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesdata);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulestemp);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "attendance_scheduleattendance_schedulesprepareparam_01"
            when
            then
                            attendance_scheduleattendance_schedulesfilter.set("n_member_id_eq",attendance_scheduleattendance_schedulestemp.get("memberid"));
                        update(attendance_scheduleattendance_schedulesdefault);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesfilter);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesattendance_schedules);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesdata);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulestemp);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset_02"
            ruleflow-group "attendance_scheduleattendance_schedulesdedataset_02"
            when
            then
                        update(attendance_scheduleattendance_schedulesdefault);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesfilter);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesattendance_schedules);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesdata);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulestemp);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_02"
            ruleflow-group "attendance_scheduleattendance_schedulesprepareparam_02"
            when
            then
                            attendance_scheduleattendance_schedulestemp.set("data",attendance_scheduleattendance_schedulesdata.get(""));
                        update(attendance_scheduleattendance_schedulesdefault);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesfilter);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesattendance_schedules);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulesdata);//更新fact中变量值
                        update(attendance_scheduleattendance_schedulestemp);//更新fact中变量值
            end