package cn.ibizlab.attendance.logic.attendance_schedulelogic.manual;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_schedule attendance_schedulemanualdefault;
                global cn.ibizlab.core.attendance.domain.attendance_schedule attendance_schedulemanualattendance_schedule;
        global cn.ibizlab.core.attendance.service.Iattendance_scheduleService iBzSysAttendance_scheduleDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_schedulemanualbegin"
            when
            then
            end

            //逻辑处理节点[手动调班]
            rule "rawsfcode1"
            ruleflow-group "attendance_schedulemanualrawsfcode1"
            when
            then
                        update(attendance_schedulemanualdefault);//更新fact中变量值
                        update(attendance_schedulemanualattendance_schedule);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "attendance_schedulemanualend1"
            when
            then
                        update(attendance_schedulemanualdefault);//更新fact中变量值
                        update(attendance_schedulemanualattendance_schedule);//更新fact中变量值
            end