package cn.ibizlab.attendance.logic.attendance_schedulelogic.search_month;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_schedule attendance_schedulesearch_monthdefault;
                global cn.ibizlab.core.attendance.domain.attendance_schedule attendance_schedulesearch_monthresult_list;
        global cn.ibizlab.core.attendance.service.Iattendance_scheduleService iBzSysAttendance_scheduleDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_schedulesearch_monthbegin"
            when
            then
            end

            //逻辑处理节点[获取最近五个月的月份]
            rule "rawsfcode1"
            ruleflow-group "attendance_schedulesearch_monthrawsfcode1"
            when
            then
                        update(attendance_schedulesearch_monthdefault);//更新fact中变量值
                        update(attendance_schedulesearch_monthresult_list);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "attendance_schedulesearch_monthend1"
            when
            then
                        update(attendance_schedulesearch_monthdefault);//更新fact中变量值
                        update(attendance_schedulesearch_monthresult_list);//更新fact中变量值
            end