package cn.ibizlab.hr.logic.hr_idea_joblogic.get_join_idea_job;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_idea_job hr_idea_jobget_join_idea_jobdefault;
                global cn.ibizlab.core.hr.domain.hr_idea_job hr_idea_jobget_join_idea_jobidea_job;
                global cn.ibizlab.core.hr.domain.hr_idea_job hr_idea_jobget_join_idea_jobidea_job_list;
                    global cn.ibizlab.core.hr.service.Ihr_idea_jobService hr_idea_jobservice;
        global cn.ibizlab.core.hr.service.Ihr_idea_jobService iBzSysHr_idea_jobDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_idea_jobget_join_idea_jobbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "hr_idea_jobget_join_idea_jobend1"
            when
            then
                        update(hr_idea_jobget_join_idea_jobdefault);//更新fact中变量值
                        update(hr_idea_jobget_join_idea_jobidea_job);//更新fact中变量值
                        update(hr_idea_jobget_join_idea_jobidea_job_list);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "hr_idea_jobget_join_idea_jobprepareparam1"
            when
            then
                        update(hr_idea_jobget_join_idea_jobdefault);//更新fact中变量值
                        update(hr_idea_jobget_join_idea_jobidea_job);//更新fact中变量值
                        update(hr_idea_jobget_join_idea_jobidea_job_list);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数111111111]
            rule "debugparam2"
            ruleflow-group "hr_idea_jobget_join_idea_jobdebugparam2"
            when
            then
                        update(hr_idea_jobget_join_idea_jobdefault);//更新fact中变量值
                        update(hr_idea_jobget_join_idea_jobidea_job);//更新fact中变量值
                        update(hr_idea_jobget_join_idea_jobidea_job_list);//更新fact中变量值
            end

            //逻辑处理节点[实体数据查询11111111]
            rule "dedataquery1"
            ruleflow-group "hr_idea_jobget_join_idea_jobdedataquery1"
            when
            then
                        update(hr_idea_jobget_join_idea_jobdefault);//更新fact中变量值
                        update(hr_idea_jobget_join_idea_jobidea_job);//更新fact中变量值
                        update(hr_idea_jobget_join_idea_jobidea_job_list);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数222222222]
            rule "debugparam1"
            ruleflow-group "hr_idea_jobget_join_idea_jobdebugparam1"
            when
            then
                        update(hr_idea_jobget_join_idea_jobdefault);//更新fact中变量值
                        update(hr_idea_jobget_join_idea_jobidea_job);//更新fact中变量值
                        update(hr_idea_jobget_join_idea_jobidea_job_list);//更新fact中变量值
            end