package cn.ibizlab.hr.logic.hr_idea_joblogic.join_idea_job;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_idea_job hr_idea_jobjoin_idea_jobdefault;
        global cn.ibizlab.core.hr.service.Ihr_idea_jobService iBzSysHr_idea_jobDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_idea_jobjoin_idea_jobbegin"
            when
            then
            end

            //逻辑处理节点[需求关联职位]
            rule "rawsfcode"
            ruleflow-group "hr_idea_jobjoin_idea_jobrawsfcode"
            when
            then
                        update(hr_idea_jobjoin_idea_jobdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "hr_idea_jobjoin_idea_jobend1"
            when
            then
                        update(hr_idea_jobjoin_idea_jobdefault);//更新fact中变量值
            end