package cn.ibizlab.attendance.logic.attendance_checkin_applicationlogic.cancellation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_checkin_application attendance_checkin_applicationcancellationdefault;
                    global cn.ibizlab.core.attendance.service.Iattendance_checkin_applicationService attendance_checkin_applicationservice;
        global cn.ibizlab.core.attendance.service.Iattendance_checkin_applicationService iBzSysAttendance_checkin_applicationDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_checkin_applicationcancellationbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "attendance_checkin_applicationcancellationprepareparam1"
            when
            then
                            attendance_checkin_applicationcancellationdefault.set("status","CANCELLATION");
                        update(attendance_checkin_applicationcancellationdefault);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction1"
            ruleflow-group "attendance_checkin_applicationcancellationdeaction1"
            when
            then
                        attendance_checkin_applicationservice.update(attendance_checkin_applicationcancellationdefault);
                        update(attendance_checkin_applicationcancellationdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "attendance_checkin_applicationcancellationend1"
            when
            then
                        update(attendance_checkin_applicationcancellationdefault);//更新fact中变量值
            end