package cn.ibizlab.hr.logic.hr_offer_approvallogic.approval;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_offer_approval hr_offer_approvalapprovaldefault;
                    global cn.ibizlab.core.hr.service.Ihr_offer_approvalService hr_offer_approvalservice;
        global cn.ibizlab.core.hr.service.Ihr_offer_approvalService iBzSysHr_offer_approvalDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_offer_approvalapprovalbegin"
            when
            then
            end

            //逻辑处理节点[设置审核状态]
            rule "prepareparam1"
            ruleflow-group "hr_offer_approvalapprovalprepareparam1"
            when
            then
                            hr_offer_approvalapprovaldefault.set("period","past");
                        update(hr_offer_approvalapprovaldefault);//更新fact中变量值
            end

            //逻辑处理节点[更新offer审批]
            rule "deaction1"
            ruleflow-group "hr_offer_approvalapprovaldeaction1"
            when
            then
                        hr_offer_approvalservice.update(hr_offer_approvalapprovaldefault);
                        update(hr_offer_approvalapprovaldefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "hr_offer_approvalapprovalend1"
            when
            then
                        update(hr_offer_approvalapprovaldefault);//更新fact中变量值
            end