package cn.ibizlab.hr.logic.hr_offer_approvallogic.my_offer_count;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_offer_approval hr_offer_approvalmy_offer_countdefault;
                global java.util.Map hr_offer_approvalmy_offer_countresult;
        global cn.ibizlab.core.hr.service.Ihr_offer_approvalService iBzSysHr_offer_approvalDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_offer_approvalmy_offer_countbegin"
            when
            then
            end

            //逻辑处理节点[待审批]
            rule "rawsqlcall_01"
            ruleflow-group "hr_offer_approvalmy_offer_countrawsqlcall_01"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
    String strSql="select 	count(1) as pending from 	hr_offer_approval hoa where 	hoa.STATUS = 'pending' and hoa.CREATE_UID  = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysHr_offer_approvalDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                hr_offer_approvalmy_offer_countresult.putAll(entity);
                            }
                        update(hr_offer_approvalmy_offer_countdefault);//更新fact中变量值
                        update(hr_offer_approvalmy_offer_countresult);//更新fact中变量值
            end

            //逻辑处理节点[已审批]
            rule "rawsqlcall_02"
            ruleflow-group "hr_offer_approvalmy_offer_countrawsqlcall_02"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
    String strSql="select 	count(1) as past from 	hr_offer_approval hoa where 	hoa.STATUS = 'past' and hoa.CREATE_UID  = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysHr_offer_approvalDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                hr_offer_approvalmy_offer_countresult.putAll(entity);
                            }
                        update(hr_offer_approvalmy_offer_countdefault);//更新fact中变量值
                        update(hr_offer_approvalmy_offer_countresult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "hr_offer_approvalmy_offer_countend_01"
            when
            then
                        update(hr_offer_approvalmy_offer_countdefault);//更新fact中变量值
                        update(hr_offer_approvalmy_offer_countresult);//更新fact中变量值
            end