export default {
  redirectAppViewRefs: [
    {
      realTitle: '考勤统计编辑视图',
      refAppViewId: 'attendanceapp.attendance_statistics_edit_view',
      name: 'ATTENDANCE_STATISTICS:EDITVIEW',
      id: 'attendance_statistics:editview',
    },
    {
      realTitle: '考勤统计编辑视图',
      refAppViewId: 'attendanceapp.attendance_statistics_edit_view',
      name: 'EDITVIEW',
      id: 'editview',
    },
  ],
  enableWorkflow: true,
  funcViewMode: 'REDIRECTVIEW',
  deviewCodeName: 'RedirectView',
  deviewId: '29c3115965bf61645becccf9827d6b66',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_STATISTICS',
  },
  caption: '考勤统计',
  codeName: 'attendance_statistics_redirect_view',
  appDataEntityId: 'attendanceapp.attendance_statistics',
  controls: [
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.ATTENDANCE_STATISTICS',
      },
      caption: '考勤统计',
      codeName: 'redirect_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'attendanceapp.attendance_statistics',
      controlParam: {},
      name: 'captionbar',
      id: 'redirect_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREDIRECTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'attendanceapp.attendance_statistics',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '考勤统计数据重定向视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEREDIRECTVIEW',
  enableDP: true,
  redirectView: true,
  showCaptionBar: true,
  modelId: 'fb3ccf04bceffdc844ddb9939c43faab',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_statisticsRedirectView',
  id: 'attendanceapp.attendance_statistics_redirect_view',
};
