export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: 'bb41d372de192984b1bf8f5ec24d115f',
  accUserMode: 2,
  caption: '设备信息',
  codeName: 'attendance_device_pickup_grid_view',
  appDataEntityId: 'attendanceapp.attendance_device',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '设备名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '设备名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'device',
          excelCaption: '设备SN',
          appDEFieldId: 'device',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '设备SN',
          codeName: 'device',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'device',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'device',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'device',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '主键',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'attendanceapp.attendance_device',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'attendanceapp.attendance_device',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'attendanceapp.attendance_device',
      controlParam: {
        id: 'grid',
      },
      modelId: '871020b841abbed62eba7c9f4d7ec8ce',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'attendanceapp.attendance_device.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'attendanceapp.attendance_device',
      controlParam: {
        id: 'searchform',
      },
      modelId: '7088702f4cc78c294e15663eb3f1492a',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'attendanceapp.attendance_device.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'attendanceapp.attendance_device',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '设备信息',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'attendanceapp.attendance_device',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'attendanceapp.attendance_device',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '设备信息选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'd8b2923151cf7cc2354a9d949b9d8f30',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_devicePickupGridView',
  id: 'attendanceapp.attendance_device_pickup_grid_view',
};
