export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  pickupMode: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'PickupGridView',
  deviewId: '52518ae319569b2c61dc3590d5d8f944',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_ACTIVATE_RULE',
  },
  caption: '激活规则',
  codeName: 'attendance_activate_rule_pickup_grid_view',
  appDataEntityId: 'attendanceapp.attendance_activate_rule',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'PickupGridView',
      id: 'engine',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridDataItems: [
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '主键',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'attendanceapp.attendance_activate_rule',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'attendanceapp.attendance_activate_rule',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'attendanceapp.attendance_activate_rule',
      controlParam: {
        id: 'grid',
      },
      modelId: 'cb3d158689978a5df8702c7242ae8daa',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'attendanceapp.attendance_activate_rule.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.ATTENDANCE_ACTIVATE_RULE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'attendanceapp.attendance_activate_rule',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'b736fead2c2c55a9546c9effcd75435c',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'attendanceapp.attendance_activate_rule.default',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'attendanceapp.attendance_activate_rule',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.ATTENDANCE_ACTIVATE_RULE',
      },
      caption: '激活规则',
      codeName: 'pickup_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'attendanceapp.attendance_activate_rule',
      controlParam: {},
      name: 'captionbar',
      id: 'pickup_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEPICKUPGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'attendanceapp.attendance_activate_rule',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '激活规则选择表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEPICKUPGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '9cdad79e9167faec1d54e0e903a3f148',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_activate_rulePickupGridView',
  id: 'attendanceapp.attendance_activate_rule_pickup_grid_view',
};
