export default {
  gridRowActiveMode: 2,
  expandSearchForm: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'MonthlyStatistics',
  deviewId: 'b77fca78907c38455066054f8b63ea05',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_STATISTICS',
  },
  caption: '月度汇总',
  codeName: 'attendance_statistics_monthly_statistics',
  appDataEntityId: 'attendanceapp.attendance_statistics',
  sysCss: {
    cssName: 'daily_statistics_style',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onBeforeLoadDraft',
        logicTrigger: 'CTRLEVENT',
        logicType: 'SCRIPT',
        ctrlName: 'searchform',
        scriptCode:
          "console.log(\"初始化搜索表单\")\r\nif (!viewParam.date_range || !viewParam.n_checkin_date_gtandeq || !viewParam.n_checkin_date_ltandeq){\r\n    const time = new Date(); // 当前时间\r\n    const startOfMonth = new Date(time.getFullYear(), time.getMonth(), 1); // 本月第一天，时分秒默认0\r\n    // 格式化日期函数，保证两位数\r\n    function formatDate(date) {\r\n        const y = date.getFullYear();\r\n        const m = date.getMonth() + 1;\r\n        const d = date.getDate();\r\n        return y + '-' + (m < 10 ? '0' + m : m) + '-' + (d < 10 ? '0' + d : d);\r\n    }\r\n\r\n    const n_checkin_date_gtandeq = formatDate(startOfMonth); // 本月初\r\n    const n_checkin_date_ltandeq = formatDate(time);         // 当前时间\r\n    const date_range = n_checkin_date_gtandeq + ',' + n_checkin_date_ltandeq;\r\n    Object.assign(viewParam, { n_checkin_date_gtandeq, n_checkin_date_ltandeq, date_range });\r\n    Object.assign(view.params, { n_checkin_date_gtandeq, n_checkin_date_ltandeq, date_range });\r\n}\r\n\r\n",
        builtinLogic: true,
        name: 'LOGIC',
        id: 'logic',
      },
      {
        eventNames: 'onMounted',
        logicTrigger: 'CTRLEVENT',
        logicType: 'SCRIPT',
        ctrlName: 'grid',
        scriptCode:
          "//基本信息\r\nconst panelItems = view.layoutPanel.panelItems;\r\nconst grid = view.getController('grid');\r\nconst columns = ['member_name','employee_num','dept_name','should_attendance_days','actual_attendance_days','should_attendance','working_hours','billable','late_times','late_duration','leave_early','leave_early_duration','leave_duration'];\r\ngrid.state.columnStates.forEach((item) => {\r\n    if (columns.includes(item.key)) {\r\n        item.hidden = false\r\n    }else{\r\n        item.hidden = true\r\n    }\r\n})\r\n",
        builtinLogic: true,
        name: 'ACTIONCLICKGRID',
        id: 'actionclickgrid',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'attendanceapp.attendance_statistics_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'attendanceapp.attendance_statistics_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'attendanceapp.attendance_statistics_redirect_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'attendanceapp.attendance_statistics_redirect_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '考勤统计编辑视图',
        refAppViewId: 'attendanceapp.attendance_statistics_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '考勤统计数据重定向视图',
        refAppViewId: 'attendanceapp.attendance_statistics_redirect_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'export_report@attendance_statistics',
            uiactionTarget: 'NONE',
            valid: true,
            caption: '导出报表',
            itemType: 'DEUIACTION',
            sysCss: {
              cssName: 'export-toolbar-item',
            },
            tooltip: '导出报表',
            userTag: 'teleport',
            showCaption: true,
            showIcon: true,
            id: 'deuiaction1',
          },
        ],
        xdataControlName: 'grid',
        codeName: 'monthly_statistics_tabtoolbar',
        controlType: 'TOOLBAR',
        logicName: '月度统计表格视图_工具栏',
        appDataEntityId: 'attendanceapp.attendance_statistics',
        controlParam: {
          ctrlParams: {
            TELEPORTFLAG: 'true',
          },
          id: 'tabtoolbar',
        },
        modelId: '7007a23f13e1cb2f5281273d6d98cb6b',
        modelType: 'PSDETOOLBAR',
        name: 'tabtoolbar',
        id: 'monthly_statistics_tabtoolbar',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'member_name',
            excelCaption: '姓名',
            appDEFieldId: 'member_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.MEMBER_NAME',
            },
            caption: '姓名',
            codeName: 'member_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 150,
            widthUnit: 'STAR',
            id: 'member_name',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'employee_num',
                excelCaption: '工号',
                appDEFieldId: 'employee_num',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.EMPLOYEE_NUM',
                },
                caption: '工号',
                codeName: 'employee_num',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                id: 'employee_num',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'dept_name',
                excelCaption: '部门',
                appDEFieldId: 'dept_name',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.DEPT_NAME',
                },
                caption: '部门',
                codeName: 'dept_name',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                id: 'dept_name',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'title',
                excelCaption: '职位',
                appDEFieldId: 'title',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.TITLE',
                },
                caption: '职位',
                codeName: 'title',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'title',
              },
            ],
            aggMode: 'NONE',
            caption: '基本信息',
            codeName: 'base_info',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'base_info',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'should_attendance_days',
                excelCaption: '应出勤天数',
                appDEFieldId: 'should_attendance_days',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag:
                    'DEF.LNAME.ATTENDANCE_STATISTICS.SHOULD_ATTENDANCE_DAYS',
                },
                caption: '应出勤天数',
                codeName: 'should_attendance_days',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                userParam: {
                  tooltip:
                    '选择时间段内累计需要上班的天数（计算方式：时间段内每天设置的总工时记为出勤天数之和；若没有设置，则累计时间段内每天应出勤时长除以每天班次中规定的工作时长，如果考勤规则中几个班次的工作时长不一样，则选择时长最长的）',
                },
                id: 'should_attendance_days',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'actual_attendance_days',
                excelCaption: '实际出勤天数',
                appDEFieldId: 'actual_attendance_days',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag:
                    'DEF.LNAME.ATTENDANCE_STATISTICS.ACTUAL_ATTENDANCE_DAYS',
                },
                caption: '实际出勤天数',
                codeName: 'actual_attendance_days',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                userParam: {
                  'èªç±ç­ï¼æè§åä¸­è®¾ç½®çéæå¡æ¬¡æ°ï¼è®¡ç®å®éåºå¤': '',
                  tooltip:
                    '非自由班：时间段内累计实际上班天数（计算方式：积累每天实际出勤天数（计薪时长-带薪假）/总工时*应出勤天数比例；若没有设置出勤天数，则积累每天计薪时长减带薪假后除以时间段内最长工作时长）',
                },
                id: 'actual_attendance_days',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'should_attendance_time',
                excelCaption: '应出勤时长(小时)',
                appDEFieldId: 'should_attendance_time',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag:
                    'DEF.LNAME.ATTENDANCE_STATISTICS.SHOULD_ATTENDANCE_TIME',
                },
                caption: '应出勤时长(小时)',
                codeName: 'should_attendance_time',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                userParam: {
                  tooltip: '选择时间段内累计每天班次规定的工作时长',
                },
                id: 'should_attendance_time',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'working_hours',
                excelCaption: '实际出勤时长(小时)',
                appDEFieldId: 'working_hours',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '实际出勤时长(小时)',
                codeName: 'working_hours',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                userParam: {
                  tooltip:
                    '选择时间段内累计每天实际出勤时长（每天实际出勤时长为早晚打卡时间相减并扣掉休息时间）',
                },
                id: 'working_hours',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'billable_time',
                excelCaption: '计薪工作时长（小时）',
                appDEFieldId: 'billable_time',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.BILLABLE_TIME',
                },
                caption: '计薪工作时长（小时）',
                codeName: 'billable_time',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                userParam: {
                  tooltip:
                    '选择时间段内累计每天计薪工作时长（每天计薪工作时长为当天班次规定的工作时长减掉旷工时长和不带薪的假期时长）',
                },
                id: 'billable_time',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'pay_overtime_time',
                excelCaption: '加班时长(记加班费)(小时)',
                appDEFieldId: 'pay_overtime_time',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag:
                    'DEF.LNAME.ATTENDANCE_STATISTICS.PAY_OVERTIME_TIME',
                },
                caption: '加班时长(记加班费)(小时)',
                codeName: 'pay_overtime_time',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 220,
                widthUnit: 'PX',
                userParam: {
                  tooltip:
                    '选择时间段内累计每日统计的加班时长和加班申请计加班费的加班时长（每日统计的加班时长最小单位为0.1小时，少于0.1小时不计算）',
                },
                id: 'pay_overtime_time',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'rest_overtime_time',
                excelCaption: '加班时长(记调休假)(小时)',
                appDEFieldId: 'rest_overtime_time',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag:
                    'DEF.LNAME.ATTENDANCE_STATISTICS.REST_OVERTIME_TIME',
                },
                caption: '加班时长(记调休假)(小时)',
                codeName: 'rest_overtime_time',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 220,
                widthUnit: 'PX',
                userParam: {
                  tooltip:
                    '选择时间段内累计加班申请计调休假的加班时长（最小单位为0.1小时）',
                },
                id: 'rest_overtime_time',
              },
            ],
            aggMode: 'NONE',
            caption: '出勤统计',
            codeName: 'attendance',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'attendance',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'late_times',
                excelCaption: '迟到次数',
                appDEFieldId: 'late_times',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.LATE_TIMES',
                },
                caption: '迟到次数',
                codeName: 'late_times',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                id: 'late_times',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'late_time',
                excelCaption: '迟到时长',
                appDEFieldId: 'late_time',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.LATE_TIME',
                },
                caption: '迟到时长',
                codeName: 'late_duration',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                id: 'late_duration',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'leave_early_times',
                excelCaption: '早退次数',
                appDEFieldId: 'leave_early_times',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag:
                    'DEF.LNAME.ATTENDANCE_STATISTICS.LEAVE_EARLY_TIMES',
                },
                caption: '早退次数',
                codeName: 'leave_early',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                id: 'leave_early',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'leave_early_time',
                excelCaption: '早退时长',
                appDEFieldId: 'leave_early_time',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.LEAVE_EARLY_TIME',
                },
                caption: '早退时长',
                codeName: 'leave_early_duration',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                id: 'leave_early_duration',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'on_missing',
                excelCaption: '上班卡缺卡',
                appDEFieldId: 'on_missing',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '上班卡缺卡',
                codeName: 'on_missing',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                id: 'on_missing',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'off_missing',
                excelCaption: '下班卡缺卡',
                appDEFieldId: 'off_missing',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '下班卡缺卡',
                codeName: 'off_missing',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                id: 'off_missing',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'absent_days',
                excelCaption: '旷工天数',
                appDEFieldId: 'absent_days',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.ABSENT_DAYS',
                },
                caption: '旷工天数',
                codeName: 'absent_days',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                id: 'absent_days',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'on_business_days',
                excelCaption: '出差天数',
                appDEFieldId: 'on_business_days',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.ON_BUSINESS_DAYS',
                },
                caption: '出差天数',
                codeName: 'on_business_days',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                id: 'on_business_days',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'out_time',
                excelCaption: '外出时长(小时)',
                appDEFieldId: 'out_time',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.OUT_TIME',
                },
                caption: '外出时长(小时)',
                codeName: 'out_time',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                id: 'out_time',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'make_card_times',
                excelCaption: '补卡次数',
                appDEFieldId: 'make_card_times',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.MAKE_CARD_TIMES',
                },
                caption: '补卡次数',
                codeName: 'make_card_times',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                id: 'make_card_times',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'out_work_times',
                excelCaption: '外勤次数',
                appDEFieldId: 'out_work_times',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.OUT_WORK_TIMES',
                },
                caption: '外勤次数',
                codeName: 'out_work_times',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                id: 'out_work_times',
              },
            ],
            aggMode: 'NONE',
            caption: '异常统计',
            codeName: 'abnormal',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'abnormal',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'leave_duration',
                excelCaption: '请假时长(小时)',
                appDEFieldId: 'leave_duration',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '请假时长(小时)',
                codeName: 'leave_duration',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                id: 'leave_duration',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'annual_leave',
                excelCaption: '年假(小时)',
                appDEFieldId: 'annual_leave',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '年假(小时)',
                codeName: 'annual_leave',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'annual_leave',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'compassionate_leave',
                excelCaption: '事假(小时)',
                appDEFieldId: 'compassionate_leave',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '事假(小时)',
                codeName: 'compassionate_leave',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'compassionate_leave',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'vacation_leave',
                excelCaption: '调休假(小时)',
                appDEFieldId: 'vacation_leave',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '调休假(小时)',
                codeName: 'vacation_leave',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'vacation_leave',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'sick_leave',
                excelCaption: '病假(小时)',
                appDEFieldId: 'sick_leave',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '病假(小时)',
                codeName: 'sick_leave',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'sick_leave',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'parental_leave',
                excelCaption: '育儿假(小时)',
                appDEFieldId: 'parental_leave',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '育儿假(小时)',
                codeName: 'parental_leave',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'parental_leave',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'paternity_leave',
                excelCaption: '陪产假(小时)',
                appDEFieldId: 'paternity_leave',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '陪产假(小时)',
                codeName: 'paternity_leave',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'paternity_leave',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'marriage_holiday',
                excelCaption: '婚假(小时)',
                appDEFieldId: 'marriage_holiday',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '婚假(小时)',
                codeName: 'marriage_holiday',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'marriage_holiday',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'funeral_leave',
                excelCaption: '丧假(小时)',
                appDEFieldId: 'funeral_leave',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '丧假(小时)',
                codeName: 'funeral_leave',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'funeral_leave',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'maternity_leave',
                excelCaption: '产假(小时)',
                appDEFieldId: 'maternity_leave',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '产假(小时)',
                codeName: 'maternity_leave',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 100,
                widthUnit: 'PX',
                id: 'maternity_leave',
              },
            ],
            aggMode: 'NONE',
            caption: '请假统计',
            codeName: 'leave',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'leave',
          },
          {
            aggMode: 'NONE',
            caption: '每日统计',
            codeName: 'daily',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'PX',
            id: 'daily',
          },
          {
            clconvertMode: 'NONE',
            dataItemName: 'id',
            excelCaption: '模板列',
            linkAppViewId:
              'attendanceapp.attendance_statistics_details_edit_view',
            linkValueItem: 'id',
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            enableLinkView: true,
            aggMode: 'NONE',
            align: 'CENTER',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.ATTENDANCE_STATISTICS.ID',
            },
            caption: '模板列',
            codeName: 'template',
            columnType: 'DEFGRIDCOLUMN',
            hideMode: 1,
            noPrivDisplayMode: 1,
            width: 200,
            widthUnit: 'PX',
            enableSort: true,
            hideDefault: true,
            userParam: {
              'SRFNAVPARAM.member_id': '%member_id%',
              'SRFNAVPARAM.custom_id': '%id%',
              'SRFNAVPARAM.checkin_date': '%checkin_date%',
            },
            id: 'template',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'member_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'member_name',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'id',
          },
          {
            appDEFieldId: 'employee_num',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'employee_num',
          },
          {
            appDEFieldId: 'dept_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'dept_name',
          },
          {
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'title',
          },
          {
            appDEFieldId: 'should_attendance_days',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'should_attendance_days',
          },
          {
            appDEFieldId: 'actual_attendance_days',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'actual_attendance_days',
          },
          {
            appDEFieldId: 'should_attendance_time',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'should_attendance_time',
          },
          {
            appDEFieldId: 'working_hours',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'working_hours',
          },
          {
            appDEFieldId: 'billable_time',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'billable_time',
          },
          {
            appDEFieldId: 'pay_overtime_time',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'pay_overtime_time',
          },
          {
            appDEFieldId: 'rest_overtime_time',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'rest_overtime_time',
          },
          {
            appDEFieldId: 'late_times',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'late_times',
          },
          {
            appDEFieldId: 'late_time',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'late_time',
          },
          {
            appDEFieldId: 'leave_early_times',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'leave_early_times',
          },
          {
            appDEFieldId: 'leave_early_time',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'leave_early_time',
          },
          {
            appDEFieldId: 'on_missing',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'on_missing',
          },
          {
            appDEFieldId: 'off_missing',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'off_missing',
          },
          {
            appDEFieldId: 'absent_days',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'absent_days',
          },
          {
            appDEFieldId: 'on_business_days',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'on_business_days',
          },
          {
            appDEFieldId: 'out_time',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'out_time',
          },
          {
            appDEFieldId: 'make_card_times',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'make_card_times',
          },
          {
            appDEFieldId: 'out_work_times',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'out_work_times',
          },
          {
            appDEFieldId: 'leave_duration',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'leave_duration',
          },
          {
            appDEFieldId: 'annual_leave',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'annual_leave',
          },
          {
            appDEFieldId: 'compassionate_leave',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'compassionate_leave',
          },
          {
            appDEFieldId: 'vacation_leave',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'vacation_leave',
          },
          {
            appDEFieldId: 'sick_leave',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'sick_leave',
          },
          {
            appDEFieldId: 'parental_leave',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'parental_leave',
          },
          {
            appDEFieldId: 'paternity_leave',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'paternity_leave',
          },
          {
            appDEFieldId: 'marriage_holiday',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'marriage_holiday',
          },
          {
            appDEFieldId: 'funeral_leave',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'funeral_leave',
          },
          {
            appDEFieldId: 'maternity_leave',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'maternity_leave',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '标识',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        singleSelect: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_month_report',
          appDataEntityId: 'attendanceapp.attendance_statistics',
          id: 'fetch',
        },
        dedataExportId: 'dataexport',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'attendanceapp.attendance_statistics',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'monthly_statistics_grid',
        controlStyle: 'MONTH',
        controlType: 'GRID',
        logicName: '月度统计表格视图_表格',
        appDataEntityId: 'attendanceapp.attendance_statistics',
        controlLogics: [
          {
            eventNames: 'onMounted',
            logicTag: 'grid',
            logicType: 'SCRIPT',
            triggerType: 'CTRLEVENT',
            id: 'default_hidden',
          },
        ],
        controlParam: {
          ctrlParams: {
            STARTFIELD: 'n_checkin_date_gtandeq',
            GROUPCOLUMNFIELD: 'daily',
            ENDFIELD: 'n_checkin_date_ltandeq',
            COLWIDTH: '200',
          },
          id: 'grid',
        },
        sysPFPluginId: 'month',
        modelId: '08e35f576ca6876ae0d9224c8e8151f7',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'attendanceapp.attendance_statistics.monthly_statistics_grid',
      },
      {
        searchButtonStyle: 'NONE',
        enableAutoSearch: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                createDV: 'member_name,employee_num,dept_name',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId: 'attendanceapp.attendance__base_info',
                  editorParams: {
                    DEFAULTDISABLEDLIST: '["member_name"]',
                  },
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'base_info',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '基本信息',
                codeName: 'base_info',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'base_info',
              },
              {
                createDV:
                  'should_attendance_days,actual_attendance_days,should_attendance,working_hours,billable',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId:
                    'attendanceapp.attendance__attendance_statistics',
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'attendance',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '出勤统计',
                codeName: 'attendance',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'attendance',
              },
              {
                createDV:
                  'late_times,late_duration,leave_early,leave_early_duration',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId:
                    'attendanceapp.attendance__abnormal_statistics',
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'abnormal',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '异常统计',
                codeName: 'abnormal',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'abnormal',
              },
              {
                createDV: 'leave_duration',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId:
                    'attendanceapp.attendance__leave_application_statistics',
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'leave',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '请假统计',
                codeName: 'leave',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'leave',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId: 'attendanceapp.attendance__daily_statistics',
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'daily',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '每日统计',
                codeName: 'daily',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'daily',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'monthly_statistics_search_form',
        controlType: 'SEARCHFORM',
        logicName: '月度统计表格视图_搜索表单',
        appDataEntityId: 'attendanceapp.attendance_statistics',
        controlLogics: [
          {
            eventNames: 'onChange',
            itemName: 'base_info',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].base_info || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['member_name', 'employee_num', 'dept_name', 'title', 'xqsyr', 'gys_infoname'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    console.log(\"隐藏表格列\"+grid)\r\n    if (values.includes(key)) {\r\n        item.hidden = false;\r\n    } else {\r\n        item.hidden = true;\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'base_info',
          },
          {
            eventNames: 'onChange',
            itemName: 'attendance',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].attendance || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['should_attendance_days', 'actual_attendance_days', 'should_attendance_time', 'working_hours', 'billable_time', 'pay_overtime_time', 'rest_overtime_time'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    if(item){\r\n        if (values.includes(key)) {\r\n            item.hidden = false;\r\n        } else {\r\n            item.hidden = true;\r\n        }\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'attendance',
          },
          {
            eventNames: 'onChange',
            itemName: 'abnormal',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].abnormal || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['late_times', 'late_duration', 'leave_early', 'leave_early_duration', 'on_missing', 'off_missing', 'absent_days', 'on_business_days', 'out_time', 'make_card_times', 'out_work_times'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    if(item){\r\n        if (values.includes(key)) {\r\n            item.hidden = false;\r\n        } else {\r\n            item.hidden = true;\r\n        }\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'abnormal',
          },
          {
            eventNames: 'onChange',
            itemName: 'daily',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].daily || '';\r\ngrid.toggleCustomColumn(value === 'daily');\r\n",
            triggerType: 'CTRLEVENT',
            id: 'daily',
          },
          {
            eventNames: 'onChange',
            itemName: 'leave',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].leave || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['leave_duration', 'annual_leave', 'vacation_leave', 'sick_leave', 'parental_leave', 'paternity_leave', 'marriage_holiday', 'funeral_leave', 'maternity_leave', 'compassionate_leave'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    if(item){\r\n        if (values.includes(key)) {\r\n            item.hidden = false;\r\n        } else {\r\n            item.hidden = true;\r\n        }\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'leave',
          },
        ],
        controlParam: {
          id: 'searchform',
        },
        modelId: 'e75e612cebf232dd535c9095358fa2c1',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'attendanceapp.attendance_statistics.monthly_statistics_search_form',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'attendanceapp.attendance_statistics',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.ATTENDANCE_STATISTICS',
        },
        caption: '月度汇总',
        codeName: 'monthly_statistics_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'attendanceapp.attendance_statistics',
        controlParam: {},
        name: 'captionbar',
        id: 'monthly_statistics_captionbar',
      },
    ],
    codeName: 'usr0605245689',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'MonthlyStatistics表格视图布局',
    appDataEntityId: 'attendanceapp.attendance_statistics',
    controlParam: {},
    modelId: 'cf33e62b0cf1d5156f8610254145cfb6',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0605245689',
  },
  title: '月度汇总',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: false,
  modelId: '29f0f48aa7acc02a37ba35bd850fb286',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_statisticsMonthlyStatistics',
  id: 'attendanceapp.attendance_statistics_monthly_statistics',
};
