export default {
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'WorkRestGridView',
  deviewId: 'c5f51eeb21a93a8a8c290368bdf2e517',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_WORKDAY',
  },
  caption: '工作日',
  codeName: 'attendance_workday_work_rest_grid_view',
  appDataEntityId: 'attendanceapp.attendance_workday',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      eventNames: 'onMounted',
      logicTrigger: 'VIEWEVENT',
      logicType: 'SCRIPT',
      scriptCode:
        'const grid = view.getCtrl("GRID", "grid");\r\n\r\n// 刷新表格数据\r\nawait grid.load();',
      builtinLogic: true,
      name: 'LOGIC',
      id: 'logic',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'attendanceapp.attendance_workday_edit_view',
        },
        enableBatchAdd: true,
        appDataEntityId: 'attendanceapp.attendance_workday',
        appUILogicRefViews: [
          {
            refAppViewId: 'attendanceapp.attendance_workday_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'attendanceapp.attendance_workday_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'attendanceapp.attendance_workday_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '工作日编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.ATTENDANCE_WORKDAY.EDITVIEW',
      },
      refAppViewId: 'attendanceapp.attendance_workday_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '工作日编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.ATTENDANCE_WORKDAY.EDITVIEW',
      },
      refAppViewId: 'attendanceapp.attendance_workday_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      name: 'MPICKUPVIEW:RULE',
      id: 'mpickupview:rule',
    },
    {
      name: 'MPICKUPVIEW:ATTENDANCE_SHIFT',
      id: 'mpickupview:attendance_shift',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '工作日',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_WORKDAY.NAME',
          },
          caption: '工作日',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 120,
          widthUnit: 'STAR',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'title',
          excelCaption: '标题',
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '标题',
          codeName: 'title',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 120,
          widthUnit: 'STAR',
          id: 'title',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'title',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'title',
        },
        {
          appDEFieldId: 'shift_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'shift_id',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'rule_id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'rule_id',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '标识',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      hideHeader: true,
      singleSelect: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'attendanceapp.attendance_workday',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'attendanceapp.attendance_workday',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'work_rest',
      controlType: 'GRID',
      logicName: '上A休B表格',
      appDataEntityId: 'attendanceapp.attendance_workday',
      controlParam: {
        id: 'grid',
      },
      modelId: 'a98d8b56972f1c077e2b25152e1e4101',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'attendanceapp.attendance_workday.work_rest',
    },
    {
      groupMode: 'SINGLE',
      controlType: 'SEARCHBAR',
      appDataEntityId: 'attendanceapp.attendance_workday',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.ATTENDANCE_WORKDAY',
      },
      caption: '工作日',
      codeName: 'work_rest_grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'attendanceapp.attendance_workday',
      controlParam: {},
      name: 'captionbar',
      id: 'work_rest_grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'attendanceapp.attendance_workday',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '工作日表格视图-上A休B',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.ATTENDANCE_WORKDAY.GRIDVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  width: 300,
  enableDP: true,
  showCaptionBar: false,
  modelId: 'a21cfd6df3f88047cd4971d66fd8b451',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_workdayWorkRestGridView',
  id: 'attendanceapp.attendance_workday_work_rest_grid_view',
};
