export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'ActiveOptionView',
  deviewId: 'f871104eb540530198ce5fa860817c1b',
  accUserMode: 2,
  caption: '保存考勤规则',
  codeName: 'attendance_rule_active_option_view',
  height: 270,
  appDataEntityId: 'attendanceapp.attendance_rule',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'OptionView',
      id: 'engine',
    },
  ],
  controls: [
    {
      createControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'attendanceapp.attendance_rule',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'attendanceapp.attendance_rule',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'attendanceapp.attendance_rule',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'attendanceapp.attendance_rule',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'attendanceapp.attendance_rule',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'nothing',
        appDataEntityId: 'attendanceapp.attendance_rule',
        id: 'update',
      },
      deformItemUpdates: [
        {
          codeName: 'UpdateEffectTime',
          defiupdateDetails: [
            {
              id: 'effect_time',
            },
          ],
          scriptCode:
            'console.log("刷新生效时间");\r\n\r\n// 定义日期格式化函数\r\nfunction formatToDateString(date) {\r\n    const year = date.getFullYear();\r\n    const month = String(date.getMonth() + 1).padStart(2, \'0\'); \r\n    const day = String(date.getDate()).padStart(2, \'0\');\r\n    return `${year}-${month}-${day}`;\r\n}\r\n\r\nif (data.effect_date == "1") {\r\n    const today = new Date();\r\n    data.effect_time = formatToDateString(today); \r\n}\r\n\r\nif (data.effect_date == "2") {\r\n    const tomorrow = new Date();\r\n    tomorrow.setDate(tomorrow.getDate() + 1);\r\n    tomorrow.setHours(0, 0, 0, 0);\r\n    data.effect_time = formatToDateString(tomorrow); \r\n}',
          customCode: true,
          showBusyIndicator: true,
          name: '刷新生效时间',
          id: 'updateeffecttime',
        },
      ],
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  createDV: '3',
                  dataType: 25,
                  enableCond: 3,
                  labelPos: 'LEFT',
                  labelWidth: 130,
                  noPrivDisplayMode: 1,
                  deformItemUpdateId: 'updateeffecttime',
                  editor: {
                    singleSelect: true,
                    appCodeListId: 'attendanceapp.attendance__effectconfig',
                    editorType: 'DROPDOWNLIST',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'effect_date',
                  },
                  updateDV: '3',
                  needCodeListConfig: true,
                  caption: '生效日期',
                  codeName: 'effect_date',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  layoutPos: {
                    colLG: 15,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'effect_date',
                },
                {
                  dataType: 5,
                  enableCond: 3,
                  itemWidth: 100,
                  labelPos: 'NONE',
                  noPrivDisplayMode: 1,
                  appDEFieldId: 'effect_time',
                  editor: {
                    dateTimeFormat: 'YYYY-MM-DD',
                    editorParams: {
                      TIMEFMT: 'YYYY-MM-DD',
                    },
                    editorType: 'DATEPICKEREX_NOTIME',
                    editorWidth: 100,
                    placeHolder: '请选择日期',
                    valueType: 'SIMPLE',
                    editable: true,
                    id: 'effect_time',
                  },
                  valueFormat: 'YYYY-MM-DD',
                  caption: '生效时间',
                  codeName: 'effect_time',
                  detailStyle: 'DEFAULT',
                  detailType: 'FORMITEM',
                  defdgroupLogics: [
                    {
                      logicCat: 'PANELVISIBLE',
                      relatedDetailNames: ['effect_date'],
                      groupOP: 'AND',
                      defdlogics: [
                        {
                          condOP: 'EQ',
                          defdname: 'effect_date',
                          value: '3',
                          logicType: 'SINGLE',
                          id: 'effect_date等于(=) 3',
                        },
                      ],
                      logicType: 'GROUP',
                    },
                    {
                      logicCat: 'ITEMBLANK',
                      relatedDetailNames: ['effect_date'],
                      groupOP: 'AND',
                      defdlogics: [
                        {
                          condOP: 'NOTEQ',
                          defdname: 'effect_date',
                          value: '3',
                          logicType: 'SINGLE',
                          id: 'effect_date不等于(<>) 3',
                        },
                      ],
                      logicType: 'GROUP',
                    },
                    {
                      logicCat: 'ITEMENABLE',
                      relatedDetailNames: ['effect_date'],
                      groupOP: 'AND',
                      defdlogics: [
                        {
                          condOP: 'EQ',
                          defdname: 'effect_date',
                          value: '3',
                          logicType: 'SINGLE',
                          id: 'effect_date等于(=) 3',
                        },
                      ],
                      logicType: 'GROUP',
                    },
                  ],
                  layoutPos: {
                    colLG: 9,
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'effect_time',
                },
              ],
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ATTENDANCE_RULE.ID',
              },
              caption: '主键',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main2',
      controlType: 'FORM',
      logicName: '保存考勤规则_表单',
      appDataEntityId: 'attendanceapp.attendance_rule',
      controlParam: {
        id: 'form',
      },
      modelId: '1066244dd99950b0a2af8022ee2cd776',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'attendanceapp.attendance_rule.main2',
    },
    {
      codeName: 'active_option_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'attendanceapp.attendance_rule',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'active_option_view_datainfobar',
    },
    {
      caption: '保存考勤规则',
      codeName: 'active_option_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'attendanceapp.attendance_rule',
      controlParam: {},
      name: 'captionbar',
      id: 'active_option_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEOPTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'attendanceapp.attendance_rule',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '保存考勤规则',
  viewStyle: 'DEFAULT',
  viewType: 'DEOPTVIEW',
  width: 520,
  enableDP: true,
  showCaptionBar: true,
  modelId: 'd26e5d843bd44a227ece38bd2165d248',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_ruleActiveOptionView',
  id: 'attendanceapp.attendance_rule_active_option_view',
};
