export default {
  gridRowActiveMode: 2,
  xdataControlName: 'grid',
  loadDefault: true,
  funcViewMode: 'MDATAVIEW',
  deviewCodeName: 'GridView',
  deviewId: '98cb7fd5a0902e4db6f927309740c3ba',
  accUserMode: 2,
  caption: '考勤规则',
  codeName: 'attendance_rule_grid_view',
  appDataEntityId: 'attendanceapp.attendance_rule',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewRefs: [
    {
      realOpenMode: 'INDEXVIEWTAB',
      realTitle: '考勤规则编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.ATTENDANCE_RULE.EDITVIEW',
      },
      refAppViewId: 'attendanceapp.attendance_rule_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
    {
      realOpenMode: 'INDEXVIEWTAB',
      realTitle: '考勤规则编辑视图',
      realTitleLanguageRes: {
        lanResTag: 'PAGE.TITLE.ATTENDANCE_RULE.EDITVIEW',
      },
      refAppViewId: 'attendanceapp.attendance_rule_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '规则名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'CENTER',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RULE.NAME',
          },
          caption: '规则名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 360,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'schedule_type',
          excelCaption: '考勤类型',
          appCodeListId: 'attendanceapp.attendance__all_schedule_type',
          appDEFieldId: 'schedule_type',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'CENTER',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RULE.SCHEDULE_TYPE',
          },
          caption: '考勤类型',
          codeName: 'schedule_type',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'schedule_type',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'total_members',
          excelCaption: '人数',
          appDEFieldId: 'total_members',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '人数',
          codeName: 'total_members',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          id: 'total_members',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'work_times',
          excelCaption: '考勤时段',
          appDEFieldId: 'work_times',
          valueType: 'OBJECTS',
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '考勤时段',
          cellSysCss: {
            cssName: 'grid-script-column',
          },
          codeName: 'work_times',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 300,
          widthUnit: 'STAR',
          id: 'work_times',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'effect_time',
          excelCaption: '生效时间',
          appDEFieldId: 'effect_time',
          valueFormat: 'YYYY-MM-DD HH:mm:ss',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '生效时间',
          codeName: 'effect_time',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'effect_time',
        },
        {
          clconvertMode: 'FRONT',
          dataItemName: 'write_uid',
          excelCaption: '最后操作人',
          appCodeListId: 'attendanceapp.sysoperator',
          appDEFieldId: 'write_uid',
          valueType: 'SIMPLE',
          aggMode: 'NONE',
          align: 'CENTER',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RULE.WRITE_UID',
          },
          caption: '最后操作人',
          codeName: 'write_uid',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'write_uid',
        },
        {
          deuiactionGroup: {
            uiactionGroupDetails: [
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '手动排班',
                detailType: 'DEUIACTION',
                enableScriptCode: 'data.schedule_type =="manual"',
                uiactionId: 'openschedule@attendance_rule',
                visibleScriptCode: 'data.schedule_type =="manual"',
                showCaption: true,
                id: 'u755368d',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '编辑排班',
                detailType: 'DEUIACTION',
                enableScriptCode: 'data.schedule_type !="no_required"',
                uiactionId: 'edit@attendance_rule',
                visibleScriptCode: 'data.schedule_type !="no_required"',
                showCaption: true,
                id: 'u921821c',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '删除',
                detailType: 'DEUIACTION',
                enableScriptCode: 'data.schedule_type !="no_required"',
                uiactionId: 'remove@attendance_rule',
                visibleScriptCode: 'data.schedule_type !="no_required"',
                showCaption: true,
                sysCss: {
                  cssName: 'danger-text-button',
                },
                id: 'u4760b66',
              },
              {
                actionLevel: 100,
                afterItemType: 'NONE',
                beforeItemType: 'NONE',
                buttonStyle: 'DEFAULT',
                caption: '添加人员',
                detailType: 'DEUIACTION',
                enableScriptCode: 'data.schedule_type =="no_required"',
                uiactionId: 'addmembers@attendance_rule',
                visibleScriptCode: 'data.schedule_type =="no_required"',
                showCaption: true,
                id: 'uf371582',
              },
            ],
            appDataEntityId: 'attendanceapp.attendance_rule',
            uniqueTag: 'attendance_rule__A7bd49c5fe104a9e587',
            name: '操作',
            id: 'a7bd49c5fe104a9e587',
          },
          aggMode: 'NONE',
          align: 'CENTER',
          caption: '操作',
          codeName: 'uagridcolumn1',
          columnType: 'UAGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 380,
          widthUnit: 'PX',
          id: 'uagridcolumn1',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'schedule_type',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'schedule_type',
        },
        {
          appDEFieldId: 'total_members',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'total_members',
        },
        {
          appDEFieldId: 'work_times',
          scriptCode:
            'var worktimeParts = [];\r\nif ((data.schedule_type == "alternate_week" || data.schedule_type == "fixed" || data.schedule_type == "flexible" || data.schedule_type == "work_rest" || data.schedule_type == "free") && data.shifts != null) {\r\n    var shift = data.shifts.find(item => item.default_flag == 1);\r\n    if (shift != null && shift.scopes != null) {\r\n        var scopes = shift.scopes\r\n        var parts = [];\r\n        scopes.forEach(scope => {\r\n            var start = scope.start_base_time.substring(0, 5);\r\n            if(scope.next_tag === "1,0"||scope.next_tag === "1,1"){\r\n                start = "次日" + start;\r\n            }\r\n            var end = scope.end_base_time.substring(0, 5);\r\n            if(scope.next_tag === "0,1"||scope.next_tag === "1,1"){\r\n                end = "次日" + end;\r\n            }\r\n            parts.push(start + \'~\' + end);\r\n        })\r\n        data.work_times = worktimeParts.push(parts.join(\'，\'))\r\n    }\r\n}\r\nif (data.schedule_type == "manual" || data.schedule_type == \'class_inversion\') {\r\n    var shifts = data.shifts\r\n    if (shifts == null) {\r\n        return;\r\n    }\r\n    shifts.forEach(shift => {\r\n        if (shift.scopes != null) {\r\n            var scopes = shift.scopes\r\n            var scopeParts = [];\r\n            scopes.forEach(scope => {\r\n                var start = scope.start_base_time.substring(0, 5);\r\n                if(scope.next_tag === "1,0"||scope.next_tag === "1,1"){\r\n                    start = "次日" + start;\r\n                }\r\n                var end = scope.end_base_time.substring(0, 5);\r\n                if(scope.next_tag === "0,1"||scope.next_tag === "1,1"){\r\n                    end = "次日" + end;\r\n                }\r\n                scopeParts.push(start + \'~\' + end);\r\n            })\r\n            worktimeParts.push(shift.name + \'：\' +scopeParts.join(\'，\'))\r\n        }\r\n    })\r\n\r\n}\r\nif (data.schedule_type == "no_required"){\r\n    worktimeParts.push("无需考勤")\r\n}\r\nreturn worktimeParts.join(\'\\n\');',
          valueType: 'OBJECTS',
          customCode: true,
          dataType: 21,
          id: 'work_times',
        },
        {
          format: 'YYYY-MM-DD HH:mm:ss',
          appDEFieldId: 'effect_time',
          scriptCode: "return data.effect_time.split(' ')[0];",
          valueType: 'SIMPLE',
          customCode: true,
          dataType: 5,
          id: 'effect_time',
        },
        {
          appDEFieldId: 'write_uid',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'write_uid',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '主键',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      singleSelect: true,
      navViewPos: 'NONE',
      fetchControlAction: {
        appDEMethodId: 'fetch_complete',
        appDataEntityId: 'attendanceapp.attendance_rule',
        id: 'fetch',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'attendanceapp.attendance_rule',
        id: 'remove',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'attendanceapp.attendance_rule',
      controlParam: {
        ctrlParams: {
          ENABLEGRIDROWBREAK: 'TRUE',
        },
        id: 'grid',
      },
      modelId: '6cd7965118802af306eb9683d03469a9',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'attendanceapp.attendance_rule.main',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.ATTENDANCE_RULE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'attendanceapp.attendance_rule',
      controlParam: {
        id: 'searchform',
      },
      modelId: '5802b9a7317d0ac6051872719b999281',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'attendanceapp.attendance_rule.default',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'createrule@attendance_rule',
          uiactionTarget: 'NONE',
          valid: true,
          caption: '新建考勤规则',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-plus',
            glyph: 'xf067@FontAwesome',
          },
          tooltip: '新建考勤规则',
          showCaption: true,
          showIcon: true,
          id: 'tbitem1_createrule',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '工具栏模板（默认表格界面）',
      appDataEntityId: 'attendanceapp.attendance_rule',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '95007e82726c9de412bfb29d3ae8cabf',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_toolbar',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'attendanceapp.attendance_rule',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      caption: '考勤规则',
      codeName: 'grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'attendanceapp.attendance_rule',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'attendanceapp.attendance_rule',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '考勤规则表格视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.ATTENDANCE_RULE.GRIDVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '28764c7330a4e4e139d0fca1832744d8',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_ruleGridView',
  id: 'attendanceapp.attendance_rule_grid_view',
};
