export default {
  expandSearchForm: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'DailyStatisticsView',
  deviewId: '719c0f8ae3c81c8661711da1eea0e16b',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_RECORD',
  },
  caption: '每日统计',
  codeName: 'attendance_record_daily_statistics_view',
  appDataEntityId: 'attendanceapp.attendance_record',
  sysCss: {
    cssName: 'daily_statistics_style',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onBeforeLoadDraft',
        logicTrigger: 'CTRLEVENT',
        logicType: 'SCRIPT',
        ctrlName: 'searchform',
        scriptCode:
          "const time = new Date(); // 当前时间\r\nconst startOfDay = new Date(time.getFullYear(), time.getMonth(), time.getDate()); // 今天的00:00:00\r\n\r\n// 格式化日期函数，保证两位数\r\nfunction formatDate(date) {\r\n  const y = date.getFullYear();\r\n  const m = date.getMonth() + 1;\r\n  const d = date.getDate();\r\n  return y + '-' + (m < 10 ? '0' + m : m) + '-' + (d < 10 ? '0' + d : d);\r\n}\r\n\r\nconst n_checkin_date_gtandeq = formatDate(startOfDay); // 今天\r\nconst n_checkin_date_ltandeq = formatDate(time);       // 当前时间\r\nconst date_range = n_checkin_date_gtandeq + ',' + n_checkin_date_ltandeq;\r\n\r\nObject.assign(viewParam, { n_checkin_date_gtandeq, n_checkin_date_ltandeq, date_range });\r\n",
        builtinLogic: true,
        name: 'DEFAULT_DATE_RANGE',
        id: 'default_date_range',
      },
      {
        eventNames: 'actionClick',
        logicTrigger: 'CTRLEVENT',
        logicType: 'SCRIPT',
        ctrlName: 'searchform',
        scriptCode: "consloe.log('actionClickform')",
        builtinLogic: true,
        name: 'ACTIONCLICKFORM',
        id: 'actionclickform',
      },
      {
        eventNames: 'onMounted',
        logicTrigger: 'CTRLEVENT',
        logicType: 'SCRIPT',
        ctrlName: 'grid',
        scriptCode:
          "//基本信息\r\nconst panelItems = view.layoutPanel.panelItems;\r\nconst grid = view.getController('grid');\r\nconst columns = ['member_name', 'member_num', 'dept_name',  'checkin_date', 'rule_name', 'shift_message', 'checkin_time', 'checkin_result', 'should_attendance_hours', 'billable_hours', 'working_hours',  'start_1', 'end_1'];\r\ngrid.state.columnStates.forEach((item) => {\r\n    if (columns.includes(item.key)) {\r\n        item.hidden = false\r\n    }else{\r\n        item.hidden = true\r\n    }\r\n})\r\n",
        builtinLogic: true,
        name: 'ACTIONCLICKGRID',
        id: 'actionclickgrid',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'attendanceapp.attendance_record_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'attendanceapp.attendance_record_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'attendanceapp.attendance_record_edit_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'attendanceapp.attendance_record_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '考勤记录编辑视图',
        refAppViewId: 'attendanceapp.attendance_record_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
      {
        realTitle: '考勤记录编辑视图',
        refAppViewId: 'attendanceapp.attendance_record_edit_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
    ],
    controls: [
      {
        searchButtonStyle: 'NONE',
        enableAutoSearch: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  align: 'flex-start',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    editor: {
                      enablePickupView: true,
                      pickupAppViewId:
                        'attendanceapp.user_object_preson_limit_m_pickup_view',
                      appDEACModeId: 'people',
                      appDEDataSetId: 'fetchdefault',
                      appDataEntityId: 'attendanceapp.user_object',
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        valuetype: 'OBJECTS',
                        objectnamefield: 'name',
                        keymapping: 'type:type;',
                        objectidfield: 'id',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'ADDRESSPICKUP',
                      objectIdField: 'id',
                      objectNameField: 'name',
                      valueType: 'OBJECTS',
                      editable: true,
                      id: 'n_member_id_in',
                    },
                    allowEmpty: true,
                    caption: '人员范围',
                    codeName: 'n_member_id_in',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'n_member_id_in',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    editor: {
                      editorParams: {
                        TIMEFMT: 'YYYY-MM-DD',
                      },
                      editorStyle: 'DATE_RANGE_EX',
                      editorType: 'DATERANGE_NOTIME',
                      editorItems: [
                        {
                          id: 'n_checkin_date_gtandeq',
                        },
                        {
                          id: 'n_checkin_date_ltandeq',
                        },
                      ],
                      sysPFPluginId: 'date_range_ex',
                      placeHolder: '开始日期;结束日期',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'date_range',
                    },
                    allowEmpty: true,
                    caption: '时间范围',
                    codeName: 'date_range',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'date_range',
                  },
                  {
                    actionType: 'UIACTION',
                    buttonStyle: 'DEFAULT',
                    uiactionId: 'searchbuttonclick',
                    tooltip: '查询',
                    uiactionTarget: 'NONE',
                    caption: '查询',
                    codeName: 'button1',
                    detailStyle: 'DEFAULT',
                    detailType: 'BUTTON',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      width: 100,
                      widthMode: 'PX',
                    },
                    showCaption: true,
                    id: 'button1',
                  },
                  {
                    actionType: 'UIACTION',
                    buttonStyle: 'DEFAULT',
                    uiactionId: 'export_report@attendance_record',
                    tooltip: '导出报表',
                    uiactionTarget: 'NONE',
                    caption: '导出报表',
                    codeName: 'button2',
                    detailStyle: 'DEFAULT',
                    detailType: 'BUTTON',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      width: 100,
                      widthMode: 'PX',
                    },
                    showCaption: true,
                    id: 'button2',
                  },
                ],
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'grouppanel1',
              },
              {
                createDV:
                  'member_name,member_num,dept_name,checkin_date,rule_name,shift,xqsyr,gys_infoname',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId:
                    'attendanceapp.attendance__dailystatisticsbase',
                  editorParams: {
                    DEFAULTDISABLEDLIST: '["member_name"]',
                  },
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'base_info',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '基本信息',
                codeName: 'base_info',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'base_info',
              },
              {
                createDV: '1',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorParams: {
                    customprops: '{"max":10,"min":1}',
                  },
                  editorType: 'NUMBER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'index_num',
                },
                allowEmpty: true,
                caption: '打卡信息',
                codeName: 'index_num',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 2,
                  colMD: 2,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'index_num',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  halign: 'LEFT',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  editorType: 'SPAN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'formitem',
                },
                allowEmpty: true,
                caption: '次上下班',
                codeName: 'formitem',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 1,
                  colMD: 1,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'formitem',
              },
              {
                createDV: 'checkin_time,checkin_result',
                dataType: 25,
                enableCond: 3,
                labelPos: 'NONE',
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId: 'attendanceapp.attendance__checkin_info',
                  editorParams: {
                    DEFAULTDISABLEDLIST: '["checkin_time"]',
                  },
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'check_in_info',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '表单项',
                codeName: 'check_in_info',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 8,
                  colMD: 8,
                  layout: 'TABLE_24COL',
                },
                id: 'check_in_info',
              },
              {
                createDV:
                  'should_attendance_hours,billable_hours,working_hours',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId: 'attendanceapp.attendance__durationstatistics',
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'duration_statistics',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '时长统计',
                codeName: 'duration_statistics',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'duration_statistics',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId: 'attendanceapp.attendance__abnormalstatistics',
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'abnormal_statistics',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '异常统计',
                codeName: 'abnormal_statistics',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'abnormal_statistics',
              },
              {
                dataType: 5,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'checkin_date',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_checkin_date_ltandeq',
                },
                valueFormat: 'YYYY-MM-DD',
                allowEmpty: true,
                hidden: true,
                caption: '考勤日期',
                codeName: 'n_checkin_date_ltandeq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'n_checkin_date_ltandeq',
              },
              {
                dataType: 5,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'checkin_date',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_checkin_date_gtandeq',
                },
                valueFormat: 'YYYY-MM-DD',
                allowEmpty: true,
                hidden: true,
                caption: '考勤日期',
                codeName: 'n_checkin_date_gtandeq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'n_checkin_date_gtandeq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main2',
        controlType: 'SEARCHFORM',
        logicName: '考勤数据每日统计表格视图_搜索表单',
        appDataEntityId: 'attendanceapp.attendance_record',
        controlLogics: [
          {
            eventNames: 'onChange',
            itemName: 'base_info',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].base_info || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['member_name', 'member_num', 'dept_name', 'title', 'checkin_date', 'rule_name', 'shift_message'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    if(item){\r\n        if (values.includes(key)) {\r\n            item.hidden = false;\r\n        } else {\r\n            item.hidden = true;\r\n        }\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'base_info',
          },
          {
            eventNames: 'onChange',
            itemName: 'check_in_info',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].check_in_info || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['checkin_time', 'checkin_result'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    if(item){\r\n        if (values.includes(key)) {\r\n            item.hidden = false;\r\n        } else {\r\n            item.hidden = true;\r\n        }\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'check_in_info',
          },
          {
            eventNames: 'onChange',
            itemName: 'duration_statistics',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].duration_statistics || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['should_attendance_hours', 'billable_hours', 'working_hours', 'late_minutes', 'leave_early_minutes', 'overtime_hours'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    if(item){\r\n        if (values.includes(key)) {\r\n            item.hidden = false;\r\n        } else {\r\n            item.hidden = true;\r\n        }\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'duration_statistics',
          },
          {
            eventNames: 'onChange',
            itemName: 'abnormal_statistics',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].abnormal_statistics || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['leave_duration', 'leave_type', 'on_business_days', 'out_hours'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    if(item){\r\n        if (values.includes(key)) {\r\n            item.hidden = false;\r\n        } else {\r\n            item.hidden = true;\r\n        }\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'abnormal_statistics',
          },
          {
            eventNames: 'onChange',
            itemName: 'index_num',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst columnStates = grid.state.columnStates\r\nconst value = data[0].index_num;\r\ncolumnStates.forEach( item => {\r\n    const suffix = parseInt(item.key.replace(/\\D/g, ''));\r\n    console.log(item.key, suffix);\r\n    if (suffix && suffix <= value) {\r\n        item.hidden = false;\r\n    } else if (suffix && suffix > value) {\r\n        item.hidden = true;\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'index_num',
          },
          {
            eventNames: 'onLoadDraftSuccess',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "console.log('每日统计搜索表单加载');\r\nconst curDate = new Date();\r\n// 几种默认值处理方式\r\nconst year = curDate.getFullYear();\r\nconst month = curDate.getMonth() + 1;\r\nconst day = curDate.getDate();\r\nconst tempMonth = month < 10 ? `0${month}` : month\r\nconst tempDay = day < 10 ? `0${day}` : day;\r\n// 今天\r\nconst end = `${year}-${tempMonth}-${tempDay}`;\r\n// 默认值为当前月一号到现在\r\n// const start = `${year}-${tempMonth}-01`;\r\n\r\n// 默认值为最新一个月时间,默认为31天，暂不考虑其他情况\r\n// const prevTime = curDate.getTime() - 1000 * 60 * 60 * 24 * 31;\r\n// const prevDate = new Date(prevTime);\r\n// let prevYear = prevDate.getFullYear();\r\n// let prevMonth = prevDate.getMonth() +1;\r\n// const prevDay = prevDate.getDate();\r\n// const start = `${prevYear}-${prevMonth}-${prevDay}`;\r\n\r\n// 默认值为今天\r\nconst start = end;\r\n\r\nObject.assign(ctrl.data, {\r\n    date_range: `${start},${end}`,\r\n    n_checkin_date_gtandeq: start,\r\n    n_checkin_date_ltandeq: end\r\n})",
            triggerType: 'CTRLEVENT',
            id: 'logic11',
          },
        ],
        controlParam: {
          ctrlParams: {
            FILTERPARAMS:
              '["n_member_id_in","n_checkin_date_gtandeq","n_checkin_date_ltandeq"]',
          },
          id: 'searchform',
        },
        modelId: '8ff02367d6add2c93062d3a533903eda',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'attendanceapp.attendance_record.main2',
      },
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        frozenFirstColumn: 1,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'member_name',
            excelCaption: '姓名',
            appDEFieldId: 'member_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.MEMBER_NAME',
            },
            caption: '姓名',
            codeName: 'member_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'member_name',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'member_num',
                excelCaption: '工号',
                appDEFieldId: 'member_num',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '工号',
                codeName: 'member_num',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                id: 'member_num',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'dept_name',
                excelCaption: '部门',
                appDEFieldId: 'dept_name',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'CENTER',
                caption: '部门',
                codeName: 'dept_name',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                id: 'dept_name',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'title',
                excelCaption: '职位',
                appDEFieldId: 'title',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'CENTER',
                caption: '职位',
                codeName: 'title',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                id: 'title',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'checkin_date',
                excelCaption: '日期',
                appDEFieldId: 'checkin_date',
                valueFormat: 'YYYY-MM-DD',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_DATE',
                },
                caption: '日期',
                codeName: 'checkin_date',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                id: 'checkin_date',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'rule_name',
                excelCaption: '考勤规则',
                appDEFieldId: 'rule_name',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.RULE_NAME',
                },
                caption: '考勤规则',
                codeName: 'rule_name',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                id: 'rule_name',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'shift_message',
                excelCaption: '班次',
                appDEFieldId: 'shift_message',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.SHIFT_MESSAGE',
                },
                caption: '班次',
                codeName: 'shift_message',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                id: 'shift_message',
              },
            ],
            aggMode: 'NONE',
            align: 'CENTER',
            caption: '基本信息',
            codeName: 'base_info',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'STAR',
            id: 'base_info',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班1打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班1打卡时间',
                codeName: 'start_1',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_1',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班1打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班1打卡时间',
                codeName: 'end_1',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_1',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班2打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班2打卡时间',
                codeName: 'start_2',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_2',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班2打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班2打卡时间',
                codeName: 'end_2',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_2',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班3打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班3打卡时间',
                codeName: 'start_3',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_3',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班3打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班3打卡时间',
                codeName: 'end_3',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_3',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班4打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班4打卡时间',
                codeName: 'start_4',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_4',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班4打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班4打卡时间',
                codeName: 'end_4',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_4',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班5打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班5打卡时间',
                codeName: 'start_5',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_5',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班5打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班5打卡时间',
                codeName: 'end_5',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_5',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班6打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班6打卡时间',
                codeName: 'start_6',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_6',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班6打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班6打卡时间',
                codeName: 'end_6',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_6',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班7打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班7打卡时间',
                codeName: 'start_7',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_7',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班7打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班7打卡时间',
                codeName: 'end_7',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_7',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班8打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班8打卡时间',
                codeName: 'start_8',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_8',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班8打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班8打卡时间',
                codeName: 'end_8',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_8',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班9打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班9打卡时间',
                codeName: 'start_9',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_9',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班9打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班9打卡时间',
                codeName: 'end_9',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_9',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班10打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班10打卡时间',
                codeName: 'start_10',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_10',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班10打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班10打卡时间',
                codeName: 'end_10',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_10',
              },
              {
                clconvertMode: 'FRONT',
                dataItemName: 'checkin_result',
                excelCaption: '考勤结果',
                appCodeListId: 'attendanceapp.attendance__attendance_result',
                appDEFieldId: 'checkin_result',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'CENTER',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_RESULT',
                },
                caption: '考勤结果',
                codeName: 'checkin_result',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                enableSort: true,
                id: 'checkin_result',
              },
            ],
            aggMode: 'NONE',
            caption: '打卡信息',
            codeName: 'groupgridcolumn2',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'STAR',
            id: 'groupgridcolumn2',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'should_attendance_hours',
                excelCaption: '应出勤时长（小时）',
                appDEFieldId: 'should_attendance_hours',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag:
                    'DEF.LNAME.ATTENDANCE_RECORD.SHOULD_ATTENDANCE_HOURS',
                },
                caption: '应出勤时长（小时）',
                codeName: 'should_attendance_hours',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                userParam: {
                  tooltip: '当天班次规定的工作时长',
                },
                id: 'should_attendance_hours',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'billable_hours',
                excelCaption: '计薪时长（小时）',
                appDEFieldId: 'billable_hours',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.BILLABLE_HOURS',
                },
                caption: '计薪时长（小时）',
                codeName: 'billable_hours',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                enableSort: true,
                userParam: {
                  tooltip:
                    '当天班次规定的工作时长减掉旷工时长和不带薪的假期时长',
                },
                id: 'billable_hours',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'working_hours',
                excelCaption: '实际出勤时长（小时）',
                appDEFieldId: 'working_hours',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.WORKING_HOURS',
                },
                caption: '实际出勤时长（小时）',
                codeName: 'working_hours',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 180,
                widthUnit: 'PX',
                enableSort: true,
                userParam: {
                  tooltip:
                    '当天班次的考勤周期内，早晚打卡时间相减并扣掉休息时间所得为实际出勤时长',
                },
                id: 'working_hours',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'late_minutes',
                excelCaption: '迟到时长（分钟）',
                appDEFieldId: 'late_minutes',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LATE_MINUTES',
                },
                caption: '迟到时长（分钟）',
                codeName: 'late_minutes',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                enableSort: true,
                id: 'late_minutes',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'leave_early_minutes',
                excelCaption: '早退时长（分钟）',
                appDEFieldId: 'leave_early_minutes',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LEAVE_EARLY_MINUTES',
                },
                caption: '早退时长（分钟）',
                codeName: 'leave_early_minutes',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                enableSort: true,
                id: 'leave_early_minutes',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'overtime_hours',
                excelCaption: '加班时长（小时）',
                appDEFieldId: 'overtime_hours',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OVERTIME_HOURS',
                },
                caption: '加班时长（小时）',
                codeName: 'overtime_hours',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                enableSort: true,
                id: 'overtime_hours',
              },
            ],
            aggMode: 'NONE',
            align: 'CENTER',
            caption: '时长统计',
            codeName: 'duration_statistics',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 700,
            widthUnit: 'STAR',
            id: 'duration_statistics',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'leave_duration',
                excelCaption: '请假时长(小时)',
                appDEFieldId: 'leave_duration',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                caption: '请假时长(小时)',
                codeName: 'leave_duration',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                enableSort: true,
                id: 'leave_duration',
              },
              {
                clconvertMode: 'FRONT',
                dataItemName: 'leave_type',
                excelCaption: '请假类型',
                appCodeListId: 'attendanceapp.attendance__holidaytype',
                appDEFieldId: 'leave_type',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '请假类型',
                codeName: 'leave_type',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                enableSort: true,
                id: 'leave_type',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'on_business_days',
                excelCaption: '出差天数',
                appDEFieldId: 'on_business_days',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.ON_BUSINESS_DAYS',
                },
                caption: '出差天数',
                codeName: 'on_business_days',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 120,
                widthUnit: 'PX',
                enableSort: true,
                id: 'on_business_days',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'out_hours',
                excelCaption: '外出时长（小时）',
                appDEFieldId: 'out_hours',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OUT_HOURS',
                },
                caption: '外出时长（小时）',
                codeName: 'out_hours',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 150,
                widthUnit: 'PX',
                enableSort: true,
                id: 'out_hours',
              },
            ],
            aggMode: 'NONE',
            align: 'CENTER',
            caption: '异常统计',
            codeName: 'abnormal_statistics',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'STAR',
            id: 'abnormal_statistics',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'member_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'member_name',
          },
          {
            appDEFieldId: 'member_num',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'member_num',
          },
          {
            appDEFieldId: 'dept_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'dept_name',
          },
          {
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'title',
          },
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'checkin_date',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'checkin_date',
          },
          {
            appDEFieldId: 'rule_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'rule_name',
          },
          {
            appDEFieldId: 'shift_message',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'shift_message',
          },
          {
            appDEFieldId: 'details',
            scriptCode:
              'let details = data.details;\r\nconst result = details?.filter(item => item.detail_index === metadata.column.codeName).map(item => item.checkin_time);\r\nreturn result;',
            valueType: 'OBJECTS',
            customCode: true,
            dataType: 21,
            id: 'details',
          },
          {
            appDEFieldId: 'checkin_result',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'checkin_result',
          },
          {
            appDEFieldId: 'should_attendance_hours',
            valueType: 'SIMPLE',
            dataType: 6,
            id: 'should_attendance_hours',
          },
          {
            appDEFieldId: 'billable_hours',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'billable_hours',
          },
          {
            appDEFieldId: 'working_hours',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'working_hours',
          },
          {
            appDEFieldId: 'late_minutes',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'late_minutes',
          },
          {
            appDEFieldId: 'leave_early_minutes',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'leave_early_minutes',
          },
          {
            appDEFieldId: 'overtime_hours',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'overtime_hours',
          },
          {
            appDEFieldId: 'leave_duration',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'leave_duration',
          },
          {
            appDEFieldId: 'leave_type',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'leave_type',
          },
          {
            appDEFieldId: 'on_business_days',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'on_business_days',
          },
          {
            appDEFieldId: 'out_hours',
            valueType: 'SIMPLE',
            dataType: 7,
            id: 'out_hours',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'member_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'member_id',
          },
          {
            appDEFieldId: 'rule_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'rule_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '考勤记录ID',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        singleSelect: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_record',
          appDataEntityId: 'attendanceapp.attendance_record',
          id: 'fetch',
        },
        dedataExportId: 'dataexport',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'attendanceapp.attendance_record',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main2',
        controlStyle: 'MONTH',
        controlType: 'GRID',
        logicName: '考勤数据每日统计表格视图_表格',
        appDataEntityId: 'attendanceapp.attendance_record',
        controlLogics: [
          {
            eventNames: 'onClick',
            itemName: 'start_1',
            logicTag: 'grid',
            logicType: 'APPDEUIACTION',
            appDEUIActionId: 'check_info@attendance_record',
            triggerType: 'CTRLEVENT',
            name: 'clickDetail',
            id: 'clickdetail',
          },
          {
            eventNames: 'onMounted',
            logicTag: 'grid',
            logicType: 'SCRIPT',
            triggerType: 'CTRLEVENT',
            id: 'default_hidden',
          },
        ],
        controlParam: {
          id: 'grid',
        },
        sysPFPluginId: 'month',
        modelId: '8ff02367d6add2c93062d3a533903eda',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'attendanceapp.attendance_record.main2',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'attendanceapp.attendance_record',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.ATTENDANCE_RECORD',
        },
        caption: '每日统计',
        codeName: 'daily_statistics_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'attendanceapp.attendance_record',
        controlParam: {},
        name: 'captionbar',
        id: 'daily_statistics_view_captionbar',
      },
    ],
    codeName: 'usr0603892371',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'DailyStatisticsView表格视图布局',
    appDataEntityId: 'attendanceapp.attendance_record',
    controlParam: {},
    modelId: 'bf2c13f2253595a1ce122f364d7ceae9',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0603892371',
  },
  title: '每日统计',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'df0f9e32bc2ea54538a8a1fa2c83424b',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_recordDailyStatisticsView',
  id: 'attendanceapp.attendance_record_daily_statistics_view',
};
