export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  openMode: 'POPUPMODAL',
  deviewCodeName: 'CheckInfoEditView',
  deviewId: '6ee4cac0536a7d1b4c954d99277fa92d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_RECORD',
  },
  caption: '考勤记录',
  codeName: 'attendance_record_check_info_edit_view',
  height: 685,
  appDataEntityId: 'attendanceapp.attendance_record',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'EditView',
      id: 'engine',
    },
  ],
  appViewNavContexts: [
    {
      rawValue: true,
      key: 'ID',
      name: 'ID',
      id: 'id',
    },
  ],
  controls: [
    {
      xdataControlName: 'form',
      codeName: 'check_info_edit_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '考勤记录反查编辑视图_工具栏',
      appDataEntityId: 'attendanceapp.attendance_record',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '609922da84c77775060e6230febeef87',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'check_info_edit_view_toolbar',
    },
    {
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'attendanceapp.attendance_record',
        id: 'create',
      },
      getDraftFromControlAction: {
        appDataEntityId: 'attendanceapp.attendance_record',
        id: 'loaddraftfrom',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'attendanceapp.attendance_record',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'attendanceapp.attendance_record',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'attendanceapp.attendance_record',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'attendanceapp.attendance_record',
        id: 'update',
      },
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          deformDetails: [
            {
              layout: {
                columnCount: 24,
                layout: 'TABLE_24COL',
              },
              deformDetails: [
                {
                  layout: {
                    align: 'flex-start',
                    dir: 'row',
                    layout: 'FLEX',
                    valign: 'center',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'NONE',
                      noPrivDisplayMode: 1,
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'member_name',
                      },
                      allowEmpty: true,
                      codeName: 'member_name',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'member_name',
                    },
                    {
                      rawItem: {
                        caption: '：',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem7',
                      },
                      codeName: 'rawitem7',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      showCaption: true,
                      id: 'rawitem7',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'NONE',
                      noPrivDisplayMode: 1,
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'checkin_date',
                      },
                      allowEmpty: true,
                      codeName: 'checkin_date',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                      },
                      id: 'checkin_date',
                    },
                  ],
                  codeName: 'base_info',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'base_info',
                },
                {
                  layout: {
                    dir: 'row',
                    layout: 'FLEX',
                  },
                  deformDetails: [
                    {
                      rawItem: {
                        caption: '考勤时间',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem2',
                      },
                      codeName: 'rawitem2',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem2',
                    },
                    {
                      rawItem: {
                        caption: '打卡时间',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem6',
                      },
                      codeName: 'rawitem6',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem6',
                    },
                    {
                      rawItem: {
                        caption: '打卡结果',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem5',
                      },
                      codeName: 'rawitem5',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem5',
                    },
                    {
                      rawItem: {
                        caption: '打卡地址',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem4',
                      },
                      codeName: 'rawitem4',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem4',
                    },
                    {
                      rawItem: {
                        caption: '打卡备注',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem3',
                      },
                      codeName: 'rawitem3',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem3',
                    },
                    {
                      rawItem: {
                        caption: '打卡图片',
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        contentType: 'RAW',
                        id: 'rawitem1',
                      },
                      codeName: 'rawitem1',
                      detailStyle: 'DEFAULT',
                      detailType: 'RAWITEM',
                      layoutPos: {
                        shrink: 1,
                        layout: 'FLEX',
                        width: 100,
                        widthMode: 'PX',
                      },
                      showCaption: true,
                      id: 'rawitem1',
                    },
                  ],
                  codeName: 'header',
                  detailStyle: 'DEFAULT',
                  detailType: 'GROUPPANEL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  id: 'header',
                },
                {
                  contentType: 'REPEATER',
                  layout: {
                    columnCount: 12,
                    layout: 'TABLE_12COL',
                  },
                  deformDetails: [
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'NONE',
                      noPrivDisplayMode: 1,
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'should_checkin_time',
                      },
                      allowEmpty: true,
                      codeName: 'should_checkin_time',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 2,
                        colMD: 2,
                        layout: 'TABLE_12COL',
                      },
                      repeatContent: true,
                      id: 'should_checkin_time',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'NONE',
                      noPrivDisplayMode: 1,
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'checkin_time',
                      },
                      allowEmpty: true,
                      codeName: 'checkin_time',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 2,
                        colMD: 2,
                        layout: 'TABLE_12COL',
                      },
                      repeatContent: true,
                      id: 'checkin_time',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      ignoreInput: 3,
                      labelPos: 'NONE',
                      noPrivDisplayMode: 1,
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        appCodeListId:
                          'attendanceapp.attendance__details_result',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'checkin_result',
                      },
                      allowEmpty: true,
                      convertToCodeItemText: true,
                      codeName: 'checkin_result',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 2,
                        colMD: 2,
                        layout: 'TABLE_12COL',
                      },
                      repeatContent: true,
                      id: 'checkin_result',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'NONE',
                      noPrivDisplayMode: 1,
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'checkin_place',
                      },
                      allowEmpty: true,
                      codeName: 'checkin_place',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 2,
                        colMD: 2,
                        layout: 'TABLE_12COL',
                      },
                      repeatContent: true,
                      id: 'checkin_place',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'NONE',
                      noPrivDisplayMode: 1,
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'checkin_remark',
                      },
                      allowEmpty: true,
                      codeName: 'checkin_remark',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 2,
                        colMD: 2,
                        layout: 'TABLE_12COL',
                      },
                      repeatContent: true,
                      id: 'checkin_remark',
                    },
                    {
                      dataType: 25,
                      enableCond: 3,
                      labelPos: 'NONE',
                      noPrivDisplayMode: 1,
                      editor: {
                        halign: 'LEFT',
                        valign: 'MIDDLE',
                        wrapMode: 'NOWRAP',
                        editorType: 'SPAN',
                        valueType: 'SIMPLE',
                        editable: true,
                        id: 'checkin_image',
                      },
                      allowEmpty: true,
                      codeName: 'checkin_image',
                      detailStyle: 'DEFAULT',
                      detailType: 'FORMITEM',
                      layoutPos: {
                        colLG: 2,
                        colMD: 2,
                        layout: 'TABLE_12COL',
                      },
                      repeatContent: true,
                      id: 'checkin_image',
                    },
                  ],
                  codeName: 'details',
                  detailStyle: 'DEFAULT',
                  detailType: 'MDCTRL',
                  layoutPos: {
                    colMD: 24,
                    layout: 'TABLE_24COL',
                  },
                  showCaption: true,
                  id: 'details',
                },
              ],
              caption: '考勤记录基本信息',
              codeName: 'group1',
              detailStyle: 'DEFAULT',
              detailType: 'GROUPPANEL',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'group1',
            },
            {
              dataType: 25,
              enableCond: 3,
              labelPos: 'LEFT',
              labelWidth: 130,
              noPrivDisplayMode: 1,
              appDEFieldId: 'id',
              editor: {
                editorType: 'HIDDEN',
                valueType: 'SIMPLE',
                editable: true,
                id: 'id',
              },
              allowEmpty: true,
              hidden: true,
              capLanguageRes: {
                lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.ID',
              },
              caption: '考勤记录ID',
              codeName: 'id',
              detailStyle: 'DEFAULT',
              detailType: 'FORMITEM',
              layoutPos: {
                colMD: 24,
                layout: 'TABLE_24COL',
              },
              id: 'id',
            },
          ],
          caption: '基本信息',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'check_info_edit_view_form',
      controlType: 'FORM',
      logicName: '考勤记录反查编辑视图_表单',
      appDataEntityId: 'attendanceapp.attendance_record',
      controlParam: {
        id: 'form',
      },
      modelId: 'e672315c1389fda3a5918fdb55336901',
      modelType: 'PSDEFORM_EDITFORM',
      name: 'form',
      id: 'attendanceapp.attendance_record.check_info_edit_view_form',
    },
    {
      codeName: 'check_info_edit_view_datainfobar',
      controlType: 'DATAINFOBAR',
      appDataEntityId: 'attendanceapp.attendance_record',
      controlParam: {
        id: 'datainfobar',
      },
      name: 'datainfobar',
      id: 'check_info_edit_view_datainfobar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.ATTENDANCE_RECORD',
      },
      caption: '考勤记录',
      codeName: 'check_info_edit_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'attendanceapp.attendance_record',
      controlParam: {},
      name: 'captionbar',
      id: 'check_info_edit_view_captionbar',
    },
  ],
  sysCss: {
    cssName: 'attendance_record_style',
  },
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEEDITVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'attendanceapp.attendance_record',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '考勤记录反查',
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  width: 700,
  enableDP: true,
  showCaptionBar: true,
  modelId: '21f6d8a8fc6f68cdb1759446ccbc5601',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_recordCheckInfoEditView',
  id: 'attendanceapp.attendance_record_check_info_edit_view',
};
