export default {
  tabLayout: 'TOP',
  enableSearch: true,
  expandSearchForm: true,
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'MonthlyStatisticsTabSearchView',
  deviewId: '4c5503710cf503543ba1978902302b98',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_STATISTICS',
  },
  caption: '月度汇总',
  codeName: 'attendance_statistics_monthly_statistics_tab_search_view',
  appDataEntityId: 'attendanceapp.attendance_statistics',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '搜索表单',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'searchform',
              },
              {
                rawItem: {
                  cssStyle: 'padding-top :16px',
                  predefinedType: 'TELEPORT_PLACEHOLDER',
                  id: 'tabtoolbar',
                },
                caption: '传送部件占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabtoolbar',
              },
              {
                rawItem: {
                  cssStyle: 'padding-top :16px',
                  predefinedType: 'TELEPORT_PLACEHOLDER',
                  id: 'tabtoolbar1',
                },
                caption: '传送部件占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabtoolbar1',
              },
            ],
            layout: {
              align: 'flex-start',
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container3',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '关系分页部件',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabexppanel',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentHeight: 54,
            height: 54,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              height: 54,
              heightMode: 'PX',
              layout: 'FLEX',
            },
            id: 'view_tabexppanel',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  predefinedType: 'NAV_POS',
                  id: 'nav_pos',
                },
                caption: '导航区占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'nav_pos',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_nav_pos',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        searchButtonStyle: 'NONE',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  align: 'flex-start',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 85,
                    noPrivDisplayMode: 1,
                    editor: {
                      enablePickupView: true,
                      pickupAppViewId:
                        'attendanceapp.user_object_preson_limit_m_pickup_view',
                      appDEACModeId: 'people',
                      appDEDataSetId: 'fetchdefault',
                      appDataEntityId: 'attendanceapp.user_object',
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        valuetype: 'OBJECTS',
                        objectnamefield: 'name',
                        keymapping: 'type:type',
                        objectidfield: 'id',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'ADDRESSPICKUP',
                      objectIdField: 'id',
                      objectNameField: 'name',
                      valueType: 'OBJECTS',
                      editable: true,
                      id: 'n_member_id_in',
                    },
                    allowEmpty: true,
                    caption: '人员范围',
                    codeName: 'n_member_id_in',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'n_member_id_in',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 85,
                    noPrivDisplayMode: 1,
                    editor: {
                      editorParams: {
                        TIMEFMT: 'YYYY-MM-DD',
                      },
                      editorStyle: 'DATE_RANGE_EX',
                      editorType: 'DATERANGE_NOTIME',
                      editorItems: [
                        {
                          id: 'n_checkin_date_gtandeq',
                        },
                        {
                          id: 'n_checkin_date_ltandeq',
                        },
                      ],
                      sysPFPluginId: 'date_range_ex',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'date_range',
                    },
                    allowEmpty: true,
                    caption: '时间范围',
                    codeName: 'date_range',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'date_range',
                  },
                  {
                    actionType: 'UIACTION',
                    buttonStyle: 'DEFAULT',
                    uiactionId: 'searchbuttonclick',
                    tooltip: '查询',
                    uiactionTarget: 'NONE',
                    caption: '查询',
                    codeName: 'button1',
                    detailStyle: 'DEFAULT',
                    detailType: 'BUTTON',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      width: 100,
                      widthMode: 'PX',
                    },
                    showCaption: true,
                    id: 'button1',
                  },
                ],
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'grouppanel1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_checkin_date_gtandeq',
                },
                allowEmpty: true,
                hidden: true,
                caption: '开始日期',
                codeName: 'n_checkin_date_gtandeq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'n_checkin_date_gtandeq',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_checkin_date_ltandeq',
                },
                allowEmpty: true,
                hidden: true,
                caption: '结束日期',
                codeName: 'n_checkin_date_ltandeq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'n_checkin_date_ltandeq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'monthly_statistics_search_form',
        controlType: 'SEARCHFORM',
        logicName: '月度汇总搜索表单',
        appDataEntityId: 'attendanceapp.attendance_statistics',
        controlParam: {
          id: 'searchform',
        },
        sysCss: {
          cssName: 'search_form_style',
        },
        modelId: '3c45d9247bb73e43dd4d38cebe92b1c9',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'attendanceapp.attendance_statistics.monthly_statistics_search_form',
      },
      {
        tabExpPageIds: ['all', 'personal'],
        tabLayout: 'TOP',
        uniqueTag:
          'attendance_statistics_monthly_statistics_tab_search_view__tabexppanel',
        appViewRefs: [
          {
            realTitle: '月度汇总',
            refAppViewId:
              'attendanceapp.attendance_statistics_monthly_statistics',
            name: 'EXPITEM:all',
            id: 'expitem:all',
          },
          {
            realTitle: '月度汇总个人卡片导航视图',
            refAppViewId: 'attendanceapp.employee_data_view_exp_view',
            name: 'EXPITEM:personal',
            id: 'expitem:personal',
          },
        ],
        controls: [
          {
            caption: '全员视图',
            embeddedAppDEViewId:
              'attendanceapp.attendance_statistics_monthly_statistics',
            codeName: 'monthly_statistics_tab_search_view_all',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'attendanceapp.attendance_statistics',
            controlParam: {
              id: 'all',
            },
            modelId: '307b5643282b0a27dd8b54c939ae5d0b_all',
            modelType: 'PSVIEWPANEL',
            name: 'all',
            id: 'monthly_statistics_tab_search_view_all',
          },
          {
            caption: '个人视图',
            embeddedAppDEViewId: 'attendanceapp.employee_data_view_exp_view',
            codeName: 'monthly_statistics_tab_search_view_personal',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'attendanceapp.attendance_statistics',
            controlParam: {
              id: 'personal',
            },
            modelId: '307b5643282b0a27dd8b54c939ae5d0b_personal',
            modelType: 'PSVIEWPANEL',
            name: 'personal',
            id: 'monthly_statistics_tab_search_view_personal',
          },
        ],
        codeName: 'monthly_statistics_tab_search_view_tabexppanel',
        controlType: 'TABEXPPANEL',
        appDataEntityId: 'attendanceapp.attendance_statistics',
        controlParam: {},
        modelId: '307b5643282b0a27dd8b54c939ae5d0b_tabexppanel',
        modelType: 'PSTABEXPPANEL',
        name: 'tabexppanel',
        id: 'monthly_statistics_tab_search_view_tabexppanel',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.ATTENDANCE_STATISTICS',
        },
        caption: '月度汇总',
        codeName: 'monthly_statistics_tab_search_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'attendanceapp.attendance_statistics',
        controlParam: {},
        name: 'captionbar',
        id: 'monthly_statistics_tab_search_view_captionbar',
      },
    ],
    codeName: 'usr0731975789',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'MonthlyStatisticsTabSearchView分页搜索视图布局面板',
    appDataEntityId: 'attendanceapp.attendance_statistics',
    controlLogics: [
      {
        eventNames: 'onBeforeLoadDraft',
        itemName: 'SEARCHFORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "console.log('触发加载草稿事件')\n\nconst current = new Date();\nconst year = current.getFullYear();\nconst month = current.getMonth() + 1;\nconst day = current.getDate();\nlet tempMonth = month;\nlet tempDay = day;\nif(month < 10){\n    tempMonth = `0${month}`\n}\nif(day < 10){\n    tempDay = `0${day}`\n}\n// 开始\nconst n_checkin_date_gtandeq = `${year}-${tempMonth}-01`\n// 结束\nconst n_checkin_date_ltandeq = `${year}-${tempMonth}-${tempDay}`\nconst date_range = `${n_checkin_date_gtandeq},${n_checkin_date_ltandeq}`\nObject.assign(ctrl.data, {\n    date_range: date_range,\n    n_checkin_date_gtandeq: n_checkin_date_gtandeq,\n    n_checkin_date_ltandeq: n_checkin_date_ltandeq\n})\n\nObject.assign(viewParam, {\n    n_checkin_date_gtandeq,\n    n_checkin_date_ltandeq,\n    date_range,\n});\n\nObject.assign(view.params, {\n    n_checkin_date_gtandeq,\n    n_checkin_date_ltandeq,\n    date_range,\n});",
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
    ],
    controlParam: {},
    modelId: '9a6d432ded9aac643a99bf94c885c49d',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0731975789',
  },
  title: '月度汇总',
  viewStyle: 'DEFAULT',
  viewType: 'DETABSEARCHVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '307b5643282b0a27dd8b54c939ae5d0b',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_statisticsMonthlyStatisticsTabSearchView',
  id: 'attendanceapp.attendance_statistics_monthly_statistics_tab_search_view',
};
