export default {
  expandSearchForm: true,
  xdataControlName: 'grid',
  loadDefault: true,
  deviewCodeName: 'AbnormalAttendance',
  deviewId: '2b6af5aeac95d46cf036d55df189203c',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_RECORD',
  },
  caption: '异常考勤',
  codeName: 'attendance_record_abnormal_attendance',
  appDataEntityId: 'attendanceapp.attendance_record',
  sysCss: {
    cssName: 'daily_statistics_style',
  },
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '搜索表单',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'searchform',
          },
        ],
        layout: {
          dir: 'column',
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            caption: '表格',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'grid',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'GridView',
        id: 'engine',
      },
    ],
    appViewLogics: [
      {
        eventNames: 'onMounted',
        logicTrigger: 'VIEWEVENT',
        logicType: 'SCRIPT',
        ctrlName: 'grid',
        scriptCode:
          "//基本信息\r\nconst grid = view.getController('grid');\r\nconst columns = ['title','shift_message', 'start_2', 'start_3', 'start_4', 'start_5', 'start_6', 'start_7', 'start_8', 'start_9', 'start_10', 'end_2', 'end_3', 'end_4', 'end_5', 'end_6', 'end_7', 'end_8', 'end_9', 'end_10'];\r\n\r\ngrid.state.columnStates.forEach((item) => {\r\n    if (columns.includes(item.key)) {\r\n        item.hidden = true\r\n    }else{\r\n        item.hidden = false\r\n    }\r\n})\r\n",
        builtinLogic: true,
        name: 'HIDDEN',
        id: 'hidden',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          actionAfterWizard: 'DEFAULT',
          newDataAppView: {
            refAppViewId: 'attendanceapp.attendance_record_edit_view',
          },
          appUILogicRefViews: [
            {
              refAppViewId: 'attendanceapp.attendance_record_edit_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_NEWDATA',
          id: '新建数据',
        },
        builtinLogic: true,
        id: 'newdata',
      },
      {
        logicTrigger: 'CUSTOM',
        logicType: 'APPUILOGIC',
        builtinAppUILogic: {
          openDataAppView: {
            refAppViewId: 'attendanceapp.attendance_record_redirect_view',
          },
          editMode: true,
          appUILogicRefViews: [
            {
              refAppViewId: 'attendanceapp.attendance_record_redirect_view',
            },
          ],
          builtinLogic: true,
          logicType: 'PREDEFINED',
          viewLogicType: 'APP_OPENDATA',
          id: '打开数据',
        },
        builtinLogic: true,
        id: 'opendata',
      },
    ],
    appViewRefs: [
      {
        realTitle: '考勤记录数据重定向视图',
        refAppViewId: 'attendanceapp.attendance_record_redirect_view',
        name: 'EDITDATA',
        id: 'editdata',
      },
      {
        realTitle: '考勤记录编辑视图',
        refAppViewId: 'attendanceapp.attendance_record_edit_view',
        name: 'NEWDATA',
        id: 'newdata',
      },
    ],
    controls: [
      {
        aggMode: 'NONE',
        columnEnableFilter: 2,
        columnEnableLink: 2,
        frozenFirstColumn: 1,
        groupMode: 'NONE',
        groupStyle: 'DEFAULT',
        degridColumns: [
          {
            clconvertMode: 'NONE',
            dataItemName: 'member_name',
            excelCaption: '姓名',
            appDEFieldId: 'member_name',
            valueType: 'SIMPLE',
            aggMode: 'NONE',
            align: 'LEFT',
            capLanguageRes: {
              lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.MEMBER_NAME',
            },
            caption: '姓名',
            codeName: 'member_name',
            columnType: 'DEFGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'STAR',
            enableSort: true,
            id: 'member_name',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'member_num',
                excelCaption: '工号',
                appDEFieldId: 'member_num',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '工号',
                codeName: 'member_num',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                id: 'member_num',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'dept_name',
                excelCaption: '部门',
                appDEFieldId: 'dept_name',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'CENTER',
                caption: '部门',
                codeName: 'dept_name',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                id: 'dept_name',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'title',
                excelCaption: '职位',
                appDEFieldId: 'title',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'CENTER',
                caption: '职位',
                codeName: 'title',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                id: 'title',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'checkin_date',
                excelCaption: '日期',
                appDEFieldId: 'checkin_date',
                valueFormat: 'YYYY-MM-DD',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_DATE',
                },
                caption: '日期',
                codeName: 'checkin_date',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                enableSort: true,
                id: 'checkin_date',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'rule_name',
                excelCaption: '考勤规则',
                appDEFieldId: 'rule_name',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.RULE_NAME',
                },
                caption: '考勤规则',
                codeName: 'rule_name',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 220,
                widthUnit: 'PX',
                enableSort: true,
                id: 'rule_name',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'shift_message',
                excelCaption: '班次',
                appDEFieldId: 'shift_message',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.SHIFT_MESSAGE',
                },
                caption: '班次',
                codeName: 'shift_message',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 220,
                widthUnit: 'PX',
                enableSort: true,
                id: 'shift_message',
              },
            ],
            aggMode: 'NONE',
            align: 'CENTER',
            caption: '基本信息',
            codeName: 'base_info',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'STAR',
            id: 'base_info',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班1打开时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班1打开时间',
                codeName: 'start_1',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_1',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班1打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班1打卡时间',
                codeName: 'end_1',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_1',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班2打开时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班2打开时间',
                codeName: 'start_2',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_2',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班2打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班2打卡时间',
                codeName: 'end_2',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_2',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班3打开时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班3打开时间',
                codeName: 'start_3',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_3',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班3打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班3打卡时间',
                codeName: 'end_3',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_3',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班4打开时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班4打开时间',
                codeName: 'start_4',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_4',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班4打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班4打卡时间',
                codeName: 'end_4',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_4',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班5打开时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班5打开时间',
                codeName: 'start_5',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_5',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班5打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班5打卡时间',
                codeName: 'end_5',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_5',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班6打开时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班6打开时间',
                codeName: 'start_6',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_6',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班6打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班6打卡时间',
                codeName: 'end_6',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_6',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班7打开时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班7打开时间',
                codeName: 'start_7',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_7',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班7打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班7打卡时间',
                codeName: 'end_7',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_7',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班8打开时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班8打开时间',
                codeName: 'start_8',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_8',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班8打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班8打卡时间',
                codeName: 'end_8',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_8',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班9打开时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班9打开时间',
                codeName: 'start_9',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_9',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班9打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班9打卡时间',
                codeName: 'end_9',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_9',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '上班10打开时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '上班10打开时间',
                codeName: 'start_10',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'start_10',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'details',
                excelCaption: '下班10打卡时间',
                objectIdField: 'id',
                objectNameField: 'name',
                appDEFieldId: 'details',
                deuiactionId: 'check_info_vail@attendance_record',
                valueType: 'OBJECTS',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'LEFT',
                caption: '下班10打卡时间',
                codeName: 'end_10',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 200,
                widthUnit: 'PX',
                id: 'end_10',
              },
              {
                clconvertMode: 'FRONT',
                dataItemName: 'checkin_result',
                excelCaption: '考勤结果',
                appCodeListId: 'attendanceapp.attendance__attendance_result',
                appDEFieldId: 'checkin_result',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'CENTER',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_RESULT',
                },
                caption: '考勤结果',
                codeName: 'checkin_result',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 220,
                widthUnit: 'PX',
                enableSort: true,
                id: 'checkin_result',
              },
            ],
            aggMode: 'NONE',
            caption: '打卡信息',
            codeName: 'groupgridcolumn2',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 100,
            widthUnit: 'STAR',
            id: 'groupgridcolumn2',
          },
          {
            degridColumns: [
              {
                clconvertMode: 'NONE',
                dataItemName: 'late_minutes',
                excelCaption: '迟到时长（分钟）',
                appDEFieldId: 'late_minutes',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LATE_MINUTES',
                },
                caption: '迟到时长（分钟）',
                codeName: 'late_minutes',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 220,
                widthUnit: 'PX',
                enableSort: true,
                id: 'late_minutes',
              },
              {
                clconvertMode: 'NONE',
                dataItemName: 'leave_early_minutes',
                excelCaption: '早退时长（分钟）',
                appDEFieldId: 'leave_early_minutes',
                valueType: 'SIMPLE',
                enableCond: 3,
                allowEmpty: true,
                aggMode: 'NONE',
                align: 'RIGHT',
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LEAVE_EARLY_MINUTES',
                },
                caption: '早退时长（分钟）',
                codeName: 'leave_early_minutes',
                columnType: 'DEFGRIDCOLUMN',
                noPrivDisplayMode: 1,
                width: 220,
                widthUnit: 'PX',
                enableSort: true,
                id: 'leave_early_minutes',
              },
            ],
            aggMode: 'NONE',
            align: 'CENTER',
            caption: '时长统计',
            codeName: 'duration_statistics',
            columnType: 'GROUPGRIDCOLUMN',
            noPrivDisplayMode: 1,
            width: 700,
            widthUnit: 'STAR',
            id: 'duration_statistics',
          },
        ],
        degridDataItems: [
          {
            appDEFieldId: 'member_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'member_name',
          },
          {
            appDEFieldId: 'member_num',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'member_num',
          },
          {
            appDEFieldId: 'dept_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'dept_name',
          },
          {
            appDEFieldId: 'title',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'title',
          },
          {
            format: 'YYYY-MM-DD',
            appDEFieldId: 'checkin_date',
            valueType: 'SIMPLE',
            dataType: 5,
            id: 'checkin_date',
          },
          {
            appDEFieldId: 'rule_name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'rule_name',
          },
          {
            appDEFieldId: 'shift_message',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'shift_message',
          },
          {
            appDEFieldId: 'details',
            scriptCode:
              'let details = data.details;\r\nconst result = details?.filter(item => item.detail_index === metadata.column.codeName).map(item => item.checkin_time);\r\nreturn result;',
            valueType: 'OBJECTS',
            customCode: true,
            dataType: 21,
            id: 'details',
          },
          {
            appDEFieldId: 'checkin_result',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'checkin_result',
          },
          {
            appDEFieldId: 'late_minutes',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'late_minutes',
          },
          {
            appDEFieldId: 'leave_early_minutes',
            valueType: 'SIMPLE',
            dataType: 9,
            id: 'leave_early_minutes',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfkey',
          },
          {
            appDEFieldId: 'id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfdataaccaction',
          },
          {
            appDEFieldId: 'member_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'member_id',
          },
          {
            appDEFieldId: 'rule_id',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'rule_id',
          },
          {
            appDEFieldId: 'name',
            valueType: 'SIMPLE',
            dataType: 25,
            id: 'srfmajortext',
          },
        ],
        degridEditItems: [
          {
            caption: '考勤记录ID',
            codeName: 'srfkey',
            enableCond: 3,
            appDEFieldId: 'id',
            editor: {
              editorType: 'HIDDEN',
              valueType: 'SIMPLE',
              editable: true,
              id: 'srfkey',
            },
            allowEmpty: true,
            id: 'srfkey',
          },
        ],
        pagingMode: 1,
        pagingSize: 20,
        sortMode: 'REMOTE',
        enableCustomized: true,
        enablePagingBar: true,
        singleSelect: true,
        navViewPos: 'NONE',
        fetchControlAction: {
          appDEMethodId: 'fetch_abnormal_attendance',
          appDataEntityId: 'attendanceapp.attendance_record',
          id: 'fetch',
        },
        dedataExportId: 'abnormalattendance',
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'attendanceapp.attendance_record',
          id: 'remove',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'abnormal_attendance_grid',
        controlType: 'GRID',
        logicName: '异常考勤表格',
        appDataEntityId: 'attendanceapp.attendance_record',
        controlLogics: [
          {
            eventNames: 'onMounted',
            logicTag: 'grid',
            logicType: 'SCRIPT',
            triggerType: 'CTRLEVENT',
            id: 'default_hidden',
          },
        ],
        controlParam: {
          id: 'grid',
        },
        modelId: '29d8069f7485323d695563de77aecb9a',
        modelType: 'PSDEGRID',
        name: 'grid',
        id: 'attendanceapp.attendance_record.abnormal_attendance_grid',
      },
      {
        searchButtonStyle: 'NONE',
        enableAutoSearch: true,
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  align: 'flex-start',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    editor: {
                      enablePickupView: true,
                      pickupAppViewId:
                        'attendanceapp.user_object_preson_limit_m_pickup_view',
                      appDEACModeId: 'people',
                      appDEDataSetId: 'fetchdefault',
                      appDataEntityId: 'attendanceapp.user_object',
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        valuetype: 'OBJECTS',
                        objectnamefield: 'name',
                        keymapping: 'type:type;',
                        objectidfield: 'id',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'ADDRESSPICKUP',
                      objectIdField: 'id',
                      objectNameField: 'name',
                      valueType: 'OBJECTS',
                      editable: true,
                      id: 'n_member_id_in',
                    },
                    allowEmpty: true,
                    caption: '人员范围',
                    codeName: 'n_member_id_in',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'n_member_id_in',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    editor: {
                      editorParams: {
                        TIMEFMT: 'YYYY-MM-DD',
                      },
                      editorStyle: 'DATE_RANGE_EX',
                      editorType: 'DATERANGE_NOTIME',
                      editorItems: [
                        {
                          id: 'n_checkin_date_gtandeq',
                        },
                        {
                          id: 'n_checkin_date_ltandeq',
                        },
                      ],
                      sysPFPluginId: 'date_range_ex',
                      placeHolder: '开始日期;结束日期',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'date_range',
                    },
                    allowEmpty: true,
                    caption: '时间范围',
                    codeName: 'date_range',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'date_range',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'checkin_result',
                    editor: {
                      singleSelect: true,
                      appCodeListId:
                        'attendanceapp.attendance__attendance_result',
                      editorType: 'DROPDOWNLIST',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'n_checkin_result_eq',
                    },
                    allowEmpty: true,
                    needCodeListConfig: true,
                    capLanguageRes: {
                      lanResTag:
                        'CONTROL.DEFSFITEM.ATTENDANCE_RECORD.N_CHECKIN_RESULT_EQ',
                    },
                    caption: '异常状态',
                    codeName: 'n_checkin_result_eq',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'n_checkin_result_eq',
                  },
                  {
                    actionType: 'UIACTION',
                    buttonStyle: 'DEFAULT',
                    uiactionId: 'searchbuttonclick',
                    tooltip: '查询',
                    uiactionTarget: 'NONE',
                    caption: '查询',
                    codeName: 'button1',
                    detailStyle: 'DEFAULT',
                    detailType: 'BUTTON',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      width: 100,
                      widthMode: 'PX',
                    },
                    showCaption: true,
                    id: 'button1',
                  },
                  {
                    actionType: 'UIACTION',
                    buttonStyle: 'DEFAULT',
                    uiactionId: 'abnormalattendance@attendance_record',
                    tooltip: '导出报表',
                    uiactionTarget: 'NONE',
                    caption: '导出报表',
                    codeName: 'button2',
                    detailStyle: 'DEFAULT',
                    detailType: 'BUTTON',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      width: 100,
                      widthMode: 'PX',
                    },
                    showCaption: true,
                    id: 'button2',
                  },
                ],
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'grouppanel1',
              },
              {
                createDV:
                  'member_name,member_num,dept_name,checkin_date,rule_name,shift,xqsyr,gys_infoname',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId:
                    'attendanceapp.attendance__dailystatisticsbase',
                  editorParams: {
                    DEFAULTDISABLEDLIST: '["member_name"]',
                  },
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'base_info',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '基本信息',
                codeName: 'base_info',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'base_info',
              },
              {
                createDV: '1',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  maxValue: 10,
                  minValue: 1,
                  editorParams: {
                    minvalue: '1',
                    maxvalue: '10',
                  },
                  editorType: 'NUMBER',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'index_num',
                },
                allowEmpty: true,
                caption: '打卡信息',
                codeName: 'index_num',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 2,
                  colMD: 2,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'index_num',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  halign: 'LEFT',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  editorType: 'SPAN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'formitem3',
                },
                allowEmpty: true,
                caption: '次上下班',
                codeName: 'formitem3',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 1,
                  colMD: 1,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'formitem3',
              },
              {
                createDV: 'checkin_time,checkin_result',
                dataType: 25,
                enableCond: 3,
                labelPos: 'NONE',
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId: 'attendanceapp.attendance__checkin_info',
                  editorParams: {
                    DEFAULTDISABLEDLIST: '["checkin_time","checkin_result"]',
                  },
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'check_in_info',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '打卡信息',
                codeName: 'check_in_info',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colLG: 6,
                  colMD: 6,
                  layout: 'TABLE_24COL',
                },
                id: 'check_in_info',
              },
              {
                createDV: 'late_minutes,leave_early_minutes',
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  appCodeListId: 'attendanceapp.duration',
                  editorType: 'CHECKBOXLIST',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'duration_statistics',
                },
                allowEmpty: true,
                needCodeListConfig: true,
                caption: '时长统计',
                codeName: 'duration_statistics',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'duration_statistics',
              },
              {
                dataType: 5,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'checkin_date',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_checkin_date_ltandeq',
                },
                valueFormat: 'YYYY-MM-DD',
                allowEmpty: true,
                hidden: true,
                caption: '考勤日期',
                codeName: 'n_checkin_date_ltandeq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'n_checkin_date_ltandeq',
              },
              {
                dataType: 5,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'checkin_date',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_checkin_date_gtandeq',
                },
                valueFormat: 'YYYY-MM-DD',
                allowEmpty: true,
                hidden: true,
                caption: '考勤日期',
                codeName: 'n_checkin_date_gtandeq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'n_checkin_date_gtandeq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'abnormal_attendance_search_form',
        controlType: 'SEARCHFORM',
        logicName: '异常考勤表格视图_搜索表单',
        appDataEntityId: 'attendanceapp.attendance_record',
        controlLogics: [
          {
            eventNames: 'onChange',
            itemName: 'base_info',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].base_info || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['member_name', 'member_num', 'dept_name', 'title', 'checkin_date', 'rule_name', 'shift_message'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    if(item){\r\n        if (values.includes(key)) {\r\n            item.hidden = false;\r\n        } else {\r\n            item.hidden = true;\r\n        }\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'base_info',
          },
          {
            eventNames: 'onChange',
            itemName: 'check_in_info',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].check_in_info || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['checkin_time', 'checkin_result'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    if(item){\r\n        if (values.includes(key)) {\r\n            item.hidden = false;\r\n        } else {\r\n            item.hidden = true;\r\n        }\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'check_in_info',
          },
          {
            eventNames: 'onChange',
            itemName: 'duration_statistics',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst value = data[0].duration_statistics || '';\r\nconst values = value.split(',').filter(item => item !== \"\");\r\nconst cols = ['late_minutes', 'leave_early_minutes'];\r\ncols.forEach(key => {\r\n    const item = grid.state.columnStates.find(x => x.key === key);\r\n    if(item){\r\n        if (values.includes(key)) {\r\n            item.hidden = false;\r\n        } else {\r\n            item.hidden = true;\r\n        }\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'duration_statistics',
          },
          {
            eventNames: 'onChange',
            itemName: 'index_num',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "const grid = view.getController('grid');\r\nconst columnStates = grid.state.columnStates\r\nconst value = data[0].index_num;\r\ncolumnStates.forEach( item => {\r\n    const suffix = parseInt(item.key.replace(/\\D/g, ''));\r\n    console.log(item.key, suffix);\r\n    if (suffix && suffix <= value) {\r\n        item.hidden = false;\r\n    } else if (suffix && suffix > value) {\r\n        item.hidden = true;\r\n    }\r\n});",
            triggerType: 'CTRLEVENT',
            id: 'index_num',
          },
          {
            eventNames: 'onLoadDraftSuccess',
            logicTag: 'searchform',
            logicType: 'SCRIPT',
            scriptCode:
              "console.log('异常考勤搜索表单加载');\r\nconst curDate = new Date();\r\n// 几种默认值处理方式\r\nconst year = curDate.getFullYear();\r\nconst month = curDate.getMonth() + 1;\r\nconst day = curDate.getDate();\r\nconst tempMonth = month < 10 ? `0${month}` : month\r\nconst tempDay = day < 10 ? `0${day}` : day;\r\n// 今天\r\nconst end = `${year}-${tempMonth}-${tempDay}`;\r\n// 默认值为当前月一号到现在\r\n// const start = `${year}-${tempMonth}-01`;\r\n\r\n// 默认值为最新一个月时间,默认为31天，暂不考虑其他情况\r\n// const prevTime = curDate.getTime() - 1000 * 60 * 60 * 24 * 31;\r\n// const prevDate = new Date(prevTime);\r\n// let prevYear = prevDate.getFullYear();\r\n// let prevMonth = prevDate.getMonth() +1;\r\n// const prevDay = prevDate.getDate();\r\n// const start = `${prevYear}-${prevMonth}-${prevDay}`;\r\n\r\n// 默认值为今天\r\nconst start = end;\r\n\r\nObject.assign(ctrl.data, {\r\n    date_range: `${start},${end}`,\r\n    n_checkin_date_gtandeq: start,\r\n    n_checkin_date_ltandeq: end\r\n})",
            triggerType: 'CTRLEVENT',
            id: 'loaddraftsuccess',
          },
        ],
        controlParam: {
          ctrlParams: {
            FILTERPARAMS:
              '["n_member_id_in","n_checkin_date_gtandeq","n_checkin_date_ltandeq","n_checkin_result_eq"]',
          },
          id: 'searchform',
        },
        modelId: 'eb903f6b4d303957a7e9490dc7106772',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'attendanceapp.attendance_record.abnormal_attendance_search_form',
      },
      {
        groupMode: 'SINGLE',
        controlType: 'SEARCHBAR',
        appDataEntityId: 'attendanceapp.attendance_record',
        controlParam: {
          id: 'searchbar',
        },
        id: 'searchbar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.ATTENDANCE_RECORD',
        },
        caption: '异常考勤',
        codeName: 'abnormal_attendance_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'attendanceapp.attendance_record',
        controlParam: {},
        name: 'captionbar',
        id: 'abnormal_attendance_captionbar',
      },
    ],
    codeName: 'usr0605864388',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'AbnormalAttendance表格视图布局',
    appDataEntityId: 'attendanceapp.attendance_record',
    controlParam: {},
    modelId: '2ad1ef2dd552ff60d414ade70e74c971',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0605864388',
  },
  title: '异常考勤',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '17fa93e7f8e0726d2a1a34a166c06a7c',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_recordAbnormalAttendance',
  id: 'attendanceapp.attendance_record_abnormal_attendance',
};
