export default {
  redirectAppViewRefs: [
    {
      realTitle: '考勤记录编辑视图',
      refAppViewId: 'attendanceapp.attendance_record_edit_view',
      name: 'ATTENDANCE_RECORD:EDITVIEW',
      id: 'attendance_record:editview',
    },
    {
      realTitle: '考勤记录编辑视图',
      refAppViewId: 'attendanceapp.attendance_record_edit_view',
      name: 'EDITVIEW',
      id: 'editview',
    },
  ],
  enableWorkflow: true,
  funcViewMode: 'REDIRECTVIEW',
  deviewCodeName: 'RedirectView',
  deviewId: 'd602a124e74f54f63ce983975c5434d2',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_RECORD',
  },
  caption: '考勤记录',
  codeName: 'attendance_record_redirect_view',
  appDataEntityId: 'attendanceapp.attendance_record',
  controls: [
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.ATTENDANCE_RECORD',
      },
      caption: '考勤记录',
      codeName: 'redirect_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'attendanceapp.attendance_record',
      controlParam: {},
      name: 'captionbar',
      id: 'redirect_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEREDIRECTVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'attendanceapp.attendance_record',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '考勤记录数据重定向视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEREDIRECTVIEW',
  enableDP: true,
  redirectView: true,
  showCaptionBar: true,
  modelId: '93cb18794b8c724d8ffa4d55db0f7515',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_recordRedirectView',
  id: 'attendanceapp.attendance_record_redirect_view',
};
