export default {
  tabLayout: 'TOP',
  enableSearch: true,
  expandSearchForm: true,
  loadDefault: true,
  showDataInfoBar: true,
  deviewCodeName: 'TabSearchView',
  deviewId: '6c385e85153ebb6fabbf32e3f426234b',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_CLOCK_IN_RECORD',
  },
  caption: '打卡记录',
  codeName: 'attendance_clock_in_record_tab_search_view',
  appDataEntityId: 'attendanceapp.attendance_clock_in_record',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_right',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '搜索表单',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'searchform',
              },
              {
                rawItem: {
                  cssStyle: 'padding-top :16px',
                  predefinedType: 'TELEPORT_PLACEHOLDER',
                  id: 'tabtoolbar',
                },
                caption: '传送部件占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabtoolbar',
              },
              {
                rawItem: {
                  cssStyle: 'padding-top :16px',
                  predefinedType: 'TELEPORT_PLACEHOLDER',
                  id: 'tabtoolbar1',
                },
                caption: '传送部件占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabtoolbar1',
              },
            ],
            layout: {
              align: 'flex-start',
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container3',
          },
        ],
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_searchform',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                caption: '关系分页部件',
                itemStyle: 'DEFAULT',
                itemType: 'CTRLPOS',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'tabexppanel',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            contentHeight: 54,
            height: 54,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 0,
              height: 54,
              heightMode: 'PX',
              layout: 'FLEX',
            },
            id: 'view_tabexppanel',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  predefinedType: 'NAV_POS',
                  id: 'nav_pos',
                },
                caption: '导航区占位',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'nav_pos',
              },
            ],
            layout: {
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'view_nav_pos',
          },
        ],
        predefinedType: 'VIEWCONTENT',
        layout: {
          layout: 'FLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          grow: 1,
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'view_content',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        searchButtonStyle: 'NONE',
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  align: 'flex-start',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                deformDetails: [
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 85,
                    noPrivDisplayMode: 1,
                    editor: {
                      enablePickupView: true,
                      pickupAppViewId:
                        'attendanceapp.user_object_preson_limit_m_pickup_view',
                      appDEACModeId: 'people',
                      appDEDataSetId: 'fetchdefault',
                      appDataEntityId: 'attendanceapp.user_object',
                      forceSelection: true,
                      showTrigger: true,
                      editorParams: {
                        valuetype: 'OBJECTS',
                        objectnamefield: 'name',
                        keymapping: 'type:type',
                        objectidfield: 'id',
                        PICKUPVIEW: 'TRUE',
                      },
                      editorType: 'ADDRESSPICKUP',
                      objectIdField: 'id',
                      objectNameField: 'name',
                      valueType: 'OBJECTS',
                      editable: true,
                      id: 'n_member_id_in',
                    },
                    allowEmpty: true,
                    caption: '人员范围',
                    codeName: 'n_member_id_in',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'n_member_id_in',
                  },
                  {
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 85,
                    noPrivDisplayMode: 1,
                    editor: {
                      editorParams: {
                        TIMEFMT: 'YYYY-MM-DD',
                        customProps: '{"format":"yyyy-MM-dd"}',
                      },
                      editorStyle: 'DATE_RANGE_EX',
                      editorType: 'DATERANGE_NOTIME',
                      editorItems: [
                        {
                          id: 'n_checkin_time_gtandeq',
                        },
                        {
                          id: 'n_checkin_time_ltandeq',
                        },
                      ],
                      sysPFPluginId: 'date_range_ex',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'date_range',
                    },
                    allowEmpty: true,
                    caption: '时间范围',
                    codeName: 'date_range',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'date_range',
                  },
                  {
                    actionType: 'UIACTION',
                    buttonStyle: 'DEFAULT',
                    uiactionId: 'searchbuttonclick',
                    tooltip: '查询',
                    uiactionTarget: 'NONE',
                    caption: '查询',
                    codeName: 'button1',
                    detailStyle: 'DEFAULT',
                    detailType: 'BUTTON',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      width: 100,
                      widthMode: 'PX',
                    },
                    showCaption: true,
                    id: 'button1',
                  },
                ],
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'grouppanel1',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_checkin_time_ltandeq',
                },
                allowEmpty: true,
                hidden: true,
                caption: '打卡时间',
                codeName: 'n_checkin_time_ltandeq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'n_checkin_time_ltandeq',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'n_checkin_time_gtandeq',
                },
                allowEmpty: true,
                hidden: true,
                caption: '打卡时间',
                codeName: 'n_checkin_time_gtandeq',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'n_checkin_time_gtandeq',
              },
            ],
            caption: '常规条件',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'search_form',
        controlType: 'SEARCHFORM',
        logicName: '打卡记录搜索表单',
        appDataEntityId: 'attendanceapp.attendance_clock_in_record',
        controlParam: {
          id: 'searchform',
        },
        sysCss: {
          cssName: 'search_form_style',
        },
        modelId: 'c7eadd1d63a6b6f11e6af9a3696fc657',
        modelType: 'PSDEFORM_SEARCHFORM',
        name: 'searchform',
        id: 'attendanceapp.attendance_clock_in_record.search_form',
      },
      {
        tabExpPageIds: ['list', 'month'],
        tabLayout: 'TOP',
        uniqueTag: 'attendance_clock_in_record_tab_search_view__tabexppanel',
        appViewRefs: [
          {
            realTitle: '打卡记录表格视图',
            refAppViewId: 'attendanceapp.attendance_clock_in_record_grid_view',
            name: 'EXPITEM:list',
            id: 'expitem:list',
          },
          {
            realTitle: '月度视图',
            refAppViewId:
              'attendanceapp.attendance_clock_in_record_monthly_clock_in_record',
            name: 'EXPITEM:month',
            id: 'expitem:month',
          },
        ],
        controls: [
          {
            caption: '列表视图',
            embeddedAppDEViewId:
              'attendanceapp.attendance_clock_in_record_grid_view',
            codeName: 'tab_search_view_list',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'attendanceapp.attendance_clock_in_record',
            controlParam: {
              id: 'list',
            },
            modelId: '6d814db5ec949ad3df21eefa8399b004_list',
            modelType: 'PSVIEWPANEL',
            name: 'list',
            id: 'tab_search_view_list',
          },
          {
            caption: '月度视图',
            embeddedAppDEViewId:
              'attendanceapp.attendance_clock_in_record_monthly_clock_in_record',
            codeName: 'tab_search_view_month',
            controlType: 'TABVIEWPANEL',
            appDataEntityId: 'attendanceapp.attendance_clock_in_record',
            controlParam: {
              id: 'month',
            },
            modelId: '6d814db5ec949ad3df21eefa8399b004_month',
            modelType: 'PSVIEWPANEL',
            name: 'month',
            id: 'tab_search_view_month',
          },
        ],
        codeName: 'tab_search_view_tabexppanel',
        controlType: 'TABEXPPANEL',
        appDataEntityId: 'attendanceapp.attendance_clock_in_record',
        controlParam: {},
        modelId: '6d814db5ec949ad3df21eefa8399b004_tabexppanel',
        modelType: 'PSTABEXPPANEL',
        name: 'tabexppanel',
        id: 'tab_search_view_tabexppanel',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.ATTENDANCE_CLOCK_IN_RECORD',
        },
        caption: '打卡记录',
        codeName: 'tab_search_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'attendanceapp.attendance_clock_in_record',
        controlParam: {},
        name: 'captionbar',
        id: 'tab_search_view_captionbar',
      },
    ],
    codeName: 'usr0731975787',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '打卡记录分页搜索视图布局面板',
    appDataEntityId: 'attendanceapp.attendance_clock_in_record',
    controlLogics: [
      {
        eventNames: 'onBeforeLoadDraft',
        itemName: 'SEARCHFORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          "console.log('打卡记录搜索表单加载');\r\nconst curDate = new Date();\r\n// 几种默认值处理方式\r\nconst year = curDate.getFullYear();\r\nconst month = curDate.getMonth() + 1;\r\nconst day = curDate.getDate();\r\nconst tempMonth = month < 10 ? `0${month}` : month\r\nconst tempDay = day < 10 ? `0${day}` : day;\r\n// 今天\r\nconst end = `${year}-${tempMonth}-${tempDay}`;\r\n// 默认值为今天\r\nconst starttime = `${end} 00:00:00`;\r\nconst endtime = `${end} 23:59:59`\r\n\r\nObject.assign(ctrl.data, {\r\n    date_range: `${starttime},${endtime}`,\r\n    n_checkin_time_gtandeq: starttime,\r\n    n_checkin_time_ltandeq: endtime\r\n})\r\nObject.assign(view.params, {\r\n    date_range: `${starttime},${endtime}`,\r\n    n_checkin_time_gtandeq: starttime,\r\n    n_checkin_time_ltandeq: endtime\r\n})\r\nObject.assign(viewParam, {\r\n    date_range: `${starttime},${endtime}`,\r\n    n_checkin_time_gtandeq: starttime,\r\n    n_checkin_time_ltandeq: endtime\r\n})",
        triggerType: 'CTRLEVENT',
        id: 'logic1',
      },
    ],
    controlParam: {},
    modelId: 'e80589aa962349589d1fdb6a9139a15d',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0731975787',
  },
  title: '打卡记录',
  viewStyle: 'DEFAULT',
  viewType: 'DETABSEARCHVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '6d814db5ec949ad3df21eefa8399b004',
  modelType: 'PSAPPDEVIEW',
  name: 'attendance_clock_in_recordTabSearchView',
  id: 'attendanceapp.attendance_clock_in_record_tab_search_view',
};
