export default {
  blankMode: true,
  caption: '自助考勤模式',
  codeName: 'blank_index_view',
  controls: [
    {
      layoutMode: 'TABLE_24COL',
      appMenuItems: [
        {
          accUserMode: 2,
          itemType: 'MENUITEM',
          appFuncId: 'appfunc10',
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          layoutPos: {
            colMD: 24,
            layout: 'TABLE_24COL',
          },
          openDefault: true,
          valid: true,
          caption: '自助考勤模式',
          tooltip: '自助考勤模式',
          expanded: true,
          id: 'menuitem1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'blank_index_view',
      controlType: 'APPMENU',
      logicName: '应用首页视图',
      controlParam: {},
      modelId: 'bfcd7af1530c536b70cb2ce4713b0525',
      modelType: 'PSAPPMENU',
      name: 'appmenu',
      id: 'blank_index_view',
    },
    {
      caption: '自助考勤模式',
      codeName: 'captionbar',
      controlType: 'CAPTIONBAR',
      controlParam: {},
      id: 'captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPINDEXVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '应用首页视图',
  viewStyle: 'DEFAULT',
  viewType: 'APPINDEXVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'a5085720538c9ddcff979340884715ca',
  modelType: 'PSAPPINDEXVIEW',
  name: 'blank_index_view',
  id: 'attendanceapp.blank_index_view',
};
