export default {
  appSwitchMode: 1,
  mainMenuAlign: 'TOP',
  defaultPage: true,
  enableAppSwitch: true,
  caption: '出勤',
  codeName: 'hr_attendance_index_view',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        rawItem: {
                          rawItemParams: [
                            {
                              key: 'navmode',
                              value: 'store',
                              id: 'panelitem',
                            },
                            {
                              key: 'navmode',
                              value: 'store',
                            },
                          ],
                          predefinedType: 'NAV_BREADCRUMB',
                          id: 'nav_breadcrumb',
                        },
                        caption: '面包屑导航',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          shrink: 1,
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'nav_breadcrumb',
                      },
                      {
                        rawItem: {
                          predefinedType: 'NAV_POS_INDEX',
                          id: 'nav_pos_index',
                        },
                        caption: '导航区占位',
                        itemStyle: 'DEFAULT',
                        itemType: 'RAWITEM',
                        layoutPos: {
                          grow: 1,
                          shrink: 1,
                          heightMode: 'FULL',
                          layout: 'FLEX',
                        },
                        showCaption: true,
                        id: 'nav_pos_index',
                      },
                    ],
                    layout: {
                      layout: 'FLEX',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    contentHeight: 100,
                    height: 100,
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      height: 100,
                      heightMode: 'FULL',
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container4_all',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                },
                id: 'container6_all',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_MAIN',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentWidth: 100,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'CENTER',
              layout: 'BORDER',
              width: 100,
              widthMode: 'PERCENTAGE',
            },
            showCaption: true,
            id: 'container_scroll_main',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    actionGroupExtractMode: 'ITEM',
                    panelItems: [
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              contentType: 'USER',
                              rawItemParams: [
                                {
                                  key: 'sourcetype',
                                  value: 'UTIL',
                                },
                              ],
                              predefinedType: 'APP_SWITCH',
                              id: 'app_switch',
                            },
                            caption: '应用切换器',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                              spacingLeft: 'OUTERMEDIUM',
                            },
                            showCaption: true,
                            id: 'app_switch',
                          },
                          {
                            caption: '首页菜单',
                            contentHeight: 60,
                            contentWidth: 800,
                            height: 60,
                            itemStyle: 'DEFAULT',
                            itemType: 'CTRLPOS',
                            layoutPos: {
                              grow: 1,
                              shrink: 1,
                              height: 60,
                              heightMode: 'PX',
                              layout: 'FLEX',
                              width: 800,
                              widthMode: 'PX',
                            },
                            width: 800,
                            showCaption: true,
                            id: 'appmenu',
                          },
                        ],
                        layout: {
                          align: 'flex-start',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        id: 'container2',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            rawItem: {
                              caption: '文本内容',
                              halign: 'LEFT',
                              renderMode: 'TEXT',
                              valign: 'MIDDLE',
                              wrapMode: 'NOWRAP',
                              contentType: 'RAW',
                              predefinedType: 'INDEX_VIEW_SEARCH',
                              id: 'index_view_search',
                            },
                            caption: '搜索栏',
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 1,
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'index_view_search',
                          },
                        ],
                        layout: {
                          align: 'center',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        contentHeight: 52,
                        height: 52,
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          height: 52,
                          heightMode: 'PX',
                          layout: 'FLEX',
                        },
                        id: 'container',
                      },
                      {
                        actionGroupExtractMode: 'ITEM',
                        panelItems: [
                          {
                            actionGroupExtractMode: 'ITEM',
                            panelItems: [
                              {
                                rawItem: {
                                  contentType: 'IMAGE',
                                  predefinedType: 'USERMESSAGE',
                                  id: 'usermessage',
                                },
                                caption: '消息通知',
                                itemStyle: 'DEFAULT',
                                itemType: 'RAWITEM',
                                layoutPos: {
                                  shrink: 1,
                                  heightMode: 'FULL',
                                  layout: 'FLEX',
                                  widthMode: 'FULL',
                                },
                                showCaption: true,
                                id: 'usermessage',
                              },
                            ],
                            layout: {
                              layout: 'FLEX',
                            },
                            dataRegionType: 'INHERIT',
                            caption: '容器',
                            contentHeight: 48,
                            contentWidth: 48,
                            height: 48,
                            itemStyle: 'DEFAULT',
                            itemType: 'CONTAINER',
                            layoutPos: {
                              shrink: 1,
                              height: 48,
                              heightMode: 'PX',
                              layout: 'FLEX',
                              width: 48,
                              widthMode: 'PX',
                            },
                            width: 48,
                            id: 'container1',
                          },
                          {
                            rawItem: {
                              predefinedType: 'AUTH_USERINFO',
                              rawItemHeight: 60,
                              id: 'auth_userinfo',
                            },
                            caption: '用户信息',
                            contentHeight: 60,
                            height: 60,
                            itemStyle: 'DEFAULT',
                            itemType: 'RAWITEM',
                            layoutPos: {
                              shrink: 0,
                              height: 60,
                              heightMode: 'PX',
                              layout: 'FLEX',
                            },
                            showCaption: true,
                            id: 'auth_userinfo',
                          },
                        ],
                        predefinedType: 'INDEX_ACTIONS',
                        layout: {
                          align: 'space-between',
                          dir: 'row',
                          layout: 'FLEX',
                          valign: 'center',
                        },
                        dataRegionType: 'INHERIT',
                        caption: '容器',
                        itemStyle: 'DEFAULT',
                        itemType: 'CONTAINER',
                        layoutPos: {
                          shrink: 0,
                          layout: 'FLEX',
                        },
                        id: 'indexactions',
                      },
                    ],
                    layout: {
                      align: 'space-between',
                      dir: 'row',
                      layout: 'FLEX',
                      valign: 'center',
                    },
                    dataRegionType: 'INHERIT',
                    caption: '容器',
                    itemStyle: 'DEFAULT',
                    itemType: 'CONTAINER',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                      widthMode: 'FULL',
                    },
                    id: 'container7',
                  },
                ],
                predefinedType: 'AppHeader',
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  layoutPos: 'CENTER',
                  heightMode: 'FULL',
                  layout: 'BORDER',
                  widthMode: 'FULL',
                },
                id: 'app_header',
              },
            ],
            predefinedType: 'CONTAINER_SCROLL_HEADER',
            layout: {
              layout: 'BORDER',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            contentHeight: 60,
            height: 60,
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              layoutPos: 'NORTH',
              height: 60,
              heightMode: 'PX',
              layout: 'BORDER',
            },
            showCaption: true,
            id: 'container_scroll_header',
          },
        ],
        predefinedType: 'CONTAINER_SCROLL',
        layout: {
          layout: 'BORDER',
        },
        dataRegionType: 'INHERIT',
        caption: '滚动条容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_scroll1',
      },
    ],
    layoutPanel: true,
    controls: [
      {
        layoutMode: 'TABLE_24COL',
        appMenuItems: [
          {
            itemType: 'MENUITEM',
            appMenuItems: [
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'attentdance_attentdance',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                openDefault: true,
                valid: true,
                caption: '概览',
                tooltip: '概览',
                id: 'attentdance_attentdance',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'appfunc4',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                openDefault: true,
                valid: true,
                caption: '管理',
                tooltip: '管理',
                id: 'menuitem9',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'appfunc8',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                openDefault: true,
                valid: true,
                caption: '报表',
                tooltip: '报表',
                id: 'menuitem14',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '出勤',
            tooltip: '出勤',
            id: 'menuitem17',
          },
          {
            itemType: 'MENUITEM',
            appFuncId: 'appfunc12',
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '自助考勤模式',
            tooltip: '自助考勤模式',
            id: 'menuitem19',
          },
          {
            itemType: 'MENUITEM',
            appMenuItems: [
              {
                accUserMode: 4,
                accessKey: 'ATTENDANCE_RULE',
                itemType: 'MENUITEM',
                appFuncId: 'appfunc',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '考勤规则',
                tooltip: '考勤规则',
                id: 'menuitem12',
              },
              {
                accUserMode: 4,
                accessKey: 'ATTENDANCE_SCHEDULE',
                itemType: 'MENUITEM',
                appFuncId: 'appfunc5',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '排班视图',
                tooltip: '排班视图',
                id: 'menuitem13',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '考勤设置',
            tooltip: '考勤设置',
            id: 'menuitem1',
          },
          {
            itemType: 'MENUITEM',
            appMenuItems: [
              {
                accUserMode: 4,
                accessKey: 'DAILYSTATISTICS',
                itemType: 'MENUITEM',
                appFuncId: 'dailystatistics',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                openDefault: true,
                valid: true,
                caption: '每日统计',
                tooltip: '每日统计',
                id: 'menuitem5',
              },
              {
                accUserMode: 4,
                accessKey: 'ABNORMALATTENDANCE',
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0605038736',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '异常考勤',
                tooltip: '异常考勤',
                id: 'menuitem6',
              },
              {
                accUserMode: 4,
                accessKey: 'MONTHLYSTATISTICS',
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0605131726',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '月度汇总',
                tooltip: '月度汇总',
                id: 'menuitem7',
              },
              {
                accUserMode: 4,
                accessKey: 'ATTENDANCE_DEPARTMENT_STATISTICS',
                itemType: 'MENUITEM',
                appFuncId: 'usrappfunc0605137873',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '部门统计',
                tooltip: '部门统计',
                id: 'menuitem8',
              },
              {
                accUserMode: 4,
                accessKey: 'ATTENDANCE_CLOCK_IN_RECORD',
                itemType: 'MENUITEM',
                appFuncId: 'appfunc3',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '打卡记录',
                tooltip: '打卡记录',
                id: 'menuitem4',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '考勤数据',
            tooltip: '考勤数据',
            id: 'menuitem2',
          },
          {
            itemType: 'MENUITEM',
            appMenuItems: [
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'appfunc9',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '公共假期类型',
                tooltip: '公共假期类型',
                id: 'menuitem11',
              },
              {
                accUserMode: 2,
                itemType: 'MENUITEM',
                appFuncId: 'appfunc2',
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                valid: true,
                caption: '公共假期',
                tooltip: '公共假期',
                id: 'menuitem3',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            layoutPos: {
              colMD: 24,
              layout: 'TABLE_24COL',
            },
            valid: true,
            caption: '假期管理',
            tooltip: '假期管理',
            id: 'menuitem10',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'hr_attendance_index_view',
        controlType: 'APPMENU',
        logicName: '应用首页视图',
        controlParam: {},
        modelId: 'bb72e9195091d0f9bf41d5d0c8c559f1',
        modelType: 'PSAPPMENU',
        name: 'appmenu',
        id: 'hr_attendance_index_view',
      },
      {
        caption: '出勤',
        subCaption: '出勤',
        codeName: 'captionbar',
        controlType: 'CAPTIONBAR',
        controlParam: {},
        id: 'captionbar',
      },
    ],
    codeName: 'usr0816975858',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: 'AppIndexView',
    controlParam: {},
    modelId: '21f3f21b39a12e6aa06af432c6ee2d0b',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'usr0816975858',
  },
  subCaption: '出勤',
  title: '应用首页视图',
  viewStyle: 'DEFAULT',
  viewType: 'APPINDEXVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'a1ddedea8f9a3dd86ca65b28cf21e2e8',
  modelType: 'PSAPPINDEXVIEW',
  name: 'hr_attendance_index_view',
  id: 'attendanceapp.hr_attendance_index_view',
};
