export default {
  enableDirtyChecking: true,
  showDataInfoBar: true,
  xdataControlName: 'form',
  loadDefault: true,
  funcViewMode: 'EDITVIEW',
  deviewCodeName: 'main_view',
  deviewId: 'fb2fa2c83139edcefd9d9227ebaf32a8',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.HR_ATTENDANCE',
  },
  caption: '出勤',
  codeName: 'hr_attendance_main_view',
  appDataEntityId: 'attendanceapp.hr_attendance',
  viewLayoutPanel: {
    viewProxyMode: true,
    layoutMode: 'FLEX',
    layout: {
      layout: 'FLEX',
    },
    rootPanelItems: [
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar1',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                id: 'container2',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '页面标题',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    sysPFPluginId: 'identifier_title',
                    showCaption: true,
                    userTag: 'identifier',
                    id: 'captionbar',
                  },
                ],
                layout: {
                  align: 'center',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_captionbar',
              },
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '工具栏',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'toolbar',
                  },
                ],
                layout: {
                  align: 'center',
                  dir: 'row',
                  layout: 'FLEX',
                  valign: 'center',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  shrink: 1,
                  heightMode: 'FULL',
                  layout: 'FLEX',
                },
                id: 'view_toolbar',
              },
            ],
            layout: {
              dir: 'row',
              layout: 'FLEX',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              heightMode: 'FULL',
              layout: 'FLEX',
            },
            id: 'view_header_left',
          },
          {
            caption: '关系数据栏',
            itemStyle: 'DEFAULT',
            itemType: 'CTRLPOS',
            layoutPos: {
              grow: 1,
              shrink: 1,
              layout: 'FLEX',
            },
            showCaption: true,
            id: 'drbar',
          },
        ],
        predefinedType: 'VIEWHEADER',
        layout: {
          align: 'space-between',
          dir: 'row',
          layout: 'FLEX',
          valign: 'center',
        },
        dataRegionType: 'INHERIT',
        caption: '容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        id: 'view_header',
      },
      {
        rawItem: {
          rawItemParams: [
            {
              key: 'POSITION',
              value: 'TOP',
            },
          ],
          predefinedType: 'VIEWMSG_POS',
          id: 'viewmsg_pos',
        },
        caption: '视图消息占位',
        itemStyle: 'DEFAULT',
        itemType: 'RAWITEM',
        layoutPos: {
          shrink: 0,
          layout: 'FLEX',
        },
        showCaption: true,
        id: 'viewmsg_pos',
      },
      {
        actionGroupExtractMode: 'ITEM',
        panelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '表单',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 0,
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'form',
                  },
                ],
                predefinedType: 'VIEWCONTENT',
                layout: {
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'view_content',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 8,
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container',
          },
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                actionGroupExtractMode: 'ITEM',
                panelItems: [
                  {
                    caption: '实体部件',
                    itemStyle: 'DEFAULT',
                    itemType: 'CTRLPOS',
                    layoutPos: {
                      grow: 1,
                      shrink: 1,
                      heightMode: 'FULL',
                      layout: 'FLEX',
                    },
                    showCaption: true,
                    id: 'control',
                  },
                ],
                layout: {
                  dir: 'column',
                  layout: 'FLEX',
                },
                dataRegionType: 'INHERIT',
                caption: '容器',
                itemStyle: 'DEFAULT',
                itemType: 'CONTAINER',
                layoutPos: {
                  colMD: 24,
                  heightMode: 'FULL',
                  layout: 'TABLE_24COL',
                },
                id: 'mail_thread_panel',
              },
            ],
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            dataRegionType: 'INHERIT',
            caption: '面板容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              grow: 4,
              shrink: 1,
              layout: 'SIMPLEFLEX',
            },
            id: 'container1',
          },
        ],
        predefinedType: 'CONTAINER_GRID',
        layout: {
          layout: 'SIMPLEFLEX',
        },
        dataRegionType: 'INHERIT',
        caption: '栅格容器',
        itemStyle: 'DEFAULT',
        itemType: 'CONTAINER',
        layoutPos: {
          shrink: 1,
          layout: 'FLEX',
        },
        id: 'container_grid',
      },
    ],
    layoutPanel: true,
    appViewEngines: [
      {
        engineCat: 'VIEW',
        engineType: 'EditView',
        id: 'engine',
      },
    ],
    controls: [
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            detoolbarItems: [
              {
                actionLevel: 100,
                groupExtractMode: 'ITEM',
                uiactionGroup: {
                  uiactionGroupDetails: [
                    {
                      actionLevel: 100,
                      afterItemType: 'NONE',
                      beforeItemType: 'NONE',
                      buttonStyle: 'DEFAULT',
                      capLanguageRes: {
                        lanResTag: 'TBB.TEXT.EDITVIEW.REMOVEANDCLOSE',
                      },
                      caption: '删除并关闭',
                      detailType: 'DEUIACTION',
                      uiactionId: 'editview_removeandexitaction',
                      tooltipLanguageRes: {
                        lanResTag: 'TBB.TOOLTIP.EDITVIEW.REMOVEANDCLOSE',
                      },
                      showCaption: true,
                      showIcon: true,
                      sysImage: {
                        cssClass: 'fa fa-remove',
                        glyph: 'xf00d@FontAwesome',
                      },
                      id: 'u157c2ca',
                    },
                  ],
                  name: '通用编辑页面删除界面行为组',
                  id: 'auto90393125',
                },
                valid: true,
                itemType: 'ITEMS',
                showCaption: true,
                showIcon: true,
                id: 'deuiaction2',
              },
            ],
            valid: true,
            caption: '更多',
            itemType: 'ITEMS',
            sysImage: {
              cssClass: 'fa fa-cog',
              glyph: 'xf013@FontAwesome',
            },
            tooltip: '更多',
            showIcon: true,
            id: 'items1',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_saveaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.SAVE',
            },
            caption: '保存',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_save',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-cloud-upload',
              glyph: 'xf0ee@FontAwesome',
            },
            tooltip: '保存',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.SAVE',
            },
            showIcon: true,
            id: 'toolbar_save',
          },
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'data_cancelchanges',
            valid: true,
            caption: '取消变更',
            itemType: 'DEUIACTION',
            controlLogics: [
              {
                itemName: 'toolbar_cancel',
                logicTag: 'toolbar',
                logicType: 'SCRIPT',
                scriptCode:
                  'data.id == null || view.getController("form").state.modified || ibiz.uiDomainManager.get(view.context.srfsessionid).dataModification',
                triggerType: 'ITEMVISIBLE',
                id: 'logic2',
              },
            ],
            sysImage: {
              cssClass: 'fa fa-times',
              glyph: 'xf00d@FontAwesome',
            },
            tooltip: '取消变更',
            showIcon: true,
            id: 'toolbar_cancel',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（默认主视图）',
        appDataEntityId: 'attendanceapp.hr_attendance',
        controlParam: {
          id: 'toolbar',
        },
        modelId: '8f5624914fcfc7bbc63de650a6b2aa59',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar',
        id: 'main_view_toolbar',
      },
      {
        detoolbarItems: [
          {
            actionLevel: 100,
            noPrivDisplayMode: 2,
            uiactionId: 'editview_newaction',
            valid: true,
            capLanguageRes: {
              lanResTag: 'TBB.TEXT.*.NEW',
            },
            caption: '新建',
            itemType: 'DEUIACTION',
            sysImage: {
              cssClass: 'fa fa-file-text-o',
              glyph: 'xf0f6@FontAwesome',
            },
            tooltip: '新建',
            tooltipLanguageRes: {
              lanResTag: 'TBB.TOOLTIP.*.NEW',
            },
            showCaption: true,
            id: 'deuiaction2',
          },
        ],
        xdataControlName: 'form',
        codeName: 'main_view_toolbar1',
        controlType: 'TOOLBAR',
        logicName: '工具栏模板（嵌入编辑表单，只有一个新建按钮）',
        appDataEntityId: 'attendanceapp.hr_attendance',
        controlParam: {
          id: 'toolbar1',
        },
        modelId: '6a271f6ceebaa5b850a3e67f7ec201b2',
        modelType: 'PSDETOOLBAR',
        name: 'toolbar1',
        id: 'main_view_toolbar1',
      },
      {
        createControlAction: {
          appDEMethodId: 'create',
          appDataEntityId: 'attendanceapp.hr_attendance',
          id: 'create',
        },
        getDraftFromControlAction: {
          appDataEntityId: 'attendanceapp.hr_attendance',
          id: 'loaddraftfrom',
        },
        getDraftControlAction: {
          appDEMethodId: 'get_draft',
          appDataEntityId: 'attendanceapp.hr_attendance',
          id: 'loaddraft',
        },
        getControlAction: {
          appDEMethodId: 'get',
          appDataEntityId: 'attendanceapp.hr_attendance',
          id: 'load',
        },
        removeControlAction: {
          appDEMethodId: 'remove',
          appDataEntityId: 'attendanceapp.hr_attendance',
          id: 'remove',
        },
        updateControlAction: {
          appDEMethodId: 'update',
          appDataEntityId: 'attendanceapp.hr_attendance',
          id: 'update',
        },
        deformItemUpdates: [
          {
            codeName: 'ComputeWorkHour',
            appDEMethodId: 'compute_work_hour',
            defiupdateDetails: [
              {
                id: 'worked_hours',
              },
              {
                id: 'overtime_hours',
              },
            ],
            showBusyIndicator: true,
            name: '计算工作/加班时间',
            id: 'computeworkhour',
          },
        ],
        deformPages: [
          {
            layout: {
              columnCount: 24,
              layout: 'TABLE_24COL',
            },
            deformDetails: [
              {
                layout: {
                  align: 'space-between',
                  dir: 'row-reverse',
                  layout: 'FLEX',
                },
                deformDetails: [
                  {
                    createDV: 'to_approve',
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'NONE',
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'overtime_status',
                    editor: {
                      singleSelect: true,
                      appCodeListId:
                        'attendanceapp.hr__hr_attendance_overtime_status',
                      editorParams: {
                        duration_tracking: 'duration_tracking',
                      },
                      editorStyle: 'STATUS_BAR',
                      editorType: 'DROPDOWNLIST',
                      sysPFPluginId: 'odoo_status_bar',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'overtime_status',
                    },
                    allowEmpty: true,
                    needCodeListConfig: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.HR_ATTENDANCE.OVERTIME_STATUS',
                    },
                    caption: '加班状态',
                    codeName: 'overtime_status',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      shrink: 1,
                      layout: 'FLEX',
                    },
                    id: 'overtime_status',
                  },
                ],
                codeName: 'grouppanel1',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'grouppanel1',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        createDVT: 'OPERATORNAME',
                        dataType: 25,
                        enableCond: 3,
                        itemWidth: 390,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'employee_name',
                        deformItemUpdateId: 'computeworkhour',
                        editor: {
                          singleSelect: true,
                          handlerType: 'PickupText',
                          appDEACModeId: 'default',
                          appDEDataSetId: 'fetch_default',
                          appDataEntityId: 'attendanceapp.hr_employee',
                          enableAC: true,
                          forceSelection: true,
                          showTrigger: true,
                          valueItemName: 'employee_id',
                          editorParams: {
                            URL: '/hr_employees/fetch_default',
                            ISSHOWTAB: 'false',
                            USERMAP: '{"id":"id","name":"name"}',
                            AC: 'TRUE',
                            USERMETHOD: 'post',
                            TRIGGER: 'TRUE',
                            PICKUPVIEW: 'FALSE',
                          },
                          editorStyle: 'PERSONEL_SELECT_EMP',
                          editorType: 'PICKEREX_TRIGGER',
                          editorWidth: 260,
                          editorItems: [
                            {
                              id: 'employee_id',
                            },
                          ],
                          sysPFPluginId: 'person_select',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'employee_name',
                        },
                        caption: '员工',
                        codeName: 'employee_name',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 20,
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'employee_name',
                      },
                      {
                        createDVT: 'CURTIME',
                        dataType: 5,
                        enableCond: 3,
                        itemWidth: 390,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'check_in',
                        deformItemUpdateId: 'computeworkhour',
                        editor: {
                          dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                          editorParams: {
                            TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                          },
                          editorType: 'DATEPICKER',
                          editorWidth: 260,
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'check_in',
                        },
                        valueFormat: 'YYYY-MM-DD HH:mm:ss',
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.CHECK_IN',
                        },
                        caption: '签到',
                        codeName: 'check_in',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 20,
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'check_in',
                      },
                      {
                        dataType: 5,
                        enableCond: 3,
                        itemWidth: 390,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'check_out',
                        deformItemUpdateId: 'computeworkhour',
                        editor: {
                          dateTimeFormat: 'YYYY-MM-DD HH:mm:ss',
                          editorParams: {
                            TIMEFMT: 'YYYY-MM-DD HH:mm:ss',
                          },
                          editorType: 'DATEPICKER',
                          editorWidth: 260,
                          placeHolder: '目前工作中',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'check_out',
                        },
                        valueFormat: 'YYYY-MM-DD HH:mm:ss',
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.CHECK_OUT',
                        },
                        caption: '签离',
                        codeName: 'check_out',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 20,
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'check_out',
                      },
                    ],
                    codeName: 'grouppanel6',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel6',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        createDV: '0.0',
                        dataType: 7,
                        itemWidth: 280,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'worked_hours',
                        editor: {
                          precision: 2,
                          editorType: 'NUMBER',
                          editorWidth: 150,
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'worked_hours',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.WORKED_HOURS',
                        },
                        caption: '已工作时间',
                        codeName: 'worked_hours',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'worked_hours',
                      },
                      {
                        layout: {
                          columnCount: 24,
                          layout: 'TABLE_24COL',
                        },
                        deformDetails: [
                          {
                            createDV: '0.0',
                            dataType: 7,
                            enableCond: 3,
                            itemWidth: 280,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'overtime_hours',
                            editor: {
                              precision: 2,
                              editorType: 'NUMBER',
                              editorWidth: 150,
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'overtime_hours',
                            },
                            allowEmpty: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.HR_ATTENDANCE.OVERTIME_HOURS',
                            },
                            caption: '加班时间',
                            codeName: 'overtime_hours',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colLG: 12,
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            showCaption: true,
                            id: 'overtime_hours',
                          },
                          {
                            actionType: 'UIACTION',
                            buttonStyle: 'DEFAULT',
                            uiactionId: 'approveovertime@hr_attendance',
                            tooltip: '批准',
                            uiactionTarget: 'SINGLEDATA',
                            caption: '批准',
                            codeName: 'button1',
                            detailStyle: 'DEFAULT',
                            detailType: 'BUTTON',
                            controlLogics: [
                              {
                                itemName: 'button1',
                                logicTag: 'form',
                                logicType: 'SCRIPT',
                                scriptCode: '!ctrl.state.modified',
                                triggerType: 'ITEMVISIBLE',
                                id: 'button1',
                              },
                            ],
                            defdgroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedDetailNames: [
                                  'check_out',
                                  'overtime_status',
                                ],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'ISNOTNULL',
                                    defdname: 'check_out',
                                    logicType: 'SINGLE',
                                    name: 'check_out值不为空(NotNil)',
                                    id: 'check_out值不为空(notnil)',
                                  },
                                  {
                                    groupOP: 'OR',
                                    defdlogics: [
                                      {
                                        condOP: 'EQ',
                                        defdname: 'overtime_status',
                                        value: 'to_approve',
                                        logicType: 'SINGLE',
                                        id: 'overtime_status等于(=) to_approve',
                                      },
                                      {
                                        condOP: 'EQ',
                                        defdname: 'overtime_status',
                                        value: 'refused',
                                        logicType: 'SINGLE',
                                        id: 'overtime_status等于(=) refused',
                                      },
                                    ],
                                    logicType: 'GROUP',
                                    name: 'OR',
                                    id: 'or',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colLG: 4,
                              colMD: 4,
                              layout: 'TABLE_24COL',
                            },
                            sysImage: {
                              cssClass: 'fa fa-check',
                              glyph: 'xf00c@FontAwesome',
                            },
                            showCaption: true,
                            id: 'button1',
                          },
                          {
                            actionType: 'UIACTION',
                            buttonStyle: 'DEFAULT',
                            uiactionId: 'refusedovertime@hr_attendance',
                            tooltip: '拒绝',
                            uiactionTarget: 'SINGLEDATA',
                            caption: '拒绝',
                            codeName: 'button2',
                            detailStyle: 'DEFAULT',
                            detailType: 'BUTTON',
                            controlLogics: [
                              {
                                itemName: 'button2',
                                logicTag: 'form',
                                logicType: 'SCRIPT',
                                scriptCode: '!ctrl.state.modified',
                                triggerType: 'ITEMVISIBLE',
                                id: 'button2',
                              },
                            ],
                            defdgroupLogics: [
                              {
                                logicCat: 'PANELVISIBLE',
                                relatedDetailNames: [
                                  'check_out',
                                  'overtime_status',
                                ],
                                groupOP: 'AND',
                                defdlogics: [
                                  {
                                    condOP: 'ISNOTNULL',
                                    defdname: 'check_out',
                                    logicType: 'SINGLE',
                                    name: 'check_out值不为空(NotNil)',
                                    id: 'check_out值不为空(notnil)',
                                  },
                                  {
                                    groupOP: 'OR',
                                    defdlogics: [
                                      {
                                        condOP: 'EQ',
                                        defdname: 'overtime_status',
                                        value: 'approved',
                                        logicType: 'SINGLE',
                                        id: 'overtime_status等于(=) approved',
                                      },
                                      {
                                        condOP: 'EQ',
                                        defdname: 'overtime_status',
                                        value: 'to_approve',
                                        logicType: 'SINGLE',
                                        id: 'overtime_status等于(=) to_approve',
                                      },
                                    ],
                                    logicType: 'GROUP',
                                    name: 'OR',
                                    id: 'or',
                                  },
                                ],
                                logicType: 'GROUP',
                              },
                            ],
                            layoutPos: {
                              colLG: 4,
                              colMD: 4,
                              layout: 'TABLE_24COL',
                            },
                            sysImage: {
                              cssClass: 'fa fa-times',
                              glyph: 'xf00d@FontAwesome',
                            },
                            showCaption: true,
                            id: 'button2',
                          },
                          {
                            createDV: '0.0',
                            dataType: 7,
                            enableCond: 3,
                            labelPos: 'LEFT',
                            labelWidth: 130,
                            noPrivDisplayMode: 1,
                            appDEFieldId: 'validated_overtime_hours',
                            editor: {
                              editorType: 'HIDDEN',
                              valueType: 'SIMPLE',
                              editable: true,
                              id: 'validated_overtime_hours',
                            },
                            allowEmpty: true,
                            hidden: true,
                            capLanguageRes: {
                              lanResTag:
                                'DEF.LNAME.HR_ATTENDANCE.VALIDATED_OVERTIME_HOURS',
                            },
                            caption: '加班时间',
                            codeName: 'validated_overtime_hours',
                            detailStyle: 'DEFAULT',
                            detailType: 'FORMITEM',
                            layoutPos: {
                              colMD: 24,
                              layout: 'TABLE_24COL',
                            },
                            id: 'validated_overtime_hours',
                          },
                        ],
                        codeName: 'grouppanel8',
                        detailStyle: 'DEFAULT',
                        detailType: 'GROUPPANEL',
                        layoutPos: {
                          colMD: 24,
                          layout: 'TABLE_24COL',
                        },
                        id: 'grouppanel8',
                      },
                    ],
                    codeName: 'grouppanel7',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel7',
                  },
                  {
                    createDVT: 'OPERATOR',
                    dataType: 25,
                    enableCond: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'employee_id',
                    editor: {
                      editorType: 'HIDDEN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'employee_id',
                    },
                    allowEmpty: true,
                    hidden: true,
                    caption: '员工',
                    codeName: 'employee_id',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    id: 'employee_id',
                  },
                ],
                caption: '基础信息',
                codeName: 'group_base',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'group_base',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    createDV: 'manual',
                    dataType: 25,
                    ignoreInput: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'in_mode',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId: 'attendanceapp.hr__hr_attendance_in_mode',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'in_mode',
                    },
                    updateDV: 'manual',
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.HR_ATTENDANCE.IN_MODE',
                    },
                    caption: '模式',
                    codeName: 'in_mode',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'in_mode',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'in_ip_address',
                        editor: {
                          maxLength: 500,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'in_ip_address',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.IN_IP_ADDRESS',
                        },
                        caption: 'IP地址',
                        codeName: 'in_ip_address',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'in_ip_address',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'in_browser',
                        editor: {
                          maxLength: 500,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'in_browser',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.IN_BROWSER',
                        },
                        caption: '浏览器',
                        codeName: 'in_browser',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'in_browser',
                      },
                      {
                        dataType: 7,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'in_longitude',
                        editor: {
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'in_longitude',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.IN_LONGITUDE',
                        },
                        caption: '经度',
                        codeName: 'in_longitude',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'in_longitude',
                      },
                      {
                        dataType: 7,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'in_latitude',
                        editor: {
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'in_latitude',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.IN_LATITUDE',
                        },
                        caption: '纬度',
                        codeName: 'in_latitude',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'in_latitude',
                      },
                    ],
                    codeName: 'grouppanel4',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    defdgroupLogics: [
                      {
                        logicCat: 'PANELVISIBLE',
                        relatedDetailNames: ['in_mode'],
                        groupOP: 'AND',
                        defdlogics: [
                          {
                            condOP: 'EQ',
                            defdname: 'in_mode',
                            value: 'technical',
                            logicType: 'SINGLE',
                            id: 'in_mode等于(=) technical',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel4',
                  },
                ],
                caption: '签到',
                codeName: 'grouppanel2',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel2',
              },
              {
                layout: {
                  columnCount: 24,
                  layout: 'TABLE_24COL',
                },
                deformDetails: [
                  {
                    createDV: 'manual',
                    dataType: 25,
                    enableCond: 3,
                    ignoreInput: 3,
                    labelPos: 'LEFT',
                    labelWidth: 130,
                    noPrivDisplayMode: 1,
                    appDEFieldId: 'out_mode',
                    editor: {
                      halign: 'LEFT',
                      valign: 'MIDDLE',
                      wrapMode: 'NOWRAP',
                      appCodeListId: 'attendanceapp.hr__hr_attendance_out_mode',
                      editorType: 'SPAN',
                      valueType: 'SIMPLE',
                      editable: true,
                      id: 'out_mode',
                    },
                    updateDV: 'manual',
                    allowEmpty: true,
                    convertToCodeItemText: true,
                    capLanguageRes: {
                      lanResTag: 'DEF.LNAME.HR_ATTENDANCE.OUT_MODE',
                    },
                    caption: '模式',
                    codeName: 'out_mode',
                    detailStyle: 'DEFAULT',
                    detailType: 'FORMITEM',
                    layoutPos: {
                      colLG: 12,
                      colMD: 12,
                      layout: 'TABLE_24COL',
                    },
                    showCaption: true,
                    id: 'out_mode',
                  },
                  {
                    layout: {
                      columnCount: 24,
                      layout: 'TABLE_24COL',
                    },
                    deformDetails: [
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'out_ip_address',
                        editor: {
                          maxLength: 500,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'out_ip_address',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.OUT_IP_ADDRESS',
                        },
                        caption: 'IP地址',
                        codeName: 'out_ip_address',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'out_ip_address',
                      },
                      {
                        dataType: 25,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'out_browser',
                        editor: {
                          maxLength: 500,
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'out_browser',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.OUT_BROWSER',
                        },
                        caption: '浏览器',
                        codeName: 'out_browser',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'out_browser',
                      },
                      {
                        dataType: 7,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'out_longitude',
                        editor: {
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'out_longitude',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.OUT_LONGITUDE',
                        },
                        caption: '经度',
                        codeName: 'out_longitude',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'out_longitude',
                      },
                      {
                        dataType: 7,
                        enableCond: 3,
                        labelPos: 'LEFT',
                        labelWidth: 130,
                        noPrivDisplayMode: 1,
                        appDEFieldId: 'out_latitude',
                        editor: {
                          editorType: 'TEXTBOX',
                          valueType: 'SIMPLE',
                          editable: true,
                          id: 'out_latitude',
                        },
                        allowEmpty: true,
                        capLanguageRes: {
                          lanResTag: 'DEF.LNAME.HR_ATTENDANCE.OUT_LATITUDE',
                        },
                        caption: '纬度',
                        codeName: 'out_latitude',
                        detailStyle: 'DEFAULT',
                        detailType: 'FORMITEM',
                        layoutPos: {
                          colLG: 12,
                          colMD: 12,
                          layout: 'TABLE_24COL',
                        },
                        showCaption: true,
                        id: 'out_latitude',
                      },
                    ],
                    codeName: 'grouppanel5',
                    detailStyle: 'DEFAULT',
                    detailType: 'GROUPPANEL',
                    defdgroupLogics: [
                      {
                        logicCat: 'PANELVISIBLE',
                        relatedDetailNames: ['in_mode'],
                        groupOP: 'AND',
                        defdlogics: [
                          {
                            condOP: 'EQ',
                            defdname: 'in_mode',
                            value: 'technical',
                            logicType: 'SINGLE',
                            id: 'in_mode等于(=) technical',
                          },
                        ],
                        logicType: 'GROUP',
                      },
                    ],
                    layoutPos: {
                      colLG: 24,
                      colMD: 24,
                      layout: 'TABLE_24COL',
                    },
                    id: 'grouppanel5',
                  },
                ],
                caption: '签离',
                codeName: 'grouppanel3',
                detailStyle: 'DEFAULT',
                detailType: 'GROUPPANEL',
                defdgroupLogics: [
                  {
                    logicCat: 'PANELVISIBLE',
                    relatedDetailNames: ['check_out'],
                    groupOP: 'AND',
                    defdlogics: [
                      {
                        condOP: 'ISNOTNULL',
                        defdname: 'check_out',
                        logicType: 'SINGLE',
                        name: 'check_out值不为空(NotNil)',
                        id: 'check_out值不为空(notnil)',
                      },
                    ],
                    logicType: 'GROUP',
                  },
                ],
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                showCaption: true,
                id: 'grouppanel3',
              },
              {
                dataType: 25,
                enableCond: 3,
                labelPos: 'LEFT',
                labelWidth: 130,
                noPrivDisplayMode: 1,
                appDEFieldId: 'id',
                editor: {
                  editorType: 'HIDDEN',
                  valueType: 'SIMPLE',
                  editable: true,
                  id: 'id',
                },
                allowEmpty: true,
                hidden: true,
                capLanguageRes: {
                  lanResTag: 'DEF.LNAME.HR_ATTENDANCE.ID',
                },
                caption: '标识',
                codeName: 'id',
                detailStyle: 'DEFAULT',
                detailType: 'FORMITEM',
                layoutPos: {
                  colMD: 24,
                  layout: 'TABLE_24COL',
                },
                id: 'id',
              },
            ],
            caption: '出勤信息',
            codeName: 'formpage1',
            detailStyle: 'DEFAULT',
            detailType: 'FORMPAGE',
            id: 'formpage1',
          },
        ],
        layout: {
          columnCount: 24,
          layout: 'TABLE_24COL',
        },
        tabHeaderPos: 'TOP',
        noTabHeader: true,
        autoLoad: true,
        showBusyIndicator: true,
        codeName: 'main',
        controlType: 'FORM',
        logicName: '主编辑表单',
        appDataEntityId: 'attendanceapp.hr_attendance',
        controlParam: {
          id: 'form',
        },
        modelId: '55989e05ccba6deba8a561e71d6f4f78',
        modelType: 'PSDEFORM_EDITFORM',
        name: 'form',
        id: 'attendanceapp.hr_attendance.main',
      },
      {
        embeddedAppDEViewId: 'attendanceapp.mail_thread_component_view',
        codeName: 'main_view_control',
        controlType: 'VIEWPANEL',
        appDataEntityId: 'attendanceapp.hr_attendance',
        controlParam: {},
        name: 'control',
        id: 'main_view_control',
      },
      {
        codeName: 'main_view_datainfobar',
        controlType: 'DATAINFOBAR',
        appDataEntityId: 'attendanceapp.hr_attendance',
        controlParam: {
          id: 'datainfobar',
        },
        name: 'datainfobar',
        id: 'main_view_datainfobar',
      },
      {
        capLanguageRes: {
          lanResTag: 'DE.LNAME.HR_ATTENDANCE',
        },
        caption: '出勤',
        codeName: 'main_view_captionbar',
        controlType: 'CAPTIONBAR',
        appDataEntityId: 'attendanceapp.hr_attendance',
        controlParam: {},
        name: 'captionbar',
        id: 'main_view_captionbar',
      },
    ],
    codeName: 'main_view_layout_new',
    controlType: 'VIEWLAYOUTPANEL',
    logicName: '主视图布局面板_new',
    appDataEntityId: 'attendanceapp.hr_attendance',
    controlLogics: [
      {
        eventNames: 'onMounted',
        itemName: 'DRBAR',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'ibiz.uiDomainManager.get(view.context.srfsessionid).evt.on("stateChange", (state, isTrusted )=> {\n    console.log("");\n    const data = view.getController("form").getData()[0];\n    view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);\n});\n\nconst topContext = view.context;\nconst appEntityId = view.model.appDataEntityId;\nconst entityName = appEntityId.split(\'.\').pop();\nconst bExist = topContext[entityName];\nconst drbar = view.getCtrl("DRBAR", "drbar");\nif(!bExist){\n    drbar.disabled({ mode: \'BLANK\' })\n    //  drbar.disabled({ mode: \'MASK\' })\n}',
        triggerType: 'CTRLEVENT',
        id: 'drbar_draft_state',
      },
      {
        eventNames: 'onFormDataChange',
        itemName: 'FORM',
        logicTag: 'layoutpanel',
        logicType: 'SCRIPT',
        scriptCode:
          'view.getController("toolbar")?.calcButtonState(data,view.model.appDataEntityId);',
        triggerType: 'CTRLEVENT',
        id: 'logic',
      },
    ],
    controlParam: {},
    modelId: '31fa7086ff6a353ca3fdf381a934b594',
    modelType: 'PSSYSVIEWLAYOUTPANEL',
    name: 'layoutpanel',
    id: 'main_view_layout_new',
  },
  title: '出勤编辑视图',
  titleLanguageRes: {
    lanResTag: 'PAGE.TITLE.HR_ATTENDANCE.EDITVIEW',
  },
  viewStyle: 'DEFAULT',
  viewType: 'DEEDITVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: 'c14fc3675d1c727d0f6f4fcf4fa436ac',
  modelType: 'PSAPPDEVIEW',
  name: 'hr_attendancemain_view',
  id: 'attendanceapp.hr_attendance_main_view',
};
