export default {
  gridRowActiveMode: 2,
  enableRowEdit: true,
  rowEditDefault: true,
  xdataControlName: 'grid',
  loadDefault: true,
  funcViewMode: 'MDATAVIEW',
  deviewCodeName: 'GridView',
  deviewId: 'a1b719b57a9355d3ae294aa2ed278f8a',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.PUBLIC_LEAVE_TYPE',
  },
  caption: '公共假期类型',
  codeName: 'public_leave_type_grid_view',
  appDataEntityId: 'attendanceapp.public_leave_type',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'GridView',
      id: 'engine',
    },
  ],
  appViewLogics: [
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        actionAfterWizard: 'DEFAULT',
        newDataAppView: {
          refAppViewId: 'attendanceapp.public_leave_type_edit_view',
        },
        appUILogicRefViews: [
          {
            refAppViewId: 'attendanceapp.public_leave_type_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_NEWDATA',
        id: '新建数据',
      },
      builtinLogic: true,
      id: 'newdata',
    },
    {
      logicTrigger: 'CUSTOM',
      logicType: 'APPUILOGIC',
      builtinAppUILogic: {
        openDataAppView: {
          refAppViewId: 'attendanceapp.public_leave_type_edit_view',
        },
        editMode: true,
        appUILogicRefViews: [
          {
            refAppViewId: 'attendanceapp.public_leave_type_edit_view',
          },
        ],
        builtinLogic: true,
        logicType: 'PREDEFINED',
        viewLogicType: 'APP_OPENDATA',
        id: '打开数据',
      },
      builtinLogic: true,
      id: 'opendata',
    },
  ],
  appViewRefs: [
    {
      realTitle: '公共假期类型编辑视图',
      refAppViewId: 'attendanceapp.public_leave_type_edit_view',
      name: 'EDITDATA',
      id: 'editdata',
    },
    {
      realTitle: '公共假期类型编辑视图',
      refAppViewId: 'attendanceapp.public_leave_type_edit_view',
      name: 'NEWDATA',
      id: 'newdata',
    },
  ],
  controls: [
    {
      aggMode: 'NONE',
      columnEnableFilter: 2,
      columnEnableLink: 2,
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      degridColumns: [
        {
          clconvertMode: 'NONE',
          dataItemName: 'name',
          excelCaption: '类型名称',
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.PUBLIC_LEAVE_TYPE.NAME',
          },
          caption: '类型名称',
          codeName: 'name',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'name',
        },
        {
          clconvertMode: 'NONE',
          dataItemName: 'code',
          excelCaption: '代码名称',
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          enableRowEdit: true,
          aggMode: 'NONE',
          align: 'LEFT',
          caption: '代码名称',
          codeName: 'code',
          columnType: 'DEFGRIDCOLUMN',
          noPrivDisplayMode: 1,
          width: 200,
          widthUnit: 'PX',
          enableSort: true,
          id: 'code',
        },
      ],
      degridDataItems: [
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'name',
        },
        {
          appDEFieldId: 'code',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'code',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'id',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfdataaccaction',
        },
        {
          appDEFieldId: 'name',
          valueType: 'SIMPLE',
          dataType: 25,
          id: 'srfmajortext',
        },
      ],
      degridEditItems: [
        {
          caption: '类型名称',
          codeName: 'name',
          enableCond: 3,
          appDEFieldId: 'name',
          editor: {
            maxLength: 200,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'name',
          },
          allowEmpty: true,
          id: 'name',
        },
        {
          caption: '代码名称',
          codeName: 'code',
          enableCond: 3,
          appDEFieldId: 'code',
          editor: {
            maxLength: 100,
            editorType: 'TEXTBOX',
            valueType: 'SIMPLE',
            editable: true,
            id: 'code',
          },
          allowEmpty: true,
          id: 'code',
        },
        {
          caption: '主键',
          codeName: 'srfkey',
          enableCond: 3,
          appDEFieldId: 'id',
          editor: {
            editorType: 'HIDDEN',
            valueType: 'SIMPLE',
            editable: true,
            id: 'srfkey',
          },
          allowEmpty: true,
          id: 'srfkey',
        },
      ],
      pagingMode: 1,
      pagingSize: 20,
      sortMode: 'REMOTE',
      enableCustomized: true,
      enablePagingBar: true,
      enableRowEdit: true,
      enableRowNew: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'attendanceapp.public_leave_type',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetch_default',
        appDataEntityId: 'attendanceapp.public_leave_type',
        id: 'fetch',
      },
      getDraftControlAction: {
        appDEMethodId: 'get_draft',
        appDataEntityId: 'attendanceapp.public_leave_type',
        id: 'loaddraft',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'attendanceapp.public_leave_type',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'attendanceapp.public_leave_type',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'attendanceapp.public_leave_type',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'main',
      controlType: 'GRID',
      logicName: '主表格',
      appDataEntityId: 'attendanceapp.public_leave_type',
      controlParam: {
        ctrlParams: {
          EDITSHOWMODE: 'row',
        },
        id: 'grid',
      },
      modelId: '00d9b9c2eca67f6f0576c88eb1067411',
      modelType: 'PSDEGRID',
      name: 'grid',
      id: 'attendanceapp.public_leave_type.main',
    },
    {
      detoolbarItems: [
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_newrowaction',
          valid: true,
          caption: '新建',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-plus',
            glyph: 'xf067@FontAwesome',
          },
          tooltip: '新建',
          showCaption: true,
          showIcon: true,
          id: 'deuiaction1',
        },
        {
          actionLevel: 100,
          noPrivDisplayMode: 2,
          uiactionId: 'gridview_removeaction',
          uiactionTarget: 'MULTIKEY',
          valid: true,
          capLanguageRes: {
            lanResTag: 'TBB.TEXT.*.REMOVE',
          },
          caption: '删除',
          itemType: 'DEUIACTION',
          sysImage: {
            cssClass: 'fa fa-remove',
            glyph: 'xf00d@FontAwesome',
          },
          tooltip: '删除',
          tooltipLanguageRes: {
            lanResTag: 'TBB.TOOLTIP.*.REMOVE',
          },
          showCaption: true,
          showIcon: true,
          id: 'deuiaction2',
        },
      ],
      xdataControlName: 'grid',
      codeName: 'grid_view_toolbar',
      controlType: 'TOOLBAR',
      logicName: '主表格工具栏',
      appDataEntityId: 'attendanceapp.public_leave_type',
      controlParam: {
        id: 'toolbar',
      },
      modelId: '00d9b9c2eca67f6f0576c88eb1067411',
      modelType: 'PSDETOOLBAR',
      name: 'toolbar',
      id: 'grid_view_toolbar',
    },
    {
      searchButtonStyle: 'DEFAULT',
      deformPages: [
        {
          layout: {
            columnCount: 24,
            layout: 'TABLE_24COL',
          },
          capLanguageRes: {
            lanResTag:
              'CONTROL.DEFORM.PUBLIC_LEAVE_TYPE.DEFAULT.FORMPAGE.FORMPAGE1',
          },
          caption: '常规条件',
          codeName: 'formpage1',
          detailStyle: 'DEFAULT',
          detailType: 'FORMPAGE',
          id: 'formpage1',
        },
      ],
      layout: {
        columnCount: 24,
        layout: 'TABLE_24COL',
      },
      tabHeaderPos: 'TOP',
      noTabHeader: true,
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'default',
      controlType: 'SEARCHFORM',
      logicName: '默认搜索表单',
      appDataEntityId: 'attendanceapp.public_leave_type',
      controlParam: {
        id: 'searchform',
      },
      modelId: 'aaffdd765ed594b6d0700e6c434d0fdb',
      modelType: 'PSDEFORM_SEARCHFORM',
      name: 'searchform',
      id: 'attendanceapp.public_leave_type.default',
    },
    {
      groupMode: 'SINGLE',
      quickSearchMode: 1,
      enableQuickSearch: true,
      controlType: 'SEARCHBAR',
      appDataEntityId: 'attendanceapp.public_leave_type',
      controlParam: {
        id: 'searchbar',
      },
      id: 'searchbar',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.PUBLIC_LEAVE_TYPE',
      },
      caption: '公共假期类型',
      codeName: 'grid_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'attendanceapp.public_leave_type',
      controlParam: {},
      name: 'captionbar',
      id: 'grid_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEGRIDVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'attendanceapp.public_leave_type',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '公共假期类型表格视图',
  viewStyle: 'DEFAULT',
  viewType: 'DEGRIDVIEW',
  enableDP: true,
  showCaptionBar: true,
  modelId: '3a0f5aa552bc947cf9e7e2c6fb9d49c6',
  modelType: 'PSAPPDEVIEW',
  name: 'public_leave_typeGridView',
  id: 'attendanceapp.public_leave_type_grid_view',
};
