export default {
  openMode: 'POPUPMODAL',
  deviewCodeName: 'presonLimitMPickupView',
  deviewId: '42ad7d03eb53b983fbd6e886ac73af0d',
  accUserMode: 2,
  capLanguageRes: {
    lanResTag: 'DE.LNAME.USER_OBJECT',
  },
  caption: '选择部门和人员',
  codeName: 'user_object_preson_limit_m_pickup_view',
  height: 540,
  appDataEntityId: 'attendanceapp.user_object',
  appViewEngines: [
    {
      engineCat: 'VIEW',
      engineType: 'MPickupView',
      id: 'engine',
    },
  ],
  appViewNavParams: [
    {
      key: 'reserver14',
      value: 'reserver14',
      id: 'reserver14',
    },
    {
      key: 'srfpdept',
      value: 'srforgsectorid',
      id: 'srfpdept',
    },
    {
      key: 'srforgid',
      value: 'srforgid',
      id: 'srforgid',
    },
  ],
  controls: [
    {
      embeddedAppDEViewId: 'attendanceapp.user_object_pickup_tree_view',
      codeName: 'preson_limit_m_pickup_view_pickupviewpanel',
      controlType: 'PICKUPVIEWPANEL',
      appDataEntityId: 'attendanceapp.user_object',
      controlParam: {
        id: 'pickupviewpanel',
      },
      name: 'pickupviewpanel',
      id: 'preson_limit_m_pickup_view_pickupviewpanel',
    },
    {
      groupMode: 'NONE',
      groupStyle: 'DEFAULT',
      delistDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'srfkey',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'srfmajortext',
        },
        {
          appDEFieldId: 'parent_id',
          dataType: 25,
          id: 'parent_id',
        },
      ],
      pagingSize: 1000,
      showHeader: true,
      navViewPos: 'NONE',
      createControlAction: {
        appDEMethodId: 'create',
        appDataEntityId: 'attendanceapp.user_object',
        id: 'create',
      },
      fetchControlAction: {
        appDEMethodId: 'fetchdefault',
        appDataEntityId: 'attendanceapp.user_object',
        id: 'fetch',
      },
      getControlAction: {
        appDEMethodId: 'get',
        appDataEntityId: 'attendanceapp.user_object',
        id: 'load',
      },
      removeControlAction: {
        appDEMethodId: 'remove',
        appDataEntityId: 'attendanceapp.user_object',
        id: 'remove',
      },
      updateControlAction: {
        appDEMethodId: 'update',
        appDataEntityId: 'attendanceapp.user_object',
        id: 'update',
      },
      autoLoad: true,
      showBusyIndicator: true,
      codeName: 'simplelist',
      controlType: 'LIST',
      logicName: 'simplelist',
      appDataEntityId: 'attendanceapp.user_object',
      controlParam: {
        id: 'simplelist',
      },
      modelId: '35c4a61b778bc4a2f2ecc35112dabffd',
      modelType: 'PSDELIST',
      name: 'simplelist',
      id: 'attendanceapp.user_object.simplelist',
    },
    {
      capLanguageRes: {
        lanResTag: 'DE.LNAME.USER_OBJECT',
      },
      caption: '选择部门和人员',
      codeName: 'preson_limit_m_pickup_view_captionbar',
      controlType: 'CAPTIONBAR',
      appDataEntityId: 'attendanceapp.user_object',
      controlParam: {},
      name: 'captionbar',
      id: 'preson_limit_m_pickup_view_captionbar',
    },
  ],
  viewLayoutPanel: {
    layoutBodyOnly: true,
    useDefaultLayout: true,
    layoutPanel: true,
    codeName: 'layoutpanel',
    controlStyle: 'APPDEMPICKUPVIEW',
    controlType: 'VIEWLAYOUTPANEL',
    appDataEntityId: 'attendanceapp.user_object',
    controlParam: {},
    id: 'layoutpanel',
  },
  title: '人员范围选择',
  viewStyle: 'DEFAULT',
  viewType: 'DEMPICKUPVIEW',
  width: 680,
  enableDP: true,
  showCaptionBar: true,
  modelId: '8126db546719cf012e76a27e21318731',
  modelType: 'PSAPPDEVIEW',
  name: 'user_objectpresonLimitMPickupView',
  id: 'attendanceapp.user_object_preson_limit_m_pickup_view',
};
