package cn.ibizlab.hr.logic.hr_employeelogic.company_staff_counter;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_employee hr_employeecompany_staff_counterdefault;
                global cn.ibizlab.core.hr.domain.hr_employee hr_employeecompany_staff_counterempfilter;
                global cn.ibizlab.core.hr.domain.hr_employee hr_employeecompany_staff_counteremps;
                    global cn.ibizlab.core.hr.service.Ihr_employeeService hr_employeeservice;
        global cn.ibizlab.core.hr.service.Ihr_employeeService iBzSysHr_employeeDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_employeecompany_staff_counterbegin"
            when
            then
            end

            //逻辑处理节点[实体数据查询]
            rule "dedataquery_01"
            ruleflow-group "hr_employeecompany_staff_counterdedataquery_01"
            when
            then
                        update(hr_employeecompany_staff_counterdefault);//更新fact中变量值
                        update(hr_employeecompany_staff_counterempfilter);//更新fact中变量值
                        update(hr_employeecompany_staff_counteremps);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "hr_employeecompany_staff_counterprepareparam_01"
            when
            then
                            hr_employeecompany_staff_counterempfilter.set("n_company_id_eq",hr_employeecompany_staff_counterdefault.get("companyid"));
                        update(hr_employeecompany_staff_counterdefault);//更新fact中变量值
                        update(hr_employeecompany_staff_counterempfilter);//更新fact中变量值
                        update(hr_employeecompany_staff_counteremps);//更新fact中变量值
            end

            //逻辑处理节点[查看default的值]
            rule "debugparam_01"
            ruleflow-group "hr_employeecompany_staff_counterdebugparam_01"
            when
            then
                        update(hr_employeecompany_staff_counterdefault);//更新fact中变量值
                        update(hr_employeecompany_staff_counterempfilter);//更新fact中变量值
                        update(hr_employeecompany_staff_counteremps);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_02"
            ruleflow-group "hr_employeecompany_staff_counterprepareparam_02"
            when
            then
                            hr_employeecompany_staff_counterdefault.set("company_staff_count",hr_employeecompany_staff_counteremps.get("size"));
                        update(hr_employeecompany_staff_counterdefault);//更新fact中变量值
                        update(hr_employeecompany_staff_counterempfilter);//更新fact中变量值
                        update(hr_employeecompany_staff_counteremps);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "hr_employeecompany_staff_counterend_01"
            when
            then
                        update(hr_employeecompany_staff_counterdefault);//更新fact中变量值
                        update(hr_employeecompany_staff_counterempfilter);//更新fact中变量值
                        update(hr_employeecompany_staff_counteremps);//更新fact中变量值
            end