package cn.ibizlab.hr.logic.hr_employeelogic.emp_counter;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_employee hr_employeeemp_counterdefault;
        global cn.ibizlab.core.hr.service.Ihr_employeeService iBzSysHr_employeeDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_employeeemp_counterbegin"
            when
            then
            end