package cn.ibizlab.hr.logic.hr_employeelogic.prepare_default_user;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_employee hr_employeeprepare_default_userdefault;
                global cn.ibizlab.core.base.domain.res_users hr_employeeprepare_default_userdefault_user;
        global cn.ibizlab.core.hr.service.Ihr_employeeService iBzSysHr_employeeDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_employeeprepare_default_userbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "hr_employeeprepare_default_userprepareparam_01"
            when
            then
                            hr_employeeprepare_default_userdefault_user.set("login",hr_employeeprepare_default_userdefault.get("workemail"));
                            hr_employeeprepare_default_userdefault_user.set("name",hr_employeeprepare_default_userdefault.get("name"));
                        update(hr_employeeprepare_default_userdefault);//更新fact中变量值
                        update(hr_employeeprepare_default_userdefault_user);//更新fact中变量值
            end