export default {
  appDEFields: [
    {
      codeName: 'type',
      logicName: '类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'TYPE',
      id: 'type',
    },
    {
      codeName: 'status',
      logicName: '状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATUS',
      id: 'status',
    },
    {
      codeName: 'memo',
      logicName: '备注',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 2000,
      name: 'MEMO',
      id: 'memo',
    },
    {
      codeName: 'content',
      logicName: '内容',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'CONTENT',
      id: 'content',
    },
    {
      codeName: 'applicant_id',
      logicName: '申请标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'APPLICANT_ID',
      id: 'applicant_id',
    },
    {
      codeName: 'user_name',
      logicName: '用户姓名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'USER_NAME',
      id: 'user_name',
    },
    {
      codeName: 'job_name',
      logicName: '职位名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'JOB_NAME',
      id: 'job_name',
    },
    {
      codeName: 'priority_id',
      logicName: '职位优先级',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRIORITY_ID',
      id: 'priority_id',
    },
    {
      codeName: 'applicant_create_date',
      logicName: '申请日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'APPLICANT_CREATE_DATE',
      id: 'applicant_create_date',
    },
    {
      codeName: 'feedback_information',
      logicName: '反馈信息',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 2000,
      name: 'FEEDBACK_INFORMATION',
      id: 'feedback_information',
    },
    {
      codeName: 'experience',
      logicName: '工作经验',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'EXPERIENCE',
      id: 'experience',
    },
    {
      codeName: 'mobile_phone',
      logicName: '手机号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MOBILE_PHONE',
      id: 'mobile_phone',
    },
    {
      codeName: 'address',
      logicName: '所在地',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'ADDRESS',
      id: 'address',
    },
    {
      codeName: 'last_edu_school',
      logicName: '毕业院校',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'LAST_EDU_SCHOOL',
      id: 'last_edu_school',
    },
    {
      codeName: 'email_from',
      logicName: '邮箱',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'EMAIL_FROM',
      id: 'email_from',
    },
    {
      codeName: 'education',
      logicName: '教育程度',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'EDUCATION',
      id: 'education',
    },
    {
      codeName: 'job_platform_name',
      logicName: '招聘平台',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'JOB_PLATFORM_NAME',
      id: 'job_platform_name',
    },
    {
      codeName: 'candidate_name',
      logicName: '候选人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'CANDIDATE_NAME',
      id: 'candidate_name',
    },
    {
      codeName: 'description',
      logicName: '备注',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'last_edu_academic_degree',
      logicName: '教育程度',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'LAST_EDU_ACADEMIC_DEGREE',
      id: 'last_edu_academic_degree',
    },
    {
      codeName: 'candidate_display_name',
      logicName: '候选人名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CANDIDATE_DISPLAY_NAME',
      id: 'candidate_display_name',
    },
    {
      codeName: 'stage_name',
      logicName: '阶段名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'STAGE_NAME',
      id: 'stage_name',
    },
    {
      codeName: 'candidate_filter_id',
      logicName: '筛选',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CANDIDATE_FILTER_ID',
      id: 'candidate_filter_id',
    },
    {
      codeName: 'create_uid',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'id',
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'create_date',
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'name',
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'user_id',
      logicName: '人员',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'USER_ID',
      id: 'user_id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'hr_candidate_filter_detail_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'type',
          logicName: '类型',
          appDEFieldId: 'type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'type',
        },
        {
          codeName: 'status',
          logicName: '状态',
          appDEFieldId: 'status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'status',
        },
        {
          codeName: 'content',
          logicName: '内容',
          appDEFieldId: 'content',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'content',
        },
        {
          codeName: 'memo',
          logicName: '备注',
          appDEFieldId: 'memo',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'memo',
        },
        {
          codeName: 'applicant_id',
          logicName: '申请标识',
          appDEFieldId: 'applicant_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'applicant_id',
        },
        {
          codeName: 'user_name',
          logicName: '用户姓名',
          appDEFieldId: 'user_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_name',
        },
        {
          codeName: 'job_name',
          logicName: '职位名称',
          appDEFieldId: 'job_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'job_name',
        },
        {
          codeName: 'priority_id',
          logicName: '职位优先级',
          appDEFieldId: 'priority_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'priority_id',
        },
        {
          codeName: 'applicant_create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '申请日期',
          appDEFieldId: 'applicant_create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'applicant_create_date',
        },
        {
          codeName: 'feedback_information',
          logicName: '反馈信息',
          appDEFieldId: 'feedback_information',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'feedback_information',
        },
        {
          codeName: 'address',
          logicName: '所在地',
          appDEFieldId: 'address',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'address',
        },
        {
          codeName: 'experience',
          logicName: '工作经验',
          appDEFieldId: 'experience',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'experience',
        },
        {
          codeName: 'last_edu_school',
          logicName: '毕业院校',
          appDEFieldId: 'last_edu_school',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_edu_school',
        },
        {
          codeName: 'mobile_phone',
          logicName: '手机号',
          appDEFieldId: 'mobile_phone',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'mobile_phone',
        },
        {
          codeName: 'email_from',
          logicName: '邮箱',
          appDEFieldId: 'email_from',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'email_from',
        },
        {
          codeName: 'education',
          logicName: '教育程度',
          appDEFieldId: 'education',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'education',
        },
        {
          codeName: 'job_platform_name',
          logicName: '招聘平台',
          appDEFieldId: 'job_platform_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'job_platform_name',
        },
        {
          codeName: 'candidate_name',
          logicName: '候选人',
          appDEFieldId: 'candidate_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'candidate_name',
        },
        {
          codeName: 'description',
          logicName: '备注',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'last_edu_academic_degree',
          logicName: '教育程度',
          appDEFieldId: 'last_edu_academic_degree',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'last_edu_academic_degree',
        },
        {
          codeName: 'candidate_display_name',
          logicName: '候选人名称',
          appDEFieldId: 'candidate_display_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'candidate_display_name',
        },
        {
          codeName: 'stage_name',
          logicName: '阶段名',
          appDEFieldId: 'stage_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'stage_name',
        },
        {
          codeName: 'candidate_filter_id',
          logicName: '筛选',
          appDEFieldId: 'candidate_filter_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'candidate_filter_id',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'user_id',
          logicName: '人员',
          appDEFieldId: 'user_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'user_id',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'hr_candidate_filter_detail_dto',
    },
    {
      codeName: 'hr_candidate_filter_detail_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_applicant_id_eq',
          logicName: '申请标识',
          appDEFieldId: 'applicant_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_applicant_id_eq',
        },
        {
          codeName: 'n_candidate_filter_id_eq',
          logicName: '筛选',
          appDEFieldId: 'candidate_filter_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_candidate_filter_id_eq',
        },
        {
          codeName: 'n_candidate_name_eq',
          logicName: '候选人',
          appDEFieldId: 'candidate_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_candidate_name_eq',
        },
        {
          codeName: 'n_candidate_name_like',
          logicName: '候选人',
          appDEFieldId: 'candidate_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_candidate_name_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_job_name_eq',
          logicName: '职位名称',
          appDEFieldId: 'job_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_job_name_eq',
        },
        {
          codeName: 'n_job_name_like',
          logicName: '职位名称',
          appDEFieldId: 'job_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_job_name_like',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_priority_id_eq',
          logicName: '职位优先级',
          appDEFieldId: 'priority_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_priority_id_eq',
        },
        {
          codeName: 'n_status_eq',
          logicName: '状态',
          appDEFieldId: 'status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_status_eq',
        },
        {
          codeName: 'n_type_eq',
          logicName: '类型',
          appDEFieldId: 'type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_type_eq',
        },
        {
          codeName: 'n_user_id_eq',
          logicName: '人员',
          appDEFieldId: 'user_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_user_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'hr_candidate_filter_detail_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'filter_count',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/filter_count',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'filter_count',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'my_filter_count',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/my_filter_count',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'my_filter_count',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_evaluated',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_evaluated',
      actionType: 'REMOTE',
      dataSetName: 'evaluated',
      dataSetTag: 'evaluated',
      dataSetType: 'REMOTE',
      id: 'fetch_evaluated',
    },
    {
      codeName: 'fetch_filter_myself',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_filter_myself',
      actionType: 'REMOTE',
      dataSetName: 'filter_myself',
      dataSetTag: 'filter_myself',
      dataSetType: 'REMOTE',
      id: 'fetch_filter_myself',
    },
    {
      codeName: 'fetch_unevaluated',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_candidate_filter_detail_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_unevaluated',
      actionType: 'REMOTE',
      dataSetName: 'unevaluated',
      dataSetTag: 'unevaluated',
      dataSetType: 'REMOTE',
      id: 'fetch_unevaluated',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '筛选',
      codeName: 'filter',
      frontAppViewId: 'web.hr_candidate_filter_detail_filter_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'hr_candidate_filter_detail_filter',
      uiactionMode: 'FRONT',
      uiactionTag: 'filter',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.hr_candidate_filter_detail',
      name: '打开筛选操作界面',
      id: 'filter@hr_candidate_filter_detail',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '查看详情',
      codeName: 'open_edit',
      frontAppViewId: 'web.hr_candidate_filter_detail_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'hr_candidate_filter_detail_open_edit',
      uiactionMode: 'FRONT',
      uiactionTag: 'open_edit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.hr_candidate_filter_detail',
      name: '查看详情',
      id: 'open_edit@hr_candidate_filter_detail',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'hr_candidate_filter_detail',
  deapicodeName: 'hr_candidate_filter_detail',
  deapicodeName2: 'hr_candidate_filter_details',
  deapitag: 'HR_CANDIDATE_FILTER_DETAIL',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.HR_CANDIDATE_FILTER_DETAIL',
  },
  logicName: '筛选候选人明细',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  unionKeyValueAppDEFieldIds: ['applicant_id', 'user_id'],
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'HR_CANDIDATE_FILTER_DETAIL',
  id: 'web.hr_candidate_filter_detail',
  codeName2: 'hr_candidate_filter_details',
  requestPaths: [],
};
