export default {
  appDEACModes: [
    {
      actype: 'AUTOCOMPLETE',
      codeName: 'Default',
      logicName: 'DEFAULT',
      deacmodeDataItems: [
        {
          appDEFieldId: 'id',
          dataType: 25,
          id: 'value',
        },
        {
          appDEFieldId: 'name',
          dataType: 25,
          id: 'text',
        },
      ],
      pagingSize: 50,
      defaultMode: true,
      appDataEntityId: 'web.hr_job',
      textAppDEFieldId: 'name',
      valueAppDEFieldId: 'id',
      name: 'DEFAULT',
      id: 'default',
    },
  ],
  appDEFields: [
    {
      codeName: 'min_salary',
      logicName: '最低薪资',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MIN_SALARY',
      id: 'min_salary',
    },
    {
      codeName: 'max_salary',
      logicName: '最高薪资',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MAX_SALARY',
      id: 'max_salary',
    },
    {
      codeName: 'address_id',
      logicName: '工作地点',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ADDRESS_ID',
      id: 'address_id',
    },
    {
      codeName: 'is_virtual',
      logicName: '是否为虚拟职位',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'IS_VIRTUAL',
      id: 'is_virtual',
    },
    {
      codeName: 'owner_id',
      logicName: '招聘负责人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'OWNER_ID',
      id: 'owner_id',
    },
    {
      codeName: 'manager_id',
      logicName: '部门经理',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MANAGER_ID',
      id: 'manager_id',
    },
    {
      codeName: 'source_type',
      logicName: '职位来源',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'SOURCE_TYPE',
      id: 'source_type',
    },
    {
      codeName: 'category',
      logicName: '职位类别',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CATEGORY',
      id: 'category',
    },
    {
      codeName: 'department_id',
      logicName: '部门',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'DEPARTMENT_ID',
      id: 'department_id',
    },
    {
      codeName: 'job_type',
      logicName: '职位性质',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'JOB_TYPE',
      id: 'job_type',
    },
    {
      codeName: 'hired_employees',
      logicName: '入职人数',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'HIRED_EMPLOYEES',
      id: 'hired_employees',
    },
    {
      codeName: 'experience',
      logicName: '工作经验',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'EXPERIENCE',
      id: 'experience',
    },
    {
      codeName: 'job_rank_ids',
      logicName: '职位级别',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'JOB_RANK_IDS',
      id: 'job_rank_ids',
    },
    {
      codeName: 'education',
      logicName: '学历要求',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'EDUCATION',
      id: 'education',
    },
    {
      codeName: 'function_type',
      logicName: '职能类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'FUNCTION_TYPE',
      id: 'function_type',
    },
    {
      codeName: 'status',
      logicName: '岗位状态',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'STATUS',
      id: 'status',
    },
    {
      codeName: 'assistant_uid',
      logicName: '招聘协助人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ASSISTANT_UID',
      id: 'assistant_uid',
    },
    {
      codeName: 'manager_uid',
      logicName: '用人经理',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MANAGER_UID',
      id: 'manager_uid',
    },
    {
      codeName: 'interviewer_uid',
      logicName: '面试官',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'INTERVIEWER_UID',
      id: 'interviewer_uid',
    },
    {
      codeName: 'priority_id',
      logicName: '优先级',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PRIORITY_ID',
      id: 'priority_id',
    },
    {
      codeName: 'total_employees',
      logicName: '候选人总数',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'TOTAL_EMPLOYEES',
      id: 'total_employees',
    },
    {
      codeName: 'job_platforms',
      logicName: '招聘渠道',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'JOB_PLATFORMS',
      id: 'job_platforms',
    },
    {
      codeName: 'is_publish_social',
      logicName: '显示在社招官网',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_PUBLISH_SOCIAL',
      id: 'is_publish_social',
    },
    {
      codeName: 'is_publish_referral',
      logicName: '显示在内推官网',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_PUBLISH_REFERRAL',
      id: 'is_publish_referral',
    },
    {
      codeName: 'is_publish_headhunter',
      logicName: '发布到猎头',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_PUBLISH_HEADHUNTER',
      id: 'is_publish_headhunter',
    },
    {
      codeName: 'id',
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'description',
      logicName: '职位描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DESCRIPTION',
      id: 'description',
    },
    {
      codeName: 'expected_employees',
      logicName: '招聘人数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'EXPECTED_EMPLOYEES',
      id: 'expected_employees',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'create_uid',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'name',
      logicName: '职位名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_date',
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'progress_id',
      logicName: '招聘流程',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PROGRESS_ID',
      id: 'progress_id',
    },
    {
      codeName: 'progress_name',
      logicName: '招聘流程名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PROGRESS_NAME',
      id: 'progress_name',
    },
    {
      codeName: 'date_from',
      logicName: '招聘开始时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'DATE_FROM',
      id: 'date_from',
    },
    {
      codeName: 'date_to',
      logicName: '招聘结束时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'DATE_TO',
      id: 'date_to',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'hr_job_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'min_salary',
          logicName: '最低薪资',
          appDEFieldId: 'min_salary',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'min_salary',
        },
        {
          codeName: 'max_salary',
          logicName: '最高薪资',
          appDEFieldId: 'max_salary',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'max_salary',
        },
        {
          codeName: 'address_id',
          logicName: '工作地点',
          appDEFieldId: 'address_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'address_id',
        },
        {
          codeName: 'is_virtual',
          logicName: '是否为虚拟职位',
          appDEFieldId: 'is_virtual',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_virtual',
        },
        {
          codeName: 'owner_id',
          logicName: '招聘负责人',
          appDEFieldId: 'owner_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'owner_id',
        },
        {
          codeName: 'manager_id',
          logicName: '部门经理',
          appDEFieldId: 'manager_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'manager_id',
        },
        {
          codeName: 'source_type',
          logicName: '职位来源',
          appDEFieldId: 'source_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'source_type',
        },
        {
          codeName: 'category',
          logicName: '职位类别',
          appDEFieldId: 'category',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'category',
        },
        {
          codeName: 'department_id',
          logicName: '部门',
          appDEFieldId: 'department_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'department_id',
        },
        {
          codeName: 'job_type',
          logicName: '职位性质',
          appDEFieldId: 'job_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'job_type',
        },
        {
          codeName: 'hired_employees',
          logicName: '入职人数',
          appDEFieldId: 'hired_employees',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'hired_employees',
        },
        {
          codeName: 'experience',
          logicName: '工作经验',
          appDEFieldId: 'experience',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'experience',
        },
        {
          codeName: 'job_rank_ids',
          logicName: '职位级别',
          appDEFieldId: 'job_rank_ids',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'job_rank_ids',
        },
        {
          codeName: 'education',
          logicName: '学历要求',
          appDEFieldId: 'education',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'education',
        },
        {
          codeName: 'function_type',
          logicName: '职能类型',
          appDEFieldId: 'function_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'function_type',
        },
        {
          codeName: 'status',
          logicName: '岗位状态',
          appDEFieldId: 'status',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'status',
        },
        {
          codeName: 'assistant_uid',
          logicName: '招聘协助人',
          appDEFieldId: 'assistant_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'assistant_uid',
        },
        {
          codeName: 'manager_uid',
          logicName: '用人经理',
          appDEFieldId: 'manager_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'manager_uid',
        },
        {
          codeName: 'interviewer_uid',
          logicName: '面试官',
          appDEFieldId: 'interviewer_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'interviewer_uid',
        },
        {
          codeName: 'priority_id',
          logicName: '优先级',
          appDEFieldId: 'priority_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'priority_id',
        },
        {
          codeName: 'total_employees',
          logicName: '候选人总数',
          appDEFieldId: 'total_employees',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'total_employees',
        },
        {
          codeName: 'job_platforms',
          logicName: '招聘渠道',
          appDEFieldId: 'job_platforms',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'job_platforms',
        },
        {
          codeName: 'is_publish_social',
          logicName: '显示在社招官网',
          appDEFieldId: 'is_publish_social',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_publish_social',
        },
        {
          codeName: 'is_publish_referral',
          logicName: '显示在内推官网',
          appDEFieldId: 'is_publish_referral',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_publish_referral',
        },
        {
          codeName: 'is_publish_headhunter',
          logicName: '发布到猎头',
          appDEFieldId: 'is_publish_headhunter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_publish_headhunter',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'date_from',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '招聘开始时间',
          appDEFieldId: 'date_from',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_from',
        },
        {
          codeName: 'date_to',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '招聘结束时间',
          appDEFieldId: 'date_to',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date_to',
        },
        {
          codeName: 'description',
          logicName: '职位描述',
          appDEFieldId: 'description',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'description',
        },
        {
          codeName: 'expected_employees',
          logicName: '招聘人数',
          appDEFieldId: 'expected_employees',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'expected_employees',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '职位名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'progress_id',
          logicName: '招聘流程',
          appDEFieldId: 'progress_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'progress_id',
        },
        {
          codeName: 'progress_name',
          logicName: '招聘流程名称',
          appDEFieldId: 'progress_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'progress_name',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
        {
          codeName: 'hr_job_platform_records',
          refAppDEMethodDTOId: 'hr_job_platform_record_dto',
          refAppDataEntityId: 'web.hr_job_platform_record',
          refPickupAppDEFieldId: 'job_id',
          sourceType: 'DER',
          type: 'DTOS',
          allowEmpty: true,
          id: 'hr_job_platform_records',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'hr_job_dto',
    },
    {
      codeName: 'hr_job_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_education_eq',
          logicName: '学历要求',
          appDEFieldId: 'education',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_education_eq',
        },
        {
          codeName: 'n_experience_eq',
          logicName: '工作经验',
          appDEFieldId: 'experience',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_experience_eq',
        },
        {
          codeName: 'n_function_type_eq',
          logicName: '职能类型',
          appDEFieldId: 'function_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_function_type_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_is_virtual_eq',
          logicName: '是否为虚拟职位',
          appDEFieldId: 'is_virtual',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_is_virtual_eq',
        },
        {
          codeName: 'n_job_platforms_like',
          logicName: '招聘渠道',
          appDEFieldId: 'job_platforms',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_job_platforms_like',
        },
        {
          codeName: 'n_job_type_eq',
          logicName: '职位性质',
          appDEFieldId: 'job_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_job_type_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '职位名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_owner_id_eq',
          logicName: '招聘负责人',
          appDEFieldId: 'owner_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_owner_id_eq',
        },
        {
          codeName: 'n_progress_id_eq',
          logicName: '招聘流程',
          appDEFieldId: 'progress_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_progress_id_eq',
        },
        {
          codeName: 'n_progress_name_eq',
          logicName: '招聘流程名称',
          appDEFieldId: 'progress_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_progress_name_eq',
        },
        {
          codeName: 'n_progress_name_like',
          logicName: '招聘流程名称',
          appDEFieldId: 'progress_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_progress_name_like',
        },
        {
          codeName: 'n_source_type_eq',
          logicName: '职位来源',
          appDEFieldId: 'source_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_source_type_eq',
        },
        {
          codeName: 'n_status_eq',
          logicName: '岗位状态',
          appDEFieldId: 'status',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_status_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'hr_job_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CreateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        output: true,
        name: 'CreateTempInput',
        id: 'createtempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempResult',
        id: 'createtempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTemp',
      id: 'createtemp',
    },
    {
      codeName: 'CreateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        output: true,
        name: 'CreateTempMajorInput',
        id: 'createtempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempMajorResult',
        id: 'createtempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTempMajor',
      id: 'createtempmajor',
    },
    {
      codeName: 'GetDraftTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        name: 'GetDraftTempInput',
        id: 'getdrafttempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        name: 'GetDraftTempResult',
        id: 'getdrafttempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTemp',
      id: 'getdrafttemp',
    },
    {
      codeName: 'GetDraftTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        name: 'GetDraftTempMajorInput',
        id: 'getdrafttempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        name: 'GetDraftTempMajorResult',
        id: 'getdrafttempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTempMajor',
      id: 'getdrafttempmajor',
    },
    {
      codeName: 'GetTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetTempInput',
        id: 'gettempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        name: 'GetTempResult',
        id: 'gettempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTemp',
      id: 'gettemp',
    },
    {
      codeName: 'GetTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetTempMajorInput',
        id: 'gettempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        name: 'GetTempMajorResult',
        id: 'gettempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTempMajor',
      id: 'gettempmajor',
    },
    {
      codeName: 'RemoveTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveTempInput',
        id: 'removetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempResult',
        id: 'removetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTemp',
      id: 'removetemp',
    },
    {
      codeName: 'RemoveTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveTempMajorInput',
        id: 'removetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempMajorResult',
        id: 'removetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTempMajor',
      id: 'removetempmajor',
    },
    {
      codeName: 'UpdateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempInput',
        id: 'updatetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempResult',
        id: 'updatetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTemp',
      id: 'updatetemp',
    },
    {
      codeName: 'UpdateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempMajorInput',
        id: 'updatetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempMajorResult',
        id: 'updatetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTempMajor',
      id: 'updatetempmajor',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'job_status_count',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/job_status_count',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'job_status_count',
    },
    {
      codeName: 'join_idea_job',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/join_idea_job',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'join_idea_job',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'website_apply_save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/website_apply_save',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'website_apply_save',
    },
    {
      codeName: 'fetch_all',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_all',
      actionType: 'REMOTE',
      dataSetName: 'all',
      dataSetTag: 'all',
      dataSetType: 'REMOTE',
      id: 'fetch_all',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_open',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_open',
      actionType: 'REMOTE',
      dataSetName: 'open',
      dataSetTag: 'open',
      dataSetType: 'REMOTE',
      id: 'fetch_open',
    },
    {
      codeName: 'FetchTempAll',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_filter_dto',
        type: 'DTO',
        name: 'AllInput',
        id: 'allinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'PAGE',
        name: 'AllResult',
        id: 'allresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'all',
      dataSetType: 'DATAQUERY',
      name: 'all',
      id: 'fetchtempall',
    },
    {
      codeName: 'FetchTempDefault',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_filter_dto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchtempdefault',
    },
    {
      codeName: 'FetchTempOpen',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'hr_job_filter_dto',
        type: 'DTO',
        name: 'OpenInput',
        id: 'openinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'hr_job_dto',
        type: 'PAGE',
        name: 'OpenResult',
        id: 'openresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'open',
      dataSetType: 'DATAQUERY',
      dedqgroupConditions: [
        {
          condOp: 'AND',
          dedqconditions: [
            {
              condOp: 'EQ',
              condValue: 'open',
              fieldName: 'STATUS',
              condType: 'SINGLE',
              name: '(STATUS) 等于(=) open',
              id: '(status) 等于(=) open',
            },
          ],
          condType: 'GROUP',
          id: '连接条件',
        },
      ],
      name: 'open',
      id: 'fetchtempopen',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '创建职位',
      codeName: 'create_job',
      frontAppViewId: 'web.hr_job_create_wizard_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'hr_job_create_job',
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'create_job',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.hr_job',
      name: '创建职位',
      id: 'create_job@hr_job',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '开放所有招聘渠道',
      codeName: 'open_all_channel',
      confirmMsg: '该功能未实现！',
      frontProcessType: 'WIZARD',
      fullCodeName: 'hr_job_open_all_channel',
      appDEMethodId: 'get',
      refreshMode: 1,
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'open_all_channel',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.hr_job',
      name: '开放所有招聘渠道',
      id: 'open_all_channel@hr_job',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '打开招聘官网职位申请',
      codeName: 'open_apply',
      frontAppViewId: 'web.hr_applicant_website_apply_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'hr_job_open_apply',
      navigateParams: [
        {
          key: 'address_id1',
          value: 'address_id',
          id: 'address_id1',
        },
        {
          key: 'job_name1',
          value: 'name',
          id: 'job_name1',
        },
        {
          key: 'create_date1',
          value: 'create_date',
          id: 'create_date1',
        },
        {
          key: 'department1',
          value: 'department',
          id: 'department1',
        },
        {
          key: 'job_type1',
          value: 'job_type',
          id: 'job_type1',
        },
        {
          key: 'company_id1',
          value: 'company_id',
          id: 'company_id1',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'open_apply',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.hr_job',
      name: '打开招聘官网职位申请',
      id: 'open_apply@hr_job',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: 'open_website',
      codeName: 'open_website',
      frontAppViewId: 'web.hr_job_website_job_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'hr_job_open_website',
      uiactionMode: 'FRONT',
      uiactionTag: 'open_website',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.hr_job',
      name: '打开招聘官网职位页面',
      id: 'open_website@hr_job',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '一键刷新',
      codeName: 'refresh',
      confirmMsg: '该功能未实现！',
      frontProcessType: 'WIZARD',
      fullCodeName: 'hr_job_refresh',
      appDEMethodId: 'get',
      refreshMode: 1,
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'refresh',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.hr_job',
      name: '一键刷新',
      id: 'refresh@hr_job',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '官网职位申请信息保存',
      codeName: 'website_apply_save',
      fullCodeName: 'hr_job_website_apply_save',
      appDEMethodId: 'website_apply_save',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'website_apply_save',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.hr_job',
      name: '官网职位申请信息保存',
      id: 'website_apply_save@hr_job',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'hr_job',
  deapicodeName: 'hr_job',
  deapicodeName2: 'hr_jobs',
  deapitag: 'HR_JOB',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.HR_JOB',
  },
  logicName: '招聘职位',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  enableTempData: true,
  major: true,
  name: 'HR_JOB',
  id: 'web.hr_job',
  codeName2: 'hr_jobs',
  requestPaths: [],
};
