export default {
  appDEFields: [
    {
      codeName: 'DynaModelFlag',
      logicName: '扩展模型',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'DYNAMODELFLAG',
      id: 'dynamodelflag',
    },
    {
      codeName: 'CodeName',
      logicName: '代码名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      userTag: 'MODELV2TAG',
      name: 'CODENAME',
      id: 'codename',
    },
    {
      codeName: 'Memo',
      logicName: '备注',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 2000,
      name: 'MEMO',
      id: 'memo',
    },
    {
      codeName: 'PSSysBICubeName',
      logicName: '智能报表立方体',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBICUBENAME',
      id: 'pssysbicubename',
    },
    {
      codeName: 'PSSysBISchemeId',
      logicName: 'PSSYSBISCHEMEID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBISCHEMEID',
      id: 'pssysbischemeid',
    },
    {
      codeName: 'PSSysBICubeId',
      logicName: '智能报表立方体',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBICUBEID',
      id: 'pssysbicubeid',
    },
    {
      codeName: 'OrderValue',
      logicName: '排序值',
      predefinedType: 'ORDERVALUE',
      stdDataType: 9,
      name: 'ORDERVALUE',
      id: 'ordervalue',
    },
    {
      codeName: 'MeasureFormula',
      logicName: '指标公式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 2000,
      name: 'MEASUREFORMULA',
      id: 'measureformula',
    },
    {
      codeName: 'PSSysBICubeMeasureName',
      logicName: '立方体指标名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'PSSYSBICUBEMEASURENAME',
      id: 'pssysbicubemeasurename',
    },
    {
      codeName: 'PSSysBICubeMeasureId',
      logicName: '智能报表指标标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBICUBEMEASUREID',
      id: 'pssysbicubemeasureid',
    },
    {
      codeName: 'ValidFlag',
      logicName: '启用',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'VALIDFLAG',
      id: 'validflag',
    },
    {
      codeName: 'BIMeasureType',
      logicName: '指标类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'BIMEASURETYPE',
      id: 'bimeasuretype',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'PSSysBICubeMeasureDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'DynaModelFlag',
          logicName: '扩展模型',
          appDEFieldId: 'dynamodelflag',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'DynaModelFlag',
          id: 'dynamodelflag',
        },
        {
          codeName: 'BIMeasureType',
          logicName: '指标类型',
          appDEFieldId: 'bimeasuretype',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'BIMeasureType',
          id: 'bimeasuretype',
        },
        {
          codeName: 'CodeName',
          logicName: '代码名称',
          appDEFieldId: 'codename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'CodeName',
          id: 'codename',
        },
        {
          codeName: 'MeasureFormula',
          logicName: '指标公式',
          appDEFieldId: 'measureformula',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'MeasureFormula',
          id: 'measureformula',
        },
        {
          codeName: 'Memo',
          logicName: '备注',
          appDEFieldId: 'memo',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Memo',
          id: 'memo',
        },
        {
          codeName: 'OrderValue',
          logicName: '排序值',
          appDEFieldId: 'ordervalue',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'OrderValue',
          id: 'ordervalue',
        },
        {
          codeName: 'PSSysBICubeId',
          logicName: '智能报表立方体',
          appDEFieldId: 'pssysbicubeid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSSysBICubeId',
          id: 'pssysbicubeid',
        },
        {
          codeName: 'PSSysBICubeMeasureId',
          logicName: '智能报表指标标识',
          appDEFieldId: 'pssysbicubemeasureid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSSysBICubeMeasureId',
          id: 'pssysbicubemeasureid',
        },
        {
          codeName: 'PSSysBICubeMeasureName',
          logicName: '立方体指标名称',
          appDEFieldId: 'pssysbicubemeasurename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSSysBICubeMeasureName',
          id: 'pssysbicubemeasurename',
        },
        {
          codeName: 'PSSysBICubeName',
          logicName: '智能报表立方体',
          appDEFieldId: 'pssysbicubename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBICubeName',
          id: 'pssysbicubename',
        },
        {
          codeName: 'PSSysBISchemeId',
          logicName: 'PSSYSBISCHEMEID',
          appDEFieldId: 'pssysbischemeid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBISchemeId',
          id: 'pssysbischemeid',
        },
        {
          codeName: 'ValidFlag',
          logicName: '启用',
          appDEFieldId: 'validflag',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          name: 'ValidFlag',
          id: 'validflag',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'PSSysBICubeMeasureDTO',
      id: 'pssysbicubemeasuredto',
    },
    {
      codeName: 'PSSysBICubeMeasureFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_BIMEASURETYPE_EQ',
          logicName: '指标类型',
          appDEFieldId: 'bimeasuretype',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_BIMEASURETYPE_EQ',
          id: 'n_bimeasuretype_eq',
        },
        {
          codeName: 'N_PSSYSBICUBEID_EQ',
          logicName: '智能报表立方体',
          appDEFieldId: 'pssysbicubeid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSSYSBICUBEID_EQ',
          id: 'n_pssysbicubeid_eq',
        },
        {
          codeName: 'N_PSSYSBICUBEMEASUREID_EQ',
          logicName: '智能报表指标标识',
          appDEFieldId: 'pssysbicubemeasureid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSSYSBICUBEMEASUREID_EQ',
          id: 'n_pssysbicubemeasureid_eq',
        },
        {
          codeName: 'N_PSSYSBICUBEMEASURENAME_LIKE',
          logicName: '立方体指标名称',
          appDEFieldId: 'pssysbicubemeasurename',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSSYSBICUBEMEASURENAME_LIKE',
          id: 'n_pssysbicubemeasurename_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'PSSysBICubeMeasureFilterDTO',
      id: 'pssysbicubemeasurefilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/checkkey',
      actionMode: 'CHECKKEY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'pssysbicubemeasureid',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'PSSYSBICUBEMEASUREID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/getdraft',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'pssysbicubemeasureid',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'PSSYSBICUBEMEASUREID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'apply',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/apply',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionName: 'APPLY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'apply',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbicubemeasurefilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbicubemeasuredto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchdefault',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      name: 'FetchDefault',
      id: 'fetchdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'PSSysBICubeMeasure',
  deapicodeName: 'pssysbicubemeasure',
  deapicodeName2: 'pssysbicubemeasures',
  deapitag: 'PSSYSBICUBEMEASURE',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'pssysbicubemeasureid',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.PSSYSBICUBEMEASURE',
  },
  logicName: '智能报表立方体指标',
  majorAppDEFieldId: 'pssysbicubemeasurename',
  quickSearchAppDEFieldIds: ['pssysbicubemeasurename'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'PSSYSBICUBEMEASURE',
  id: 'web.pssysbicubemeasure',
  codeName2: 'PSSysBICubeMeasures',
  requestPaths: [],
};
