export default {
  appDEFields: [
    {
      codeName: 'StdDataType',
      logicName: '标准数据类型',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'STDDATATYPE',
      id: 'stddatatype',
    },
    {
      codeName: 'BIRepItemTag2',
      logicName: '报表列标记2',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'BIREPITEMTAG2',
      id: 'birepitemtag2',
    },
    {
      codeName: 'BIRepItemTag',
      logicName: '报表列标记',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'BIREPITEMTAG',
      id: 'birepitemtag',
    },
    {
      codeName: 'BIRepItemParams',
      logicName: '项参数',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'BIREPITEMPARAMS',
      id: 'birepitemparams',
    },
    {
      codeName: 'PSSysBICubeName',
      logicName: '智能报表立方体',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBICUBENAME',
      id: 'pssysbicubename',
    },
    {
      codeName: 'Data',
      logicName: '项数据',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DATA',
      id: 'data',
    },
    {
      codeName: 'PSSysBICubeMeasureName',
      logicName: '立方体指标',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBICUBEMEASURENAME',
      id: 'pssysbicubemeasurename',
    },
    {
      codeName: 'PSSysBICubeMeasureId',
      logicName: '智能报表指标',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBICUBEMEASUREID',
      id: 'pssysbicubemeasureid',
    },
    {
      codeName: 'PSSysBIReportItemName',
      logicName: '智能报表项名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'PSSYSBIREPORTITEMNAME',
      id: 'pssysbireportitemname',
    },
    {
      codeName: 'PSSysBIReportItemId',
      logicName: '智能报表项标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBIREPORTITEMID',
      id: 'pssysbireportitemid',
    },
    {
      codeName: 'PSSysBICubeDimensionName',
      logicName: '立方体维度',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBICUBEDIMENSIONNAME',
      id: 'pssysbicubedimensionname',
    },
    {
      codeName: 'ValidFlag',
      logicName: '启用',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'VALIDFLAG',
      id: 'validflag',
    },
    {
      codeName: 'PSSysBICubeDimensionId',
      logicName: '智能报表立方体维度',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBICUBEDIMENSIONID',
      id: 'pssysbicubedimensionid',
    },
    {
      codeName: 'PSSysBICubeId',
      logicName: '智能报表立方体',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBICUBEID',
      id: 'pssysbicubeid',
    },
    {
      codeName: 'ValueFormat',
      logicName: '值格式化',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'VALUEFORMAT',
      id: 'valueformat',
    },
    {
      codeName: 'BIRepItemType',
      logicName: '报表项类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'BIREPITEMTYPE',
      id: 'birepitemtype',
    },
    {
      codeName: 'AggType',
      logicName: '聚合类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 20,
      name: 'AGGTYPE',
      id: 'aggtype',
    },
    {
      codeName: 'Placement',
      logicName: '放置位置',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'PLACEMENT',
      id: 'placement',
    },
    {
      codeName: 'RefType',
      logicName: '指标引用类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'REFTYPE',
      id: 'reftype',
    },
    {
      codeName: 'PlaceType',
      logicName: '放置类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 30,
      name: 'PLACETYPE',
      id: 'placetype',
    },
    {
      codeName: 'PSSysBIReportName',
      logicName: '智能报表报表',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PSSYSBIREPORTNAME',
      id: 'pssysbireportname',
    },
    {
      codeName: 'PSSysBIReportId',
      logicName: '智能报表报表',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBIREPORTID',
      id: 'pssysbireportid',
    },
    {
      codeName: 'PSSysBISchemeId',
      logicName: 'PSSYSBISCHEMEID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSSYSBISCHEMEID',
      id: 'pssysbischemeid',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'PSSysBIReportItemDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'AggType',
          logicName: '聚合类型',
          appDEFieldId: 'aggtype',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'AggType',
          id: 'aggtype',
        },
        {
          codeName: 'BIRepItemParams',
          logicName: '项参数',
          appDEFieldId: 'birepitemparams',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'BIRepItemParams',
          id: 'birepitemparams',
        },
        {
          codeName: 'BIRepItemTag',
          logicName: '报表列标记',
          appDEFieldId: 'birepitemtag',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'BIRepItemTag',
          id: 'birepitemtag',
        },
        {
          codeName: 'BIRepItemTag2',
          logicName: '报表列标记2',
          appDEFieldId: 'birepitemtag2',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'BIRepItemTag2',
          id: 'birepitemtag2',
        },
        {
          codeName: 'BIRepItemType',
          logicName: '报表项类型',
          appDEFieldId: 'birepitemtype',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'BIRepItemType',
          id: 'birepitemtype',
        },
        {
          codeName: 'Data',
          logicName: '项数据',
          appDEFieldId: 'data',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Data',
          id: 'data',
        },
        {
          codeName: 'PSSysBICubeDimensionId',
          logicName: '智能报表立方体维度',
          appDEFieldId: 'pssysbicubedimensionid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBICubeDimensionId',
          id: 'pssysbicubedimensionid',
        },
        {
          codeName: 'PSSysBICubeDimensionName',
          logicName: '立方体维度',
          appDEFieldId: 'pssysbicubedimensionname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBICubeDimensionName',
          id: 'pssysbicubedimensionname',
        },
        {
          codeName: 'PSSysBICubeId',
          logicName: '智能报表立方体',
          appDEFieldId: 'pssysbicubeid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBICubeId',
          id: 'pssysbicubeid',
        },
        {
          codeName: 'PSSysBICubeMeasureId',
          logicName: '智能报表指标',
          appDEFieldId: 'pssysbicubemeasureid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBICubeMeasureId',
          id: 'pssysbicubemeasureid',
        },
        {
          codeName: 'PSSysBICubeMeasureName',
          logicName: '立方体指标',
          appDEFieldId: 'pssysbicubemeasurename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBICubeMeasureName',
          id: 'pssysbicubemeasurename',
        },
        {
          codeName: 'PSSysBICubeName',
          logicName: '智能报表立方体',
          appDEFieldId: 'pssysbicubename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBICubeName',
          id: 'pssysbicubename',
        },
        {
          codeName: 'PSSysBIReportId',
          logicName: '智能报表报表',
          appDEFieldId: 'pssysbireportid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBIReportId',
          id: 'pssysbireportid',
        },
        {
          codeName: 'PSSysBIReportItemId',
          logicName: '智能报表项标识',
          appDEFieldId: 'pssysbireportitemid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSSysBIReportItemId',
          id: 'pssysbireportitemid',
        },
        {
          codeName: 'PSSysBIReportItemName',
          logicName: '智能报表项名称',
          appDEFieldId: 'pssysbireportitemname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBIReportItemName',
          id: 'pssysbireportitemname',
        },
        {
          codeName: 'PSSysBIReportName',
          logicName: '智能报表报表',
          appDEFieldId: 'pssysbireportname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBIReportName',
          id: 'pssysbireportname',
        },
        {
          codeName: 'PSSysBISchemeId',
          logicName: 'PSSYSBISCHEMEID',
          appDEFieldId: 'pssysbischemeid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PSSysBISchemeId',
          id: 'pssysbischemeid',
        },
        {
          codeName: 'PlaceType',
          logicName: '放置类型',
          appDEFieldId: 'placetype',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'PlaceType',
          id: 'placetype',
        },
        {
          codeName: 'Placement',
          logicName: '放置位置',
          appDEFieldId: 'placement',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Placement',
          id: 'placement',
        },
        {
          codeName: 'RefType',
          logicName: '指标引用类型',
          appDEFieldId: 'reftype',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'RefType',
          id: 'reftype',
        },
        {
          codeName: 'StdDataType',
          logicName: '标准数据类型',
          appDEFieldId: 'stddatatype',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'StdDataType',
          id: 'stddatatype',
        },
        {
          codeName: 'ValidFlag',
          logicName: '启用',
          appDEFieldId: 'validflag',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          name: 'ValidFlag',
          id: 'validflag',
        },
        {
          codeName: 'ValueFormat',
          logicName: '值格式化',
          appDEFieldId: 'valueformat',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'ValueFormat',
          id: 'valueformat',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'PSSysBIReportItemDTO',
      id: 'pssysbireportitemdto',
    },
    {
      codeName: 'PSSysBIReportItemFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_AGGTYPE_EQ',
          logicName: '聚合类型',
          appDEFieldId: 'aggtype',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_AGGTYPE_EQ',
          id: 'n_aggtype_eq',
        },
        {
          codeName: 'N_BIREPITEMTYPE_EQ',
          logicName: '报表项类型',
          appDEFieldId: 'birepitemtype',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_BIREPITEMTYPE_EQ',
          id: 'n_birepitemtype_eq',
        },
        {
          codeName: 'N_PSSYSBIREPORTID_EQ',
          logicName: '智能报表报表',
          appDEFieldId: 'pssysbireportid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSSYSBIREPORTID_EQ',
          id: 'n_pssysbireportid_eq',
        },
        {
          codeName: 'N_PSSYSBIREPORTITEMID_EQ',
          logicName: '智能报表项标识',
          appDEFieldId: 'pssysbireportitemid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSSYSBIREPORTITEMID_EQ',
          id: 'n_pssysbireportitemid_eq',
        },
        {
          codeName: 'N_PSSYSBIREPORTITEMNAME_LIKE',
          logicName: '智能报表项名称',
          appDEFieldId: 'pssysbireportitemname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSSYSBIREPORTITEMNAME_LIKE',
          id: 'n_pssysbireportitemname_like',
        },
        {
          codeName: 'N_PSSYSBIREPORTNAME_EQ',
          logicName: '智能报表报表',
          appDEFieldId: 'pssysbireportname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSSYSBIREPORTNAME_EQ',
          id: 'n_pssysbireportname_eq',
        },
        {
          codeName: 'N_PSSYSBIREPORTNAME_LIKE',
          logicName: '智能报表报表',
          appDEFieldId: 'pssysbireportname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSSYSBIREPORTNAME_LIKE',
          id: 'n_pssysbireportname_like',
        },
        {
          codeName: 'N_REFTYPE_EQ',
          logicName: '指标引用类型',
          appDEFieldId: 'reftype',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_REFTYPE_EQ',
          id: 'n_reftype_eq',
        },
        {
          codeName: 'N_STDDATATYPE_EQ',
          logicName: '标准数据类型',
          appDEFieldId: 'stddatatype',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_STDDATATYPE_EQ',
          id: 'n_stddatatype_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'PSSysBIReportItemFilterDTO',
      id: 'pssysbireportitemfilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/checkkey',
      actionMode: 'CHECKKEY',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'pssysbireportitemid',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'PSSYSBIREPORTITEMID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/getdraft',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'pssysbireportitemid',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'PSSYSBIREPORTITEMID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'pssysbireportitemfilterdto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'pssysbireportitemdto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetchdefault',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      name: 'FetchDefault',
      id: 'fetchdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'PSSysBIReportItem',
  deapicodeName: 'pssysbireportitem',
  deapicodeName2: 'pssysbireportitems',
  deapitag: 'PSSYSBIREPORTITEM',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'pssysbireportitemid',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.PSSYSBIREPORTITEM',
  },
  logicName: '智能报表项',
  majorAppDEFieldId: 'pssysbireportitemname',
  quickSearchAppDEFieldIds: ['pssysbireportitemname'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'PSSYSBIREPORTITEM',
  id: 'web.pssysbireportitem',
  codeName2: 'PSSysBIReportItems',
  requestPaths: [],
};
