export default {
  appDEFields: [
    {
      codeName: 'work_item_type_id',
      logicName: '工作项类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'WORK_ITEM_TYPE_ID',
      id: 'work_item_type_id',
    },
    {
      codeName: 'work_item_type_name',
      logicName: '工作项类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'WORK_ITEM_TYPE_NAME',
      id: 'work_item_type_name',
    },
    {
      codeName: 'title',
      logicName: '标题',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'TITLE',
      id: 'title',
    },
    {
      codeName: 'content',
      logicName: '内容',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CONTENT',
      id: 'content',
    },
    {
      codeName: 'OrderValue',
      logicName: '排序属性',
      predefinedType: 'ORDERVALUE',
      stdDataType: 9,
      name: 'ORDERVALUE',
      id: 'ordervalue',
    },
    {
      codeName: 'PSDELogicNodeName',
      logicName: '逻辑处理名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'PSDELOGICNODENAME',
      id: 'psdelogicnodename',
    },
    {
      codeName: 'PSDELogicNodeId',
      logicName: '实体处理逻辑节点标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDELOGICNODEID',
      id: 'psdelogicnodeid',
    },
    {
      codeName: 'PSDELogicId',
      logicName: '实体处理逻辑',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PSDELOGICID',
      id: 'psdelogicid',
    },
    {
      codeName: 'PSDELogicName',
      logicName: '实体处理逻辑',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'PSDELOGICNAME',
      id: 'psdelogicname',
    },
    {
      codeName: 'LogicNodeType',
      logicName: '逻辑节点类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 40,
      name: 'LOGICNODETYPE',
      id: 'logicnodetype',
    },
    {
      codeName: 'ParallelOutput',
      logicName: '循环后续处理',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PARALLELOUTPUT',
      id: 'paralleloutput',
    },
    {
      codeName: 'CodeName',
      logicName: '代码名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CODENAME',
      id: 'codename',
    },
    {
      codeName: 'Param8',
      logicName: '参数8',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PARAM8',
      id: 'param8',
    },
    {
      codeName: 'Param7',
      logicName: '参数7',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PARAM7',
      id: 'param7',
    },
    {
      codeName: 'Param9',
      logicName: '参数9',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PARAM9',
      id: 'param9',
    },
    {
      codeName: 'Param10',
      logicName: '参数10',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PARAM10',
      id: 'param10',
    },
    {
      codeName: 'Param1',
      logicName: '参数1',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARAM1',
      id: 'param1',
    },
    {
      codeName: 'Param12',
      logicName: '参数12',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARAM12',
      id: 'param12',
    },
    {
      codeName: 'Param11',
      logicName: '参数11',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARAM11',
      id: 'param11',
    },
    {
      codeName: 'Param13',
      logicName: '参数13',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'PARAM13',
      id: 'param13',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'PSDELogicNodeDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'work_item_type_id',
          logicName: '工作项类型',
          appDEFieldId: 'work_item_type_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'work_item_type_id',
        },
        {
          codeName: 'work_item_type_name',
          logicName: '工作项类型',
          appDEFieldId: 'work_item_type_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'work_item_type_name',
        },
        {
          codeName: 'title',
          logicName: '标题',
          appDEFieldId: 'title',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'title',
        },
        {
          codeName: 'content',
          logicName: '内容',
          appDEFieldId: 'content',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'content',
        },
        {
          codeName: 'OrderValue',
          logicName: '排序属性',
          appDEFieldId: 'ordervalue',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'OrderValue',
          id: 'ordervalue',
        },
        {
          codeName: 'CodeName',
          logicName: '代码名称',
          appDEFieldId: 'codename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'CodeName',
          id: 'codename',
        },
        {
          codeName: 'LogicNodeType',
          logicName: '逻辑节点类型',
          appDEFieldId: 'logicnodetype',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'LogicNodeType',
          id: 'logicnodetype',
        },
        {
          codeName: 'PSDELogicId',
          logicName: '实体处理逻辑',
          appDEFieldId: 'psdelogicid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDELogicId',
          id: 'psdelogicid',
        },
        {
          codeName: 'PSDELogicName',
          logicName: '实体处理逻辑',
          appDEFieldId: 'psdelogicname',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDELogicName',
          id: 'psdelogicname',
        },
        {
          codeName: 'PSDELogicNodeId',
          logicName: '实体处理逻辑节点标识',
          appDEFieldId: 'psdelogicnodeid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDELogicNodeId',
          id: 'psdelogicnodeid',
        },
        {
          codeName: 'PSDELogicNodeName',
          logicName: '逻辑处理名称',
          appDEFieldId: 'psdelogicnodename',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          name: 'PSDELogicNodeName',
          id: 'psdelogicnodename',
        },
        {
          codeName: 'ParallelOutput',
          logicName: '循环后续处理',
          appDEFieldId: 'paralleloutput',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'ParallelOutput',
          id: 'paralleloutput',
        },
        {
          codeName: 'Param1',
          logicName: '参数1',
          appDEFieldId: 'param1',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Param1',
          id: 'param1',
        },
        {
          codeName: 'Param10',
          logicName: '参数10',
          appDEFieldId: 'param10',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Param10',
          id: 'param10',
        },
        {
          codeName: 'Param11',
          logicName: '参数11',
          appDEFieldId: 'param11',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Param11',
          id: 'param11',
        },
        {
          codeName: 'Param12',
          logicName: '参数12',
          appDEFieldId: 'param12',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Param12',
          id: 'param12',
        },
        {
          codeName: 'Param13',
          logicName: '参数13',
          appDEFieldId: 'param13',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Param13',
          id: 'param13',
        },
        {
          codeName: 'Param7',
          logicName: '参数7',
          appDEFieldId: 'param7',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Param7',
          id: 'param7',
        },
        {
          codeName: 'Param8',
          logicName: '参数8',
          appDEFieldId: 'param8',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Param8',
          id: 'param8',
        },
        {
          codeName: 'Param9',
          logicName: '参数9',
          appDEFieldId: 'param9',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'Param9',
          id: 'param9',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      name: 'PSDELogicNodeDTO',
      id: 'psdelogicnodedto',
    },
    {
      codeName: 'PSDELogicNodeFilterDTO',
      appDEMethodDTOFields: [
        {
          codeName: 'N_LOGICNODETYPE_EQ',
          logicName: '逻辑节点类型',
          appDEFieldId: 'logicnodetype',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_LOGICNODETYPE_EQ',
          id: 'n_logicnodetype_eq',
        },
        {
          codeName: 'N_PSDELOGICID_EQ',
          logicName: '实体处理逻辑',
          appDEFieldId: 'psdelogicid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDELOGICID_EQ',
          id: 'n_psdelogicid_eq',
        },
        {
          codeName: 'N_PSDELOGICNAME_EQ',
          logicName: '实体处理逻辑',
          appDEFieldId: 'psdelogicname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDELOGICNAME_EQ',
          id: 'n_psdelogicname_eq',
        },
        {
          codeName: 'N_PSDELOGICNAME_LIKE',
          logicName: '实体处理逻辑',
          appDEFieldId: 'psdelogicname',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDELOGICNAME_LIKE',
          id: 'n_psdelogicname_like',
        },
        {
          codeName: 'N_PSDELOGICNODEID_EQ',
          logicName: '实体处理逻辑节点标识',
          appDEFieldId: 'psdelogicnodeid',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDELOGICNODEID_EQ',
          id: 'n_psdelogicnodeid_eq',
        },
        {
          codeName: 'N_PSDELOGICNODENAME_LIKE',
          logicName: '逻辑处理名称',
          appDEFieldId: 'psdelogicnodename',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          name: 'N_PSDELOGICNODENAME_LIKE',
          id: 'n_psdelogicnodename_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      name: 'PSDELogicNodeFilterDTO',
      id: 'psdelogicnodefilterdto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CheckKey',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        name: 'CheckKeyInput',
        id: 'checkkeyinput',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        name: 'CheckKeyResult',
        id: 'checkkeyresult',
      },
      builtinMethod: true,
      actionMode: 'CHECKKEY',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'checkkey',
    },
    {
      codeName: 'Create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        output: true,
        name: 'CreateInput',
        id: 'createinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateResult',
        id: 'createresult',
      },
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'CreateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        output: true,
        name: 'CreateTempInput',
        id: 'createtempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempResult',
        id: 'createtempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTemp',
      id: 'createtemp',
    },
    {
      codeName: 'CreateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        output: true,
        name: 'CreateTempMajorInput',
        id: 'createtempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempMajorResult',
        id: 'createtempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTempMajor',
      id: 'createtempmajor',
    },
    {
      codeName: 'Get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'psdelogicnodeid',
        type: 'KEYFIELD',
        name: 'GetInput',
        id: 'getinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        name: 'GetResult',
        id: 'getresult',
      },
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'GetDraft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        name: 'GetDraftInput',
        id: 'getdraftinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        name: 'GetDraftResult',
        id: 'getdraftresult',
      },
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'getdraft',
    },
    {
      codeName: 'GetDraftTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        name: 'GetDraftTempInput',
        id: 'getdrafttempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        name: 'GetDraftTempResult',
        id: 'getdrafttempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTemp',
      id: 'getdrafttemp',
    },
    {
      codeName: 'GetDraftTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        name: 'GetDraftTempMajorInput',
        id: 'getdrafttempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        name: 'GetDraftTempMajorResult',
        id: 'getdrafttempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTempMajor',
      id: 'getdrafttempmajor',
    },
    {
      codeName: 'GetTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'psdelogicnodeid',
        type: 'KEYFIELD',
        name: 'GetTempInput',
        id: 'gettempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        name: 'GetTempResult',
        id: 'gettempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTemp',
      id: 'gettemp',
    },
    {
      codeName: 'GetTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'psdelogicnodeid',
        type: 'KEYFIELD',
        name: 'GetTempMajorInput',
        id: 'gettempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        name: 'GetTempMajorResult',
        id: 'gettempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTempMajor',
      id: 'gettempmajor',
    },
    {
      codeName: 'Remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'psdelogicnodeid',
        type: 'KEYFIELDS',
        name: 'RemoveInput',
        id: 'removeinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveResult',
        id: 'removeresult',
      },
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'RemoveTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'psdelogicnodeid',
        type: 'KEYFIELDS',
        name: 'RemoveTempInput',
        id: 'removetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempResult',
        id: 'removetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTemp',
      id: 'removetemp',
    },
    {
      codeName: 'RemoveTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'psdelogicnodeid',
        type: 'KEYFIELDS',
        name: 'RemoveTempMajorInput',
        id: 'removetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempMajorResult',
        id: 'removetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTempMajor',
      id: 'removetempmajor',
    },
    {
      codeName: 'Save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        output: true,
        name: 'SaveInput',
        id: 'saveinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'SaveResult',
        id: 'saveresult',
      },
      builtinMethod: true,
      actionMode: 'SAVE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'Update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        output: true,
        name: 'UpdateInput',
        id: 'updateinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateResult',
        id: 'updateresult',
      },
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'UpdateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempInput',
        id: 'updatetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempResult',
        id: 'updatetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTemp',
      id: 'updatetemp',
    },
    {
      codeName: 'UpdateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempMajorInput',
        id: 'updatetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempMajorResult',
        id: 'updatetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTempMajor',
      id: 'updatetempmajor',
    },
    {
      codeName: 'FetchDefault',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodefilterdto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchdefault',
    },
    {
      codeName: 'FetchTempDefault',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'psdelogicnodefilterdto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'psdelogicnodedto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchtempdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '添加状态',
      codeName: 'addStatus',
      frontAppViewId: 'web.psde_logic_node_quick_create_view_ms_node',
      frontProcessType: 'WIZARD',
      fullCodeName: 'PSDELogicNode_addStatus',
      navigateParams: [
        {
          key: 'leftpos',
          value: 'leftpos',
          id: 'leftpos',
        },
        {
          key: 'toppos',
          value: 'toppos',
          id: 'toppos',
        },
        {
          key: 'ordervalue',
          value: 'ordervalue',
          id: 'ordervalue',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'addStatus',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.psdelogicnode',
      name: '添加状态',
      id: 'addstatus@psdelogicnode',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'PSDELogicNode',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'psdelogicnodeid',
  logicName: '实体处理逻辑节点',
  majorAppDEFieldId: 'psdelogicnodename',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'PSDELogic',
      majorAppDataEntityId: 'web.psdelogic',
      parentAppDEFieldId: 'psdelogicid',
      parentTextAppDEFieldId: 'psdelogicname',
      rsmode: 1,
      rstype: 'DER1N',
      removeActionType: 1,
      name: 'DER1N_PSDELOGICNODE_PSDELOGIC_PSDELOGICID',
      id: 'psdelogic',
    },
  ],
  quickSearchAppDEFieldIds: ['psdelogicnodename'],
  storageMode: 4,
  defaultMode: true,
  enableFilterActions: true,
  enableTempData: true,
  major: true,
  name: 'PSDELOGICNODE',
  id: 'web.psdelogicnode',
  codeName2: 'PSDELogicNodes',
  requestPaths: [],
};
