export default {
  appDEFields: [
    {
      codeName: 'id',
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'enable',
      logicName: '逻辑有效标识',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ENABLE',
      id: 'enable',
    },
    {
      codeName: 'create_man',
      logicName: '创建人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_MAN',
      id: 'create_man',
    },
    {
      codeName: 'create_time',
      logicName: '创建时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_TIME',
      id: 'create_time',
    },
    {
      codeName: 'update_man',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'UPDATE_MAN',
      id: 'update_man',
    },
    {
      codeName: 'update_time',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'UPDATE_TIME',
      id: 'update_time',
    },
    {
      codeName: 'is_system',
      logicName: '是否系统类型',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_SYSTEM',
      id: 'is_system',
    },
    {
      codeName: 'desc',
      logicName: '描述',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DESC',
      id: 'desc',
    },
    {
      codeName: 'chart_type',
      logicName: '图表类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CHART_TYPE',
      id: 'chart_type',
    },
    {
      codeName: 'group',
      logicName: '组别',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'GROUP',
      id: 'group',
    },
    {
      codeName: 'categories',
      logicName: '类别',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 2000,
      name: 'CATEGORIES',
      id: 'categories',
    },
    {
      codeName: 'categories_name',
      logicName: '类别',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 2000,
      name: 'CATEGORIES_NAME',
      id: 'categories_name',
    },
    {
      codeName: 'template_model',
      logicName: '模板模型',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'TEMPLATE_MODEL',
      id: 'template_model',
    },
    {
      codeName: 'group_data',
      logicName: '分组数据',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'GROUP_DATA',
      id: 'group_data',
    },
    {
      codeName: 'ctrl_id',
      logicName: '报表部件标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CTRL_ID',
      id: 'ctrl_id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'report_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'enable',
          logicName: '逻辑有效标识',
          appDEFieldId: 'enable',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'enable',
        },
        {
          codeName: 'create_man',
          logicName: '创建人',
          appDEFieldId: 'create_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_man',
        },
        {
          codeName: 'create_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '创建时间',
          appDEFieldId: 'create_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_time',
        },
        {
          codeName: 'update_man',
          logicName: '更新人',
          appDEFieldId: 'update_man',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'update_man',
        },
        {
          codeName: 'update_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'update_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'update_time',
        },
        {
          codeName: 'desc',
          logicName: '描述',
          appDEFieldId: 'desc',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'desc',
        },
        {
          codeName: 'is_system',
          logicName: '是否系统类型',
          appDEFieldId: 'is_system',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_system',
        },
        {
          codeName: 'chart_type',
          logicName: '图表类型',
          appDEFieldId: 'chart_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'chart_type',
        },
        {
          codeName: 'group',
          logicName: '组别',
          appDEFieldId: 'group',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'group',
        },
        {
          codeName: 'categories',
          logicName: '类别',
          appDEFieldId: 'categories',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'categories',
        },
        {
          codeName: 'categories_name',
          logicName: '类别',
          appDEFieldId: 'categories_name',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'categories_name',
        },
        {
          codeName: 'template_model',
          logicName: '模板模型',
          appDEFieldId: 'template_model',
          sourceType: 'DEFIELD',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'template_model',
        },
        {
          codeName: 'group_data',
          logicName: '分组数据',
          appDEFieldId: 'group_data',
          sourceType: 'DEFIELD',
          type: 'DTO',
          allowEmpty: true,
          id: 'group_data',
        },
        {
          codeName: 'ctrl_id',
          logicName: '报表部件标识',
          appDEFieldId: 'ctrl_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'ctrl_id',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'report_dto',
    },
    {
      codeName: 'report_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_chart_type_eq',
          logicName: '图表类型',
          appDEFieldId: 'chart_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_chart_type_eq',
        },
        {
          codeName: 'n_group_eq',
          logicName: '组别',
          appDEFieldId: 'group',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_group_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'report_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'sync_model',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/sync_model',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'sync_model',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'report_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'report_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'report_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '新建报表',
      codeName: 'create_report',
      frontAppViewId: 'web.report_quick_create_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'report_create_report',
      nextId: 'open_report_design_view@report',
      sysImage: {
        cssClass: 'fa fa-plus',
        glyph: 'xf067@FontAwesome',
      },
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'create_report',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.report',
      name: '新建报表',
      id: 'create_report@report',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '删除',
      codeName: 'delete_report',
      confirmMsg: '确认删除选中报表吗？ 报表一旦删除无法找回。',
      frontProcessType: 'WIZARD',
      fullCodeName: 'report_delete_report',
      appDEMethodId: 'remove',
      sysImage: {
        cssClass: 'fa fa-remove',
        glyph: 'xf00d@FontAwesome',
      },
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'delete_report',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.report',
      name: '删除',
      id: 'delete_report@report',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'edit_report',
      frontAppViewId: 'web.report_baseinfo_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'report_edit_report',
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'edit_report',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.report',
      name: '编辑',
      id: 'edit_report@report',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '导出PNG',
      codeName: 'export_pdf',
      frontProcessType: 'OTHER',
      fullCodeName: 'report_export_pdf',
      uiactionMode: 'FRONT',
      uiactionTag: 'export_pdf',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'export_pdf',
      appDataEntityId: 'web.report',
      name: '导出PNG',
      id: 'export_pdf@report',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '导出表格',
      codeName: 'export_table',
      fullCodeName: 'report_export_table',
      uiactionMode: 'FRONT',
      uiactionTag: 'export_table',
      uiactionType: 'DEUIACTION',
      uilogicAttachMode: 'REPLACE',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDEUILogicId: 'export_excel',
      appDataEntityId: 'web.report',
      name: '导出表格',
      id: 'export_table@report',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '编辑',
      codeName: 'open_bi_report_panel_view',
      frontAppViewId: 'web.report_bi_report_panel_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'report_open_bi_report_panel_view',
      navigateContexts: [
        {
          key: 'SRFDEFAULTTOROUTEDEPTH',
          value: '3',
          rawValue: true,
          name: 'SRFDEFAULTTOROUTEDEPTH',
          id: 'srfdefaulttoroutedepth',
        },
        {
          key: 'REPORT',
          value: 'report',
          name: 'REPORT',
          id: 'report',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'open_bi_report_panel_view',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.report',
      name: '打开BI报表设计图面板视图',
      id: 'open_bi_report_panel_view@report',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      caption: '设计',
      codeName: 'open_report_design_view',
      frontProcessType: 'OTHER',
      fullCodeName: 'report_open_report_design_view',
      sysImage: {
        cssClass: 'fa fa-wrench',
        glyph: 'xf0ad@FontAwesome',
      },
      refreshMode: 1,
      scriptCode:
        "const result = await ibiz.util.biReport.openDesignPage(context,params,{mode:'DATA',reportId: data[0].id});\r\nreturn result;",
      uiactionMode: 'FRONT',
      uiactionTag: 'open_report_design_view',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'web.report',
      name: '打开报表设计界面',
      id: 'open_report_design_view@report',
    },
  ],
  appDEUILogics: [
    {
      codeName: 'export_excel',
      defaultParamName: 'Default',
      logicName: '导出表格',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 170,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'preparejsparam1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: 'if (uiLogic.grid) {\r\n    uiLogic.grid.exportData({params: {}});\r\n}',
          codeName: 'RAWJSCODE1',
          leftPos: 562,
          logicNodeType: 'RAWJSCODE',
          topPos: 208,
          name: '整合表格数据并导出',
          id: 'rawjscode1',
        },
        {
          codeName: 'PREPAREJSPARAM1',
          leftPos: 330,
          logicNodeType: 'PREPAREJSPARAM',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'preparejsparam1',
              id: '连接名称',
            },
          ],
          deuilogicNodeParams: [
            {
              dstDEUILogicParamId: 'bigrid',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'layoutPanel.panelItems.field_text_dynamic.grid',
              srcDEUILogicParamId: 'view',
              srcValueType: 'SRCDLPARAM',
              name: 'view[layoutPanel.panelItems.field_text_dynamic.grid] ==> biGrid',
              id: 'view[layoutpanel.panelitems.field_text_dynamic.grid] ==> bigrid',
            },
            {
              dstDEUILogicParamId: 'grid',
              paramAction: 'SETPARAMVALUE',
              srcFieldName: 'chartController',
              srcDEUILogicParamId: 'bigrid',
              srcValueType: 'SRCDLPARAM',
              name: 'biGrid[chartController] ==> grid',
              id: 'bigrid[chartcontroller] ==> grid',
            },
          ],
          topPos: 208,
          name: '获取表格',
          id: 'preparejsparam1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
        {
          codeName: 'view',
          activeViewParam: true,
          name: '视图',
          id: 'view',
        },
        {
          codeName: 'biGrid',
          entityParam: true,
          name: 'bi表格',
          id: 'bigrid',
        },
        {
          codeName: 'grid',
          entityParam: true,
          name: '表格',
          id: 'grid',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '导出表格',
      id: 'export_excel',
    },
    {
      codeName: 'export_pdf',
      defaultParamName: 'Default',
      logicName: '导出为pdf',
      deuilogicNodes: [
        {
          codeName: 'Begin',
          leftPos: 200,
          logicNodeType: 'BEGIN',
          deuilogicLinks: [
            {
              dstDEUILogicNodeId: 'rawjscode1',
              srcDEUILogicNodeId: 'begin',
              id: '连接名称',
            },
          ],
          topPos: 200,
          parallelOutput: true,
          name: '开始',
          id: 'begin',
        },
        {
          code: "const viewDom = document.getElementById(view.id);\r\nif (viewDom) {\r\n    const content = viewDom.querySelector('.ibiz-bi-report-panel-content>.el-collapse');\r\n    const fileName = view.model.caption;\r\n    ibiz.util.html2canvas.exportCanvas(content, { fileName });\r\n}",
          codeName: 'RAWJSCODE1',
          leftPos: 470,
          logicNodeType: 'RAWJSCODE',
          topPos: 208,
          name: '导出图片脚本',
          id: 'rawjscode1',
        },
      ],
      deuilogicParams: [
        {
          codeName: 'Default',
          default: true,
          entityParam: true,
          name: '传入变量',
          id: 'default',
        },
      ],
      startDEUILogicNodeId: 'begin',
      name: '导出为pdf',
      id: 'export_pdf',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'report',
  deapicodeName: 'report',
  deapicodeName2: 'reports',
  deapitag: 'REPORT',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  logicName: '分析报表',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'REPORT',
  id: 'web.report',
  codeName2: 'reports',
  requestPaths: [],
};
