package cn.ibizlab.employee_management.logic.user_objectlogic.my_dept;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.employee_management.domain.user_object user_objectmy_deptdefault;
                global cn.ibizlab.core.employee_management.domain.department user_objectmy_deptfilter;
                global cn.ibizlab.core.employee_management.domain.department user_objectmy_deptpage;
                    global cn.ibizlab.core.employee_management.service.IdepartmentService departmentservice;
        global cn.ibizlab.core.employee_management.service.Iuser_objectService iBzSysUser_objectDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "user_objectmy_deptbegin"
            when
            then
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode1"
            ruleflow-group "user_objectmy_deptrawsfcode1"
            when
            then
                        update(user_objectmy_deptdefault);//更新fact中变量值
                        update(user_objectmy_deptfilter);//更新fact中变量值
                        update(user_objectmy_deptpage);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset1"
            ruleflow-group "user_objectmy_deptdedataset1"
            when
            then
                        update(user_objectmy_deptdefault);//更新fact中变量值
                        update(user_objectmy_deptfilter);//更新fact中变量值
                        update(user_objectmy_deptpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "user_objectmy_deptend1"
            when
            then
                        update(user_objectmy_deptdefault);//更新fact中变量值
                        update(user_objectmy_deptfilter);//更新fact中变量值
                        update(user_objectmy_deptpage);//更新fact中变量值
            end