package cn.ibizlab.base.logic.res_partnerlogic.get_complete_name;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.res_partner res_partnerget_complete_namedefault;
                global cn.ibizlab.core.base.domain.res_partner res_partnerget_complete_namecompute_partner;
        global cn.ibizlab.core.base.service.Ires_partnerService iBzSysRes_partnerDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "res_partnerget_complete_namebegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "res_partnerget_complete_nameprepareparam_01"
            when
            then
                            res_partnerget_complete_namecompute_partner.set("name",res_partnerget_complete_namedefault.get("name"));
                        update(res_partnerget_complete_namedefault);//更新fact中变量值
                        update(res_partnerget_complete_namecompute_partner);//更新fact中变量值
            end