package cn.ibizlab.base.logic.res_userslogic.change_cloud_user_pwd;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.res_users res_userschange_cloud_user_pwddefault;
        global cn.ibizlab.core.base.service.Ires_usersService iBzSysRes_usersDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "res_userschange_cloud_user_pwdbegin"
            when
            then
            end