package cn.ibizlab.attendance.logic.attendance_department_statisticslogic.department_statistics;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_department_statistics attendance_department_statisticsdepartment_statisticsdefault;
                global cn.ibizlab.core.attendance.domain.attendance_department_statistics attendance_department_statisticsdepartment_statisticsdept_filter;
                global cn.ibizlab.core.employee_management.domain.department attendance_department_statisticsdepartment_statisticsdept_page;
                global cn.ibizlab.core.employee_management.domain.department attendance_department_statisticsdepartment_statisticsdept_temp;
                global cn.ibizlab.core.attendance.domain.attendance_record_detail attendance_department_statisticsdepartment_statisticsrecord_details;
                    global cn.ibizlab.core.employee_management.service.IdepartmentService departmentservice;
        global cn.ibizlab.core.attendance.service.Iattendance_department_statisticsService iBzSysAttendance_department_statisticsDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_department_statisticsdepartment_statisticsbegin"
            when
            then
            end

            //逻辑处理节点[解析搜索条件]
            rule "rawsfcode2"
            ruleflow-group "attendance_department_statisticsdepartment_statisticsrawsfcode2"
            when
            then
                        update(attendance_department_statisticsdepartment_statisticsdefault);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_filter);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_page);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_temp);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsrecord_details);//更新fact中变量值
            end

            //逻辑处理节点[查询部门]
            rule "dedataset1"
            ruleflow-group "attendance_department_statisticsdepartment_statisticsdedataset1"
            when
            then
                        update(attendance_department_statisticsdepartment_statisticsdefault);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_filter);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_page);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_temp);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsrecord_details);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "attendance_department_statisticsdepartment_statisticsloopsubcall1"
            when
            then
                        update(attendance_department_statisticsdepartment_statisticsdefault);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_filter);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_page);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_temp);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsrecord_details);//更新fact中变量值
            end

            //逻辑处理节点[统计考勤]
            rule "rawsfcode1"
            ruleflow-group "attendance_department_statisticsdepartment_statisticsrawsfcode1"
            when
            then
                        update(attendance_department_statisticsdepartment_statisticsdefault);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_filter);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_page);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_temp);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsrecord_details);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "attendance_department_statisticsdepartment_statisticsend1"
            when
            then
                        update(attendance_department_statisticsdepartment_statisticsdefault);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_filter);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_page);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsdept_temp);//更新fact中变量值
                        update(attendance_department_statisticsdepartment_statisticsrecord_details);//更新fact中变量值
            end