export default {
  appDEDataExports: [
    {
      codeName: 'AbnormalAttendance',
      maxRowCount: 5000,
      dedataExportItems: [
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.MEMBER_NAME',
          },
          caption: '姓名',
          format: '%1$s',
          appDEFieldId: 'member_name',
          id: 'member_name',
        },
        {
          caption: '工号',
          format: '%1$s',
          appDEFieldId: 'member_num',
          id: 'member_num',
        },
        {
          align: 'CENTER',
          caption: '部门',
          format: '%1$s',
          appDEFieldId: 'dept_name',
          id: 'dept_name',
        },
        {
          align: 'CENTER',
          caption: '职位',
          format: '%1$s',
          appDEFieldId: 'title',
          id: 'title',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_DATE',
          },
          caption: '日期',
          format: '%1$s',
          appDEFieldId: 'checkin_date',
          id: 'checkin_date',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.RULE_NAME',
          },
          caption: '考勤规则',
          format: '%1$s',
          appDEFieldId: 'rule_name',
          id: 'rule_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.SHIFT_MESSAGE',
          },
          caption: '班次',
          format: '%1$s',
          appDEFieldId: 'shift_message',
          id: 'shift_message',
        },
        {
          caption: '上班1打开时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_1',
        },
        {
          caption: '下班1打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_1',
        },
        {
          caption: '上班2打开时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_2',
        },
        {
          caption: '下班2打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_2',
        },
        {
          caption: '上班3打开时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_3',
        },
        {
          caption: '下班3打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_3',
        },
        {
          caption: '上班4打开时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_4',
        },
        {
          caption: '下班4打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_4',
        },
        {
          caption: '上班5打开时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_5',
        },
        {
          caption: '下班5打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_5',
        },
        {
          caption: '上班6打开时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_6',
        },
        {
          caption: '下班6打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_6',
        },
        {
          caption: '上班7打开时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_7',
        },
        {
          caption: '下班7打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_7',
        },
        {
          caption: '上班8打开时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_8',
        },
        {
          caption: '下班8打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_8',
        },
        {
          caption: '上班9打开时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_9',
        },
        {
          caption: '下班9打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_9',
        },
        {
          caption: '上班10打开时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_10',
        },
        {
          caption: '下班10打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_10',
        },
        {
          align: 'CENTER',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_RESULT',
          },
          caption: '考勤结果',
          format: '%1$s',
          appDEFieldId: 'checkin_result',
          codeListId: 'attendanceapp.attendance__attendance_result',
          id: 'checkin_result',
        },
        {
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LATE_MINUTES',
          },
          caption: '迟到时长（分钟）',
          format: '%1$s',
          appDEFieldId: 'late_minutes',
          id: 'late_minutes',
        },
        {
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LEAVE_EARLY_MINUTES',
          },
          caption: '早退时长（分钟）',
          format: '%1$s',
          appDEFieldId: 'leave_early_minutes',
          id: 'leave_early_minutes',
        },
      ],
      enableBackend: true,
      name: '异常考勤',
      id: 'abnormalattendance',
    },
    {
      codeName: 'DataExport',
      maxRowCount: 5000,
      dedataExportItems: [
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.MEMBER_NAME',
          },
          caption: '姓名',
          format: '%1$s',
          appDEFieldId: 'member_name',
          id: 'member_name',
        },
        {
          caption: '工号',
          format: '%1$s',
          appDEFieldId: 'member_num',
          id: 'member_num',
        },
        {
          align: 'CENTER',
          caption: '部门',
          format: '%1$s',
          appDEFieldId: 'dept_name',
          id: 'dept_name',
        },
        {
          align: 'CENTER',
          caption: '职位',
          format: '%1$s',
          appDEFieldId: 'title',
          id: 'title',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_DATE',
          },
          caption: '日期',
          format: '%1$s',
          appDEFieldId: 'checkin_date',
          id: 'checkin_date',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.RULE_NAME',
          },
          caption: '考勤规则',
          format: '%1$s',
          appDEFieldId: 'rule_name',
          id: 'rule_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.SHIFT_MESSAGE',
          },
          caption: '班次',
          format: '%1$s',
          appDEFieldId: 'shift_message',
          id: 'shift_message',
        },
        {
          caption: '上班1打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_1',
        },
        {
          caption: '下班1打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_1',
        },
        {
          caption: '上班2打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_2',
        },
        {
          caption: '下班2打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_2',
        },
        {
          caption: '上班3打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_3',
        },
        {
          caption: '下班3打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_3',
        },
        {
          caption: '上班4打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_4',
        },
        {
          caption: '下班4打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_4',
        },
        {
          caption: '上班5打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_5',
        },
        {
          caption: '下班5打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_5',
        },
        {
          caption: '上班6打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_6',
        },
        {
          caption: '下班6打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_6',
        },
        {
          caption: '上班7打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_7',
        },
        {
          caption: '下班7打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_7',
        },
        {
          caption: '上班8打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_8',
        },
        {
          caption: '下班8打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_8',
        },
        {
          caption: '上班9打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_9',
        },
        {
          caption: '下班9打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_9',
        },
        {
          caption: '上班10打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'start_10',
        },
        {
          caption: '下班10打卡时间',
          format: '%1$s',
          appDEFieldId: 'details',
          id: 'end_10',
        },
        {
          align: 'CENTER',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_RESULT',
          },
          caption: '考勤结果',
          format: '%1$s',
          appDEFieldId: 'checkin_result',
          codeListId: 'attendanceapp.attendance__attendance_result',
          id: 'checkin_result',
        },
        {
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.SHOULD_ATTENDANCE_HOURS',
          },
          caption: '应出勤时长（小时）',
          format: '%1$s',
          appDEFieldId: 'should_attendance_hours',
          userParam: {
            tooltip: '当天班次规定的工作时长',
          },
          id: 'should_attendance_hours',
        },
        {
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.BILLABLE_HOURS',
          },
          caption: '计薪时长（小时）',
          format: '%1$s',
          appDEFieldId: 'billable_hours',
          userParam: {
            tooltip: '当天班次规定的工作时长减掉旷工时长和不带薪的假期时长',
          },
          id: 'billable_hours',
        },
        {
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.WORKING_HOURS',
          },
          caption: '实际出勤时长（小时）',
          format: '%1$s',
          appDEFieldId: 'working_hours',
          userParam: {
            tooltip:
              '当天班次的考勤周期内，早晚打卡时间相减并扣掉休息时间所得为实际出勤时长',
          },
          id: 'working_hours',
        },
        {
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LATE_MINUTES',
          },
          caption: '迟到时长（分钟）',
          format: '%1$s',
          appDEFieldId: 'late_minutes',
          id: 'late_minutes',
        },
        {
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LEAVE_EARLY_MINUTES',
          },
          caption: '早退时长（分钟）',
          format: '%1$s',
          appDEFieldId: 'leave_early_minutes',
          id: 'leave_early_minutes',
        },
        {
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OVERTIME_HOURS',
          },
          caption: '加班时长（小时）',
          format: '%1$s',
          appDEFieldId: 'overtime_hours',
          id: 'overtime_hours',
        },
        {
          align: 'RIGHT',
          caption: '请假时长(小时)',
          format: '%1$s',
          appDEFieldId: 'leave_duration',
          id: 'leave_duration',
        },
        {
          caption: '请假类型',
          format: '%1$s',
          appDEFieldId: 'leave_type',
          codeListId: 'attendanceapp.attendance__holidaytype',
          id: 'leave_type',
        },
        {
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.ON_BUSINESS_DAYS',
          },
          caption: '出差天数',
          format: '%1$s',
          appDEFieldId: 'on_business_days',
          id: 'on_business_days',
        },
        {
          align: 'RIGHT',
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OUT_HOURS',
          },
          caption: '外出时长（小时）',
          format: '%1$s',
          appDEFieldId: 'out_hours',
          id: 'out_hours',
        },
      ],
      enableBackend: true,
      name: '每日统计',
      id: 'dataexport',
    },
  ],
  appDEFields: [
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_uid',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'details',
      logicName: '考勤明细',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'DETAILS',
      id: 'details',
    },
    {
      codeName: 'member_num',
      logicName: '工号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 20,
      name: 'MEMBER_NUM',
      id: 'member_num',
    },
    {
      codeName: 'dept_id',
      logicName: '部门ID',
      predefinedType: 'ORGSECTORID',
      stdDataType: 25,
      stringLength: 60,
      name: 'DEPT_ID',
      id: 'dept_id',
    },
    {
      codeName: 'leave_duration',
      logicName: '请假时长',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'LEAVE_DURATION',
      id: 'leave_duration',
    },
    {
      codeName: 'leave_type',
      logicName: '请假类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'LEAVE_TYPE',
      id: 'leave_type',
    },
    {
      codeName: 'checkin_missing_times',
      logicName: '缺卡次数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'CHECKIN_MISSING_TIMES',
      id: 'checkin_missing_times',
    },
    {
      codeName: 'leave_early_times',
      logicName: '早退次数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LEAVE_EARLY_TIMES',
      id: 'leave_early_times',
    },
    {
      codeName: 'late_times',
      logicName: '迟到次数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LATE_TIMES',
      id: 'late_times',
    },
    {
      codeName: 'dept_name',
      logicName: '部门',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      name: 'DEPT_NAME',
      id: 'dept_name',
    },
    {
      codeName: 'title',
      logicName: '职位',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      name: 'TITLE',
      id: 'title',
    },
    {
      codeName: 'actual_attendance_days',
      logicName: '实际出勤天数',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'ACTUAL_ATTENDANCE_DAYS',
      id: 'actual_attendance_days',
    },
    {
      codeName: 'should_attendance_days',
      logicName: '应出勤天数',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'SHOULD_ATTENDANCE_DAYS',
      id: 'should_attendance_days',
    },
    {
      codeName: 'is_overtime',
      logicName: '是否加班',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_OVERTIME',
      id: 'is_overtime',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.ID',
      },
      logicName: '考勤记录ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'member_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.MEMBER_NAME',
      },
      logicName: '员工姓名',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      name: 'MEMBER_NAME',
      id: 'member_name',
    },
    {
      codeName: 'member_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.MEMBER_ID',
      },
      logicName: '员工ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'MEMBER_ID',
      id: 'member_id',
    },
    {
      codeName: 'checkin_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_DATE',
      },
      logicName: '考勤日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'CHECKIN_DATE',
      id: 'checkin_date',
    },
    {
      codeName: 'should_attendance_hours',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.SHOULD_ATTENDANCE_HOURS',
      },
      logicName: '应出勤时长（小时）',
      predefinedType: 'NONE',
      stdDataType: 6,
      name: 'SHOULD_ATTENDANCE_HOURS',
      id: 'should_attendance_hours',
    },
    {
      codeName: 'is_business_trip',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.IS_BUSINESS_TRIP',
      },
      logicName: '是否出差',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_BUSINESS_TRIP',
      id: 'is_business_trip',
    },
    {
      codeName: 'schedule_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.SCHEDULE_TYPE',
      },
      logicName: '排班类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 20,
      name: 'SCHEDULE_TYPE',
      id: 'schedule_type',
    },
    {
      codeName: 'is_out_work',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.IS_OUT_WORK',
      },
      logicName: '是否外勤',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_OUT_WORK',
      id: 'is_out_work',
    },
    {
      codeName: 'shift_message',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.SHIFT_MESSAGE',
      },
      logicName: '班次信息',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'SHIFT_MESSAGE',
      id: 'shift_message',
    },
    {
      codeName: 'is_go_out',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.IS_GO_OUT',
      },
      logicName: '是否外出',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_GO_OUT',
      id: 'is_go_out',
    },
    {
      codeName: 'checkin_message',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_MESSAGE',
      },
      logicName: '打卡状态信息',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 20,
      name: 'CHECKIN_MESSAGE',
      id: 'checkin_message',
    },
    {
      codeName: 'is_leave',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.IS_LEAVE',
      },
      logicName: '是否请假',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_LEAVE',
      id: 'is_leave',
    },
    {
      codeName: 'checkin_result',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.CHECKIN_RESULT',
      },
      logicName: '考勤结果',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CHECKIN_RESULT',
      id: 'checkin_result',
    },
    {
      codeName: 'rule_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.RULE_NAME',
      },
      logicName: '规则名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      name: 'RULE_NAME',
      id: 'rule_name',
    },
    {
      codeName: 'rule_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.RULE_ID',
      },
      logicName: '考勤规则ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'RULE_ID',
      id: 'rule_id',
    },
    {
      codeName: 'leave_early_minutes',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LEAVE_EARLY_MINUTES',
      },
      logicName: '早退分钟数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LEAVE_EARLY_MINUTES',
      id: 'leave_early_minutes',
    },
    {
      codeName: 'working_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.WORKING_TIME',
      },
      logicName: '实际出勤时长（分钟）',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'WORKING_TIME',
      id: 'working_time',
    },
    {
      codeName: 'late_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LATE_TIME',
      },
      logicName: '迟到时间',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LATE_TIME',
      id: 'late_time',
    },
    {
      codeName: 'leave_early_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LEAVE_EARLY_TIME',
      },
      logicName: '早退时间',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LEAVE_EARLY_TIME',
      id: 'leave_early_time',
    },
    {
      codeName: 'late_minutes',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.LATE_MINUTES',
      },
      logicName: '迟到分钟数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'LATE_MINUTES',
      id: 'late_minutes',
    },
    {
      codeName: 'billable_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.BILLABLE_TIME',
      },
      logicName: '计薪时长（分钟）',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'BILLABLE_TIME',
      id: 'billable_time',
    },
    {
      codeName: 'working_hours',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.WORKING_HOURS',
      },
      logicName: '实际出勤时长（小时）',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'WORKING_HOURS',
      id: 'working_hours',
    },
    {
      codeName: 'overtime_hours',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OVERTIME_HOURS',
      },
      logicName: '加班小时数',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'OVERTIME_HOURS',
      id: 'overtime_hours',
    },
    {
      codeName: 'billable_hours',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.BILLABLE_HOURS',
      },
      logicName: '计薪时长（小时）',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'BILLABLE_HOURS',
      id: 'billable_hours',
    },
    {
      codeName: 'should_attendance_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.SHOULD_ATTENDANCE_TIME',
      },
      logicName: '应出勤时长（分钟）',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'SHOULD_ATTENDANCE_TIME',
      id: 'should_attendance_time',
    },
    {
      codeName: 'overtime_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OVERTIME_TIME',
      },
      logicName: '加班时间',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'OVERTIME_TIME',
      id: 'overtime_time',
    },
    {
      codeName: 'out_work_hours',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OUT_WORK_HOURS',
      },
      logicName: '外勤小时数',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'OUT_WORK_HOURS',
      id: 'out_work_hours',
    },
    {
      codeName: 'on_business_days',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.ON_BUSINESS_DAYS',
      },
      logicName: '出差天数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ON_BUSINESS_DAYS',
      id: 'on_business_days',
    },
    {
      codeName: 'out_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OUT_TIME',
      },
      logicName: '外出时间',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'OUT_TIME',
      id: 'out_time',
    },
    {
      codeName: 'out_work_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OUT_WORK_TIME',
      },
      logicName: '外勤时间',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'OUT_WORK_TIME',
      id: 'out_work_time',
    },
    {
      codeName: 'out_hours',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OUT_HOURS',
      },
      logicName: '外出小时数',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'OUT_HOURS',
      id: 'out_hours',
    },
    {
      codeName: 'off_hours',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_RECORD.OFF_HOURS',
      },
      logicName: '调休使用时长',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'OFF_HOURS',
      id: 'off_hours',
    },
    {
      codeName: 'is_pay_overtime',
      logicName: '是否计加班费',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_PAY_OVERTIME',
      id: 'is_pay_overtime',
    },
    {
      codeName: 'is_rest_overtime',
      logicName: '是否计调休假',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'IS_REST_OVERTIME',
      id: 'is_rest_overtime',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'attendance_record_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'details',
          logicName: '考勤明细',
          appDEFieldId: 'details',
          refAppDEDataSetId: 'fetch_default',
          refAppDEMethodDTOId: 'attendance_record_detail_dto',
          refAppDataEntityId: 'attendanceapp.attendance_record_detail',
          refPickupAppDEFieldId: 'record_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'details',
        },
        {
          codeName: 'member_num',
          logicName: '工号',
          appDEFieldId: 'member_num',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'member_num',
        },
        {
          codeName: 'dept_id',
          logicName: '部门ID',
          appDEFieldId: 'dept_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'dept_id',
        },
        {
          codeName: 'leave_duration',
          logicName: '请假时长',
          appDEFieldId: 'leave_duration',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'leave_duration',
        },
        {
          codeName: 'leave_type',
          logicName: '请假类型',
          appDEFieldId: 'leave_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'leave_type',
        },
        {
          codeName: 'checkin_missing_times',
          logicName: '缺卡次数',
          appDEFieldId: 'checkin_missing_times',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'checkin_missing_times',
        },
        {
          codeName: 'leave_early_times',
          logicName: '早退次数',
          appDEFieldId: 'leave_early_times',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'leave_early_times',
        },
        {
          codeName: 'late_times',
          logicName: '迟到次数',
          appDEFieldId: 'late_times',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'late_times',
        },
        {
          codeName: 'dept_name',
          logicName: '部门',
          appDEFieldId: 'dept_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'dept_name',
        },
        {
          codeName: 'title',
          logicName: '职位',
          appDEFieldId: 'title',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'title',
        },
        {
          codeName: 'actual_attendance_days',
          logicName: '实际出勤天数',
          appDEFieldId: 'actual_attendance_days',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'actual_attendance_days',
        },
        {
          codeName: 'should_attendance_days',
          logicName: '应出勤天数',
          appDEFieldId: 'should_attendance_days',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'should_attendance_days',
        },
        {
          codeName: 'is_overtime',
          logicName: '是否加班',
          appDEFieldId: 'is_overtime',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_overtime',
        },
        {
          codeName: 'billable_hours',
          logicName: '计薪时长（小时）',
          appDEFieldId: 'billable_hours',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'billable_hours',
        },
        {
          codeName: 'billable_time',
          logicName: '计薪时长（分钟）',
          appDEFieldId: 'billable_time',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'billable_time',
        },
        {
          codeName: 'checkin_date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '考勤日期',
          appDEFieldId: 'checkin_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'checkin_date',
        },
        {
          codeName: 'checkin_message',
          logicName: '打卡状态信息',
          appDEFieldId: 'checkin_message',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'checkin_message',
        },
        {
          codeName: 'checkin_result',
          logicName: '考勤结果',
          appDEFieldId: 'checkin_result',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'checkin_result',
        },
        {
          codeName: 'id',
          logicName: '考勤记录ID',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'id',
        },
        {
          codeName: 'is_business_trip',
          logicName: '是否出差',
          appDEFieldId: 'is_business_trip',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_business_trip',
        },
        {
          codeName: 'is_go_out',
          logicName: '是否外出',
          appDEFieldId: 'is_go_out',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_go_out',
        },
        {
          codeName: 'is_leave',
          logicName: '是否请假',
          appDEFieldId: 'is_leave',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_leave',
        },
        {
          codeName: 'is_out_work',
          logicName: '是否外勤',
          appDEFieldId: 'is_out_work',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_out_work',
        },
        {
          codeName: 'is_pay_overtime',
          logicName: '是否计加班费',
          appDEFieldId: 'is_pay_overtime',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_pay_overtime',
        },
        {
          codeName: 'is_rest_overtime',
          logicName: '是否计调休假',
          appDEFieldId: 'is_rest_overtime',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'is_rest_overtime',
        },
        {
          codeName: 'late_minutes',
          logicName: '迟到分钟数',
          appDEFieldId: 'late_minutes',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'late_minutes',
        },
        {
          codeName: 'late_time',
          logicName: '迟到时间',
          appDEFieldId: 'late_time',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'late_time',
        },
        {
          codeName: 'leave_early_minutes',
          logicName: '早退分钟数',
          appDEFieldId: 'leave_early_minutes',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'leave_early_minutes',
        },
        {
          codeName: 'leave_early_time',
          logicName: '早退时间',
          appDEFieldId: 'leave_early_time',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'leave_early_time',
        },
        {
          codeName: 'member_id',
          logicName: '员工ID',
          appDEFieldId: 'member_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'member_id',
        },
        {
          codeName: 'member_name',
          logicName: '员工姓名',
          appDEFieldId: 'member_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'member_name',
        },
        {
          codeName: 'off_hours',
          logicName: '调休使用时长',
          appDEFieldId: 'off_hours',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'off_hours',
        },
        {
          codeName: 'on_business_days',
          logicName: '出差天数',
          appDEFieldId: 'on_business_days',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'on_business_days',
        },
        {
          codeName: 'out_hours',
          logicName: '外出小时数',
          appDEFieldId: 'out_hours',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'out_hours',
        },
        {
          codeName: 'out_time',
          logicName: '外出时间',
          appDEFieldId: 'out_time',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'out_time',
        },
        {
          codeName: 'out_work_hours',
          logicName: '外勤小时数',
          appDEFieldId: 'out_work_hours',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'out_work_hours',
        },
        {
          codeName: 'out_work_time',
          logicName: '外勤时间',
          appDEFieldId: 'out_work_time',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'out_work_time',
        },
        {
          codeName: 'overtime_hours',
          logicName: '加班小时数',
          appDEFieldId: 'overtime_hours',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'overtime_hours',
        },
        {
          codeName: 'overtime_time',
          logicName: '加班时间',
          appDEFieldId: 'overtime_time',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'overtime_time',
        },
        {
          codeName: 'rule_id',
          logicName: '考勤规则ID',
          appDEFieldId: 'rule_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rule_id',
        },
        {
          codeName: 'rule_name',
          logicName: '规则名称',
          appDEFieldId: 'rule_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rule_name',
        },
        {
          codeName: 'schedule_type',
          logicName: '排班类型',
          appDEFieldId: 'schedule_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'schedule_type',
        },
        {
          codeName: 'shift_message',
          logicName: '班次信息',
          appDEFieldId: 'shift_message',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'shift_message',
        },
        {
          codeName: 'should_attendance_hours',
          logicName: '应出勤时长（小时）',
          appDEFieldId: 'should_attendance_hours',
          sourceType: 'DEFIELD',
          stdDataType: 6,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'should_attendance_hours',
        },
        {
          codeName: 'should_attendance_time',
          logicName: '应出勤时长（分钟）',
          appDEFieldId: 'should_attendance_time',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'should_attendance_time',
        },
        {
          codeName: 'working_hours',
          logicName: '实际出勤时长（小时）',
          appDEFieldId: 'working_hours',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'working_hours',
        },
        {
          codeName: 'working_time',
          logicName: '实际出勤时长（分钟）',
          appDEFieldId: 'working_time',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'working_time',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'attendance_record_dto',
    },
    {
      codeName: 'attendance_record_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_checkin_date_gtandeq',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '考勤日期',
          appDEFieldId: 'checkin_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_checkin_date_gtandeq',
        },
        {
          codeName: 'n_checkin_date_ltandeq',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '考勤日期',
          appDEFieldId: 'checkin_date',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_checkin_date_ltandeq',
        },
        {
          codeName: 'n_checkin_result_eq',
          logicName: '考勤结果',
          appDEFieldId: 'checkin_result',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_checkin_result_eq',
        },
        {
          codeName: 'n_checkin_result_in',
          logicName: '考勤结果',
          appDEFieldId: 'checkin_result',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLES',
          allowEmpty: true,
          id: 'n_checkin_result_in',
        },
        {
          codeName: 'n_dept_id_eq',
          logicName: '部门ID',
          appDEFieldId: 'dept_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_dept_id_eq',
        },
        {
          codeName: 'n_details_isnotnull',
          logicName: '考勤明细',
          appDEFieldId: 'details',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 21,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_details_isnotnull',
        },
        {
          codeName: 'n_id_eq',
          logicName: '考勤记录ID',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_member_id_eq',
          logicName: '员工ID',
          appDEFieldId: 'member_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_member_id_eq',
        },
        {
          codeName: 'n_member_name_eq',
          logicName: '员工姓名',
          appDEFieldId: 'member_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_member_name_eq',
        },
        {
          codeName: 'n_member_name_like',
          logicName: '员工姓名',
          appDEFieldId: 'member_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_member_name_like',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_rule_id_eq',
          logicName: '考勤规则ID',
          appDEFieldId: 'rule_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rule_id_eq',
        },
        {
          codeName: 'n_rule_name_eq',
          logicName: '规则名称',
          appDEFieldId: 'rule_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rule_name_eq',
        },
        {
          codeName: 'n_rule_name_like',
          logicName: '规则名称',
          appDEFieldId: 'rule_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rule_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'attendance_record_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_info',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_info',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'check_info',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'my_attendance_summary',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/my_attendance_summary',
      actionMode: 'GETDRAFT',
      actionTag: 'MyAttendanceSummary',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'MyAttendanceSummary',
      id: 'my_attendance_summary',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_abnormal_attendance',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_abnormal_attendance',
      actionType: 'REMOTE',
      dataSetName: 'abnormal_attendance',
      dataSetTag: 'abnormal_attendance',
      dataSetType: 'REMOTE',
      id: 'fetch_abnormal_attendance',
    },
    {
      codeName: 'fetch_clock',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_clock',
      actionType: 'REMOTE',
      dataSetName: 'clock',
      dataSetTag: 'clock',
      dataSetType: 'REMOTE',
      id: 'fetch_clock',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_record',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_record_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_record_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_record',
      actionType: 'REMOTE',
      dataSetName: 'record',
      dataSetTag: 'record',
      dataSetType: 'REMOTE',
      id: 'fetch_record',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导出报表',
      codeName: 'AbnormalAttendance',
      frontProcessType: 'OTHER',
      fullCodeName: 'attendance_record_AbnormalAttendance',
      scriptCode:
        "const viewC = view\r\nconst tempPatams = {...viewC.params};\r\nif (viewC.getController(\"searchform\")) {\r\n    const searchForm = viewC.getController(\"searchform\");\r\n    Object.assign(tempPatams, {...searchForm.data});\r\n}\r\nconsole.log('导出报表参数：', tempPatams);\r\ndelete tempPatams.n_checkin_date_gtandeq;\r\ndelete tempPatams.n_checkin_date_ltandeq;\r\ndelete tempPatams.n_member_id_in;\r\nconst urlParam = new URLSearchParams(tempPatams);\r\nconst exportUrl = `/attendance_records/exportdata/fetch_abnormal_attendance/?srfexporttag=AbnormalAttendance&${decodeURIComponent(urlParam)}`;\r\nconst app = ibiz.hub.getApp(context.srfappid);\r\nconst { data: file } = await app.net.request(exportUrl, {\r\n    method: 'post',\r\n    data: tempPatams,\r\n    responseType: 'blob',\r\n});\r\nif (file) {\r\n    const title = viewC.model.title;\r\n    const fileName = `${title}表.xlsx`;\r\n    const filetype = 'application/vnd.ms-excel';\r\n    const blob = new Blob([file], { type: filetype });\r\n    const href = URL.createObjectURL(blob);\r\n    const a = document.createElement('a');\r\n    a.href = href;\r\n    a.download = fileName;\r\n    document.body.appendChild(a);\r\n    a.click();\r\n    document.body.removeChild(a);\r\n    URL.revokeObjectURL(href);\r\n}",
      uiactionMode: 'FRONT',
      uiactionTag: 'AbnormalAttendance',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'attendanceapp.attendance_record',
      name: '导出异常考勤报表',
      id: 'abnormalattendance@attendance_record',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '考勤记录反查',
      codeName: 'check_info',
      frontAppViewId: 'attendanceapp.attendance_record_check_info_edit_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'attendance_record_check_info',
      navigateContexts: [
        {
          key: 'ATTENDANCE_RECORD',
          value: 'id',
          name: 'ATTENDANCE_RECORD',
          id: 'attendance_record',
        },
      ],
      navigateParams: [
        {
          key: 'attendance_record',
          value: 'id',
          id: 'attendance_record',
        },
      ],
      uiactionMode: 'FRONT',
      uiactionTag: 'check_info',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'attendanceapp.attendance_record',
      name: '考勤记录反查',
      id: 'check_info@attendance_record',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '考勤记录反查校验',
      codeName: 'check_info_vail',
      frontProcessType: 'OTHER',
      fullCodeName: 'attendance_record_check_info_vail',
      nextId: 'check_info@attendance_record',
      scriptCode:
        "console.log(\"表格列反查\")\r\nconst target = event.currentTarget;\r\nconst classList = target.className.split(' ');\r\nconst codeName = classList[classList.length - 1].split('--')[1];\r\nif (codeName) {\r\n    const items = data[0].details.filter(x => x.detail_index === codeName);\r\n    if (!items.length) {\r\n        // return { cancel: true }\r\n    }\r\n}",
      uiactionMode: 'FRONT',
      uiactionTag: 'check_info_vail',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'attendanceapp.attendance_record',
      name: '考勤记录反查校验',
      id: 'check_info_vail@attendance_record',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导出报表',
      codeName: 'export_report',
      frontProcessType: 'OTHER',
      fullCodeName: 'attendance_record_export_report',
      scriptCode:
        "const viewC = view\r\nconst tempPatams = {...viewC.params};\r\nif (viewC.getController(\"searchform\")) {\r\n    const searchForm = viewC.getController(\"searchform\");\r\n    Object.assign(tempPatams, {...searchForm.data});\r\n}\r\nconsole.log('导出报表参数：', tempPatams);\r\ndelete tempPatams.n_checkin_date_gtandeq;\r\ndelete tempPatams.n_checkin_date_ltandeq;\r\ndelete tempPatams.n_member_id_in;\r\nObject.keys(tempPatams).forEach(key => {\r\n    if (key.startsWith('$')) {\r\n        delete tempPatams[key];\r\n    }\r\n});\r\n\r\nconst urlParam = new URLSearchParams(tempPatams);\r\nconst exportUrl = `/attendance_records/exportdata/fetch_record/?srfexporttag=DataExport&${decodeURIComponent(urlParam)}`;\r\nconst app = ibiz.hub.getApp(context.srfappid);\r\nconst { data: file } = await app.net.request(exportUrl, {\r\n    method: 'post',\r\n    data: tempPatams,\r\n    responseType: 'blob',\r\n});\r\nif (file) {\r\n    const title = viewC.model.title;\r\n    const fileName = `${title}表.xlsx`;\r\n    const filetype = 'application/vnd.ms-excel';\r\n    const blob = new Blob([file], { type: filetype });\r\n    const href = URL.createObjectURL(blob);\r\n    const a = document.createElement('a');\r\n    a.href = href;\r\n    a.download = fileName;\r\n    document.body.appendChild(a);\r\n    a.click();\r\n    document.body.removeChild(a);\r\n    URL.revokeObjectURL(href);\r\n}",
      uiactionMode: 'FRONT',
      uiactionTag: 'export_report',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'attendanceapp.attendance_record',
      name: '导出每日统计报表',
      id: 'export_report@attendance_record',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'attendance_record',
  deapicodeName: 'attendance_record',
  deapicodeName2: 'attendance_records',
  deapitag: 'ATTENDANCE_RECORD',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_RECORD',
  },
  logicName: '考勤记录',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'ATTENDANCE_RECORD',
  id: 'attendanceapp.attendance_record',
  codeName2: 'attendance_records',
  requestPaths: [],
};
