export default {
  appDEFields: [
    {
      codeName: 'create_uid',
      logicName: '创建人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'name',
      logicName: 'WiFi名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'id',
      logicName: '主键',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'create_date',
      logicName: '创建时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'mac_address',
      logicName: 'Mac地址',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      name: 'MAC_ADDRESS',
      id: 'mac_address',
    },
    {
      codeName: 'rule_id',
      logicName: '主键',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'RULE_ID',
      id: 'rule_id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'attendance_wifi_location_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '创建时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '创建人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'create_uid',
        },
        {
          codeName: 'id',
          logicName: '主键',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'id',
        },
        {
          codeName: 'mac_address',
          logicName: 'Mac地址',
          appDEFieldId: 'mac_address',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'mac_address',
        },
        {
          codeName: 'name',
          logicName: 'WiFi名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'name',
        },
        {
          codeName: 'rule_id',
          logicName: '主键',
          appDEFieldId: 'rule_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rule_id',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'attendance_wifi_location_dto',
    },
    {
      codeName: 'attendance_wifi_location_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '主键',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: 'WiFi名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_rule_id_eq',
          logicName: '主键',
          appDEFieldId: 'rule_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rule_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'attendance_wifi_location_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CreateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        output: true,
        name: 'CreateTempInput',
        id: 'createtempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempResult',
        id: 'createtempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTemp',
      id: 'createtemp',
    },
    {
      codeName: 'CreateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        output: true,
        name: 'CreateTempMajorInput',
        id: 'createtempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempMajorResult',
        id: 'createtempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTempMajor',
      id: 'createtempmajor',
    },
    {
      codeName: 'GetDraftTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        name: 'GetDraftTempInput',
        id: 'getdrafttempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        name: 'GetDraftTempResult',
        id: 'getdrafttempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTemp',
      id: 'getdrafttemp',
    },
    {
      codeName: 'GetDraftTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        name: 'GetDraftTempMajorInput',
        id: 'getdrafttempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        name: 'GetDraftTempMajorResult',
        id: 'getdrafttempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTempMajor',
      id: 'getdrafttempmajor',
    },
    {
      codeName: 'GetTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetTempInput',
        id: 'gettempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        name: 'GetTempResult',
        id: 'gettempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTemp',
      id: 'gettemp',
    },
    {
      codeName: 'GetTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetTempMajorInput',
        id: 'gettempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        name: 'GetTempMajorResult',
        id: 'gettempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTempMajor',
      id: 'gettempmajor',
    },
    {
      codeName: 'RemoveTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveTempInput',
        id: 'removetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempResult',
        id: 'removetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTemp',
      id: 'removetemp',
    },
    {
      codeName: 'RemoveTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveTempMajorInput',
        id: 'removetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempMajorResult',
        id: 'removetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTempMajor',
      id: 'removetempmajor',
    },
    {
      codeName: 'UpdateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempInput',
        id: 'updatetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempResult',
        id: 'updatetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTemp',
      id: 'updatetemp',
    },
    {
      codeName: 'UpdateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempMajorInput',
        id: 'updatetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempMajorResult',
        id: 'updatetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTempMajor',
      id: 'updatetempmajor',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FetchTempDefault',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_wifi_location_filter_dto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_wifi_location_dto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchtempdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'attendance_wifi_location',
  deapicodeName: 'attendance_wifi_location',
  deapicodeName2: 'attendance_wifi_locations',
  deapitag: 'ATTENDANCE_WIFI_LOCATION',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  logicName: 'WiFi定位配置',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'wifi_list',
      majorAppDataEntityId: 'attendanceapp.attendance_rule',
      parentAppDEFieldId: 'rule_id',
      rsmode: 2,
      tempDataOrder: 10,
      name: '考勤规则-WIFI配置',
      id: 'wifi_list',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  enableTempData: true,
  name: 'ATTENDANCE_WIFI_LOCATION',
  id: 'attendanceapp.attendance_wifi_location',
  codeName2: 'attendance_wifi_locations',
  requestPaths: [
    'attendance_rules/${attendance_rule}/attendance_wifi_locations/${attendance_wifi_location}',
  ],
};
