export default {
  appDEFields: [
    {
      codeName: 'attendance_ratio',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.ATTENDANCE_RATIO',
      },
      logicName: '出勤比率',
      predefinedType: 'NONE',
      stdDataType: 7,
      name: 'ATTENDANCE_RATIO',
      id: 'attendance_ratio',
    },
    {
      codeName: 'working_number',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.WORKING_NUMBER',
      },
      logicName: '上下班次数',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'WORKING_NUMBER',
      id: 'working_number',
    },
    {
      codeName: 'work_load',
      computeAppDEFLogicId: 'calcworkload',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.WORK_LOAD',
      },
      logicName: '工时',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'WORK_LOAD',
      id: 'work_load',
    },
    {
      codeName: 'scopes',
      logicName: '时间范围',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'SCOPES',
      id: 'scopes',
    },
    {
      codeName: 'default_flag',
      logicName: '默认标识',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'DEFAULT_FLAG',
      id: 'default_flag',
    },
    {
      codeName: 'public_flag',
      logicName: '公共',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'PUBLIC_FLAG',
      id: 'public_flag',
    },
    {
      codeName: 'work_time',
      computeAppDEFLogicId: 'calcworktime',
      logicName: '工作时间',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'WORK_TIME',
      id: 'work_time',
    },
    {
      codeName: 'schedule_type',
      logicName: '班次类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'SCHEDULE_TYPE',
      id: 'schedule_type',
    },
    {
      codeName: 'workday_id',
      logicName: '工作日标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'WORKDAY_ID',
      id: 'workday_id',
    },
    {
      codeName: 'overtime_valid',
      logicName: '加班有效',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'OVERTIME_VALID',
      id: 'overtime_valid',
    },
    {
      codeName: 'rest_enable',
      logicName: '休息配置启用',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'REST_ENABLE',
      id: 'rest_enable',
    },
    {
      codeName: 'invalid_overtime',
      logicName: '不计入加班的分钟阈值',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'INVALID_OVERTIME',
      id: 'invalid_overtime',
    },
    {
      codeName: 'start_overtime',
      logicName: '计入加班的分钟起',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'START_OVERTIME',
      id: 'start_overtime',
    },
    {
      codeName: 'rest_start',
      logicName: '休息开始时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'HH:mm:ss',
      name: 'REST_START',
      id: 'rest_start',
    },
    {
      codeName: 'end_start',
      logicName: '休息结束时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'HH:mm:ss',
      name: 'END_START',
      id: 'end_start',
    },
    {
      codeName: 'order_value',
      logicName: '排序值',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'ORDER_VALUE',
      id: 'order_value',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.NAME',
      },
      logicName: '班次名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.ID',
      },
      logicName: '主键',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.CREATE_DATE',
      },
      logicName: '创建时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.WRITE_DATE',
      },
      logicName: '更新时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'write_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.WRITE_UID',
      },
      logicName: '更新人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'create_uid',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.CREATE_UID',
      },
      logicName: '创建人',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'rule_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.RULE_NAME',
      },
      logicName: '考勤规则名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      name: 'RULE_NAME',
      id: 'rule_name',
    },
    {
      codeName: 'rule_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.SHIFT.RULE_ID',
      },
      logicName: '考勤规则ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'RULE_ID',
      id: 'rule_id',
    },
  ],
  appDELogics: [
    {
      codeName: 'GetDefaultTemp',
      defaultParamName: 'DEFAULT',
      logicName: '获取默认班次临时数据',
      logicSubType: 'NONE',
      scriptCode:
        'console.log(\'获取默认班次临时数据:\');\r\n\r\nconst serviceUtil = ibiz.hub.getApp(context.srfappid).deService;\nconst service = await serviceUtil.getService(context, \'attendanceapp.attendance_shift\');\r\n//获取默认shift\r\nconst list = service.local.getList(context);\r\nconst defaultShift = list.find(item =>item.default_flag == 1 );\r\ncontext.shift = defaultShift.id\r\nconsole.log("计算工时" + defaultShift);\r\nvar _scopes = defaultShift.scopes || [];\r\nvar totalWorkingMinutes = 0;\r\n\r\nfunction timeToMinutes(timeStr) {\r\n  const parts = timeStr.split(\':\');\r\n  const hours = parseInt(parts[0], 10);\r\n  const minutes = parseInt(parts[1], 10);\r\n  return hours * 60 + minutes;\r\n}\r\n\r\n// 遍历现有 scope 计算总工时\r\nfor (var i = 0; i < _scopes.length; i++) {\r\n  var scope = _scopes[i];\r\n  // 转换时间为分钟数\r\n  const start = timeToMinutes(scope.start_base_time);\r\n  const end = timeToMinutes(scope.end_base_time);\r\n  \r\n  // 计算单个班次工时（分钟）\r\n  totalWorkingMinutes += (end - start);\r\n}\r\n\r\n// 转换为小时分钟格式\r\nvar hours = Math.floor(Math.abs(totalWorkingMinutes) / 60);\r\nvar minutes = totalWorkingMinutes % 60;\r\nvar workLoadText = hours + "小时" + minutes + "分钟";\r\n\r\ndefaultShift.work_load = workLoadText;\r\nreturn defaultShift;\r\n',
      customCode: true,
      enableFront: true,
      valid: true,
      name: '获取默认班次临时数据',
      id: 'getdefaulttemp',
    },
    {
      codeName: 'UpdateByType',
      defaultParamName: 'DEFAULT',
      logicName: '修改班次信息',
      logicSubType: 'NONE',
      scriptCode:
        "console.log('UpdateByType临时数据创建:');\r\n\r\nconst serviceUtil = ibiz.hub.getApp(context.srfappid).deService;\r\nconst service = await serviceUtil.getService(context, 'attendanceapp.attendance_shift');\r\nif(data.default_flag === false || data.default_flag === \"false\") {\r\n    data.default_flag = 0\r\n}\r\n\r\nif (data.default_flag === 1 && data.workday_id&& (data.schedule_type === 'fixed' || data.schedule_type === 'flexible' || data.schedule_type === 'alternate_week')) {\r\n    console.log('创建工作日班次:', data);\r\n\r\n    //获取默认shift\r\n    const list = service.local.getList(context);\r\n    const defaultShift = list.find(item =>item.default_flag == 1 );\r\n\r\n    const curScopes = data.scopes;\r\n    // 获取所有班次临时数据\r\n    const beforeScopes =defaultShift.scopes;\r\n\r\n    if (beforeScopes.length > 0 && curScopes.length > 0) {\r\n        // 与默认班次信息对比\r\n        const areScopesEqual = compareScopes(beforeScopes, curScopes);\r\n\r\n        if (!areScopesEqual) {\r\n            data.id =null;\r\n            data.default_flag = 0;\r\n            data.public_flag = 0;\r\n            curScopes.forEach(item => {\r\n                item.shift_id =null\r\n            })\r\n\r\n            //为工作日创建班次\r\n            const res = await service.exec('CreateTemp', context, data);\r\n\r\n            if (res && res.ok) {\r\n                data = res.data;\r\n                console.log('临时数据创建成功:', res);\r\n            }\r\n            const workdayService = await serviceUtil.getService(context, 'attendanceapp.attendance_workday');\r\n\r\n            const workday = await workdayService.local.get(context, data.workday_id);\r\n            console.log('workday临时数据获取成功:', workday);\r\n            workday.shift_id = data.id;\r\n            const workdayRes = await workdayService.updateTemp(context, workday)\r\n            if (workdayRes && res.workdayRes) {\r\n                console.log('workday临时数据更新成功:', workdayRes);\r\n            }\r\n        }else {\r\n            const res = await service.updateTemp(context, data)\r\n            if (res && res.ok) {\r\n                console.log('临时数据更新成功:', res);\r\n            }\r\n        }\r\n\r\n        // 班次信息对比\r\n        function compareScopes(beforeScopes, curScopes) {\r\n            if (beforeScopes.length !== curScopes.length) return false;\r\n\r\n            for (let i = 0; i < beforeScopes.length; i++ ) {\r\n                const defaultItem = beforeScopes[i];\r\n                const curItem = curScopes[i];\r\n\r\n                if (typeof defaultItem !== 'object' || typeof curItem !== 'object' ) {\r\n                    return false;\r\n                }\r\n\r\n                if (\r\n                    defaultItem.early_for_absenteeism !== curItem.early_for_absenteeism ||\r\n                    defaultItem.early_for_early !== curItem.early_for_early ||\r\n                    defaultItem.latest_checkout !== curItem.latest_checkout ||\r\n                    defaultItem.earliest_checkin !== curItem.earliest_checkin ||\r\n                    defaultItem.end_base_time !== curItem.end_base_time ||\r\n                    defaultItem.late_for_absenteeism !== curItem.late_for_absenteeism ||\r\n                    defaultItem.late_for_late !== curItem.late_for_late ||\r\n                    defaultItem.start_base_time !== curItem.start_base_time\r\n                ) {\r\n                    return false;\r\n                }\r\n            }\r\n            return true;\r\n        }\r\n    }\r\n\r\n} else {\r\n    const res = await service.exec('UpdateTemp', context, data);\r\n    if (res && res.ok) {\r\n        console.log('临时数据shift更新成功:', res);\r\n    }\r\n}",
      customCode: true,
      enableFront: true,
      valid: true,
      name: '修改班次信息',
      id: 'updatebytype',
    },
    {
      deflogicMode: 'COMPUTE',
      appDEFieldId: 'work_load',
      codeName: 'calcWorkLoad',
      defaultParamName: 'DEFAULT',
      logicName: '计算工时',
      logicSubType: 'DEFIELD',
      scriptCode:
        'var _scopes = data.scopes || [];\nvar totalWorkingMinutes = 0;\n\nfunction timeToMinutes(timeStr) {\n  const parts = timeStr.split(\':\');\n  const hours = parseInt(parts[0], 10);\n  const minutes = parseInt(parts[1], 10);\n  return hours * 60 + minutes;\n}\n\n// 遍历现有 scope 计算总工时\nfor (var i = 0; i < _scopes.length; i++) {\n  var scope = _scopes[i];\n        // 转换时间段为分钟数\n        const start = timeToMinutes(scope.start_base_time);\n        const end = timeToMinutes(scope.end_base_time);\n        // 累加工时\n        if (start >= end) {\n            totalWorkingMinutes += (24 * 60 - start + end);\n        }else {\n            totalWorkingMinutes += (end - start);\n        }\n\n}\n\n// 转换为小时分钟格式\nvar hours = Math.floor(Math.abs(totalWorkingMinutes) / 60);\nvar minutes = totalWorkingMinutes % 60;\nvar workLoadText = hours + "小时" + minutes + "分钟";\n\ndata.work_load = workLoadText;',
      customCode: true,
      enableFront: true,
      valid: true,
      name: '计算工时',
      id: 'calcworkload',
    },
    {
      deflogicMode: 'COMPUTE',
      appDEFieldId: 'work_time',
      codeName: 'calcWorkTime',
      defaultParamName: 'DEFAULT',
      logicName: '计算上下班时间',
      logicSubType: 'DEFIELD',
      scriptCode:
        'if (data != null && data.scopes != null ) {\n    function timeToMinutes(timeStr) {\n        const parts = timeStr.split(\':\');\n        const hours = parseInt(parts[0], 10);\n        const minutes = parseInt(parts[1], 10);\n        return hours * 60 + minutes;\n    }\n    \n    var scopes = data.scopes\n    var worktimeParts = [];\n    scopes.forEach(scope => {\n        var start = scope.start_base_time.substring(0, 5);\n        const startMinutes = timeToMinutes(scope.start_base_time);\n        const endMinutes = timeToMinutes(scope.end_base_time);\n        if(scope.next_tag === "1,0"||scope.next_tag === "1,1"){\n            start = "次日" + start;\n        }\n        var end = scope.end_base_time.substring(0, 5);\n        if(scope.next_tag === "0,1"||scope.next_tag === "1,1" || startMinutes >= endMinutes){\n            end = "次日" + end;\n        }\n        worktimeParts.push(start + \'-\' + end);\n    })\n    data.work_time = worktimeParts.join(\'/\');\n}',
      customCode: true,
      enableFront: true,
      valid: true,
      name: '计算上下班时间',
      id: 'calcworktime',
    },
    {
      codeName: 'nothing',
      defaultParamName: 'DEFAULT',
      logicName: 'nothing',
      logicSubType: 'NONE',
      scriptCode: 'return data;',
      customCode: true,
      enableFront: true,
      valid: true,
      id: 'nothing',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'attendance_shift_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'attendance_ratio',
          logicName: '出勤比率',
          appDEFieldId: 'attendance_ratio',
          sourceType: 'DEFIELD',
          stdDataType: 7,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'attendance_ratio',
        },
        {
          codeName: 'working_number',
          logicName: '上下班次数',
          appDEFieldId: 'working_number',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'working_number',
        },
        {
          codeName: 'scopes',
          logicName: '时间范围',
          appDEFieldId: 'scopes',
          refAppDEDataSetId: 'fetchdefault',
          refAppDEMethodDTOId: 'attendance_scope_dto',
          refAppDataEntityId: 'attendanceapp.attendance_scope',
          refPickupAppDEFieldId: 'shift_id',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'scopes',
        },
        {
          codeName: 'work_load',
          logicName: '工时',
          appDEFieldId: 'work_load',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'work_load',
        },
        {
          codeName: 'default_flag',
          logicName: '默认标识',
          appDEFieldId: 'default_flag',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'default_flag',
        },
        {
          codeName: 'public_flag',
          logicName: '公共',
          appDEFieldId: 'public_flag',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'public_flag',
        },
        {
          codeName: 'work_time',
          logicName: '工作时间',
          appDEFieldId: 'work_time',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'work_time',
        },
        {
          codeName: 'schedule_type',
          logicName: '班次类型',
          appDEFieldId: 'schedule_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'schedule_type',
        },
        {
          codeName: 'workday_id',
          logicName: '工作日标识',
          appDEFieldId: 'workday_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'workday_id',
        },
        {
          codeName: 'overtime_valid',
          logicName: '加班有效',
          appDEFieldId: 'overtime_valid',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'overtime_valid',
        },
        {
          codeName: 'rest_enable',
          logicName: '休息配置启用',
          appDEFieldId: 'rest_enable',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rest_enable',
        },
        {
          codeName: 'invalid_overtime',
          logicName: '不计入加班的分钟阈值',
          appDEFieldId: 'invalid_overtime',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'invalid_overtime',
        },
        {
          codeName: 'start_overtime',
          logicName: '计入加班的分钟起',
          appDEFieldId: 'start_overtime',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'start_overtime',
        },
        {
          codeName: 'end_start',
          jsonFormat: 'HH:mm:ss',
          logicName: '休息结束时间',
          appDEFieldId: 'end_start',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'end_start',
        },
        {
          codeName: 'rest_start',
          jsonFormat: 'HH:mm:ss',
          logicName: '休息开始时间',
          appDEFieldId: 'rest_start',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rest_start',
        },
        {
          codeName: 'order_value',
          logicName: '排序值',
          appDEFieldId: 'order_value',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'order_value',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '创建时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'create_date',
        },
        {
          codeName: 'create_uid',
          logicName: '创建人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'create_uid',
        },
        {
          codeName: 'id',
          logicName: '主键',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'id',
        },
        {
          codeName: 'name',
          logicName: '班次名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'rule_id',
          logicName: '考勤规则ID',
          appDEFieldId: 'rule_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rule_id',
        },
        {
          codeName: 'rule_name',
          logicName: '考勤规则名称',
          appDEFieldId: 'rule_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'rule_name',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'write_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'write_uid',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'attendance_shift_dto',
    },
    {
      codeName: 'attendance_shift_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_default_flag_eq',
          logicName: '默认标识',
          appDEFieldId: 'default_flag',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_default_flag_eq',
        },
        {
          codeName: 'n_id_eq',
          logicName: '主键',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '班次名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_public_flag_eq',
          logicName: '公共',
          appDEFieldId: 'public_flag',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_public_flag_eq',
        },
        {
          codeName: 'n_rule_id_eq',
          logicName: '考勤规则ID',
          appDEFieldId: 'rule_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rule_id_eq',
        },
        {
          codeName: 'n_rule_name_eq',
          logicName: '考勤规则名称',
          appDEFieldId: 'rule_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rule_name_eq',
        },
        {
          codeName: 'n_rule_name_like',
          logicName: '考勤规则名称',
          appDEFieldId: 'rule_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_rule_name_like',
        },
        {
          codeName: 'n_working_number_eq',
          logicName: '上下班次数',
          appDEFieldId: 'working_number',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_working_number_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'attendance_shift_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'CreateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        output: true,
        name: 'CreateTempInput',
        id: 'createtempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempResult',
        id: 'createtempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      afterCode:
        "// 统一处理data为对象或数组的情况\r\nconst dataList = Array.isArray(data) ? data : [data];\r\n\r\nfor (const item of dataList) {\r\n    if (item.scopes) {\r\n        let _scopes = item.scopes.map(scope => ({\r\n            ...scope,\r\n            shift_id: item.id\r\n        }));\r\n\r\n        // 创建独立上下文（避免污染全局context）\r\n        const itemContext = {\r\n            ...context,\r\n            attendance_shift: item.id  // 覆盖当前shift\r\n        };\r\n\r\n        const serviceUtil = ibiz.hub.getApp(context.srfappid).deService;\r\n        const scopeService = await serviceUtil.getService(context, 'attendanceapp.attendance_scope');\r\n        const res = await scopeService.createTemp(itemContext,_scopes)\r\n        if(res && res.ok){\r\n            _scopes = res.data;\r\n            console.log('scope临时数据创建成功:', _scopes);\r\n        }\r\n    }\r\n}",
      beforeCode:
        '\r\n// 统一处理data为对象或数组的情况\r\nconst dataList = Array.isArray(data) ? data : [data];\r\n\r\nlet counter = 0;  \r\nfor (const item of dataList) {  \r\n    if (item.id == null) {  \r\n        item.id = Date.now() + counter++;  \r\n    }  \r\n}',
      dataSetType: 'REMOTE',
      name: 'CreateTemp',
      id: 'createtemp',
    },
    {
      codeName: 'CreateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        output: true,
        name: 'CreateTempMajorInput',
        id: 'createtempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'CreateTempMajorResult',
        id: 'createtempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'CREATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'CreateTempMajor',
      id: 'createtempmajor',
    },
    {
      codeName: 'GetDefaultShift',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetDefaultShiftInput',
        id: 'getdefaultshiftinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        name: 'GetDefaultShiftResult',
        id: 'getdefaultshiftresult',
      },
      actionMode: 'READ',
      actionType: 'DELOGIC',
      appDELogicId: 'getdefaulttemp',
      dataSetType: 'REMOTE',
      name: 'GetDefaultShift',
      id: 'getdefaultshift',
    },
    {
      codeName: 'GetDraftTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        name: 'GetDraftTempInput',
        id: 'getdrafttempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        name: 'GetDraftTempResult',
        id: 'getdrafttempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      afterCode:
        'data.attendance_ratio = 1.0;\r\ndata.name = "班次";\r\nvar _workNumber = data.working_number ? data.working_number : 1;\r\nvar _scopes = [];\r\n\r\n// 根据班次数量定义时间段配置\r\nvar timeConfigs = {\r\n  1: [{ start: "08:00", end: "17:00" }],\r\n  2: [\r\n    { start: "08:00", end: "12:00" },\r\n    { start: "13:30", end: "17:30" }\r\n    ],\r\n  3: [\r\n    { start: "08:00", end: "12:00" },\r\n    { start: "13:30", end: "17:30" },\r\n    { start: "19:00", end: "23:00" }\r\n    ]\r\n};\r\n\r\n// 获取当前班次数量的时间配置\r\nvar currentConfig = timeConfigs[_workNumber] || timeConfigs[1]; \r\n\r\ncurrentConfig.forEach((timeRange, index) => {\r\n  var scope = {\r\n    early_for_absenteeism: 60,\r\n    early_for_early: 0,\r\n    latest_checkout: 480,\r\n    end_base_time: timeRange.end,\r\n    start_base_time: timeRange.start,\r\n    earliest_checkin: 60,\r\n    late_for_absenteeism: 60,\r\n    late_for_late: 0,\r\n    shift_id: data.id\r\n  };\r\n  _scopes.push(scope);\r\n});\r\n\r\ndata.scopes = _scopes;',
      dataSetType: 'REMOTE',
      name: 'GetDraftTemp',
      id: 'getdrafttemp',
    },
    {
      codeName: 'GetDraftTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        name: 'GetDraftTempMajorInput',
        id: 'getdrafttempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        name: 'GetDraftTempMajorResult',
        id: 'getdrafttempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'GETDRAFT',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetDraftTempMajor',
      id: 'getdrafttempmajor',
    },
    {
      codeName: 'GetTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetTempInput',
        id: 'gettempinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        name: 'GetTempResult',
        id: 'gettempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTemp',
      id: 'gettemp',
    },
    {
      codeName: 'GetTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        name: 'GetTempMajorInput',
        id: 'gettempmajorinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        name: 'GetTempMajorResult',
        id: 'gettempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'READ',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'GetTempMajor',
      id: 'gettempmajor',
    },
    {
      codeName: 'RemoveTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveTempInput',
        id: 'removetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempResult',
        id: 'removetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTemp',
      id: 'removetemp',
    },
    {
      codeName: 'RemoveTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        name: 'RemoveTempMajorInput',
        id: 'removetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'RemoveTempMajorResult',
        id: 'removetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'DELETE',
      actionType: 'BUILTIN',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'RemoveTempMajor',
      id: 'removetempmajor',
    },
    {
      codeName: 'UpdateByType',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateByTypeInput',
        id: 'updatebytypeinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateByTypeResult',
        id: 'updatebytyperesult',
      },
      actionMode: 'UPDATE',
      actionType: 'DELOGIC',
      appDELogicId: 'updatebytype',
      dataSetType: 'REMOTE',
      name: 'UpdateByType',
      id: 'updatebytype',
    },
    {
      codeName: 'UpdateTemp',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempInput',
        id: 'updatetempinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempResult',
        id: 'updatetempresult',
      },
      tempDataMode: 2,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      afterCode:
        "// 获取所有班次临时数据\r\nconsole.log(\"更新scope\")\r\nconst serviceUtil = ibiz.hub.getApp(context.srfappid).deService;\nconst service = await serviceUtil.getService(context, 'attendanceapp.attendance_scope');\r\nconst list = service.local.getList(context);\r\n\r\nconst beforeScopes = list.filter(item => item.shift_id === data.id);\r\nbeforeScopes.forEach(item => {\r\n    service.local.delete(context, item.id);\r\n})\r\n\r\nlet _scopes = data.scopes.map(scope => ({\r\n    ...scope,\r\n    shift_id: data.id\r\n}));\r\n\r\nconst res = await service.exec('CreateTemp', context,_scopes);\r\nif(res && res.ok){\r\n    console.log('scope临时数据创建成功:', _scopes);\r\n}\r\n\r\n\r\n\r\n",
      dataSetType: 'REMOTE',
      name: 'UpdateTemp',
      id: 'updatetemp',
    },
    {
      codeName: 'UpdateTempMajor',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        output: true,
        name: 'UpdateTempMajorInput',
        id: 'updatetempmajorinput',
      },
      appDEMethodReturn: {
        type: 'VOID',
        name: 'UpdateTempMajorResult',
        id: 'updatetempmajorresult',
      },
      tempDataMode: 1,
      builtinMethod: true,
      actionMode: 'UPDATE',
      actionType: 'BUILTIN',
      dataSetType: 'REMOTE',
      name: 'UpdateTempMajor',
      id: 'updatetempmajor',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FetchTempDefault',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_shift_filter_dto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_shift_dto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchtempdefault',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'SINGLEDATA',
      buttonStyle: 'DEFAULT',
      caption: '修改班次时间',
      codeName: 'editScope',
      frontAppViewId: 'attendanceapp.attendance_shift_default_shift_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'attendance_shift_editScope',
      navigateContexts: [
        {
          key: 'SCHEDULE_TYPE',
          value: 'schedule_type',
          name: 'SCHEDULE_TYPE',
          id: 'schedule_type',
        },
      ],
      refreshMode: 1,
      uiactionMode: 'FRONT',
      uiactionTag: 'editScope',
      uiactionType: 'DEUIACTION',
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'attendanceapp.attendance_shift',
      name: '修改班次时间',
      id: 'editscope@attendance_shift',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'attendance_shift',
  deapicodeName: 'attendance_shift',
  deapicodeName2: 'attendance_shifts',
  deapitag: 'ATTENDANCE_SHIFT',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  logicName: '班次',
  majorAppDEFieldId: 'name',
  minorAppDERSs: [
    {
      actionRSMode: 1,
      codeName: 'shifts',
      majorAppDataEntityId: 'attendanceapp.attendance_rule',
      parentAppDEFieldId: 'rule_id',
      parentTextAppDEFieldId: 'rule_name',
      rsmode: 2,
      tempDataOrder: 10,
      name: '规则-班次',
      id: 'shifts',
    },
  ],
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  enableTempData: true,
  major: true,
  name: 'ATTENDANCE_SHIFT',
  id: 'attendanceapp.attendance_shift',
  codeName2: 'attendance_shifts',
  requestPaths: [
    'attendance_rules/${attendance_rule}/attendance_shifts/${attendance_shift}',
  ],
};
