export default {
  appDEDataExports: [
    {
      codeName: 'DataExport',
      maxRowCount: 5000,
      dedataExportItems: [
        {
          caption: '姓名',
          format: '%1$s',
          appDEFieldId: 'member_name',
          id: 'member_name',
        },
        {
          caption: '工号',
          format: '%1$s',
          appDEFieldId: 'member_num',
          id: 'member_num',
        },
        {
          caption: '部门',
          format: '%1$s',
          appDEFieldId: 'dept_name',
          id: 'dept_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CHECKIN_TIME',
          },
          caption: '打卡时间',
          format: '%1$s',
          appDEFieldId: 'checkin_time',
          id: 'checkin_time',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CHECKIN_TYPE',
          },
          caption: '打卡方式',
          format: '%1$s',
          appDEFieldId: 'checkin_type',
          codeListId: 'attendanceapp.deli_checkin_type',
          id: 'checkin_type',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.DEVICE_NAME',
          },
          caption: '打卡详情',
          format: '%1$s',
          appDEFieldId: 'device_name',
          id: 'device_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CHECKIN_REMARK',
          },
          caption: '打卡备注',
          format: '%1$s',
          appDEFieldId: 'checkin_remark',
          id: 'checkin_remark',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CHECKIN_IMAGE',
          },
          caption: '打卡图片',
          format: '%1$s',
          appDEFieldId: 'checkin_image',
          id: 'checkin_image',
        },
      ],
      enableBackend: true,
      enableFront: true,
      name: '数据导出',
      id: 'dataexport',
    },
    {
      codeName: 'DataExport2',
      maxRowCount: 5000,
      dedataExportItems: [
        {
          caption: '姓名',
          format: '%1$s',
          appDEFieldId: 'member_name',
          id: 'member_name',
        },
        {
          caption: '工号',
          format: '%1$s',
          appDEFieldId: 'member_num',
          id: 'member_num',
        },
        {
          caption: '部门',
          format: '%1$s',
          appDEFieldId: 'dept_name',
          id: 'dept_name',
        },
        {
          capLanguageRes: {
            lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.ID',
          },
          caption: '模版列',
          format: '%1$s',
          appDEFieldId: 'id',
          id: 'template',
        },
      ],
      enableBackend: true,
      name: '数据导出2',
      id: 'dataexport2',
    },
  ],
  appDEFields: [
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'create_uid',
      logicName: '建立人',
      predefinedType: 'CREATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'CREATE_UID',
      id: 'create_uid',
    },
    {
      codeName: 'create_date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.CREATE_DATE',
      },
      logicName: '建立时间',
      predefinedType: 'CREATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CREATE_DATE',
      id: 'create_date',
    },
    {
      codeName: 'write_uid',
      logicName: '更新人',
      predefinedType: 'UPDATEMAN',
      stdDataType: 25,
      stringLength: 100,
      name: 'WRITE_UID',
      id: 'write_uid',
    },
    {
      codeName: 'write_date',
      logicName: '更新时间',
      predefinedType: 'UPDATEDATE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'WRITE_DATE',
      id: 'write_date',
    },
    {
      codeName: 'member_name',
      logicName: '员工名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MEMBER_NAME',
      id: 'member_name',
    },
    {
      codeName: 'dept_id',
      logicName: '部门ID',
      predefinedType: 'ORGSECTORID',
      stdDataType: 25,
      stringLength: 100,
      name: 'DEPT_ID',
      id: 'dept_id',
    },
    {
      codeName: 'dept_name',
      logicName: '部门名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'DEPT_NAME',
      id: 'dept_name',
    },
    {
      codeName: 'member_num',
      logicName: '工号',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MEMBER_NUM',
      id: 'member_num',
    },
    {
      codeName: 'date',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.DATE',
      },
      logicName: '考勤日期',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD',
      name: 'DATE',
      id: 'date',
    },
    {
      codeName: 'clock_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CLOCK_TYPE',
      },
      logicName: '打卡类型',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CLOCK_TYPE',
      id: 'clock_type',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.ID',
      },
      logicName: '记录ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'member_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.MEMBER_ID',
      },
      logicName: '员工ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'MEMBER_ID',
      id: 'member_id',
    },
    {
      codeName: 'cmd',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CMD',
      },
      logicName: '操作指令',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 50,
      name: 'CMD',
      id: 'cmd',
    },
    {
      codeName: 'source',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.SOURCE',
      },
      logicName: '数据来源',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 20,
      name: 'SOURCE',
      id: 'source',
    },
    {
      codeName: 'checkin_type',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CHECKIN_TYPE',
      },
      logicName: '打卡方式',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CHECKIN_TYPE',
      id: 'checkin_type',
    },
    {
      codeName: 'duration_hours',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.DURATION_HOURS',
      },
      logicName: '上班时长',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'DURATION_HOURS',
      id: 'duration_hours',
    },
    {
      codeName: 'should_checkin_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.SHOULD_CHECKIN_TIME',
      },
      logicName: '应打卡时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'SHOULD_CHECKIN_TIME',
      id: 'should_checkin_time',
    },
    {
      codeName: 'checkin_result',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CHECKIN_RESULT',
      },
      logicName: '打卡结果',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'CHECKIN_RESULT',
      id: 'checkin_result',
    },
    {
      codeName: 'checkin_image',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CHECKIN_IMAGE',
      },
      logicName: '打卡图片',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 500,
      name: 'CHECKIN_IMAGE',
      id: 'checkin_image',
    },
    {
      codeName: 'checkin_time',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CHECKIN_TIME',
      },
      logicName: '打卡时间',
      predefinedType: 'NONE',
      stdDataType: 5,
      valueFormat: 'YYYY-MM-DD HH:mm:ss',
      name: 'CHECKIN_TIME',
      id: 'checkin_time',
    },
    {
      codeName: 'checkin_remark',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.CHECKIN_REMARK',
      },
      logicName: '打卡备注',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      name: 'CHECKIN_REMARK',
      id: 'checkin_remark',
    },
    {
      codeName: 'device_name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.DEVICE_NAME',
      },
      logicName: '设备名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 255,
      name: 'DEVICE_NAME',
      id: 'device_name',
    },
    {
      codeName: 'terminal_id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.ATTENDANCE_CLOCK_IN_RECORD.TERMINAL_ID',
      },
      logicName: '终端设备ID',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 60,
      name: 'TERMINAL_ID',
      id: 'terminal_id',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'attendance_clock_in_record_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
        {
          codeName: 'create_uid',
          logicName: '建立人',
          appDEFieldId: 'create_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'create_uid',
        },
        {
          codeName: 'create_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '建立时间',
          appDEFieldId: 'create_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'create_date',
        },
        {
          codeName: 'write_uid',
          logicName: '更新人',
          appDEFieldId: 'write_uid',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'write_uid',
        },
        {
          codeName: 'write_date',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '更新时间',
          appDEFieldId: 'write_date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          id: 'write_date',
        },
        {
          codeName: 'member_name',
          logicName: '员工名称',
          appDEFieldId: 'member_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'member_name',
        },
        {
          codeName: 'dept_id',
          logicName: '部门ID',
          appDEFieldId: 'dept_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'dept_id',
        },
        {
          codeName: 'dept_name',
          logicName: '部门名称',
          appDEFieldId: 'dept_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'dept_name',
        },
        {
          codeName: 'member_num',
          logicName: '工号',
          appDEFieldId: 'member_num',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'member_num',
        },
        {
          codeName: 'checkin_image',
          logicName: '打卡图片',
          appDEFieldId: 'checkin_image',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'checkin_image',
        },
        {
          codeName: 'checkin_remark',
          logicName: '打卡备注',
          appDEFieldId: 'checkin_remark',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'checkin_remark',
        },
        {
          codeName: 'checkin_result',
          logicName: '打卡结果',
          appDEFieldId: 'checkin_result',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'checkin_result',
        },
        {
          codeName: 'checkin_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '打卡时间',
          appDEFieldId: 'checkin_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'checkin_time',
        },
        {
          codeName: 'checkin_type',
          logicName: '打卡方式',
          appDEFieldId: 'checkin_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'checkin_type',
        },
        {
          codeName: 'clock_type',
          logicName: '打卡类型',
          appDEFieldId: 'clock_type',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'clock_type',
        },
        {
          codeName: 'cmd',
          logicName: '操作指令',
          appDEFieldId: 'cmd',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'cmd',
        },
        {
          codeName: 'date',
          jsonFormat: 'yyyy-MM-dd',
          logicName: '考勤日期',
          appDEFieldId: 'date',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'date',
        },
        {
          codeName: 'device_name',
          logicName: '设备名称',
          appDEFieldId: 'device_name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'device_name',
        },
        {
          codeName: 'duration_hours',
          logicName: '上班时长',
          appDEFieldId: 'duration_hours',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'duration_hours',
        },
        {
          codeName: 'id',
          logicName: '记录ID',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'id',
        },
        {
          codeName: 'member_id',
          logicName: '员工ID',
          appDEFieldId: 'member_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'member_id',
        },
        {
          codeName: 'should_checkin_time',
          jsonFormat: 'yyyy-MM-dd HH:mm:ss',
          logicName: '应打卡时间',
          appDEFieldId: 'should_checkin_time',
          sourceType: 'DEFIELD',
          stdDataType: 5,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'should_checkin_time',
        },
        {
          codeName: 'source',
          logicName: '数据来源',
          appDEFieldId: 'source',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'source',
        },
        {
          codeName: 'terminal_id',
          logicName: '终端设备ID',
          appDEFieldId: 'terminal_id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'terminal_id',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'attendance_clock_in_record_dto',
    },
    {
      codeName: 'attendance_clock_in_record_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_checkin_result_eq',
          logicName: '打卡结果',
          appDEFieldId: 'checkin_result',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_checkin_result_eq',
        },
        {
          codeName: 'n_checkin_type_eq',
          logicName: '打卡方式',
          appDEFieldId: 'checkin_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_checkin_type_eq',
        },
        {
          codeName: 'n_clock_type_eq',
          logicName: '打卡类型',
          appDEFieldId: 'clock_type',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_clock_type_eq',
        },
        {
          codeName: 'n_device_name_eq',
          logicName: '设备名称',
          appDEFieldId: 'device_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_device_name_eq',
        },
        {
          codeName: 'n_device_name_like',
          logicName: '设备名称',
          appDEFieldId: 'device_name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_device_name_like',
        },
        {
          codeName: 'n_id_eq',
          logicName: '记录ID',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_member_id_eq',
          logicName: '员工ID',
          appDEFieldId: 'member_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_member_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
        {
          codeName: 'n_terminal_id_eq',
          logicName: '终端设备ID',
          appDEFieldId: 'terminal_id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_terminal_id_eq',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'attendance_clock_in_record_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'attendance_calculate',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/attendance_calculate',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'attendance_calculate',
    },
    {
      codeName: 'batch_reissue',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/batch_reissue',
      actionMode: 'CUSTOM',
      actionTag: 'batchReissue',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'batchReissue',
      id: 'batch_reissue',
    },
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'nothing',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/nothing',
      actionMode: 'GETDRAFT',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'nothing',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'fetch_my_clock_in_record',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_my_clock_in_record',
      actionType: 'REMOTE',
      dataSetName: 'MYCLOCKINRECORD',
      dataSetTag: 'MyClockInRecord',
      dataSetType: 'REMOTE',
      id: 'fetch_my_clock_in_record',
    },
    {
      codeName: 'fetch_record',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_record',
      actionType: 'REMOTE',
      dataSetName: 'record',
      dataSetTag: 'record',
      dataSetType: 'REMOTE',
      id: 'fetch_record',
    },
    {
      codeName: 'fetch_record_list',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_record_list',
      actionType: 'REMOTE',
      dataSetName: 'record_list',
      dataSetTag: 'record_list',
      dataSetType: 'REMOTE',
      id: 'fetch_record_list',
    },
    {
      codeName: 'FetchTempDefault',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_filter_dto',
        type: 'DTO',
        name: 'DefaultInput',
        id: 'defaultinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'PAGE',
        name: 'DefaultResult',
        id: 'defaultresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'Default',
      dataSetType: 'DATAQUERY',
      name: 'DEFAULT',
      id: 'fetchtempdefault',
    },
    {
      codeName: 'FetchTempMyClockInRecord',
      methodType: 'FETCHTEMP',
      appDEMethodInput: {
        appDEMethodDTOId: 'attendance_clock_in_record_filter_dto',
        type: 'DTO',
        name: 'MyClockInRecordInput',
        id: 'myclockinrecordinput',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'attendance_clock_in_record_dto',
        type: 'PAGE',
        name: 'MyClockInRecordResult',
        id: 'myclockinrecordresult',
      },
      tempDataMode: 2,
      actionType: 'REMOTE',
      dataSetTag: 'MyClockInRecord',
      dataSetType: 'DATAQUERY',
      dedqgroupConditions: [
        {
          condOp: 'AND',
          dedqconditions: [
            {
              condOp: 'EQ',
              condValue: 'srfpersonid',
              fieldName: 'MEMBER_ID',
              vartypeId: 'SESSIONCONTEXT',
              condType: 'SINGLE',
              name: '(MEMBER_ID) 等于(=) 用户上下文 srfpersonid',
              id: '(member_id) 等于(=) 用户上下文 srfpersonid',
            },
          ],
          condType: 'GROUP',
          id: '连接条件',
        },
      ],
      name: 'MYCLOCKINRECORD',
      id: 'fetchtempmyclockinrecord',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  appDEUIActions: [
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '批量补卡',
      codeName: 'batchReissue',
      frontAppViewId:
        'attendanceapp.attendance_clock_in_record_reissue_option_view',
      frontProcessType: 'WIZARD',
      fullCodeName: 'attendance_clock_in_record_batchReissue',
      appDEMethodId: 'batch_reissue',
      uiactionMode: 'FRONT',
      uiactionTag: 'batchReissue',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'attendanceapp.attendance_clock_in_record',
      name: '批量补卡',
      id: 'batchreissue@attendance_clock_in_record',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      caption: '删除',
      codeName: 'delete',
      confirmMsg: '确认执行删除操作？',
      dataAccessAction: 'SRFUR__DELETE',
      frontProcessType: 'OTHER',
      fullCodeName: 'attendance_clock_in_record_delete',
      appDEMethodId: 'remove',
      deopprivId: 'srfur__delete',
      refreshMode: 1,
      successMsg: '删除成功',
      timeout: 60000,
      uiactionMode: 'BACKEND',
      uiactionTag: 'delete',
      uiactionType: 'DEUIACTION',
      enableConfirm: true,
      reloadData: true,
      showBusyIndicator: true,
      noPrivDisplayMode: 1,
      appDataEntityId: 'attendanceapp.attendance_clock_in_record',
      name: '删除',
      id: 'delete@attendance_clock_in_record',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导出报表',
      codeName: 'export_report',
      frontProcessType: 'OTHER',
      fullCodeName: 'attendance_clock_in_record_export_report',
      scriptCode:
        "const viewC = view\r\nconst tempPatams = {...viewC.params};\r\nif (viewC.getController(\"searchform\")) {\r\n    const searchForm = viewC.getController(\"searchform\");\r\n    Object.assign(tempPatams, {...searchForm.data});\r\n}\r\nconsole.log('导出报表参数：', tempPatams);\r\ndelete tempPatams.n_checkin_date_gtandeq;\r\ndelete tempPatams.n_checkin_date_ltandeq;\r\ndelete tempPatams.n_member_id_in;\r\nconst urlParam = new URLSearchParams(tempPatams);\r\nconst exportUrl = `/attendance_clock_in_records/exportdata/fetch_record/?srfexporttag=DataExport2&${decodeURIComponent(urlParam)}`;\r\nconst app = ibiz.hub.getApp(context.srfappid);\r\nconst { data: file } = await app.net.request(exportUrl, {\r\n    method: 'post',\r\n    data: tempPatams,\r\n    responseType: 'blob',\r\n});\r\nif (file) {\r\n    const title = viewC.model.title;\r\n    const fileName = `${title}表.xlsx`;\r\n    const filetype = 'application/vnd.ms-excel';\r\n    const blob = new Blob([file], { type: filetype });\r\n    const href = URL.createObjectURL(blob);\r\n    const a = document.createElement('a');\r\n    a.href = href;\r\n    a.download = fileName;\r\n    document.body.appendChild(a);\r\n    a.click();\r\n    document.body.removeChild(a);\r\n    URL.revokeObjectURL(href);\r\n}",
      uiactionMode: 'FRONT',
      uiactionTag: 'export_report',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'attendanceapp.attendance_clock_in_record',
      name: '导出打卡记录',
      id: 'export_report@attendance_clock_in_record',
    },
    {
      actionLevel: 100,
      actionTarget: 'NONE',
      buttonStyle: 'DEFAULT',
      caption: '导出报表',
      codeName: 'export_report_list',
      frontProcessType: 'OTHER',
      fullCodeName: 'attendance_clock_in_record_export_report_list',
      scriptCode:
        "const viewC = view\nconst tempPatams = {...viewC.params};\nif (viewC.getController(\"searchform\")) {\n    const searchForm = viewC.getController(\"searchform\");\n    Object.assign(tempPatams, {...searchForm.data});\n}\nconsole.log('导出报表参数：', tempPatams);\ndelete tempPatams.n_checkin_date_gtandeq;\ndelete tempPatams.n_checkin_date_ltandeq;\ndelete tempPatams.n_member_id_in;\nconst urlParam = new URLSearchParams(tempPatams);\nconst exportUrl = `/attendance_clock_in_records/exportdata/fetch_record_list/?srfexporttag=DataExport&${decodeURIComponent(urlParam)}`;\nconst app = ibiz.hub.getApp(context.srfappid);\nconst { data: file } = await app.net.request(exportUrl, {\n    method: 'post',\n    data: tempPatams,\n    responseType: 'blob',\n});\nif (file) {\n    const title = viewC.model.title;\n    const fileName = `${title}表.xlsx`;\n    const filetype = 'application/vnd.ms-excel';\n    const blob = new Blob([file], { type: filetype });\n    const href = URL.createObjectURL(blob);\n    const a = document.createElement('a');\n    a.href = href;\n    a.download = fileName;\n    document.body.appendChild(a);\n    a.click();\n    document.body.removeChild(a);\n    URL.revokeObjectURL(href);\n}",
      uiactionMode: 'FRONT',
      uiactionTag: 'export_report_list',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      appDataEntityId: 'attendanceapp.attendance_clock_in_record',
      name: '导出列表视图打卡记录',
      id: 'export_report_list@attendance_clock_in_record',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'attendance_clock_in_record',
  deapicodeName: 'attendance_clock_in_record',
  deapicodeName2: 'attendance_clock_in_records',
  deapitag: 'ATTENDANCE_CLOCK_IN_RECORD',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.ATTENDANCE_CLOCK_IN_RECORD',
  },
  logicName: '打卡记录',
  majorAppDEFieldId: 'name',
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  enableTempData: true,
  major: true,
  name: 'ATTENDANCE_CLOCK_IN_RECORD',
  id: 'attendanceapp.attendance_clock_in_record',
  codeName2: 'attendance_clock_in_records',
  requestPaths: [],
};
