export default {
  appDEFields: [
    {
      codeName: 'followers',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.FOLLOWERS',
      },
      logicName: '关注者',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'FOLLOWERS',
      id: 'followers',
    },
    {
      codeName: 'attachments',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.ATTACHMENTS',
      },
      logicName: '附件集合',
      predefinedType: 'NONE',
      stdDataType: 21,
      stringLength: 1048576,
      name: 'ATTACHMENTS',
      id: 'attachments',
    },
    {
      codeName: 'message_needaction',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.MESSAGE_NEEDACTION',
      },
      logicName: '待处理',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_NEEDACTION',
      id: 'message_needaction',
    },
    {
      codeName: 'message_attachment_count',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.MESSAGE_ATTACHMENT_COUNT',
      },
      logicName: '附件数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_ATTACHMENT_COUNT',
      id: 'message_attachment_count',
    },
    {
      codeName: 'message_has_sms_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.MESSAGE_HAS_SMS_ERROR',
      },
      logicName: '短信发送错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_SMS_ERROR',
      id: 'message_has_sms_error',
    },
    {
      codeName: 'message_has_error',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.MESSAGE_HAS_ERROR',
      },
      logicName: '消息发送错误',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_ERROR',
      id: 'message_has_error',
    },
    {
      codeName: 'message_needaction_counter',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.MESSAGE_NEEDACTION_COUNTER',
      },
      logicName: '操作数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_NEEDACTION_COUNTER',
      id: 'message_needaction_counter',
    },
    {
      codeName: 'has_message',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.HAS_MESSAGE',
      },
      logicName: '有消息',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'HAS_MESSAGE',
      id: 'has_message',
    },
    {
      codeName: 'message_has_error_counter',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.MESSAGE_HAS_ERROR_COUNTER',
      },
      logicName: '错误数量',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_HAS_ERROR_COUNTER',
      id: 'message_has_error_counter',
    },
    {
      codeName: 'id',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.ID',
      },
      logicName: '标识',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 100,
      name: 'ID',
      id: 'id',
    },
    {
      codeName: 'name',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.NAME',
      },
      logicName: '名称',
      predefinedType: 'NONE',
      stdDataType: 25,
      stringLength: 200,
      enableQuickSearch: true,
      name: 'NAME',
      id: 'name',
    },
    {
      codeName: 'message_is_follower',
      lnlanguageRes: {
        lanResTag: 'DEF.LNAME.MAIL_THREAD.MESSAGE_IS_FOLLOWER',
      },
      logicName: '是关注者',
      predefinedType: 'NONE',
      stdDataType: 9,
      name: 'MESSAGE_IS_FOLLOWER',
      id: 'message_is_follower',
    },
  ],
  appDEMethodDTOs: [
    {
      codeName: 'mail_thread_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'followers',
          logicName: '关注者',
          appDEFieldId: 'followers',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'followers',
        },
        {
          codeName: 'attachments',
          logicName: '附件集合',
          appDEFieldId: 'attachments',
          sourceType: 'DEFIELD',
          type: 'DTOS',
          allowEmpty: true,
          id: 'attachments',
        },
        {
          codeName: 'has_message',
          logicName: '有消息',
          appDEFieldId: 'has_message',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'has_message',
        },
        {
          codeName: 'id',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          id: 'id',
        },
        {
          codeName: 'message_attachment_count',
          logicName: '附件数量',
          appDEFieldId: 'message_attachment_count',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_attachment_count',
        },
        {
          codeName: 'message_has_error',
          logicName: '消息发送错误',
          appDEFieldId: 'message_has_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_error',
        },
        {
          codeName: 'message_has_error_counter',
          logicName: '错误数量',
          appDEFieldId: 'message_has_error_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_error_counter',
        },
        {
          codeName: 'message_has_sms_error',
          logicName: '短信发送错误',
          appDEFieldId: 'message_has_sms_error',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_has_sms_error',
        },
        {
          codeName: 'message_is_follower',
          logicName: '是关注者',
          appDEFieldId: 'message_is_follower',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_is_follower',
        },
        {
          codeName: 'message_needaction',
          logicName: '待处理',
          appDEFieldId: 'message_needaction',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_needaction',
        },
        {
          codeName: 'message_needaction_counter',
          logicName: '操作数量',
          appDEFieldId: 'message_needaction_counter',
          sourceType: 'DEFIELD',
          stdDataType: 9,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'message_needaction_counter',
        },
        {
          codeName: 'name',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFIELD',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'name',
        },
      ],
      sourceType: 'DE',
      type: 'DEFAULT',
      id: 'mail_thread_dto',
    },
    {
      codeName: 'mail_thread_filter_dto',
      appDEMethodDTOFields: [
        {
          codeName: 'n_id_eq',
          logicName: '标识',
          appDEFieldId: 'id',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_id_eq',
        },
        {
          codeName: 'n_name_like',
          logicName: '名称',
          appDEFieldId: 'name',
          sourceType: 'DEFSEARCHMODE',
          stdDataType: 25,
          type: 'SIMPLE',
          allowEmpty: true,
          id: 'n_name_like',
        },
      ],
      sourceType: 'DE',
      type: 'DEFILTER',
      id: 'mail_thread_filter_dto',
    },
  ],
  appDEMethods: [
    {
      codeName: 'check_key',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        stdDataType: 9,
        type: 'SIMPLE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/check_key',
      actionMode: 'CHECKKEY',
      actionTag: 'CheckKey',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'CheckKey',
      id: 'check_key',
    },
    {
      codeName: 'create',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      noServiceCodeName: true,
      actionMode: 'CREATE',
      actionTag: 'Create',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Create',
      id: 'create',
    },
    {
      codeName: 'get',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELD',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'GET',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'READ',
      actionTag: 'Get',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Get',
      id: 'get',
    },
    {
      codeName: 'get_draft',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'GET',
      requestParamType: 'NONE',
      requestPath: '/get_draft',
      actionMode: 'GETDRAFT',
      actionTag: 'GetDraft',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'GetDraft',
      id: 'get_draft',
    },
    {
      codeName: 'mail_message_post',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/mail_message_post',
      actionMode: 'CREATE',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'mail_message_post',
    },
    {
      codeName: 'mail_track',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/mail_track',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'mail_track',
    },
    {
      codeName: 'message_notify',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/message_notify',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'message_notify',
    },
    {
      codeName: 'message_track',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/message_track',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'message_track',
    },
    {
      codeName: 'process_attachments_for_post',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/process_attachments_for_post',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'process_attachments_for_post',
    },
    {
      codeName: 'remove',
      methodType: 'DEACTION',
      appDEMethodInput: {
        keyAppDEFieldId: 'id',
        type: 'KEYFIELDS',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestField: 'ID',
      requestMethod: 'DELETE',
      requestParamType: 'FIELD',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'DELETE',
      actionTag: 'Remove',
      actionType: 'REMOTE',
      batchActionMode: 1,
      enableBatchAction: true,
      dataSetType: 'REMOTE',
      name: 'Remove',
      id: 'remove',
    },
    {
      codeName: 'save',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/save',
      actionMode: 'SAVE',
      actionTag: 'Save',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Save',
      id: 'save',
    },
    {
      codeName: 'track_discard',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/track_discard',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'track_discard',
    },
    {
      codeName: 'track_finalize',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/track_finalize',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'track_finalize',
    },
    {
      codeName: 'track_prepare',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        type: 'VOID',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/track_prepare',
      needResourceKey: true,
      actionMode: 'CUSTOM',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      id: 'track_prepare',
    },
    {
      codeName: 'update',
      methodType: 'DEACTION',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        output: true,
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'DTO',
        id: '返回对象',
      },
      requestMethod: 'PUT',
      requestParamType: 'ENTITY',
      needResourceKey: true,
      noServiceCodeName: true,
      actionMode: 'UPDATE',
      actionTag: 'Update',
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'Update',
      id: 'update',
    },
    {
      codeName: 'fetch_default',
      methodType: 'FETCH',
      appDEMethodInput: {
        appDEMethodDTOId: 'mail_thread_filter_dto',
        type: 'DTO',
        id: '输入对象',
      },
      appDEMethodReturn: {
        appDEMethodDTOId: 'mail_thread_dto',
        type: 'PAGE',
        id: '返回对象',
      },
      requestMethod: 'POST',
      requestParamType: 'ENTITY',
      requestPath: '/fetch_default',
      actionType: 'REMOTE',
      dataSetName: 'DEFAULT',
      dataSetTag: 'Default',
      dataSetType: 'REMOTE',
      id: 'fetch_default',
    },
    {
      codeName: 'FilterCreate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERCREATE',
      id: 'filtercreate',
    },
    {
      codeName: 'FilterFetch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERFETCH',
      id: 'filterfetch',
    },
    {
      codeName: 'FilterGet',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGET',
      id: 'filterget',
    },
    {
      codeName: 'FilterGetDraft',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERGETDRAFT',
      id: 'filtergetdraft',
    },
    {
      codeName: 'FilterRemove',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERREMOVE',
      id: 'filterremove',
    },
    {
      codeName: 'FilterSearch',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERSEARCH',
      id: 'filtersearch',
    },
    {
      codeName: 'FilterUpdate',
      methodType: 'FILTERACTION',
      builtinMethod: true,
      actionType: 'REMOTE',
      dataSetType: 'REMOTE',
      name: 'FILTERUPDATE',
      id: 'filterupdate',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
  ],
  codeName: 'mail_thread',
  deapicodeName: 'mail_thread',
  deapicodeName2: 'mail_threads',
  deapitag: 'MAIL_THREAD',
  dataAccCtrlArch: 1,
  dataAccCtrlMode: 1,
  enableUIActions: 15,
  keyAppDEFieldId: 'id',
  lnlanguageRes: {
    lanResTag: 'DE.LNAME.MAIL_THREAD',
  },
  logicName: '邮件会话',
  majorAppDEFieldId: 'name',
  quickSearchAppDEFieldIds: ['name'],
  sysAPITag: 'ServiceAPI',
  defaultMode: true,
  enableFilterActions: true,
  major: true,
  name: 'MAIL_THREAD',
  id: 'attendanceapp.mail_thread',
  codeName2: 'mail_threads',
  requestPaths: [],
};
