package cn.ibizlab.resource.logic.resource_calendarlogic.fill_data;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.resource.domain.resource_calendar resource_calendarfill_datadefault;
        global cn.ibizlab.core.resource.service.Iresource_calendarService iBzSysResource_calendarDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "resource_calendarfill_databegin"
            when
            then
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "resource_calendarfill_datarawsfcode_01"
            when
            then
                        update(resource_calendarfill_datadefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "resource_calendarfill_dataend_01"
            when
            then
                        update(resource_calendarfill_datadefault);//更新fact中变量值
            end