package cn.ibizlab.mail.logic.mail_templatelogic.refresh_cache;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.mail.domain.mail_template mail_templaterefresh_cachedefault;
        global cn.ibizlab.core.mail.service.Imail_templateService iBzSysMail_templateDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "mail_templaterefresh_cachebegin"
            when
            then
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "mail_templaterefresh_cacherawsfcode_01"
            when
            then
                        update(mail_templaterefresh_cachedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "mail_templaterefresh_cacheend_01"
            when
            then
                        update(mail_templaterefresh_cachedefault);//更新fact中变量值
            end