package cn.ibizlab.hr.logic.hr_departmentlogic.department_counter;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_department hr_departmentdepartment_counterdefault;
                global cn.ibizlab.core.hr.domain.hr_employee hr_departmentdepartment_counteremps;
                global cn.ibizlab.core.mail.domain.mail_activity_plan hr_departmentdepartment_counterplans;
                    global cn.ibizlab.core.hr.service.Ihr_departmentService hr_departmentservice;
        global cn.ibizlab.core.hr.service.Ihr_departmentService iBzSysHr_departmentDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_departmentdepartment_counterbegin"
            when
            then
            end

            //逻辑处理节点[获取部门信息]
            rule "deaction_01"
            ruleflow-group "hr_departmentdepartment_counterdeaction_01"
            when
            then
                            cn.ibizlab.util.helper.CachedBeanCopier.copy(hr_departmentservice.get(hr_departmentdepartment_counterdefault.getId()),hr_departmentdepartment_counterdefault);
                        update(hr_departmentdepartment_counterdefault);//更新fact中变量值
                        update(hr_departmentdepartment_counteremps);//更新fact中变量值
                        update(hr_departmentdepartment_counterplans);//更新fact中变量值
            end

            //逻辑处理节点[初始化数量]
            rule "prepareparam_02"
            ruleflow-group "hr_departmentdepartment_counterprepareparam_02"
            when
            then
                            hr_departmentdepartment_counterdefault.set("totalemployee","0");
                            hr_departmentdepartment_counterdefault.set("planscount","0");
                        update(hr_departmentdepartment_counterdefault);//更新fact中变量值
                        update(hr_departmentdepartment_counteremps);//更新fact中变量值
                        update(hr_departmentdepartment_counterplans);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "hr_departmentdepartment_counterend_01"
            when
            then
                        update(hr_departmentdepartment_counterdefault);//更新fact中变量值
                        update(hr_departmentdepartment_counteremps);//更新fact中变量值
                        update(hr_departmentdepartment_counterplans);//更新fact中变量值
            end