package cn.ibizlab.attendance.logic.attendance_recordlogic.check;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_record attendance_recordcheckdefault;
        global cn.ibizlab.core.attendance.service.Iattendance_recordService iBzSysAttendance_recordDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_recordcheckbegin"
            when
            then
            end