package cn.ibizlab.attendance.logic.attendance_recordlogic.myattendancesummary;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_record attendance_recordmyattendancesummarydefault;
                global java.util.Map attendance_recordmyattendancesummaryresult;
        global cn.ibizlab.core.attendance.service.Iattendance_recordService iBzSysAttendance_recordDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_recordmyattendancesummarybegin"
            when
            then
            end

            //逻辑处理节点[初始化]
            rule "prepareparam_01"
            ruleflow-group "attendance_recordmyattendancesummaryprepareparam_01"
            when
            then
                            attendance_recordmyattendancesummaryresult.set("should_attendance_days","0");
                            attendance_recordmyattendancesummaryresult.set("actual_attendance_days","0");
                            attendance_recordmyattendancesummaryresult.set("should_working_hours","0");
                            attendance_recordmyattendancesummaryresult.set("working_hours","0");
                            attendance_recordmyattendancesummaryresult.set("billable_hours","0");
                            attendance_recordmyattendancesummaryresult.set("pay_overtime_time","0");
                            attendance_recordmyattendancesummaryresult.set("rest_overtime_time","0");
                            attendance_recordmyattendancesummaryresult.set("late_times","0");
                            attendance_recordmyattendancesummaryresult.set("late_hours","0");
                            attendance_recordmyattendancesummaryresult.set("leave_early_times","0");
                            attendance_recordmyattendancesummaryresult.set("leave_early_hours","0");
                            attendance_recordmyattendancesummaryresult.set("in_missings","0");
                            attendance_recordmyattendancesummaryresult.set("out_missings","0");
                            attendance_recordmyattendancesummaryresult.set("absents_days","0");
                            attendance_recordmyattendancesummaryresult.set("business_trips","0");
                            attendance_recordmyattendancesummaryresult.set("outs","0");
                            attendance_recordmyattendancesummaryresult.set("make_card_times","0");
                            attendance_recordmyattendancesummaryresult.set("out_work_times","0");
                            attendance_recordmyattendancesummaryresult.set("leaves","0");
                            attendance_recordmyattendancesummaryresult.set("annual_leaves","0");
                            attendance_recordmyattendancesummaryresult.set("compassionate_leaves","0");
                            attendance_recordmyattendancesummaryresult.set("funeral_leaves","0");
                            attendance_recordmyattendancesummaryresult.set("marriage_holidays","0");
                            attendance_recordmyattendancesummaryresult.set("maternity_leaves","0");
                            attendance_recordmyattendancesummaryresult.set("parental_leaves","0");
                            attendance_recordmyattendancesummaryresult.set("paternity_leaves","0");
                            attendance_recordmyattendancesummaryresult.set("sick_leaves","0");
                            attendance_recordmyattendancesummaryresult.set("vacation_leaves","0");
                        update(attendance_recordmyattendancesummarydefault);//更新fact中变量值
                        update(attendance_recordmyattendancesummaryresult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "attendance_recordmyattendancesummaryend_01"
            when
            then
                        update(attendance_recordmyattendancesummarydefault);//更新fact中变量值
                        update(attendance_recordmyattendancesummaryresult);//更新fact中变量值
            end

            //逻辑处理节点[出勤统计]
            rule "rawsqlcall_01"
            ruleflow-group "attendance_recordmyattendancesummaryrawsqlcall_01"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfpersonid"));
    String strSql="SELECT   0 AS should_attendance_days,   COALESCE(sum((select count(1) from attendance_record tt where tt.CHECKIN_RESULT ='NORMAL'  and t.id=tt.id )),0) AS actual_attendance_days,    0 AS should_working_hours,   COALESCE(SUM(t.WORKING_HOURS), 0) AS working_hours,   COALESCE(SUM(t.BILLABLE_HOURS), 0) AS billable_hours,   0 AS pay_overtime_time,   0 AS rest_overtime_time  FROM   attendance_record t  WHERE   CHECKIN_DATE >= DATE_FORMAT(CURRENT_DATE(), '%Y-%m-01')    AND CHECKIN_DATE <= LAST_DAY(CURRENT_DATE())    AND t.MEMBER_ID = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysAttendance_recordDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                attendance_recordmyattendancesummaryresult.putAll(entity);
                            }
                        update(attendance_recordmyattendancesummarydefault);//更新fact中变量值
                        update(attendance_recordmyattendancesummaryresult);//更新fact中变量值
            end