package cn.ibizlab.attendance.logic.attendance_recordlogic.record;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_record attendance_recordrecorddefault;
                global cn.ibizlab.core.attendance.domain.attendance_record attendance_recordrecordpage;
                    global cn.ibizlab.core.attendance.service.Iattendance_recordService attendance_recordservice;
        global cn.ibizlab.core.attendance.service.Iattendance_recordService iBzSysAttendance_recordDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_recordrecordbegin"
            when
            then
            end

            //逻辑处理节点[解析搜索条件]
            rule "rawsfcode1"
            ruleflow-group "attendance_recordrecordrawsfcode1"
            when
            then
                        update(attendance_recordrecorddefault);//更新fact中变量值
                        update(attendance_recordrecordpage);//更新fact中变量值
            end

            //逻辑处理节点[获取考勤记录数据]
            rule "dedataset1"
            ruleflow-group "attendance_recordrecorddedataset1"
            when
            then
                        update(attendance_recordrecorddefault);//更新fact中变量值
                        update(attendance_recordrecordpage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "attendance_recordrecordend1"
            when
            then
                        update(attendance_recordrecorddefault);//更新fact中变量值
                        update(attendance_recordrecordpage);//更新fact中变量值
            end