package cn.ibizlab.discuss.logic.discuss_channellogic.fill_default_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.discuss.domain.discuss_channel discuss_channelfill_default_memberdefault;
                global cn.ibizlab.core.discuss.domain.discuss_channel_member discuss_channelfill_default_membermember;
                    global cn.ibizlab.core.discuss.service.Idiscuss_channel_memberService discuss_channel_memberservice;
        global cn.ibizlab.core.discuss.service.Idiscuss_channelService iBzSysDiscuss_channelDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "discuss_channelfill_default_memberbegin"
            when
            then
            end

            //逻辑处理节点[准备默认用户]
            rule "prepareparam_01"
            ruleflow-group "discuss_channelfill_default_memberprepareparam_01"
            when
            then
                            discuss_channelfill_default_membermember.set("channelid",discuss_channelfill_default_memberdefault.get("id"));
                                discuss_channelfill_default_membermember.set("partnerid",curuser.getSessionParams().get("srfpartnerid"));
                        update(discuss_channelfill_default_memberdefault);//更新fact中变量值
                        update(discuss_channelfill_default_membermember);//更新fact中变量值
            end

            //逻辑处理节点[建立成员]
            rule "deaction_01"
            ruleflow-group "discuss_channelfill_default_memberdeaction_01"
            when
            then
                        discuss_channel_memberservice.create(discuss_channelfill_default_membermember);
                        update(discuss_channelfill_default_memberdefault);//更新fact中变量值
                        update(discuss_channelfill_default_membermember);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "discuss_channelfill_default_memberend_01"
            when
            then
                        update(discuss_channelfill_default_memberdefault);//更新fact中变量值
                        update(discuss_channelfill_default_membermember);//更新fact中变量值
            end