package cn.ibizlab.mail.logic.mail_activitylogic.action_snooze;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.mail.domain.mail_activity mail_activityaction_snoozedefault;
                    global cn.ibizlab.core.mail.service.Imail_activityService mail_activityservice;
        global cn.ibizlab.core.mail.service.Imail_activityService iBzSysMail_activityDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "mail_activityaction_snoozebegin"
            when
            then
            end

            //逻辑处理节点[延迟活动7天]
            rule "deaction_01"
            ruleflow-group "mail_activityaction_snoozedeaction_01"
            when
            then
                        mail_activityservice.update(mail_activityaction_snoozedefault);
                        update(mail_activityaction_snoozedefault);//更新fact中变量值
            end

            //逻辑处理节点[准备延迟活动参数]
            rule "rawsfcode_01"
            ruleflow-group "mail_activityaction_snoozerawsfcode_01"
            when
            then
                        update(mail_activityaction_snoozedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "mail_activityaction_snoozeend_01"
            when
            then
                        update(mail_activityaction_snoozedefault);//更新fact中变量值
            end