export default {
  appBISchemeIds: ['web.bischeme'],
  appDEUIActions: [
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '添加全部',
      codeName: 'AddAll',
      fullCodeName: 'AddAll',
      predefinedType: 'UTIL_ADDALL',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'AddAll',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '添加全部数据（数据选择）',
      id: 'util_addall',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '添加选中',
      codeName: 'AddSelection',
      fullCodeName: 'AddSelection',
      predefinedType: 'UTIL_ADDSELECTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'AddSelection',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '添加选中数据（数据选择）',
      id: 'util_addselection',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '取消',
      codeName: 'Cancel',
      fullCodeName: 'Cancel',
      predefinedType: 'VIEW_CANCELACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Cancel',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_取消',
      id: 'view_cancelaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '取消变更',
      codeName: 'CancelChanges',
      fullCodeName: 'CancelChanges',
      predefinedType: 'DATA_CANCELCHANGES',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'CancelChanges',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '取消变更',
      id: 'data_cancelchanges',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '建立数据',
      codeName: 'CreateObject',
      fullCodeName: 'CreateObject',
      predefinedType: 'DATA_CREATEOBJECT',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'CreateObject',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '建立数据',
      id: 'data_createobject',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.EDIT',
      },
      caption: '编辑',
      codeName: 'Edit',
      fullCodeName: 'Edit',
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_EDITACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.EDIT',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Edit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_编辑操作',
      id: 'gridview_editaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.EDITVIEW.CLOSE',
      },
      caption: '关闭',
      codeName: 'Exit',
      fullCodeName: 'Exit',
      sysImage: {
        cssClass: 'fa fa-sign-out',
        glyph: 'xf08b@FontAwesome',
      },
      predefinedType: 'EDITVIEW_EXITACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.EDITVIEW.CLOSE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Exit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_退出操作',
      id: 'editview_exitaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '完成',
      codeName: 'Finish',
      fullCodeName: 'Finish',
      predefinedType: 'UTIL_FINISH',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Finish',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '完成（向导）',
      id: 'util_finish',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '登录',
      codeName: 'Login',
      fullCodeName: 'Login',
      predefinedType: 'APP_LOGIN',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Login',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '应用登录',
      id: 'app_login',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '登出',
      codeName: 'Logout',
      fullCodeName: 'Logout',
      predefinedType: 'APP_LOGOUT',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Logout',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '应用登出',
      id: 'app_logout',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.NEW',
      },
      caption: '新建',
      codeName: 'New',
      fullCodeName: 'New',
      sysImage: {
        cssClass: 'fa fa-file-text-o',
        glyph: 'xf0f6@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_NEWACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.NEW',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'New',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_新建操作',
      id: 'gridview_newaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '新建行',
      codeName: 'NewRow',
      fullCodeName: 'NewRow',
      sysImage: {
        cssClass: 'fa fa-plus',
        glyph: 'xf067@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_NEWROWACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'NewRow',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_新建行',
      id: 'gridview_newrowaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '下一步',
      codeName: 'NextStep',
      fullCodeName: 'NextStep',
      predefinedType: 'UTIL_NEXTSTEP',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'NextStep',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '下一步（向导）',
      id: 'util_nextstep',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '否',
      codeName: 'No',
      fullCodeName: 'No',
      predefinedType: 'VIEW_NOACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'No',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_否',
      id: 'view_noaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '确定',
      codeName: 'Ok',
      fullCodeName: 'Ok',
      predefinedType: 'VIEW_OKACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Ok',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_确定',
      id: 'view_okaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '上一步',
      codeName: 'PrevStep',
      fullCodeName: 'PrevStep',
      predefinedType: 'UTIL_PREVSTEP',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'PrevStep',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '上一步（向导）',
      id: 'util_prevstep',
    },
    {
      actionLevel: 100,
      actionTarget: 'MULTIKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.REMOVE',
      },
      caption: '删除',
      codeName: 'Remove',
      fullCodeName: 'Remove',
      sysImage: {
        cssClass: 'fa fa-remove',
        glyph: 'xf00d@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_REMOVEACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.REMOVE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Remove',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_删除操作',
      id: 'gridview_removeaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '移除全部',
      codeName: 'RemoveAll',
      fullCodeName: 'RemoveAll',
      predefinedType: 'UTIL_REMOVEALL',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveAll',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '移除全部数据（数据选择）',
      id: 'util_removeall',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '删除数据',
      codeName: 'RemoveObject',
      fullCodeName: 'RemoveObject',
      predefinedType: 'DATA_REMOVEOBJECT',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveObject',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '删除数据',
      id: 'data_removeobject',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '移除选中',
      codeName: 'RemoveSelection',
      fullCodeName: 'RemoveSelection',
      predefinedType: 'UTIL_REMOVESELECTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'RemoveSelection',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '移除选中数据（数据选择）',
      id: 'util_removeselection',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '重置',
      codeName: 'Reset',
      fullCodeName: 'Reset',
      predefinedType: 'UTIL_RESET',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Reset',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '重置（搜索栏）',
      id: 'util_reset',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.SAVE',
      },
      caption: '保存',
      codeName: 'Save',
      fullCodeName: 'Save',
      sysImage: {
        cssClass: 'fa fa-save',
        glyph: 'xf0c7@FontAwesome',
      },
      predefinedType: 'EDITVIEW_SAVEACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.SAVE',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'Save',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '编辑界面_保存操作',
      id: 'editview_saveaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '保存变更',
      codeName: 'SaveChanges',
      fullCodeName: 'SaveChanges',
      sysImage: {
        cssClass: 'fa fa-angle-right',
        glyph: 'xf105@FontAwesome',
      },
      predefinedType: 'DATA_SAVECHANGES',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'SaveChanges',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '保存变更',
      id: 'data_savechanges',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '搜索',
      codeName: 'Search',
      fullCodeName: 'Search',
      predefinedType: 'UTIL_SEARCH',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Search',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '搜索（搜索栏）',
      id: 'util_search',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '同步数据',
      codeName: 'Synchronize',
      fullCodeName: 'Synchronize',
      predefinedType: 'DATA_SYNCHRONIZE',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Synchronize',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '同步数据',
      id: 'data_synchronize',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '行编辑',
      codeName: 'ToggleRowEdit',
      fullCodeName: 'ToggleRowEdit',
      sysImage: {
        cssClass: 'fa fa-table',
        glyph: 'xf0ce@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_ROWEDITACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'ToggleRowEdit',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_行编辑开关操作',
      id: 'gridview_roweditaction',
    },
    {
      actionLevel: 100,
      actionTarget: 'SINGLEKEY',
      buttonStyle: 'DEFAULT',
      capLanguageRes: {
        lanResTag: 'TBB.TEXT.*.VIEW',
      },
      caption: '查看',
      codeName: 'View',
      fullCodeName: 'View',
      sysImage: {
        cssClass: 'fa fa-edit',
        glyph: 'xf044@FontAwesome',
      },
      predefinedType: 'GRIDVIEW_VIEWACTION',
      timeout: 60000,
      tooltipLanguageRes: {
        lanResTag: 'TBB.TOOLTIP.*.VIEW',
      },
      uiactionMode: 'SYS',
      uiactionTag: 'View',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '表格界面_查看操作',
      id: 'gridview_viewaction',
    },
    {
      actionLevel: 100,
      buttonStyle: 'DEFAULT',
      caption: '是',
      codeName: 'Yes',
      fullCodeName: 'Yes',
      predefinedType: 'VIEW_YESACTION',
      timeout: 60000,
      uiactionMode: 'SYS',
      uiactionTag: 'Yes',
      uiactionType: 'DEUIACTION',
      showBusyIndicator: true,
      noPrivDisplayMode: 2,
      name: '视图_是',
      id: 'view_yesaction',
    },
  ],
  appFuncs: [
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0827583623',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.workspace_hr_work_bench',
      name: '工作台',
      id: 'usrappfunc0827583623',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'AppFunc',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_exam_hm_grid_view',
      name: '考试/评测',
      id: 'appfunc',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0808714460',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_job_platform_account_platform_account_info',
      name: '渠道账号管理',
      id: 'usrappfunc0808714460',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0826476593',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_interview_interview_list_tab_exp_view',
      name: '面试安排',
      id: 'usrappfunc0826476593',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0820790412',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_candidate_talent_pool_list',
      name: '人才库',
      id: 'usrappfunc0820790412',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0909277924',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_idea_job_grid_view',
      name: '调试界面',
      id: 'usrappfunc0909277924',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0820091068',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_candidate_talent_pool_list',
      name: '人才库',
      id: 'usrappfunc0820091068',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0808930184',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_job_platform_info_grid_view',
      name: '渠道管理',
      id: 'usrappfunc0808930184',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0806309969',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_idea_info_view',
      name: '职位管理',
      id: 'usrappfunc0806309969',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0929071054',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_job_test_grid_view',
      name: '测试岗位',
      id: 'usrappfunc0929071054',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0827069929',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.workspace_hr_work_bench',
      name: '工作台',
      id: 'usrappfunc0827069929',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0806841809',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_idea_tab_job_requirments',
      name: '职位管理',
      id: 'usrappfunc0806841809',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0821386148',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_candidate_talentpool_management_view',
      name: '人才库',
      id: 'usrappfunc0821386148',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0826268624',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.ps_core_prd_func_tree_exp_view',
      name: '应用管理',
      id: 'usrappfunc0826268624',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0926304993',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_employee_grid_view',
      name: '人员管理',
      id: 'usrappfunc0926304993',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0822457588',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_interview_myinterview_grid',
      name: '我的面试（旧）',
      id: 'usrappfunc0822457588',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0811793875',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_candidate_base_info_view',
      name: '候选人基本信息',
      id: 'usrappfunc0811793875',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0820432412',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_candidate_talentpool_management_view',
      name: '人才库',
      id: 'usrappfunc0820432412',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0811355723',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_applicant_list_view',
      name: '候选人管理',
      id: 'usrappfunc0811355723',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0813630705',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_candidate_filter_detail_manager_filter_grid_view',
      name: '简历筛选',
      id: 'usrappfunc0813630705',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0808984644',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_job_platform_platform_list_view',
      name: '渠道管理',
      id: 'usrappfunc0808984644',
    },
    {
      appFuncType: 'CUSTOM',
      codeName: 'UsrAppFunc0808570388',
      openMode: 'INDEXVIEWTAB',
      name: '功能名称',
      id: 'usrappfunc0808570388',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0808812047',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_job_platform_platform_list_view',
      name: '渠道账号管理',
      id: 'usrappfunc0808812047',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0910679933',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_interview_interview_list_tab_search_view',
      name: '面试安排2',
      id: 'usrappfunc0910679933',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0924959812',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.internal_message_grid_view',
      name: '消息通知',
      id: 'usrappfunc0924959812',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0825533665',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.report_all_report_grid_view',
      name: '报表中心',
      id: 'usrappfunc0825533665',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'AppFunc2',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_applicant_grid_view',
      name: '候选人管理',
      id: 'appfunc2',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'AppFunc3',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_applicant_list_view',
      name: '候选人管理',
      id: 'appfunc3',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0928924036',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.res_company_grid_view',
      name: '组织机构管理',
      id: 'usrappfunc0928924036',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0928915988',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_work_location_grid_view',
      name: '工作地点',
      id: 'usrappfunc0928915988',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0808792166',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_employee_grid_view',
      name: '人员管理',
      id: 'usrappfunc0808792166',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0912315937',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.workspace_manager_index_view',
      name: '工作台（新）',
      id: 'usrappfunc0912315937',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0822244697',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_offer_approval_hm_grid_view',
      name: 'Offer审批',
      id: 'usrappfunc0822244697',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0812358789',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_interview_main_view',
      name: '面试安排',
      id: 'usrappfunc0812358789',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0808136707',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_job_platform_account_platform_account_info',
      name: '渠道账号管理',
      id: 'usrappfunc0808136707',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0901162808',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.workspace_custom_dashboard_view',
      name: '工作台',
      id: 'usrappfunc0901162808',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0829399946',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_interview_feedback_my_interview_list',
      name: '我的面试',
      id: 'usrappfunc0829399946',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0815029160',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.system_setting_tree_exp_view',
      name: '设置',
      id: 'usrappfunc0815029160',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0826138285',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.workspace_hr_work_bench',
      name: '工作台',
      id: 'usrappfunc0826138285',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0815261746',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_applicant_interview_my_interview_grid_view',
      name: '我的面试',
      id: 'usrappfunc0815261746',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0827955364',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.workspace_over_view',
      name: '工作台-总览',
      id: 'usrappfunc0827955364',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0928145263',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.hr_department_grid_view',
      name: '部门管理',
      id: 'usrappfunc0928145263',
    },
    {
      appFuncType: 'APPVIEW',
      codeName: 'UsrAppFunc0808221721',
      openMode: 'INDEXVIEWTAB',
      appViewId: 'web.res_company_grid_view',
      name: '组织机构管理',
      id: 'usrappfunc0808221721',
    },
  ],
  appPFPluginRefs: [
    {
      pluginCode: 'BI_REPORT_PANEL',
      pluginType: 'CUSTOM',
      refMode: 'CONTROLITEM',
      refTag: 'VIEWLAYOUTPANEL',
      refTag2: 'FIELD',
      name: 'BI报表面板',
      id: 'bi报表面板',
    },
    {
      pluginCode: 'BI_REPORT_PANEL',
      pluginType: 'CUSTOM',
      refMode: 'CONTROLITEM',
      refTag: 'PANEL',
      refTag2: 'FIELD',
      name: 'BI报表面板',
      id: 'bi报表面板',
    },
    {
      pluginCode: 'BI_REPORT_PANEL_CONTENT',
      pluginType: 'CUSTOM',
      refMode: 'CONTROLITEM',
      refTag: 'VIEWLAYOUTPANEL',
      refTag2: 'FIELD',
      name: 'BI报表面板呈现',
      id: 'bi报表面板呈现',
    },
    {
      pluginCode: 'COMMENT',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizHtmlComment',
      rtobjectRepo: '@ibiz-template-plm/html-comment@0.0.3-alpha.232',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      name: 'HTML（评论）',
      id: 'html（评论）',
    },
    {
      pluginCode: 'X6DesignNode',
      pluginType: 'EDITFORM_RENDER',
      refMode: 'CONTROL',
      refTag: 'FORM',
      id: 'x6设计节点',
    },
    {
      pluginCode: 'X6DesignLink',
      pluginType: 'EDITFORM_RENDER',
      refMode: 'CONTROL',
      refTag: 'FORM',
      id: 'x6设计连线',
    },
    {
      pluginCode: 'PERSONNEL_INFO',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizPersonalInfo',
      rtobjectRepo: '@ibiz-template-plm/personal-info@0.0.3-dev.119',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '人员信息',
    },
    {
      pluginCode: 'LIST_TREE',
      pluginType: 'TREE_RENDER',
      rtobjectName: 'IBizListTreeControl',
      rtobjectRepo: '@ibiz-template-plm/list-tree@0.0.3-alpha.225',
      refMode: 'CONTROL',
      refTag: 'TREEVIEW',
      runtimeObject: true,
      id: '列表树',
    },
    {
      pluginCode: 'CARD',
      pluginType: 'SEARCHBAR_RENDER',
      rtobjectName: 'CardSearchbar',
      rtobjectRepo: '@ibiz-template-ehr/card-searchbar@0.1.8-alpha.320',
      refMode: 'CONTROL',
      refTag: 'SEARCHBAR',
      runtimeObject: true,
      id: '卡片搜索栏',
    },
    {
      pluginCode: 'STEP_CODELIST',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'stepCodelist',
      rtobjectRepo: '@ibiz-template-ehr/step-codelist@0.1.8-alpha.314',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '向导步骤代码表',
    },
    {
      pluginCode: 'CUSTOM_AUTH_USERINFO',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizCustomUserInfo',
      rtobjectRepo: '@ibiz-template-plm/custom-user-info@0.0.3-dev.98',
      refMode: 'CONTROLITEM',
      refTag: 'VIEWLAYOUTPANEL',
      refTag2: 'RAWITEM',
      runtimeObject: true,
      id: '自定义用户信息',
    },
    {
      pluginCode: 'COMMENT_ITEM',
      pluginType: 'EDITOR_CUSTOMSTYLE',
      rtobjectName: 'IBizCommentItemRawItem',
      rtobjectRepo: '@ibiz-template-plm/comment-item@0.0.3-alpha.209',
      refMode: 'EDITORSTYPE',
      runtimeObject: true,
      id: '评论列表项',
    },
    {
      pluginCode: 'FILTER_SEARCHBAR',
      pluginType: 'CUSTOM',
      rtobjectName: 'IBizFilterSearchBarControl',
      rtobjectRepo: '@ibiz-template-ehr/ehr-search-bar@0.1.8-alpha.319',
      refMode: 'CONTROL',
      refTag: 'SEARCHBAR',
      runtimeObject: true,
      id: '过滤搜索栏',
    },
  ],
  appSubViewTypeRefs: [
    {
      typeCode: 'X6DesignView',
      viewType: 'DECUSTOMVIEW',
      name: 'X6设计界面',
      id: 'x6设计界面',
    },
  ],
  appViewMsgGroups: [
    {
      codeName: 'VMGroup',
      appViewMsgGroupDetails: [
        {
          appViewMsgId: 'viewmsg',
          id: '视图消息组成员',
        },
      ],
      name: '视图消息组',
      id: 'vmgroup',
    },
  ],
  appViewMsgs: [
    {
      codeName: 'ViewMsg',
      enableMode: 'DELOGIC',
      messageType: 'INFO',
      appDataEntityId: 'web.hr_applicant',
      layoutPanel: {
        layoutMode: 'FLEX',
        layout: {
          layout: 'FLEX',
        },
        rootPanelItems: [
          {
            actionGroupExtractMode: 'ITEM',
            panelItems: [
              {
                rawItem: {
                  sysImage: {
                    cssClass: 'fa fa-warning',
                    glyph: 'xf071@FontAwesome',
                  },
                  contentType: 'IMAGE',
                  predefinedType: 'STATIC_IMAGE',
                  id: 'static_image',
                },
                caption: '图片',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                  spacingRight: 'OUTERSMALL',
                },
                sysImage: {
                  cssClass: 'fa fa-warning',
                  glyph: 'xf071@FontAwesome',
                },
                showCaption: true,
                id: 'static_image',
              },
              {
                rawItem: {
                  caption: '有简历未进来？',
                  halign: 'LEFT',
                  renderMode: 'TEXT',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_TEXT',
                  id: 'static_text',
                },
                caption: '文本',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'static_text',
              },
              {
                actionType: 'UIACTION',
                buttonCssStyle: 'padding: 0px;',
                buttonStyle: 'DEFAULT',
                buttonType: 'PANELBUTTON',
                uiactionId:
                  'panel_a10a8d3fae2b835fd5c_button_link_click@workspace',
                renderMode: 'LINK',
                tooltip: '您有1份简历待分配，',
                uiactionTarget: 'SINGLEDATA',
                caption: '您有1份简历待分配，',
                itemStyle: 'DEFAULT',
                itemType: 'BUTTON',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'button_link',
              },
              {
                rawItem: {
                  caption: '去看看',
                  halign: 'LEFT',
                  renderMode: 'TEXT',
                  valign: 'MIDDLE',
                  wrapMode: 'NOWRAP',
                  contentType: 'RAW',
                  predefinedType: 'STATIC_TEXT',
                  id: 'static_text2',
                },
                caption: '文本',
                itemStyle: 'DEFAULT',
                itemType: 'RAWITEM',
                layoutPos: {
                  shrink: 1,
                  layout: 'FLEX',
                },
                showCaption: true,
                id: 'static_text2',
              },
            ],
            layout: {
              align: 'flex-start',
              dir: 'row',
              layout: 'FLEX',
              valign: 'center',
            },
            dataRegionType: 'INHERIT',
            caption: '容器',
            itemStyle: 'DEFAULT',
            itemType: 'CONTAINER',
            layoutPos: {
              shrink: 1,
              layout: 'FLEX',
            },
            id: 'container',
          },
        ],
        layoutPanel: true,
        codeName: 'a10a8d3fae2b835fd5c',
        controlType: 'PANEL',
        logicName: '候选人列表消息视图',
        appDataEntityId: 'web.hr_applicant',
        controlParam: {
          id: 'panel',
        },
        modelId: '702e8c6c5ecac55262ca0408116791c9',
        modelType: 'PSSYSVIEWPANEL',
        name: 'panel',
        id: 'web.hr_applicant.a10a8d3fae2b835fd5c',
      },
      position: 'TOP',
      removeMode: 0,
      testAppDELogicId: 'nothing',
      name: 'applicant_top',
      id: 'viewmsg',
    },
  ],
  deopprivs: [
    {
      logicName: '建立',
      name: 'CREATE',
      id: 'create',
    },
    {
      logicName: '删除',
      name: 'DELETE',
      id: 'delete',
    },
    {
      logicName: '拒绝',
      name: 'DENY',
      id: 'deny',
    },
    {
      logicName: '无控制',
      name: 'NONE',
      id: 'none',
    },
    {
      logicName: '读取',
      name: 'READ',
      id: 'read',
    },
    {
      logicName: '更新',
      name: 'UPDATE',
      id: 'update',
    },
    {
      logicName: '流程启动',
      name: 'WFSTART',
      id: 'wfstart',
    },
  ],
  appFolder: 'web',
  appMode: 'CLOUDHUBSUBAPP',
  appType: 'WEBAPP_HTML5',
  appVersion: '1.0.0.0',
  caption: 'iBizEHR 招聘管理',
  codeName: 'web',
  dynaSysMode: 1,
  engineVer: 241,
  pfstyle: 'VUE_R7_EMPTY',
  pftype: 'VUE_R7',
  pkgcodeName: 'web',
  serviceCodeName: 'web',
  sysCodeName: 'recruit',
  title: 'iBizEHR 招聘管理',
  viewCodeNameMode: 'LOWER_UNDERSCORE',
  enableServiceAPIDTO: true,
  enableUIModelEx: true,
  useServiceApi: true,
  userParam: {
    disableHomeTabs: 'true',
    DefaultOSSCat: 'ehr',
  },
  name: 'recruitapp',
  id: 'web',
  appId: 'recruit__web',
};
