package cn.ibizlab.hr.logic.hr_candidatelogic.get_my_summary_count;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_candidate hr_candidateget_my_summary_countdefault;
                global java.util.Map hr_candidateget_my_summary_countresult;
        global cn.ibizlab.core.hr.service.Ihr_candidateService iBzSysHr_candidateDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_candidateget_my_summary_countbegin"
            when
            then
            end

            //逻辑处理节点[简历筛选数量]
            rule "rawsqlcall1"
            ruleflow-group "hr_candidateget_my_summary_countrawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
    String strSql="select 	count(1) as candidate_filter from 	hr_candidate_filter_detail t where 	status = '1' and t.USER_ID  = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysHr_candidateDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                hr_candidateget_my_summary_countresult.putAll(entity);
                            }
                        update(hr_candidateget_my_summary_countdefault);//更新fact中变量值
                        update(hr_candidateget_my_summary_countresult);//更新fact中变量值
            end

            //逻辑处理节点[面试反馈数]
            rule "rawsqlcall2"
            ruleflow-group "hr_candidateget_my_summary_countrawsqlcall2"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
    String strSql="select 	count(1) as interview_feedback from 	hr_interview_feedback t where 	t.result_type is null and t.INTERVIEWER_ID  = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysHr_candidateDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                hr_candidateget_my_summary_countresult.putAll(entity);
                            }
                        update(hr_candidateget_my_summary_countdefault);//更新fact中变量值
                        update(hr_candidateget_my_summary_countresult);//更新fact中变量值
            end

            //逻辑处理节点[考试/测评返回数]
            rule "rawsqlcall3"
            ruleflow-group "hr_candidateget_my_summary_countrawsqlcall3"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
    String strSql="select 	count(1) as exam_feedback from 	hr_exam t where 	status = '10' and t.CREATE_UID  = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysHr_candidateDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                hr_candidateget_my_summary_countresult.putAll(entity);
                            }
                        update(hr_candidateget_my_summary_countdefault);//更新fact中变量值
                        update(hr_candidateget_my_summary_countresult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "hr_candidateget_my_summary_countend1"
            when
            then
                        update(hr_candidateget_my_summary_countdefault);//更新fact中变量值
                        update(hr_candidateget_my_summary_countresult);//更新fact中变量值
            end