package cn.ibizlab.hr.logic.hr_candidatelogic.get_talent_pool_count;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_candidate hr_candidateget_talent_pool_countdefault;
                global java.util.Map hr_candidateget_talent_pool_countresult;
        global cn.ibizlab.core.hr.service.Ihr_candidateService iBzSysHr_candidateDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_candidateget_talent_pool_countbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "hr_candidateget_talent_pool_countend1"
            when
            then
                        update(hr_candidateget_talent_pool_countdefault);//更新fact中变量值
                        update(hr_candidateget_talent_pool_countresult);//更新fact中变量值
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall1"
            ruleflow-group "hr_candidateget_talent_pool_countrawsqlcall1"
            when
            then
                        Map param = null;
                        String strSql="SELECT count(1) talent_pool_count from hr_candidate  where LAST_TP_TALENT_POOL is not null";
                        java.util.List<JSONObject> entities=iBzSysHr_candidateDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                hr_candidateget_talent_pool_countresult.putAll(entity);
                            }
                        update(hr_candidateget_talent_pool_countdefault);//更新fact中变量值
                        update(hr_candidateget_talent_pool_countresult);//更新fact中变量值
            end