package cn.ibizlab.mail.logic.mail_messagelogic.delete;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.mail.domain.mail_message mail_messagedeletedefault;
                    global cn.ibizlab.core.mail.service.Imail_messageService mail_messageservice;
        global cn.ibizlab.core.mail.service.Imail_messageService iBzSysMail_messageDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "mail_messagedeletebegin"
            when
            then
            end

            //逻辑处理节点[准备评论删除提示信息]
            rule "prepareparam1"
            ruleflow-group "mail_messagedeleteprepareparam1"
            when
            then
                            mail_messagedeletedefault.set("body","<p><del>该评论已删除</del></p>");
                        update(mail_messagedeletedefault);//更新fact中变量值
            end

            //逻辑处理节点[将评论内容修改为"已删除"]
            rule "deaction1"
            ruleflow-group "mail_messagedeletedeaction1"
            when
            then
                        mail_messageservice.update(mail_messagedeletedefault);
                        update(mail_messagedeletedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "mail_messagedeleteend1"
            when
            then
                        update(mail_messagedeletedefault);//更新fact中变量值
            end