package cn.ibizlab.attendance.logic.attendance_rulelogic.calcother;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_rule attendance_rulecalcotherdefault;
                global cn.ibizlab.core.attendance.domain.attendance_shift attendance_rulecalcotherattendance_shift;
                global cn.ibizlab.core.attendance.domain.attendance_shift attendance_rulecalcothershifts;
        global cn.ibizlab.core.attendance.service.Iattendance_ruleService iBzSysAttendance_ruleDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_rulecalcotherbegin"
            when
            then
            end

            //逻辑处理节点[计算上下班时间]
            rule "rawsfcode_01"
            ruleflow-group "attendance_rulecalcotherrawsfcode_01"
            when
            then
                        update(attendance_rulecalcotherdefault);//更新fact中变量值
                        update(attendance_rulecalcotherattendance_shift);//更新fact中变量值
                        update(attendance_rulecalcothershifts);//更新fact中变量值
            end

            //逻辑处理节点[填充默认班次标识]
            rule "rawsfcode_03"
            ruleflow-group "attendance_rulecalcotherrawsfcode_03"
            when
            then
                        update(attendance_rulecalcotherdefault);//更新fact中变量值
                        update(attendance_rulecalcotherattendance_shift);//更新fact中变量值
                        update(attendance_rulecalcothershifts);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "attendance_rulecalcotherend_01"
            when
            then
                        update(attendance_rulecalcotherdefault);//更新fact中变量值
                        update(attendance_rulecalcotherattendance_shift);//更新fact中变量值
                        update(attendance_rulecalcothershifts);//更新fact中变量值
            end

            //逻辑处理节点[填充自由班上下班时间]
            rule "rawsfcode_02"
            ruleflow-group "attendance_rulecalcotherrawsfcode_02"
            when
            then
                        update(attendance_rulecalcotherdefault);//更新fact中变量值
                        update(attendance_rulecalcotherattendance_shift);//更新fact中变量值
                        update(attendance_rulecalcothershifts);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam_01"
            ruleflow-group "attendance_rulecalcotherdebugparam_01"
            when
            then
                        update(attendance_rulecalcotherdefault);//更新fact中变量值
                        update(attendance_rulecalcotherattendance_shift);//更新fact中变量值
                        update(attendance_rulecalcothershifts);//更新fact中变量值
            end

            //逻辑处理节点[计算组排班数]
            rule "rawsfcode4"
            ruleflow-group "attendance_rulecalcotherrawsfcode4"
            when
            then
                        update(attendance_rulecalcotherdefault);//更新fact中变量值
                        update(attendance_rulecalcotherattendance_shift);//更新fact中变量值
                        update(attendance_rulecalcothershifts);//更新fact中变量值
            end