package cn.ibizlab.attendance.logic.attendance_rulelogic.cleanworkdays;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_rule attendance_rulecleanworkdaysdefault;
                global cn.ibizlab.core.attendance.domain.attendance_workday attendance_rulecleanworkdayslastdays;
                global cn.ibizlab.core.attendance.domain.attendance_workday attendance_rulecleanworkdaystemp;
                global cn.ibizlab.core.attendance.domain.attendance_workday attendance_rulecleanworkdaysworkdays;
        global cn.ibizlab.core.attendance.service.Iattendance_ruleService iBzSysAttendance_ruleDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_rulecleanworkdaysbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "attendance_rulecleanworkdaysprepareparam_01"
            when
            then
                            attendance_rulecleanworkdaysworkdays.set("",attendance_rulecleanworkdaysdefault.get("workdays"));
                        update(attendance_rulecleanworkdaysdefault);//更新fact中变量值
                        update(attendance_rulecleanworkdayslastdays);//更新fact中变量值
                        update(attendance_rulecleanworkdaystemp);//更新fact中变量值
                        update(attendance_rulecleanworkdaysworkdays);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_03"
            ruleflow-group "attendance_rulecleanworkdaysprepareparam_03"
            when
            then
                                attendance_rulecleanworkdaysdefault.set("workdays",null);
                        update(attendance_rulecleanworkdaysdefault);//更新fact中变量值
                        update(attendance_rulecleanworkdayslastdays);//更新fact中变量值
                        update(attendance_rulecleanworkdaystemp);//更新fact中变量值
                        update(attendance_rulecleanworkdaysworkdays);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "attendance_rulecleanworkdaysrawsfcode_01"
            when
            then
                        update(attendance_rulecleanworkdaysdefault);//更新fact中变量值
                        update(attendance_rulecleanworkdayslastdays);//更新fact中变量值
                        update(attendance_rulecleanworkdaystemp);//更新fact中变量值
                        update(attendance_rulecleanworkdaysworkdays);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam_01"
            ruleflow-group "attendance_rulecleanworkdaysdebugparam_01"
            when
            then
                        update(attendance_rulecleanworkdaysdefault);//更新fact中变量值
                        update(attendance_rulecleanworkdayslastdays);//更新fact中变量值
                        update(attendance_rulecleanworkdaystemp);//更新fact中变量值
                        update(attendance_rulecleanworkdaysworkdays);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_02"
            ruleflow-group "attendance_rulecleanworkdaysprepareparam_02"
            when
            then
                            attendance_rulecleanworkdaysdefault.set("workdays",attendance_rulecleanworkdayslastdays.get(""));
                        update(attendance_rulecleanworkdaysdefault);//更新fact中变量值
                        update(attendance_rulecleanworkdayslastdays);//更新fact中变量值
                        update(attendance_rulecleanworkdaystemp);//更新fact中变量值
                        update(attendance_rulecleanworkdaysworkdays);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "attendance_rulecleanworkdaysend_01"
            when
            then
                        update(attendance_rulecleanworkdaysdefault);//更新fact中变量值
                        update(attendance_rulecleanworkdayslastdays);//更新fact中变量值
                        update(attendance_rulecleanworkdaystemp);//更新fact中变量值
                        update(attendance_rulecleanworkdaysworkdays);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall_01"
            ruleflow-group "attendance_rulecleanworkdaysloopsubcall_01"
            when
            then
                        update(attendance_rulecleanworkdaysdefault);//更新fact中变量值
                        update(attendance_rulecleanworkdayslastdays);//更新fact中变量值
                        update(attendance_rulecleanworkdaystemp);//更新fact中变量值
                        update(attendance_rulecleanworkdaysworkdays);//更新fact中变量值
            end

            //逻辑处理节点[附加到数组参数]
            rule "appendparam_01"
            ruleflow-group "attendance_rulecleanworkdaysappendparam_01"
            when
            then
                        update(attendance_rulecleanworkdaysdefault);//更新fact中变量值
                        update(attendance_rulecleanworkdayslastdays);//更新fact中变量值
                        update(attendance_rulecleanworkdaystemp);//更新fact中变量值
                        update(attendance_rulecleanworkdaysworkdays);//更新fact中变量值
            end