package cn.ibizlab.attendance.logic.attendance_rulelogic.deleteotherinfo;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_rule attendance_ruledeleteotherinfodefault;
                    global cn.ibizlab.core.attendance.service.Iattendance_activate_ruleService attendance_activate_ruleservice;
        global cn.ibizlab.core.attendance.service.Iattendance_ruleService iBzSysAttendance_ruleDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_ruledeleteotherinfobegin"
            when
            then
            end

            //逻辑处理节点[实体行为]
            rule "deaction_01"
            ruleflow-group "attendance_ruledeleteotherinfodeaction_01"
            when
            then
                        attendance_activate_ruleservice.remove(attendance_ruledeleteotherinfodefault.getId());
                        update(attendance_ruledeleteotherinfodefault);//更新fact中变量值
            end