package cn.ibizlab.attendance.logic.attendance_rulelogic.executecompletion3;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_rule attendance_ruleexecutecompletion3default;
                global cn.ibizlab.core.attendance.domain.attendance_rule attendance_ruleexecutecompletion3rule;
                global cn.ibizlab.core.attendance.domain.attendance_activate_rule attendance_ruleexecutecompletion3rulefilter;
                global cn.ibizlab.core.attendance.domain.attendance_activate_rule attendance_ruleexecutecompletion3rules;
                global cn.ibizlab.core.attendance.domain.attendance_shift attendance_ruleexecutecompletion3shifts;
                global cn.ibizlab.core.attendance.domain.attendance_activate_rule attendance_ruleexecutecompletion3temp;
                    global cn.ibizlab.core.attendance.service.Iattendance_ruleService attendance_ruleservice;
        global cn.ibizlab.core.attendance.service.Iattendance_ruleService iBzSysAttendance_ruleDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_ruleexecutecompletion3begin"
            when
            then
            end

            //逻辑处理节点[需补全排班的规则]
            rule "rawsqlcall1"
            ruleflow-group "attendance_ruleexecutecompletion3rawsqlcall1"
            when
            then
                        Map param = null;
                        String strSql="SELECT     * FROM      attendance_activate_rule r WHERE      EXISTS (         SELECT              1         FROM              attendance_group_shift_member gsm         WHERE              gsm.rule_id = r.id     )";
                        java.util.List<JSONObject> entities=iBzSysAttendance_ruleDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    cn.ibizlab.core.attendance.domain.attendance_activate_rule targetEntity =new cn.ibizlab.core.attendance.domain.attendance_activate_rule();
                                    for (Map.Entry entry : entity.entrySet()) {
                                    targetEntity.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                                    org.springframework.cglib.beans.BeanCopier copier= org.springframework.cglib.beans.BeanCopier.create(targetEntity.getClass(),attendance_ruleexecutecompletion3rules.getClass(), false);
                                    copier.copy(targetEntity,attendance_ruleexecutecompletion3rules,null);
                            }
                        update(attendance_ruleexecutecompletion3default);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rule);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rulefilter);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rules);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3shifts);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3temp);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall_01"
            ruleflow-group "attendance_ruleexecutecompletion3loopsubcall_01"
            when
            then
                        update(attendance_ruleexecutecompletion3default);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rule);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rulefilter);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rules);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3shifts);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3temp);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode2"
            ruleflow-group "attendance_ruleexecutecompletion3rawsfcode2"
            when
            then
                        update(attendance_ruleexecutecompletion3default);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rule);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rulefilter);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rules);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3shifts);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3temp);//更新fact中变量值
            end

            //逻辑处理节点[按限制时间补全规则]
            rule "delogic_01"
            ruleflow-group "attendance_ruleexecutecompletion3delogic_01"
            when
            then
                        update(attendance_ruleexecutecompletion3default);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rule);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rulefilter);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rules);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3shifts);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3temp);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "attendance_ruleexecutecompletion3end_01"
            when
            then
                        update(attendance_ruleexecutecompletion3default);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rule);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rulefilter);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rules);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3shifts);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3temp);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "attendance_ruleexecutecompletion3prepareparam1"
            when
            then
                        update(attendance_ruleexecutecompletion3default);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rule);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rulefilter);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3rules);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3shifts);//更新fact中变量值
                        update(attendance_ruleexecutecompletion3temp);//更新fact中变量值
            end