package cn.ibizlab.attendance.logic.attendance_rulelogic.judgingeffect;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_rule attendance_rulejudgingeffectdefault;
        global cn.ibizlab.core.attendance.service.Iattendance_ruleService iBzSysAttendance_ruleDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_rulejudgingeffectbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "attendance_rulejudgingeffectprepareparam_01"
            when
            then
                            attendance_rulejudgingeffectdefault.set("isactivate","1");
                        update(attendance_rulejudgingeffectdefault);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_02"
            ruleflow-group "attendance_rulejudgingeffectprepareparam_02"
            when
            then
                            attendance_rulejudgingeffectdefault.set("isactivate","0");
                        update(attendance_rulejudgingeffectdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "attendance_rulejudgingeffectend_01"
            when
            then
                        update(attendance_rulejudgingeffectdefault);//更新fact中变量值
            end