package cn.ibizlab.attendance.logic.attendance_rulelogic.removeodoodata;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_rule attendance_ruleremoveodoodatadefault;
                    global cn.ibizlab.core.resource.service.Iresource_calendarService resource_calendarservice;
        global cn.ibizlab.core.attendance.service.Iattendance_ruleService iBzSysAttendance_ruleDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_ruleremoveodoodatabegin"
            when
            then
            end

            //逻辑处理节点[实体行为]
            rule "deaction_01"
            ruleflow-group "attendance_ruleremoveodoodatadeaction_01"
            when
            then
                        resource_calendarservice.remove(attendance_ruleremoveodoodatadefault.getId());
                        update(attendance_ruleremoveodoodatadefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "attendance_ruleremoveodoodataend_01"
            when
            then
                        update(attendance_ruleremoveodoodatadefault);//更新fact中变量值
            end