package cn.ibizlab.employee_management.logic.employeelogic.employee;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.employee_management.domain.employee employeeemployeedefault;
                global cn.ibizlab.core.employee_management.domain.employee employeeemployeepage;
                global cn.ibizlab.core.employee_management.domain.employee employeeemployeetemp;
                    global cn.ibizlab.core.employee_management.service.IemployeeService employeeservice;
        global cn.ibizlab.core.employee_management.service.IemployeeService iBzSysEmployeeDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "employeeemployeebegin"
            when
            then
            end

            //逻辑处理节点[解析搜索条件]
            rule "rawsfcode1"
            ruleflow-group "employeeemployeerawsfcode1"
            when
            then
                        update(employeeemployeedefault);//更新fact中变量值
                        update(employeeemployeepage);//更新fact中变量值
                        update(employeeemployeetemp);//更新fact中变量值
            end

            //逻辑处理节点[获取员工信息]
            rule "dedataset1"
            ruleflow-group "employeeemployeededataset1"
            when
            then
                        update(employeeemployeedefault);//更新fact中变量值
                        update(employeeemployeepage);//更新fact中变量值
                        update(employeeemployeetemp);//更新fact中变量值
            end

            //逻辑处理节点[循环子调用]
            rule "loopsubcall1"
            ruleflow-group "employeeemployeeloopsubcall1"
            when
            then
                        update(employeeemployeedefault);//更新fact中变量值
                        update(employeeemployeepage);//更新fact中变量值
                        update(employeeemployeetemp);//更新fact中变量值
            end

            //逻辑处理节点[获取时间范围搜索条件]
            rule "rawsfcode2"
            ruleflow-group "employeeemployeerawsfcode2"
            when
            then
                        update(employeeemployeedefault);//更新fact中变量值
                        update(employeeemployeepage);//更新fact中变量值
                        update(employeeemployeetemp);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "employeeemployeeend1"
            when
            then
                        update(employeeemployeedefault);//更新fact中变量值
                        update(employeeemployeepage);//更新fact中变量值
                        update(employeeemployeetemp);//更新fact中变量值
            end