package cn.ibizlab.employee_management.logic.employeelogic.nothing;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.employee_management.domain.employee employeenothingdefault;
        global cn.ibizlab.core.employee_management.service.IemployeeService iBzSysEmployeeDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "employeenothingbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "employeenothingend1"
            when
            then
                        update(employeenothingdefault);//更新fact中变量值
            end