package cn.ibizlab.hr.logic.hr_recruitment_progresslogic.disable;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_recruitment_progress hr_recruitment_progressdisabledefault;
                    global cn.ibizlab.core.hr.service.Ihr_recruitment_progressService hr_recruitment_progressservice;
        global cn.ibizlab.core.hr.service.Ihr_recruitment_progressService iBzSysHr_recruitment_progressDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_recruitment_progressdisablebegin"
            when
            then
            end

            //逻辑处理节点[设置状态为停用]
            rule "prepareparam1"
            ruleflow-group "hr_recruitment_progressdisableprepareparam1"
            when
            then
                            hr_recruitment_progressdisabledefault.set("status","0");
                        update(hr_recruitment_progressdisabledefault);//更新fact中变量值
            end

            //逻辑处理节点[更新状态]
            rule "deaction1"
            ruleflow-group "hr_recruitment_progressdisabledeaction1"
            when
            then
                        hr_recruitment_progressservice.update(hr_recruitment_progressdisabledefault);
                        update(hr_recruitment_progressdisabledefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "hr_recruitment_progressdisableend1"
            when
            then
                        update(hr_recruitment_progressdisabledefault);//更新fact中变量值
            end