package cn.ibizlab.hr.logic.hr_attendancelogic.attendancecalculate;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_attendance hr_attendanceattendancecalculatedefault;
                global cn.ibizlab.core.attendance.domain.attendance_clock_in_record hr_attendanceattendancecalculateclock;
                    global cn.ibizlab.core.attendance.service.Iattendance_clock_in_recordService attendance_clock_in_recordservice;
        global cn.ibizlab.core.hr.service.Ihr_attendanceService iBzSysHr_attendanceDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_attendanceattendancecalculatebegin"
            when
            then
            end

            //逻辑处理节点[实体行为]
            rule "deaction_01"
            ruleflow-group "hr_attendanceattendancecalculatedeaction_01"
            when
            then
                        attendance_clock_in_recordservice.attendance_calculate(hr_attendanceattendancecalculateclock);
                        update(hr_attendanceattendancecalculatedefault);//更新fact中变量值
                        update(hr_attendanceattendancecalculateclock);//更新fact中变量值
            end