package cn.ibizlab.hr.logic.hr_attendancelogic.calcother;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.hr.domain.hr_attendance hr_attendancecalcotherdefault;
        global cn.ibizlab.core.hr.service.Ihr_attendanceService iBzSysHr_attendanceDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "hr_attendancecalcotherbegin"
            when
            then
            end

            //逻辑处理节点[有效加班时间]
            rule "rawsfcode_01"
            ruleflow-group "hr_attendancecalcotherrawsfcode_01"
            when
            then
                        update(hr_attendancecalcotherdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "hr_attendancecalcotherend_01"
            when
            then
                        update(hr_attendancecalcotherdefault);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam_01"
            ruleflow-group "hr_attendancecalcotherdebugparam_01"
            when
            then
                        update(hr_attendancecalcotherdefault);//更新fact中变量值
            end