export default {
  codeListTag: 'CycleDays',
  codeListType: 'STATIC',
  codeName: 'CycleDays',
  emptyText: '未定义',
  codeItems: [
    {
      codeName: 'item_2',
      text: '2天',
      value: '2',
      id: 'item_2',
    },
    {
      codeName: 'item_3',
      text: '3天',
      value: '3',
      id: 'item_3',
    },
    {
      codeName: 'item_4',
      text: '4天',
      value: '4',
      id: 'item_4',
    },
    {
      codeName: 'item_5',
      text: '5天',
      value: '5',
      id: 'item_5',
    },
    {
      codeName: 'item_6',
      text: '6天',
      value: '6',
      id: 'item_6',
    },
    {
      codeName: 'item_7',
      text: '7天',
      value: '7',
      id: 'item_7',
    },
    {
      codeName: 'item_8',
      text: '8天',
      value: '8',
      id: 'item_8',
    },
    {
      codeName: 'item_9',
      text: '9天',
      value: '9',
      id: 'item_9',
    },
    {
      codeName: 'item_10',
      text: '10天',
      value: '10',
      id: 'item_10',
    },
    {
      codeName: 'item_11',
      text: '11天',
      value: '11',
      id: 'item_11',
    },
    {
      codeName: 'item_12',
      text: '12天',
      value: '12',
      id: 'item_12',
    },
    {
      codeName: 'item_13',
      text: '13天',
      value: '13',
      id: 'item_13',
    },
    {
      codeName: 'item_14',
      text: '14天',
      value: '14',
      id: 'item_14',
    },
    {
      codeName: 'item_15',
      text: '15天',
      value: '15',
      id: 'item_15',
    },
    {
      codeName: 'item_16',
      text: '16天',
      value: '16',
      id: 'item_16',
    },
    {
      codeName: 'item_17',
      text: '17天',
      value: '17',
      id: 'item_17',
    },
    {
      codeName: 'item_18',
      text: '18天',
      value: '18',
      id: 'item_18',
    },
    {
      codeName: 'item_19',
      text: '19天',
      value: '19',
      id: 'item_19',
    },
    {
      codeName: 'item_20',
      text: '20天',
      value: '20',
      id: 'item_20',
    },
    {
      codeName: 'item_21',
      text: '21天',
      value: '21',
      id: 'item_21',
    },
    {
      codeName: 'item_22',
      text: '22天',
      value: '22',
      id: 'item_22',
    },
    {
      codeName: 'item_23',
      text: '23天',
      value: '23',
      id: 'item_23',
    },
    {
      codeName: 'item_24',
      text: '24天',
      value: '24',
      id: 'item_24',
    },
    {
      codeName: 'item_25',
      text: '25天',
      value: '25',
      id: 'item_25',
    },
    {
      codeName: 'item_26',
      text: '26天',
      value: '26',
      id: 'item_26',
    },
    {
      codeName: 'item_27',
      text: '27天',
      value: '27',
      id: 'item_27',
    },
    {
      codeName: 'item_28',
      text: '28天',
      value: '28',
      id: 'item_28',
    },
    {
      codeName: 'item_29',
      text: '29天',
      value: '29',
      id: 'item_29',
    },
    {
      codeName: 'item_30',
      text: '30天',
      value: '30',
      id: 'item_30',
    },
    {
      codeName: 'item_31',
      text: '31天',
      value: '31',
      id: 'item_31',
    },
  ],
  codeItemValueNumber: true,
  enableCache: true,
  name: '循环天数',
  id: 'attendanceapp.cycledays',
};
