package cn.ibizlab.mail.logic.mail_threadlogic.message_post_with_source;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.mail.domain.mail_thread mail_threadmessage_post_with_sourcedefault;
                global cn.ibizlab.core.mail.domain.mail_message mail_threadmessage_post_with_sourcemessage;
                    global cn.ibizlab.core.mail.service.Imail_messageService mail_messageservice;
        global cn.ibizlab.core.mail.service.Imail_threadService iBzSysMail_threadDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "mail_threadmessage_post_with_sourcebegin"
            when
            then
            end

            //逻辑处理节点[构造消息对象]
            rule "prepareparam_01"
            ruleflow-group "mail_threadmessage_post_with_sourceprepareparam_01"
            when
            then
                            mail_threadmessage_post_with_sourcemessage.set("",mail_threadmessage_post_with_sourcedefault.get(""));
                        update(mail_threadmessage_post_with_sourcedefault);//更新fact中变量值
                        update(mail_threadmessage_post_with_sourcemessage);//更新fact中变量值
            end

            //逻辑处理节点[建立消息]
            rule "deaction_01"
            ruleflow-group "mail_threadmessage_post_with_sourcedeaction_01"
            when
            then
                        mail_messageservice.create(mail_threadmessage_post_with_sourcemessage);
                        update(mail_threadmessage_post_with_sourcedefault);//更新fact中变量值
                        update(mail_threadmessage_post_with_sourcemessage);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "mail_threadmessage_post_with_sourceend_01"
            when
            then
                        update(mail_threadmessage_post_with_sourcedefault);//更新fact中变量值
                        update(mail_threadmessage_post_with_sourcemessage);//更新fact中变量值
            end