package cn.ibizlab.attendance.logic.attendance_statisticslogic.personal;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.attendance.domain.attendance_statistics attendance_statisticspersonaldefault;
                global cn.ibizlab.core.employee_management.domain.employee attendance_statisticspersonalemp;
                    global cn.ibizlab.core.employee_management.service.IemployeeService employeeservice;
        global cn.ibizlab.core.attendance.service.Iattendance_statisticsService iBzSysAttendance_statisticsDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "attendance_statisticspersonalbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam1"
            ruleflow-group "attendance_statisticspersonalprepareparam1"
            when
            then
                            attendance_statisticspersonalemp.set("id",attendance_statisticspersonaldefault.get("id"));
                        update(attendance_statisticspersonaldefault);//更新fact中变量值
                        update(attendance_statisticspersonalemp);//更新fact中变量值
            end

            //逻辑处理节点[获取员工]
            rule "deaction1"
            ruleflow-group "attendance_statisticspersonaldeaction1"
            when
            then
                            cn.ibizlab.util.helper.CachedBeanCopier.copy(employeeservice.get(attendance_statisticspersonalemp.getId()),attendance_statisticspersonalemp);
                        update(attendance_statisticspersonaldefault);//更新fact中变量值
                        update(attendance_statisticspersonalemp);//更新fact中变量值
            end

            //逻辑处理节点[获取考勤记录]
            rule "rawsfcode1"
            ruleflow-group "attendance_statisticspersonalrawsfcode1"
            when
            then
                        update(attendance_statisticspersonaldefault);//更新fact中变量值
                        update(attendance_statisticspersonalemp);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "attendance_statisticspersonalend1"
            when
            then
                        update(attendance_statisticspersonaldefault);//更新fact中变量值
                        update(attendance_statisticspersonalemp);//更新fact中变量值
            end